The task has been completed and tests have been written
frontend-park-mail-ru/homework_2023_2 pull request #11
Opened 2023-09-07 01:04 UTC by wolpy01

Фоменко Владислав, WEB-21, variant-3

P.S.
В исходных тестах, которые лежат в исходном репозитории ошибка: при проверке перевода из римской системы счисления в десятичную есть вариант перевода "iiii" и в качестве ответа выставлено "4".

Сама строка с кодом: assert.strictEqual(roman('iiii'), 4);

2023-09-07 06:54 UTC, johnSamilin commented
Привет, добро пожаловать на курс по фронтенд-разработке. Я буду проверять твое ДЗ 0.
Если у меня появятся комментарии к коду, то я опишу их здесь. Можешь отвечать на них тут же, а чтобы что-то уточнить - [телеграм](https://t.me/WatasheeBaka)

2023-09-07 13:17 UTC, johnSamilin requested changes

2023-09-07 18:56 UTC, wolpy01 commented on source/roman.js
> +        for (let i = 0; i < number.length - 1; i++) {
Сделал.

2023-09-07 18:56 UTC, wolpy01 commented on source/roman.js
> +'use strict'
Для облегчения разработки, т.к. использование use strict не позволяет использование переменных до их объявления, упрощает написание "безопасного" JS (из-за замены ранее принятого "плохого" синтаксиса на ошибки) и предотвращает использование слов, которые могут быть использованы в будущем, в качестве названия переменных.

2023-09-07 18:57 UTC, wolpy01 commented on source/roman.js
> +};
Добавил.

2023-09-07 18:59 UTC, wolpy01 commented on source/roman.js
> +    if (s.trim().match(/^M{0,3}(CM|CD|D?C{0,3})?(XC|XL|L?X{0,3})?(IX|IV|V?I{0,3})?$/i)) {
Можно, например, после  "^" и перед "$" добавить " *". trim в данном случае использовался для улучшения читаемости, т.к. регулярное выражение и без этого довольно сложное, а наличие " *" лишь ухудшит читаемость из-за малой величины пробела.

2023-09-07 19:00 UTC, wolpy01 commented on tests/roman.js
> +        assert.strictEqual(roman('2017'), 'MMXVII', 'roman(\'2017\') === \'MMXVII\'');
Заменить внешние одинарные кавычки заменить двойными, а внутренние оставить одинарными, убрав экранирование.

2023-09-07 19:02 UTC, wolpy01 commented on source/roman.js
> +let roman = function (s) {
Исправил. В данном случае использование Function expression неоправданно, поэтому лучше использовать Function Declaration.

Написал для каждой функции.

2023-09-07 19:04 UTC, wolpy01 commented on source/roman.js
> +    let result = checkTheCorrectnessOfNumber(String(s));
Исправил все объявления неизменяемых переменных на const.
const и let похожи, но их главное отличие, что const используется для объявления констант, а let - для переменных, значение которых будет изменяться.

2023-09-08 06:44 UTC, johnSamilin requested changes

2023-09-08 06:44 UTC, johnSamilin commented on source/roman.js
> +* @param {*} s - user expression
Лучше подсказать тому, кто будет использовать эту функцию, какой тип аргумента тут ожидается. Передать можно все, что угодно, но все равно лучше прямо указать, что мы тут ожидаем

2023-09-08 06:53 UTC, wolpy01 commented on source/roman.js
> +* @param {*} s - user expression
Поправил, добавив ожидаемые типы аргументов для преобразования.

2023-09-08 07:13 UTC, johnSamilin approved these changes

2023-09-11 00:19 UTC, DPeshkoff requested changes
Привет! Поздравляю с переходом на второй семестр)

Классное решение получилось, но у меня есть пара замечаний. Если возникнут вопросы - можешь писать в [Telegram](t.me/DmPesh)

2023-09-11 00:19 UTC, DPeshkoff commented on source/roman.js
> +        return 'Your input is empty!';
Кажется, что здесь лучше выбрасывать ошибку

2023-09-11 00:19 UTC, DPeshkoff commented on tests/roman.js
> -		assert.strictEqual(roman('I'), 1);
Здесь не нужны изменения, предлагаю вернуть как было

2023-09-11 00:19 UTC, DPeshkoff commented on source/roman.js
> +function roman (s) {
А какие еще бывают виды функций в языке? Распишешь, пожалуйста, в ответе? Почему выбрал именно function?

2023-09-11 00:19 UTC, DPeshkoff commented on source/roman.js
> +        return "empty";
Вообще обычно принято использовать одиночные кавычки, давай поменяем)

2023-09-11 00:19 UTC, DPeshkoff commented on source/roman.js
> +    return `Your number ${String(s)} is incorrect or it is not a number!`;
И тут ошибку бы)

2023-09-11 10:46 UTC, wolpy01 commented on source/roman.js
> +        return "empty";
Поменял.

2023-09-11 10:47 UTC, wolpy01 commented on tests/roman.js
> -		assert.strictEqual(roman('I'), 1);
Исходные тесты я оставил, какими они и были. Лишь добавил более подробный вывод вместо сообщения "okay", чтобы было понятно, что это за тест.

2023-09-11 10:47 UTC, wolpy01 commented on source/roman.js
> +    return `Your number ${String(s)} is incorrect or it is not a number!`;
Добавил.

2023-09-11 10:47 UTC, wolpy01 commented on source/roman.js
> +        return 'Your input is empty!';
Добавил.

2023-09-11 10:48 UTC, wolpy01 commented on index.html
> -<script src="tests/max.js"></script>
Вернул.

2023-09-11 11:38 UTC, wolpy01 commented on source/roman.js
> +function roman (s) {
Можно выделить два способа объявления функций: 1) Function Expression Declaration; 2) Function Declaration.
1-й способ объявляется, как у меня в коде, а 2-й, например, выглядел бы в данном случае так let roman =..., т.е. функцию можно присвоить переменной.

Отличие между этими способами в следующем: 
- 1) видна только после своего объявления в коде, что неудобно, когда надо объявить функцию, например, в зависимости от блока if, т.к. 2) в strict-режиме доступна лишь в блоке, в котором выполнятся;
- 2) видна в любом месте кода.

Выбрал 2) потому, что 1) в данной задаче не требуется, а 2) позволяет обеспечить большую гибкость последующего кода.

2023-09-11 19:42 UTC, DPeshkoff approved these changes

2023-09-11 19:43 UTC, DPeshkoff commented on source/roman.js
> +function roman (s) {
Вообще чаще в таком случае используют стрелочные функции - потому что this нам в этом случае не нужен, и это упрощает немного нашу жизнь)

Однако ты подробно расписал, оставим так, убедил)

2023-09-11 19:43 UTC, closed without merging