done zero hw
frontend-park-mail-ru/homework_2023_2 pull request #13
Opened 2023-09-07 08:15 UTC by fitzplsr

Халиков Руслан

2023-09-07 17:18 UTC, Ivan-Bir commented
Привет!
Добро пожаловать на курс по фронтенд-разработке 👋
Я буду проверять твое дз0. Ниже я оставлю комментарии по коду. Можно отвечать здесь или написать мне в телеграмм @Ivanchello_br.

2023-09-07 17:34 UTC, Ivan-Bir requested changes

2023-09-07 17:34 UTC, Ivan-Bir commented on source/solve.js
> +const solve = (...args) => {
Хорошие разработчики документируют свой код.
Давай добавим JSDoc к функции https://jsdoc.app/about-getting-started.html

2023-09-07 17:34 UTC, Ivan-Bir commented on source/solve.js
> +    return eval(expression.replaceAll("x", value));
А ловко ты это придумал
![image](https://github.com/frontend-park-mail-ru/homework_2023_2/assets/91963263/650a5954-5181-4feb-9810-67ee29c97d5d)

Но в реальной жизни такими "фичами" не пользуются. "eval is evil"
А теперь давай представим, что эта функция принимает пользовательский ввод. Сюда очень легко вписать xss и выполнить. Попробуй в браузере выполнить этот код

const solve = (...args) => {
    let [expression, value] = args;
    return eval(expression.replaceAll("x", value));
    };
    solve('alert("lolkek")');
    
    Подробнее про xss можно почитать туть: https://habr.com/ru/articles/511318/
    
    А теперь давай подумаем как можно обезопасить вызов этой функции для твой задачи

2023-09-07 17:34 UTC, Ivan-Bir commented on tests/solve.js
> +	QUnit.test('solve работает как калькулятор при отсутствии x', function (assert) {
Позитивный кейс это хорошо, а что будет, если передать некорректные аргументы. Подумай, какие ещё негативные кейсы здесь возможны

2023-09-07 17:36 UTC, Ivan-Bir commented
Поменяй, пожалуйста, название ПР на "Фамилия Имя", чтобы нам в дальнейшем было проще его проверять

2023-09-07 19:19 UTC, fitzplsr commented
Добавил комментарии
Сделал валидацию для безопасного использования eval
Сделал валидацию на количество и тип аргументов
Дописал соответствующие тесты

2023-09-07 20:22 UTC, Ivan-Bir requested changes

2023-09-07 20:22 UTC, Ivan-Bir commented on source/solve.js
> +    if (args.length != 2) {
Ок, в задании указано, что строка должна приходить с переменной

2023-09-07 20:22 UTC, Ivan-Bir commented on source/solve.js
> + */
Функция научилась кидать эксепшены, давай отразим это
https://jsdoc.app/tags-throws.html

2023-09-07 20:22 UTC, Ivan-Bir commented on source/solve.js
> +    }
В задании говорится "...строку с математическим выражением, зависящим от переменной x".
solve('2+2', 6); выполнится без проблем, хотя выражение не зависит от x

2023-09-07 20:36 UTC, fitzplsr commented
исправил нестрогое сравнение на строгое
описал в комментарии когда функции кидает исключения
добавил проверку на зависимость выражения от икса

2023-09-07 20:42 UTC, Ivan-Bir approved these changes

2023-09-10 21:37 UTC, DPeshkoff requested changes
Привет! Поздравляю с переходом на второй семестр)

Хорошее решение получилось, но у меня есть пара замечаний. Если возникнут вопросы - можешь писать в [Telegram](t.me/DmPesh)

2023-09-10 21:37 UTC, DPeshkoff commented on source/solve.js
> +'use strict';
Распиши, пожалуйста, что это за строчка и зачем она нужна)

2023-09-10 21:37 UTC, DPeshkoff commented on source/solve.js
> +        throw new Error('Error: incorrect type of arguments');
В стандарте прописаны годные [типы ошибок](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Error#%D1%82%D0%B8%D0%BF%D1%8B_%D0%BE%D1%88%D0%B8%D0%B1%D0%BE%D0%BA), давай используем

2023-09-10 21:37 UTC, DPeshkoff commented on source/solve.js
> + * @throws Will throw an error if the expression won't depend on x.
... и типы надо будет отразить в JSDoc

2023-09-10 21:37 UTC, DPeshkoff commented on source/solve.js
> +    if (typeof expression !== 'string' || typeof value !== 'number') {
Упс! 

![изображение](https://github.com/frontend-park-mail-ru/homework_2023_2/assets/31134795/5afd937a-9f4c-4dbd-a0a1-8d4662f11341)

При этом это валидные строки... непорядок! Давай подумаем, как это починить)

2023-09-10 21:37 UTC, DPeshkoff commented on tests/solve.js
> +			new Error('Error: incorrect number of arguments'),
Можно вынести в константу

2023-09-10 21:37 UTC, DPeshkoff commented on source/solve.js
> +    return eval(expression.replaceAll("x", value));
А я против даже такого eval'а)

Давай сделаем [правильнее](https://habr.com/ru/articles/555380/) и даже еще более безопасно)

<details><summary>Почему плох даже экранируемый eval?</summary>
<p>

- eval медленный
- eval часто нельзя нормально минифицировать)
- через eval можно получить доступ к области видимости на момент ее вызова - и потенциально слить для third-party то, чего им знать не следует

Подробнее [тут](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/eval#never_use_eval!)
</p>
</details>

2023-09-10 23:54 UTC, fitzplsr commented on source/solve.js
> +'use strict';
директива, которая включает строгий режим языка. нужно прописывать в начале файлов где не используются модули или классы

2023-09-10 23:58 UTC, fitzplsr commented
Добавил ошибки из стандарта
Изменил проверку типа строки
Заменил eval на калькулятор
вынес повторяющиеся ошибки в константы

2023-09-11 07:43 UTC, DPeshkoff commented on source/solve.js
> +'use strict';
А что входит в "строгий режим? Чем он отличается от обычного?

2023-09-11 07:47 UTC, DPeshkoff commented on source/solve.js
> +    if (String(expression) !== expression || typeof value !== 'number') {
Можно проверить expression на объектную строку без каста, через [проверку](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Operators/instanceof)

Ну и объединить со старой проверкой на plain-строку)

2023-09-11 16:08 UTC, fitzplsr commented on source/solve.js
> +'use strict';
Некоторые ошибки преобразуются в исключения, код в строгом режиме более оптимизирован и более безопасен

2023-09-11 16:10 UTC, fitzplsr commented
сделал проверку типа без каста к строке

2023-09-11 19:40 UTC, DPeshkoff approved these changes

2023-09-11 19:40 UTC, closed without merging