add variant-1
frontend-park-mail-ru/homework_2023_2 pull request #14
Opened 2023-09-07 08:40 UTC by TanyaEmka

2023-09-07 12:34 UTC, LDK28 commented on source/max.js
Привет! Я ментор программы Фронтенд разработки. Я буду проверять твое дз, так что в следующих комментариях опишу свои вопросики по коду :)

2023-09-07 12:34 UTC, LDK28 commented on source/max.js
Поменяй, пожалуйста, название ПР на "Фамилия Имя", чтобы нам в дальнейшем было проще его проверять

2023-09-07 12:34 UTC, LDK28 commented on source/max.js
> +const zip = (...objects) => {
Скрипт max.js - это пример, как надо сделать, так что надо будет убрать свой код отсюда и оставить только в файле с твоим решением. Чтобы тесты корректно сработали тебе нужно будет в index.html подключить скрипт со своим решением(аналогично скрипту max.js, строка 15)

2023-09-07 12:34 UTC, LDK28 commented on source/zip.js
> +const zip = (...objects) => {
Тут использована стрелочная функция. А чем она отличается от обычной?

2023-09-07 12:34 UTC, LDK28 commented on source/zip.js
> +}
По "канону" в конце файла с кодом должна быть пустая строчка

2023-09-07 18:10 UTC, TanyaEmka commented on source/max.js
Спасибо за все указания!

2023-09-07 18:12 UTC, TanyaEmka commented on source/zip.js
> +const zip = (...objects) => {
Стрелочная функция отличается тем, что она берёт контекст функции, внутри которой она находится

2023-09-07 18:13 UTC, TanyaEmka commented on source/zip.js
> +'use strict';
Это нужно для строго режима (чтобы не было небезопасных конструкций, нельзя было использовать уже занятые слова и пр.)

2023-09-09 15:03 UTC, LDK28 commented on source/zip.js
> +'use strict';
Да верно, по сути это позволяет писать в "современном" режиме

2023-09-10 13:15 UTC, LDK28 commented on source/zip.js
> +const zip = (...objects) => {
А если на вход функции будут поданы не объекты?

2023-09-10 13:15 UTC, LDK28 commented on tests/zip.js
> +	QUnit.test('Функция правильно работает с непустыми объектами, которые стоят в конце среди пустых объектов', function (assert) {
И в следствие предыдущему комменту, надо написать тесты, когда будут переданы не только объекты в функцию

2023-09-10 13:50 UTC, TanyaEmka commented on source/zip.js
> +const zip = (...objects) => {
Если не объекты, то вернётся пустой объект

2023-09-10 14:06 UTC, TanyaEmka commented on tests/zip.js
> +	QUnit.test('Функция правильно работает с непустыми объектами, которые стоят в конце среди пустых объектов', function (assert) {
Я добавила тесты, но также проверку на массивы и строки, потому что не понимаю, нужно ли их как-то иначе обрабатывать, хотя они тоже объекты
Спасибо за замечания

2023-09-11 10:38 UTC, LDK28 commented on source/zip.js
> +const zip = (...objects) => {
Давай лучше пробрасывать ошибку https://learn.javascript.ru/exception#operator-throw

2023-09-11 10:49 UTC, LDK28 requested changes

2023-09-11 10:49 UTC, LDK28 commented on source/zip.js
> +    let resultObject = {}
Объекты надо объявлять как `const`, так как ты меняешь не сам объект, а его содержимое

2023-09-11 18:59 UTC, TanyaEmka commented on source/zip.js
> +const zip = (...objects) => {
Добавила пробрасывание и проверку ошибки

2023-09-12 09:08 UTC, LDK28 requested changes

2023-09-12 09:08 UTC, LDK28 commented on source/zip.js
> +            throw new Error('TYPE ERROR IN ARGUMENTS')
Для ошибок в типах можно пробрасывать `TypeError`

2023-09-12 09:08 UTC, LDK28 commented on source/zip.js
> +        if (!Array.isArray(object) && typeof object !== 'string' && typeof object === 'object') {
Как то здесь немного замудрено. Лучше сделать проверку на тип, если передано не то, то бросать ошибку, а логику уже просто ниже писать, чтобы условными ветвлениями сильно не грузить код.
То есть 
`if (...) { throw ... }; Остальной код`

2023-09-12 09:08 UTC, LDK28 commented on source/zip.js
> +        if (!Array.isArray(object) && typeof object !== 'string' && typeof object === 'object') {
И как будто условие проверки не полное. Например `typeof null` равен `object`

2023-09-12 09:08 UTC, LDK28 commented on tests/zip.js
> +			Error("TYPE ERROR IN ARGUMENTS")
Тут тогда тоже надо будет с `TypeError` тесты написать

2023-09-12 13:18 UTC, TanyaEmka commented on tests/zip.js
> +			Error("TYPE ERROR IN ARGUMENTS")
Добавила исправления в обработку ошибок

2023-09-12 15:13 UTC, LDK28 commented on source/zip.js
> +        if (Array.isArray(object) || typeof object === 'string' || typeof object !== 'object' || object === null)
Для чего здесь проверка на строку?

2023-09-12 18:02 UTC, TanyaEmka commented on source/zip.js
> +        if (Array.isArray(object) || typeof object === 'string' || typeof object !== 'object' || object === null)
Потому что строка тоже объект, и если не делать проверку, то она также будет проходить обработку. Мне показалось, что строка слишком необычный объект для такой функции

2023-09-13 12:07 UTC, LDK28 commented on source/zip.js
> +        if (Array.isArray(object) || typeof object === 'string' || typeof object !== 'object' || object === null)
В общем, как будто эта проверка здесь лишняя 
<img width="129" alt="image" src="https://github.com/frontend-park-mail-ru/homework_2023_2/assets/66313699/79f7b3df-dafd-4375-9494-867ee61b92c3">

2023-09-13 15:10 UTC, TanyaEmka commented on source/zip.js
> +        if (Array.isArray(object) || typeof object === 'string' || typeof object !== 'object' || object === null)
Да, это так, но строка всё равно будет обработана как объект, если вызвать для неё один из методов для объектов. В любом случае, я удалила эту проверку, если она действительно лишняя

2023-09-13 16:15 UTC, LDK28 commented on source/zip.js
> +        if (Array.isArray(object) || typeof object === 'string' || typeof object !== 'object' || object === null)
> Да, это так, но строка всё равно будет обработана как объект, если вызвать для неё один из методов для объектов. В любом случае, я удалила эту проверку, если она действительно лишняя

Не торопись, я могу быть не прав :)
Ты же проверяешь typeof object !== 'object'. По сути эта же проверка исключит строку?

2023-09-13 16:27 UTC, TanyaEmka commented on source/zip.js
> +        if (Array.isArray(object) || typeof object === 'string' || typeof object !== 'object' || object === null)
1. Нет, не исключит, потому что вернётся тип 'string'. При этом если для переменной вызвать функции объекта вроде Object.entries, то это сработает. Вроде функция вернёт объект с ключами в виде букв строки, а это немного неожиданный результат (как мне кажется), поэтому я и добавляла проверку.
2. В случае String я вижу только проверку через instanceof.

2023-09-13 16:53 UTC, LDK28 commented on source/zip.js
> +        if (Array.isArray(object) || typeof object === 'string' || typeof object !== 'object' || object === null)
1. У тебя же обязательно typeof должен отдать 'object', а значит строка простая просто не пройдет до Object.entries. Или я что-то не так понимаю?
2. Вот тут верно подмечено, имеет смысл добавить эту проверку

2023-09-13 17:00 UTC, TanyaEmka commented on source/zip.js
> +        if (Array.isArray(object) || typeof object === 'string' || typeof object !== 'object' || object === null)
1. Да, поняла, в чём дело. Прошу прощения, что немного запуталась

2023-09-14 11:01 UTC, LDK28 commented on source/zip.js
> +        if (Array.isArray(object) || typeof object === 'string' || typeof object !== 'object' || object === null)
Дава тогда еще и на `instanceof Number` проверим

2023-09-14 11:02 UTC, LDK28 commented on source/zip.js
> +        if (Array.isArray(object) || typeof object === 'string' || typeof object !== 'object' || object === null)
И так как условие становится большим, то по хорошему код стайлу надо каждое условие проверки на новой строке написать

2023-09-14 13:12 UTC, TanyaEmka commented on source/zip.js
> +        if (Array.isArray(object) || typeof object === 'string' || typeof object !== 'object' || object === null)
Добавила новое условие и сделала переносы

2023-09-14 13:15 UTC, LDK28 approved these changes

2023-09-14 22:46 UTC, DPeshkoff requested changes
Привет! Поздравляю с переходом на второй семестр)

Классное решение получилось, но у меня есть пара замечаний. Если возникнут вопросы - можешь писать в [Telegram](t.me/DmPesh)

2023-09-14 22:46 UTC, DPeshkoff commented on source/zip.js
> +            throw new TypeError('TYPE ERROR IN ARGUMENTS')
Не забывай про точки с запятой! Несмотря на то, что парсер умеет автоматически их проставлять - иногда это приводит к странным результатам. 

<details><summary>Каким?</summary>
<p>
К примеру, тривиальный и понятный код:

![изображение](https://github.com/frontend-park-mail-ru/homework_2023_2/assets/31134795/3d22e9a8-baee-4bfb-886a-b4dfe665364a)

Внезапно падает:

![изображение](https://github.com/frontend-park-mail-ru/homework_2023_2/assets/31134795/582afa37-106b-4330-acaf-6a622c1cda61)

Почему так происходит, думаю, наглядно видно по тексту ошибки - он считает `[3]` частью `s`. Если при этом поставить ;, то код магически начинает работать)

![изображение](https://github.com/frontend-park-mail-ru/homework_2023_2/assets/31134795/9210ce09-d52b-40aa-9731-dd12424c685b)
</p>
</details> 

Давай везде проставим точки с запятой)

2023-09-15 07:41 UTC, TanyaEmka commented on source/zip.js
> +            throw new TypeError('TYPE ERROR IN ARGUMENTS')
Здравствуйте! 
Спасибо за указания, добавила точки с запятой

2023-09-15 19:19 UTC, DPeshkoff approved these changes

2023-09-15 19:19 UTC, closed without merging