Стома Фёдор
frontend-park-mail-ru/homework_2023_2 pull request #15
Opened 2023-09-07 11:56 UTC by StomaFedor

2023-09-07 16:17 UTC, Kostich31 commented
Привет! Добро пожаловать на курс по фронтенд-разработке. Я буду проверять твое ДЗ 0. Ниже будут мои вопросы и комментарии по коду.

2023-09-07 16:34 UTC, Kostich31 requested changes

2023-09-07 16:34 UTC, Kostich31 commented on source/chess.js
> +
Нужно добавить JSDoc к функции https://jsdoc.app/about-getting-started.html

2023-09-07 16:34 UTC, Kostich31 commented on source/chess.js
> +const chess = function (number) {
Ты объявил функцию через function. Расскажи, в чем разница между этим объявлением и стрелочным объявлением?

2023-09-07 16:34 UTC, Kostich31 commented on source/chess.js
> +    if (number <= 1 || number % 1 != 0) return null
В функцию могут быть переданы число или строка, нужно добавить явную проверку на эти типы.

2023-09-07 16:34 UTC, Kostich31 commented on source/chess.js
> +    if (number <= 1 || number % 1 != 0) return null
Название аргумента должно быть более информативным. Например, size.

2023-09-07 16:34 UTC, Kostich31 commented on source/chess.js
> +        for (let j = 0; j < number; j++) {
Слишком большое количество ветвлений. Кажется, что можно упростить алгоритм формирования шахматной доски, если объединить несколько if-else и использовать тернарный оператор https://learn.javascript.ru/ifelse

2023-09-07 16:34 UTC, Kostich31 commented on tests/chess.js
> +	QUnit.test('Шахматной доски с отрицательной стороной не бывает', function (assert) {
Добавь больше проверок на негативные сценарии с null, undefined, NaN и другими типами данных.

2023-09-07 16:38 UTC, Kostich31 requested changes

2023-09-07 16:38 UTC, Kostich31 commented on source/chess.js
> +}
Добавь, пожалуйста, пустую строку в конце файла.

2023-09-08 00:08 UTC, StomaFedor commented on source/chess.js
> +const chess = function (number) {
Насколько я понял, в большинстве своем это используется для более краткого и изящного кода. Но также стрелочные ф-ции отличаются тем, что у них нет this, arguments, а также они не могут быть использованы как конструкторы.

2023-09-08 16:14 UTC, Kostich31 requested changes

2023-09-08 16:14 UTC, Kostich31 commented on source/chess.js
> +'use strict';
Расскажи, что такое use strict.

2023-09-08 16:14 UTC, Kostich31 commented on tests/chess.js
> +		let x
А зачем объявлять переменную, если можно сразу передать undefined внутрь функции

2023-09-08 16:14 UTC, Kostich31 commented on source/chess.js
> + * @returns {string} Шахматная доска
Забыл указать тип входных параметров и тип null у возвращаемого значения

2023-09-08 16:15 UTC, Kostich31 commented on source/chess.js
> +const chess = function (number) {
Отлично. Тогда перепиши с использованием стрелочной функции, чтобы код стал более кратким и изящным.

2023-09-09 00:55 UTC, StomaFedor commented on source/chess.js
> +'use strict';
Для выполнения кода в строгом режиме. К примеру, нельзя использовать не объявленные переменные (как я понял, "строгий режим" не применяется по умолчанию для того, чтобы устаревший код работал

2023-09-09 00:57 UTC, StomaFedor commented on tests/chess.js
> +		let x
В принципе незачем. Показалось, так более наглядно. Исправил

2023-09-09 01:04 UTC, StomaFedor commented on source/chess.js
> + * @returns {string} Шахматная доска
Тип входных параметров указал, но не полностью. Не смог найти, как можно указать два типа значений в JSDoc (как для входных, так и выходных параметров)

2023-09-09 09:17 UTC, Kostich31 commented on source/chess.js
> + * @returns {string} Шахматная доска
@param {number|string} 
Прочитай в этом разделе https://jsdoc.app/tags-type.html

2023-09-09 09:19 UTC, Kostich31 commented on source/chess.js
> +'use strict';
А можешь расписать чуть подробнее, чем отличается выполнения кода в строгом режиме

2023-09-09 11:36 UTC, StomaFedor commented on source/chess.js
> + * @returns {string} Шахматная доска
Спасибо, сделал

2023-09-09 12:09 UTC, StomaFedor commented on source/chess.js
> +'use strict';
В строгом режиме ошибки в коде преобразуются в исключения. То, что в нестрогом режиме тихо даёт сбой, в строгом вызывает сообщение об ошибке. Также подключение строгого режима позволяет JS-движкам оптимизировать код.

2023-09-09 12:24 UTC, Kostich31 approved these changes

2023-09-10 23:08 UTC, DPeshkoff requested changes
Привет! Поздравляю с переходом на второй семестр)

Классное решение получилось, но у меня есть пара замечаний. Если возникнут вопросы - можешь писать в [Telegram](t.me/DmPesh)

2023-09-10 23:08 UTC, DPeshkoff commented on source/chess.js
> +        || boardSize <= 1 || boardSize % 1 != 0) return null
1) Хочу создать доску с `boardSize = Infinity`. Кто сможет со мной совладать?
2) Упс! 

![изображение](https://github.com/frontend-park-mail-ru/homework_2023_2/assets/31134795/5afd937a-9f4c-4dbd-a0a1-8d4662f11341)

При этом это валидные строки... непорядок! Давай подумаем, как это починить)
3) Лучше использовать одиночные кавычки и вытащить отрицание в сам оператор:
```suggestion
    if (typeof boardSize !== 'number' || typeof boardSize !== 'string'
        || boardSize <= 1 || boardSize % 1 != 0) return null
```
4) Выглядит, как кейс для [ошибки](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Error), давай используем

2023-09-10 23:08 UTC, DPeshkoff commented on source/chess.js
> +        for (let j = 0; j < boardSize; j++) {
Давай подумаем, как мы можем избавится от этих циклов и [использовать встроенные методы](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/String/repeat)

2023-09-10 23:08 UTC, DPeshkoff commented on source/chess.js
> +    return result
Не забывай про точки с запятой! Несмотря на то, что парсер умеет автоматически их проставлять - иногда это приводит к странным результатам. 

<details><summary>Каким?</summary>
<p>
К примеру, тривиальный и понятный код:

![изображение](https://github.com/frontend-park-mail-ru/homework_2023_2/assets/31134795/3d22e9a8-baee-4bfb-886a-b4dfe665364a)

Внезапно падает:

![изображение](https://github.com/frontend-park-mail-ru/homework_2023_2/assets/31134795/582afa37-106b-4330-acaf-6a622c1cda61)

Почему так происходит, думаю, наглядно видно по тексту ошибки - он считает `[3]` частью `s`. Если при этом поставить ;, то код магически начинает работать)

![изображение](https://github.com/frontend-park-mail-ru/homework_2023_2/assets/31134795/9210ce09-d52b-40aa-9731-dd12424c685b)
</p>
</details> 

Давай везде проставим точки с запятой)

2023-09-12 14:13 UTC, StomaFedor commented on source/chess.js
> +        for (let j = 0; j < boardSize; j++) {
Вроде бы как исправил

2023-09-13 10:13 UTC, DPeshkoff requested changes

2023-09-13 10:13 UTC, DPeshkoff commented on source/chess.js
> +    let result = (firstString + secondString).repeat(boardSize / 2) + firstString.repeat(boardSize % 2);
А чем let отличается от const? Почему тут выбрал именно так?

2023-09-13 12:15 UTC, StomaFedor commented on source/chess.js
> +    let result = (firstString + secondString).repeat(boardSize / 2) + firstString.repeat(boardSize % 2);
При объявлении переменной, как const, она не будет меняться после присвоения. При попытке ее изменить будет ошибка. В данном случае наверное правильнее было бы объявить переменные как const, на момент написания кода об этом не подумал. Исправил

2023-09-13 15:33 UTC, DPeshkoff approved these changes

2023-09-13 15:36 UTC, closed without merging