Variant 16
frontend-park-mail-ru/homework_2023_2 pull request #16
Opened 2023-09-07 12:16 UTC by flioletty

Степаненко Полина

2023-09-07 13:03 UTC, LDK28 commented on index.html
Когда поправишь замечания или если возникнут вопросы или сложности, можешь тегнуть меня тут или написать в тг https://t.me/dkey28

Также для себя можешь резолвить замечания/вопросы, когда решишь их, чтобы не мешались :)

2023-09-07 16:03 UTC, flioletty commented on source/format.js
> +    if(columns<0){
Упадет с ошибкой. Нужно сделать проверку на типы входных данных?

2023-09-07 16:03 UTC, flioletty commented on source/format.js
> +const format = function (numbers, columns) {
Стрелочная функция используется как я поняла для более краткой записи и еще this для нее передается от объекта с которым вызывается функция

2023-09-07 16:03 UTC, flioletty commented on source/format.js
> +'use strict';
Чтобы "включить" новые изменения в js, которые по умолчанию выключены чтобы работало все то, что написано на устаревшей версии языка

2023-09-07 16:07 UTC, flioletty commented on index.html
@LDK28, поправила вроде)

2023-09-09 14:52 UTC, LDK28 commented on source/format.js
> +    if(columns<0){
Да, нужно будет сделать проверку(и), и если что-то не так, то возвращать ошибку https://learn.javascript.ru/exception

2023-09-11 10:40 UTC, LDK28 requested changes

2023-09-11 11:48 UTC, LDK28 requested changes

2023-09-11 14:06 UTC, LDK28 requested changes

2023-09-11 14:06 UTC, LDK28 commented on source/format.js
> +
Надо написать JSDoc для функции https://habr.com/ru/articles/572968/
Устанавливать отображение для браузера не надо, только описание в коде

2023-09-11 15:01 UTC, LDK28 requested changes

2023-09-11 15:01 UTC, LDK28 commented on tests/format.js
> +		assert.throws(()=>format(inputArray, 2), new TypeError("An array of strings was passed as input instead of array of numbers"));
Зачем в тестах используются коллбэки?

2023-09-12 15:07 UTC, flioletty commented on tests/format.js
> +		assert.throws(()=>format(inputArray, 2), new TypeError("An array of strings was passed as input instead of array of numbers"));
На офф сайте qunit написано, что эта функция принимает callback (https://api.qunitjs.com/assert/throws/). Вообще они используются чтобы функции выполнялись в заданном порядке, тк в js функции выполняются не дожидаясь ответа от предыдущих. Но зачем они конкретно здесь я честно не знаю

2023-09-12 15:20 UTC, LDK28 commented on tests/format.js
> +		assert.throws(()=>format(inputArray, 2), new TypeError("An array of strings was passed as input instead of array of numbers"));
И в правду. Был не прав, прошу прощения

2023-09-13 10:42 UTC, DPeshkoff requested changes
Привет! Поздравляю с переходом на второй семестр)

Классное решение получилось, но у меня есть пара замечаний. Если возникнут вопросы - можешь писать в [Telegram](t.me/DmPesh)

2023-09-13 10:42 UTC, DPeshkoff commented on source/format.js
> +    if(Array.isArray(numbers) === false){
Можно проще - не проверять на false, а вынести отрицание ! в начало

2023-09-13 10:42 UTC, DPeshkoff commented on source/format.js
> +        return ''
Не забывай про точки с запятой! Несмотря на то, что парсер умеет автоматически их проставлять - иногда это приводит к странным результатам. 

<details><summary>Каким?</summary>
<p>
К примеру, тривиальный и понятный код:

![изображение](https://github.com/frontend-park-mail-ru/homework_2023_2/assets/31134795/3d22e9a8-baee-4bfb-886a-b4dfe665364a)

Внезапно падает:

![изображение](https://github.com/frontend-park-mail-ru/homework_2023_2/assets/31134795/582afa37-106b-4330-acaf-6a622c1cda61)

Почему так происходит, думаю, наглядно видно по тексту ошибки - он считает `[3]` частью `s`. Если при этом поставить ;, то код магически начинает работать)

![изображение](https://github.com/frontend-park-mail-ru/homework_2023_2/assets/31134795/9210ce09-d52b-40aa-9731-dd12424c685b)
</p>
</details> 

Давай везде проставим точки с запятой)

2023-09-14 22:48 UTC, DPeshkoff requested changes

2023-09-14 22:48 UTC, DPeshkoff commented on source/format.js
> +    if(typeof(columns) !== "number"){
поправь на одиночные кавычки везде, где двойные)

а еще давай добавим пустых строк между if для читаемости

2023-09-15 19:20 UTC, DPeshkoff approved these changes

2023-09-15 19:20 UTC, closed without merging