Сиканов Максим (8 вариант)
frontend-park-mail-ru/homework_2023_2 pull request #17
Opened 2023-09-07 13:41 UTC by Max425

2023-09-07 17:45 UTC, Ivan-Bir commented
Привет!
Добро пожаловать на курс по фронтенд-разработке 👋
Я буду проверять твое дз0. Ниже я оставлю комментарии по коду. Можно отвечать здесь или написать мне в телеграмм @Ivanchello_br.

2023-09-07 18:12 UTC, Ivan-Bir requested changes

2023-09-07 18:12 UTC, Ivan-Bir commented on tests/sort.js
> +		assert.strictEqual(sort('Rrrrrrrr'), 'Rrrrrrrr');
Согласен, похоже на ошибку в задании

2023-09-07 18:12 UTC, Ivan-Bir commented on tests/sort.js
>  });
С позитивными кейсами ок. Давай подумаем какие тут могут быть негативные кейсы

2023-09-07 18:12 UTC, Ivan-Bir commented on source/sort.js
> +
Хорошие разработчики документируют свой код.
Давай добавим JSDoc к функции https://jsdoc.app/about-getting-started.html

2023-09-07 18:12 UTC, Ivan-Bir commented on source/sort.js
> +        return sortedWord.charAt(0).toUpperCase() + sortedWord.slice(1);
Можно написать в одну строку используя метод объединения, но это остаётся на твой вкус

2023-09-07 19:18 UTC, Max425 commented on source/sort.js
> +        return sortedWord.charAt(0).toUpperCase() + sortedWord.slice(1);
пробовал, но не знаю как в одну строку сделать первый символ прописным, а остальные строчными

2023-09-07 19:19 UTC, Max425 commented on tests/sort.js
>  });
раз JS с динамической типизацией, то нужно обрабатывать случаи, если передают параметр другого типа?

2023-09-07 19:20 UTC, Max425 commented on source/sort.js
> +
добавил

2023-09-07 19:21 UTC, Max425 commented on source/sort.js
> +    .sort((a, b) => a.localeCompare(b, 'ru'))
Тест ыс буквой Ё падают иначе

2023-09-07 19:22 UTC, Max425 commented on source/sort.js
> +const sort = inputString => inputString.split(" ")
map((element) => {
В таких случаях тоже стоит добавлять скобки или нет?

2023-09-08 19:58 UTC, Ivan-Bir commented on source/sort.js
> +const sort = inputString => inputString.split(" ")
да

2023-09-08 20:00 UTC, Ivan-Bir commented on source/sort.js
> +    .sort((a, b) => a.localeCompare(b, 'ru'))
ок

2023-09-08 20:02 UTC, Ivan-Bir commented on tests/sort.js
>  });
конечно

2023-09-08 20:35 UTC, Ivan-Bir requested changes

2023-09-08 20:35 UTC, Ivan-Bir commented on source/sort.js
> + * @throws Выкинет ошибку, если тип переданного параметнра не String.
не лишним будет добавить тип ошибки в {}
https://jsdoc.app/tags-throws.html

2023-09-08 20:35 UTC, Ivan-Bir commented on source/sort.js
> +        .map(element => element.split('')
(arg1) для стрелочных функций здесь и далее

2023-09-08 20:35 UTC, Ivan-Bir commented on source/sort.js
> +                .replace(/^[^ ]/g, letter => (letter.toUpperCase()))
Сам писал регулярку?
Для чего флаг g?
Почему использовал именно пробел в диапазоне?
Какие кейсы такая регурялка как /^./ не покрывает?

2023-09-08 20:35 UTC, Ivan-Bir commented on source/sort.js
> +    if (typeof inputString !== 'string')
а пустая строка это валидное значение?
Давай и тест на это добавим

2023-09-08 20:38 UTC, Ivan-Bir commented on source/sort.js
> +    if (typeof inputString !== 'string')
Upd: тест увидел, но можно сразу вернуть значение, а не гонять ресурсы

2023-09-08 20:40 UTC, Ivan-Bir commented
Если нужно повторное ревью, то можно сразу писать в тг

2023-09-09 09:55 UTC, Ivan-Bir requested changes

2023-09-09 09:55 UTC, Ivan-Bir commented on source/sort.js
> +    return inputString === '' ? inputString :
Можно не городить, а в начале функции написать
if (!inputString) {
    return ...;
}
И код станет читаемее

как идёт преобразование в логические типы можно почитать тут
https://learn.javascript.ru/type-conversions#logicheskoe-preobrazovanie

2023-09-09 09:55 UTC, Ivan-Bir commented on source/sort.js
> + * @throws {InvalidArgumentException} - Выкинет ошибку, если тип переданного параметнра не String.
Опечатался

2023-09-09 11:13 UTC, Max425 commented on source/sort.js
> +                .replace(/^[^ ]/g, letter => (letter.toUpperCase()))
регулярку в интернете нашёл) 
/^[^ ]/ - поиск первого символа в строке не равному пробелу. Так как я делаю сплит по пробелу, то регулярка просто укажет на первый символ в любом случае.
Флаг g можно убрать, ведь нам не нужен глобальный поиск.
 /^./ тоже соответствует первому символу в строке, кроме \n. Поэтому такой способ конкретно в моём решении также покроет все кейсы, ведь в моём решении есть допущение, разделитель - пробел.

2023-09-09 11:56 UTC, Ivan-Bir requested changes

2023-09-09 11:56 UTC, Ivan-Bir commented on source/sort.js
> +        return inputString;
Описание по jsdoc не соответствует действительности @returns {string}
Здесь же ты возвращаешь то, что придёт на вход. Так, если передать 0, вернётся number. Другие разработчики будут сильно негодовать, если при дебаге придут к этому месту.
Ещё тесткейс на это давай напишем

2023-09-09 11:56 UTC, Ivan-Bir commented on source/sort.js
> +                .replace( /^[^ ]/, letter => (letter.toUpperCase()))
пробел сюда можно не добавлять, .replace(/^[^ ]/, вполне смотрится
Не исправил предыдущее замечание про агрументы функции в (). А вот тело можно и без скобок :)

2023-09-10 21:49 UTC, DPeshkoff requested changes
Привет! Поздравляю с переходом на второй семестр)

Крутое решение получилось, но у меня есть пара замечаний. Если возникнут вопросы - можешь писать в [Telegram](t.me/DmPesh)

2023-09-10 21:49 UTC, DPeshkoff commented on source/sort.js
> +'use strict';
Распиши, пожалуйста, что это за строчка и зачем она нужна)

2023-09-10 21:49 UTC, DPeshkoff commented on source/sort.js
> +    if (typeof inputString !== 'string')
Упс! 

![изображение](https://github.com/frontend-park-mail-ru/homework_2023_2/assets/31134795/5afd937a-9f4c-4dbd-a0a1-8d4662f11341)

При этом это валидные строки... непорядок! Давай подумаем, как это починить)

2023-09-10 21:49 UTC, DPeshkoff commented on source/sort.js
> +        throw new Error('Входной аргумент должен быть строкой');
В стандарте прописаны годные [типы ошибок](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Error#%D1%82%D0%B8%D0%BF%D1%8B_%D0%BE%D1%88%D0%B8%D0%B1%D0%BE%D0%BA), давай используем

2023-09-10 21:49 UTC, DPeshkoff commented on source/sort.js
> +        .sort((a, b) => a.localeCompare(b, 'ru'))
Получилось немного дублирование со строкой 20 - давай вынесем эту функцию отдельно

2023-09-10 21:49 UTC, DPeshkoff commented on source/sort.js
> +    if (!inputString)
Давай добавим скобки для читаемости)

2023-09-13 20:50 UTC, Max425 commented on source/sort.js
> +'use strict';
Это установка строгого режима.
Строгий режим влияет и на синтаксис кода, и на то, как код ведёт себя во время выполнения программы. Ошибки в коде преобразуются в исключения. То, что в нестрогом режиме тихо даёт сбой, в строгом вызывает сообщение об ошибке

2023-09-14 11:28 UTC, DPeshkoff requested changes

2023-09-14 11:28 UTC, DPeshkoff commented on source/sort.js
> +function customSort(a, b) {
Почему function?

2023-09-14 11:28 UTC, DPeshkoff commented on source/sort.js
> +}
Нужна новая строка в конце файла

2023-09-14 13:25 UTC, Max425 commented on source/sort.js
> +function customSort(a, b) {
исправил на стрелочную, почему то подумал что стрелочную не будет видно из-за разной области видимости.

2023-09-14 22:49 UTC, DPeshkoff requested changes

2023-09-14 22:49 UTC, DPeshkoff commented on source/sort.js
> +const customSort = (a, b) => {
А еще давай накинем к этой функции JSDoc)

2023-09-14 22:57 UTC, Max425 commented on source/sort.js
> +const customSort = (a, b) => {
Проверку типов для второй функции тоже добавить?)

2023-09-15 19:24 UTC, DPeshkoff approved these changes

2023-09-15 19:24 UTC, DPeshkoff commented on source/sort.js
> +const customSort = (a, b) => {
если она внутренняя и приватная - не обязательно)

2023-09-15 19:24 UTC, closed without merging