Османов Ислам(Вариант 2)
frontend-park-mail-ru/homework_2023_2 pull request #18
Opened 2023-09-07 13:56 UTC by JuFnd

2023-09-07 18:13 UTC, Ivan-Bir commented
Привет!
Добро пожаловать на курс по фронтенд-разработке 👋
Я буду проверять твое дз0. Ниже я оставлю комментарии по коду. Можно отвечать здесь или написать мне в телеграмм @Ivanchello_br.

2023-09-07 18:39 UTC, Ivan-Bir requested changes
Хорошая работа, небольшие правки и готово

2023-09-07 18:39 UTC, Ivan-Bir commented on source/euclid.js
> +const euclid = (...args) => {
Хорошие разработчики документируют свой код.
Давай добавим JSDoc к функции https://jsdoc.app/about-getting-started.html

2023-09-07 19:50 UTC, JuFnd commented on source/euclid.js
> +const euclid = (...args) => {
+

2023-09-07 20:40 UTC, Ivan-Bir requested changes

2023-09-07 20:40 UTC, Ivan-Bir commented on source/euclid.js
> +  const isValid = args.every(arg => typeof arg === 'number' && !isNaN(arg));
1. а зачем нам лишняя переменная?
2. давай всегда аргументы стрелочной функции писать в (), независимо от их количества
3. а Infinity мы разрешаем?
4. и без аргументов тоже норм?

2023-09-07 20:40 UTC, Ivan-Bir commented on tests/euclid.js
> +    assert.strictEqual(euclid(1, "123", 1), null, 'euclid(1, 1.5, 1) должна вернуть null');
пояснение теста проглядел

2023-09-07 20:40 UTC, Ivan-Bir commented on tests/euclid.js
>  });
Добавилось кейсов, извольте тесты

2023-09-08 08:25 UTC, JuFnd commented on tests/euclid.js
>  });
+

2023-09-08 09:50 UTC, Ivan-Bir requested changes
Форматирование по мелочи

2023-09-08 09:50 UTC, Ivan-Bir commented on source/euclid.js
> +  if (!args.every((arg) => typeof arg === 'number' && !isNaN(arg) && arg !== Infinity && arg !== Number.MAX_VALUE)) {
Обычно такой код сложно читать, поэтому его форматируют, разбивая на несколько строк
if (...
&& ...
&& ...
) {

2023-09-08 09:50 UTC, Ivan-Bir commented on tests/euclid.js
> +    assert.strictEqual(euclid('abc'), null, 'euclid("abc") возвращает null при передаче некорректного аргумента');
Если уже выбрал какие-то кавычки, то используй их везде

2023-09-08 09:50 UTC, Ivan-Bir commented on tests/euclid.js
>      assert.strictEqual(euclid(1, 1.5, "abc"), null, 'euclid(1, 1.5, "abc") должна вернуть null');
Давай лучше одинарные использовать ' '. Современные линтеры на это ругается, советую приучаться к ним

2023-09-10 22:44 UTC, DPeshkoff requested changes
Привет! Поздравляю с переходом на второй семестр)

Крутое решение получилось, но у меня есть пара замечаний. Если возникнут вопросы - можешь писать в [Telegram](t.me/DmPesh)

2023-09-10 22:44 UTC, DPeshkoff commented on index.html
> -<script src="tests/max.js"></script>
Давай вернем - не надо выпиливать то, что не требуется выпилить по заданию)

2023-09-10 22:44 UTC, DPeshkoff commented on source/euclid.js
> +'use strict';
Распиши, пожалуйста, что это за строчка и зачем она нужна)

2023-09-10 22:44 UTC, DPeshkoff commented on source/euclid.js
> +    return null;
Предлагаю выбрасывать [ошибку](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Error)

2023-09-10 22:44 UTC, DPeshkoff commented on source/euclid.js
> +const calculateGCD = (a, b) => {
А если на входе будут 1, 1? Зачем нам так сложно?)

2023-09-10 22:44 UTC, DPeshkoff commented on source/euclid.js
> +  }
А если b > a?

2023-09-10 22:44 UTC, DPeshkoff commented on source/euclid.js
> +  return a;
Ну и по неймингу - лучше избегать названий переменных вроде a, b, давай порефакторим немного)

2023-09-10 22:44 UTC, DPeshkoff commented on source/euclid.js
> +  if (args.length === 0) {
Немного странно сначала проверять каждый элемент в аргументах функции, а затем кейс, когда их нет. По логике нужно наоборот

2023-09-10 22:44 UTC, DPeshkoff commented on source/euclid.js
> +  if (!args.every((arg) => typeof arg === 'number' && !isNaN(arg) && arg !== Infinity && arg !== Number.MAX_VALUE)) {
А если будет -Infinity? Вообще для такой проверки есть классная функция)

Кстати, распиши, пожалуйста, чем `isNaN` отличается от `Number.isNaN` + почему ты выбрал именно такой вариант)

2023-09-10 22:44 UTC, DPeshkoff commented on tests/euclid.js
> -	QUnit.test('Функция должна правильно находить НОД трёх натуральных чисел', function (assert) {
Давай вернем отступы как было)

2023-09-11 21:18 UTC, JuFnd commented on source/euclid.js
> +'use strict';
Строгий режим выполнения кода. Позволяет избежать ошибок и неоднозначностей вроде необъявленных переменных. Повышает безопасность кода.

2023-09-11 21:18 UTC, JuFnd commented on source/euclid.js
> +  if (!args.every((arg) => typeof arg === 'number' && !isNaN(arg) && arg !== Infinity && arg !== Number.MAX_VALUE)) {
isNan преобразовывает переданный аргумент в число, а Number.isNan нет. isNan потому что аргументы могут быть не только числами т.к нет уверенности что может быть передано только число

2023-09-11 21:18 UTC, JuFnd commented on source/euclid.js
> +  }
они будут поменяны местами

2023-09-12 11:34 UTC, DPeshkoff requested changes

2023-09-12 11:34 UTC, DPeshkoff commented on source/euclid.js
> +  if (!args.every((arg) => typeof arg === 'number' && !isNaN(arg) && isFinite(arg) && arg !== Number.MAX_VALUE)) {
`isFinite` уже проверяет на NaN

2023-09-12 11:35 UTC, DPeshkoff commented on source/euclid.js
> +const calculateGCD = (firstNumber, secondNumber) => {
Кейс 1,1 можно оптимизировать, вынеся в отдельную проверку перед циклом)

2023-09-13 10:14 UTC, DPeshkoff approved these changes

2023-09-13 10:15 UTC, closed without merging