Add filter implementation
frontend-park-mail-ru/homework_2023_2 pull request #19
Opened 2023-09-07 14:20 UTC by osperelygin

Привет! Меня зовут Перелыгин Олег, студент группы web-21

2023-09-07 14:36 UTC, johnSamilin commented
Привет, добро пожаловать на курс по фронтенд-разработке. Я буду проверять твое ДЗ 0.
Если у меня появятся комментарии к коду, то я опишу их здесь. Можешь отвечать на них тут же, а чтобы что-то уточнить - [телеграм](https://t.me/WatasheeBaka)

2023-09-08 06:58 UTC, johnSamilin requested changes

2023-09-08 06:58 UTC, johnSamilin commented on index.html
>  <div id="qunit-fixture"></div>
Поправь, пожалуйста, название PR. Оно должно быть в формате "Имя Фамилия"

2023-09-08 06:58 UTC, johnSamilin commented on source/filter.js
> +    return input
Это не совсем правильная реализация. Функция должна фильтровать HTML-код, то есть убирать теги совсем вместе с их содержимым

2023-09-08 06:58 UTC, johnSamilin commented on source/filter.js
> +const filter = (input, validTags) => {
Допиши пожалуйста JSDoc для функции

2023-09-08 06:58 UTC, johnSamilin commented on source/filter.js
> +    const ltRegExp = new RegExp(`\<(?!(\/?)(${tags})[\s\>]+)`, "g"),
Добавь пожалуйста обработку случая, когда теги записаны в верхнем регистре

2023-09-08 06:58 UTC, johnSamilin commented on source/filter.js
> +}
В конец файла стоит добавлять пустую строчку, чтобы при следующих изменениях их было чуть меньше

2023-09-08 12:12 UTC, osperelygin commented on source/filter.js
> +    const tags = validTags?.join('|');
Будет ошибка... Добавил проверку второго параметра функции на массив. Так норм или лучше по-другому обрабатывать?

2023-09-08 12:18 UTC, osperelygin commented on source/filter.js
> +}
Она и была, и есть на локале. Видимо, когда через vs code пушу последняя пустая строка автоматически обрезается. Надо конфиг файл vs code'a отредачить

2023-09-08 14:29 UTC, johnSamilin requested changes

2023-09-08 14:29 UTC, johnSamilin commented on source/filter.js
> +/** @function */
Это не информативный JSDoc. Там должно быть описание функции и типы параметров и возвращаемого значения

2023-09-08 14:29 UTC, johnSamilin commented on source/filter.js
> +const filter = (input, validTags) => {
было бы неплохо еще иметь возможность просто вызвать filter с одним аргументом и получить безопасный вывод

2023-09-11 08:02 UTC, johnSamilin commented on source/filter.js
> + * @param {string[]} validTags - Valid http-tags
HTML tags

2023-09-11 08:02 UTC, johnSamilin approved these changes

2023-09-12 11:59 UTC, DPeshkoff requested changes
Привет! Поздравляю с переходом на второй семестр)

Классное решение получилось, но у меня есть пара замечаний. Если возникнут вопросы - можешь писать в [Telegram](t.me/DmPesh)

2023-09-12 11:59 UTC, DPeshkoff commented on source/filter.js
> +'use strict';
Распиши, пожалуйста, зачем эта строчка нужна? Почему ты ее решил использовать?

2023-09-12 11:59 UTC, DPeshkoff commented on source/filter.js
> + * @param {string[]} validTags - Valid http-tags
+1, давай поменяем на html)

2023-09-12 11:59 UTC, DPeshkoff commented on source/filter.js
> +        return;
Ошибки лучше выбрасывать через throw - так их можно в дальнейшем отловить через блок try...catch

2023-09-12 11:59 UTC, DPeshkoff commented on source/filter.js
> +    if (typeof input !== "string") {
Упс! 

![изображение](https://github.com/frontend-park-mail-ru/homework_2023_2/assets/31134795/5afd937a-9f4c-4dbd-a0a1-8d4662f11341)

При этом это валидные строки... непорядок! Давай подумаем, как это починить)

А еще в JS принято строки оборачивать в одиночные кавычки, а не двойные - давай сделаем так же?)

2023-09-12 11:59 UTC, DPeshkoff commented on tests/filter.js
> +	});
Нужны еще тесты на некорректный ввод)

2023-09-13 08:59 UTC, osperelygin commented on source/filter.js
> +'use strict';
Чтобы включить строгий режим. C появлением ES5 добавились новые возможности в js и изменились некоторые из существующих, следовательно, появились проблемы обратной совместимостью, которые использование данной директивы позволяет решить

2023-09-13 15:43 UTC, DPeshkoff requested changes

2023-09-13 15:43 UTC, DPeshkoff commented on source/filter.js
> + * @return {string} - String with escaped special characters
throws сюда тоже надо

2023-09-13 15:43 UTC, DPeshkoff commented on source/filter.js
> +    if (!Array.isArray(validTags) || validTags.some( (item) => typeof(item) !== 'string') ) {
По логике не some, а every
Да и вторые строки туда тоже

2023-09-14 11:30 UTC, DPeshkoff approved these changes

2023-09-14 11:31 UTC, closed without merging