Variant 10
frontend-park-mail-ru/homework_2023_2 pull request #2
Opened 2023-09-05 21:12 UTC by ambushidozho

Белокопытов Даниил

2023-09-06 07:03 UTC, LDK28 commented
Привет! Я ментор программы Фронтенд разработки. Я буду проверять твое дз, так что в следующих комментариях опишу свои вопросики по коду :)

2023-09-06 07:04 UTC, LDK28 commented
Поменяй, пожалуйста, название ПР на "Фамилия Имя", чтобы нам в дальнейшем было проще его проверять

2023-09-06 07:08 UTC, LDK28 commented
Нужно также написать свои тесты к функции

2023-09-06 07:08 UTC, LDK28 commented on source/letters.js
> +'use strict';
Для чего используется use strict?

2023-09-06 07:09 UTC, LDK28 commented on source/letters.js
> +function letters(input, flag)
Можно ли здесь использовать стрелочную функцию? И в чем их разница?

2023-09-06 07:10 UTC, LDK28 commented on source/letters.js
> +}
По "канону" в конце файла надо пустую строку поставить :)

2023-09-06 07:12 UTC, LDK28 commented on source/letters.js
> +{
Если в input будет передано число, а в flag строка, правильно ли отработает функция?

2023-09-06 07:13 UTC, LDK28 commented on source/letters.js
> +        return str.filter((item, index) =>
Напиши, пожалуйста, свою реализацию функции фильтрации и используй ее

2023-09-06 07:14 UTC, LDK28 commented
Также надо написать JSDoc к функции https://jsdoc.app/about-getting-started.html

2023-09-06 07:20 UTC, LDK28 commented
Когда поправишь замечания, можешь тегнуть меня тут или в написать в тг https://t.me/dkey28

Также для себя можешь резолвить замечания/вопросы, когда решишь их

2023-09-06 07:56 UTC, ambushidozho commented on source/letters.js
> +'use strict';
use strict нужен чтобы ограничить синтаксис js. Вследствие чего, код выглядит более чистым. Ну и ошибки искать легче в чистом коде.

2023-09-06 08:21 UTC, ambushidozho commented on source/letters.js
> +        return str.filter((item, index) =>
Как называется техника, я не знаю, попробовал погуглить четкого термина не нашел. Но насколько я понимаю, это прием из функционального программирования. В данном задании я бы мог сохранять результат работы фильтров в переменную и в конце делать return, но для краткости, и чтобы избавиться от лишней переменной, я сделал 3 return'а

2023-09-06 10:36 UTC, LDK28 commented on source/letters.js
> +'use strict';
Напиши, пожалуйста, чуть подробнее про "ограничить синтаксис". Что именно это ограничивает?

2023-09-06 10:38 UTC, LDK28 commented on source/letters.js
> +function letters(input, flag)
Да, все верно! Так как в данном случае нет работы с контекстом, то перепеши, пожалуйста, функцию на стрелочную, чтобы было меньше кода и выглядел он посовременнее 😁

2023-09-06 19:02 UTC, ambushidozho commented on source/letters.js
> +'use strict';
1. Нельзя использовать переменные без объявления
2. Параметры функции нельзя называть одинаково
3. Нельзя пользоваться словами (let, interface и т.д.), которые зарезервированы языком
Ну из того с чем сам сталкивался вроде всё. Ещё прочитал что this не будет ссылаться на глобальный обьект при включенном use strict. Ещё было написано про небезопасные конструкции, но никогда не работал с таким, поэтому не понял что это значит (там про with и eval())

2023-09-06 19:02 UTC, ambushidozho commented on source/letters.js
> +function letters(input, flag)
Сделано!

2023-09-06 19:02 UTC, ambushidozho commented on source/letters.js
> +}
Сделано)

2023-09-06 19:02 UTC, ambushidozho commented on source/letters.js
> +{
Функция крашнется из за того что у нее не получится применить необходимые методы (например split). Нужно написать так чтобы с любыми параметрами не крашилось?

2023-09-06 19:02 UTC, ambushidozho commented on source/letters.js
> +        return str.filter((item, index) =>
Сделано!

2023-09-07 10:17 UTC, LDK28 commented on source/letters.js
> +'use strict';
Да все верно! Если просто сказать, то позволяет писать код в "Современном режиме"

2023-09-07 10:18 UTC, LDK28 commented on source/letters.js
> +{
Да все верно, нужно обработать как все крайние случаи, так и ошибочные варианты

2023-09-07 10:27 UTC, LDK28 commented on source/letters.js
> +let filter = (func, str) =>
Функции нужно объявлять как const. Мы же после ее менять не будем, поэтому для читабельности кода надо использовать const

2023-09-07 10:27 UTC, LDK28 commented on documentation/files.html
> +<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
Не совсем понял, зачем меняешь html'ки, тебе надо откатить эти изменения и всего лишь подключить файл скрипта с твоей функцией

2023-09-07 10:27 UTC, LDK28 commented on documentation/symbols/_global_.html
> +<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
Аналогично, полностью менять или добавлять html'ки не надо

2023-09-07 10:27 UTC, LDK28 commented on index.html
> +<script src="source/letters.js"></script>
Этого достаточно для отработки тестов

2023-09-07 10:27 UTC, LDK28 commented on tests/letters.js
> +		assert.strictEqual(letters('', true), '');
Напиши еще, пожалуйста, тесты с полной строкой и флагом

2023-09-07 10:36 UTC, LDK28 commented on source/letters.js
> +        return str.filter((item, index) =>
Прошу прощения, неправильно прочитал код. Возврат функции из функции - это каррирование(на досуге можешь почитать). У тебя же здесь используется [коллбэк](https://learn.javascript.ru/callbacks) внутри функции фильтрации. Его нужно немного более красиво оформить. Так как у тебя кроме сравнения нет никаких действий в коллбэке, то можно опустить фигурные скобки и return. 
`return filter((item) => str.lastIndexOf(item) === str.indexOf(item), str);`

Либо же, если все таки хочешь писать с со скобками, то надо табулировать коллбэк.

`
return filter((item) =>
        {
            return str.lastIndexOf(item) === str.indexOf(item); 
        }, str);
`

2023-09-07 10:42 UTC, ambushidozho commented on documentation/files.html
> +<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
я же не менял html файлы это мне jsdoc создал эти файлы в html с тестами я просто скрипт подключил

2023-09-07 11:13 UTC, ambushidozho commented on source/letters.js
> +{
Сделано

2023-09-07 11:14 UTC, ambushidozho commented on source/letters.js
> +        return str.filter((item, index) =>
Сделано

2023-09-07 11:14 UTC, ambushidozho commented on source/letters.js
> +let filter = (func, str) =>
Сделано

2023-09-07 11:14 UTC, ambushidozho commented on tests/letters.js
> +		assert.strictEqual(letters('', true), '');
Сделано

2023-09-09 14:49 UTC, LDK28 commented on source/letters.js
> +/* Функция фильтрации элементов массива использюущая функцию-компаратор передаваемый как параметр func*/
JSDoc надо немного по другому писать
https://habr.com/ru/articles/572968/

2023-09-09 14:49 UTC, LDK28 commented on source/letters.js
> +/* функция letters в зависимости от переданных параметров удаляет неуникальные элементы из строки:
Тут тоже jsdoc надо будет поправить

2023-09-09 14:49 UTC, LDK28 commented on tests/letters.js
> +		assert.strictEqual(letters("nyx assasin", false), 'yx asin');
А если на вход функции подать например массив или объект? Надо написать максимально исчерпывающие тесты

2023-09-09 14:49 UTC, LDK28 commented on source/letters.js
> +    try {
По сути это излишний код, создавать ошибку в функции, ловить ее и возвращать строку - это тоже самое, что и просто вернуть строку по условию. 
Поэтому в таких функциях обычно не отлавливают ошибки, а просто их пробрасывают, а где-нибудь выше уже их перехватывают. Поэтому try...catch надо убрать

2023-09-09 14:49 UTC, LDK28 commented on source/letters.js
> +    if(flag)
Фигурные скобки по код стайлу лучше писать даже с одним действием в теле

2023-09-10 16:17 UTC, ambushidozho commented on source/letters.js
> +/* Функция фильтрации элементов массива использюущая функцию-компаратор передаваемый как параметр func*/
Вроде теперь нормально написал

2023-09-10 16:17 UTC, ambushidozho commented on tests/letters.js
> +		assert.strictEqual(letters("nyx assasin", false), 'yx asin');
Постарался написать исчерпывающие тесты.

2023-09-10 16:17 UTC, ambushidozho commented on source/letters.js
> +    try {
Не совсем понял, что нужно сделать, но вроде теперь просто возвращаю строку если тип параметров не тот что нужно.

2023-09-10 16:17 UTC, ambushidozho commented on source/letters.js
> +    if(flag)
Почитал про код стайл, хотел узнать по поводу 2 пробелов и табов
Увидел что правильно ставить 2 пробела внутри if например. Но привычка после плюсов таб ставить. Это сильно критично или в целом норм?

2023-09-11 10:25 UTC, LDK28 commented on source/letters.js
> +    try {
Не совсем то, что я имел ввиду. При обработке исключений, например, не корректный тип аргументов, лучше выбрасывать ошибку. Например `throw new Error()`. И в описании к ошибке уже писать что не так https://learn.javascript.ru/exception#operator-throw

2023-09-11 10:28 UTC, LDK28 commented on source/letters.js
> +    if(flag)
И в правду сразу перейти бывает сложно, но рано или поздно придется. Пока у тебя в дз только одна функция, тренируйся писать по хорошему код стайлу, чтобы не пришлось переучиваться/переделывать по ходу написания большого проекта.

2023-09-12 09:09 UTC, ambushidozho commented on source/letters.js
> +    try {
Ого, думал что все выброшенные ошибки должны обрабатываться и нельзя допускать завершения работы программы из-за выброшенной ошибки. Теперь понял что имеешь в виду. Переделаю.

2023-09-12 20:31 UTC, ambushidozho commented on source/letters.js
> +    if(flag)
скачал дополнение в vscode на форматировние кода, подойдёт такой код стайл?

2023-09-12 20:31 UTC, ambushidozho commented on source/letters.js
> +    try {
Сделано

2023-09-13 12:03 UTC, LDK28 requested changes

2023-09-13 12:03 UTC, LDK28 commented on source/letters.js
> +        if (func(str[i], i)) uniquestr.push(str[i]);
Давай ставить фигурные скобки, даже если в теле условия всего одно действие, чтобы код легче читался

2023-09-13 12:03 UTC, LDK28 commented on source/letters.js
> +"use strict";
После use strict надо пустую строку оставить по код стайлу

2023-09-13 12:03 UTC, LDK28 commented on source/letters.js
> +};
В конце файла надо пустую строку

2023-09-14 11:05 UTC, LDK28 commented on source/letters.js
> +    let uniquestr = [];
const

2023-09-14 11:07 UTC, LDK28 approved these changes

2023-09-14 11:36 UTC, DPeshkoff requested changes
Привет! Поздравляю с переходом на второй семестр)

Классное решение получилось, но у меня есть пара замечаний. Если возникнут вопросы - можешь писать в [Telegram](t.me/DmPesh)

2023-09-14 11:36 UTC, DPeshkoff commented on source/letters.js
> +"use strict";
1) Распиши, что делает эта строка
2) В JS приняты одиночные кавычки

2023-09-14 11:36 UTC, DPeshkoff commented on source/letters.js
> +    let uniquestr = [];
const.

Распиши, какие есть идентификаторы переменных в языке

2023-09-14 11:36 UTC, DPeshkoff commented on source/letters.js
> +    for (let i = 0; i < str.length; i++) {
Давай перебирающие методы)

2023-09-14 11:36 UTC, DPeshkoff commented on source/letters.js
> +        typeof input !== "string"
Упс! 

![изображение](https://github.com/frontend-park-mail-ru/homework_2023_2/assets/31134795/5afd937a-9f4c-4dbd-a0a1-8d4662f11341)

При этом это валидные строки... непорядок! Давай подумаем, как это починить)

2023-09-15 07:39 UTC, ambushidozho commented on source/letters.js
> +"use strict";
use strict ограничивает некоторые возможности языка, которые вносят неопределённость и увеличивают количество потенциальных ошибок. Например:
1. В строгом режиме вы должны объявить переменные с помощью ключевых слов var, let или const перед их использованием. В противном случае возникнет ошибка.
2. Строгий режим запрещает функции с повторяющимися именами параметров. При попытке использовать их возникнет синтаксическая ошибка.
3. Восьмеричные литералы (например, 0123) не допускаются в строгом режиме, и попытка их использования приведет к синтаксической ошибке. Вместо этого используйте префикс 0o для восьмеричных чисел.
4. В нестрогом режиме значение this внутри функции, вызываемой без явного получателя (например, в качестве отдельной функции, а не метода), по умолчанию равно глобальному объекту.
В строгом режиме this является undefined, что помогает предотвратить случайные изменения глобального объекта.
Также use strict меняет поведение eval и with но я ещё не сталкивался с ними поэтому не могу сказать про пользу use strict в этом случае.

2023-09-15 07:48 UTC, ambushidozho commented on source/letters.js
> +    let uniquestr = [];
Как я понял вопрос не про типы и названия переменных а лишь про идентификаторы по типу const.
В javascript существует ... идентификаторов переменных
1. let - современный способ обьявить переменную локально
2. var - устаревший способ обьявить переменную, так как в отличие от ключевого слова let, которое объявляет переменную локально внутри области видимости {}, var определяет переменную глобально что затрудняет работу с переменными и их именами. Так же переменные обьявленные с помощью var можно повторно инициализировать, что также является минусом
3. const - позволяет инициализировать константу, ну тут думаю понятен смысл) Тоже самое что let только переменную нельзя изменять.

2023-09-15 07:53 UTC, ambushidozho commented on source/letters.js
> +    for (let i = 0; i < str.length; i++) {
Дело в том что изначально я использовал метод filter из коробки, но ментор мне сказал написать свою функцию фильтрации. Поэтому, я так понял, от меня требуется foreach цикл вместо for. Исправил!)

2023-09-15 13:43 UTC, ambushidozho commented on source/letters.js
> +        typeof input !== "string"
Вроде бы поправил, жду ответа!

2023-09-15 19:13 UTC, DPeshkoff requested changes

2023-09-15 19:13 UTC, DPeshkoff commented on source/letters.js
> + * @returns {string} Строка состоящая из уникальных символов
throws в JSDoc

2023-09-15 19:47 UTC, ambushidozho commented on source/letters.js
> + * @returns {string} Строка состоящая из уникальных символов
Сделано!

2023-09-16 20:05 UTC, DPeshkoff approved these changes

2023-09-16 20:05 UTC, closed without merging