Мамадаев Муслим
frontend-park-mail-ru/homework_2023_2 pull request #20
Opened 2023-09-07 14:32 UTC by muslimitsuhide

2023-09-07 19:39 UTC, tUnknownLegend commented
Привет, добро пожаловать на курс по фронтенд-разработке. Я буду проверять твое ДЗ 0. Ниже будут мои вопросы и комментарии по коду. Можно отвечать на них здесь или писать в [телеграм](https://t.me/tUnknownLegend)

2023-09-07 20:08 UTC, tUnknownLegend requested changes
Интересное решение, но требуется доработка. При написании тестов постарайся думать о том, что именно проверяет данный тест, не повторяет ли он логически ранее написанные. Кроме того никак не проверены случаи с некорректными входными данными других типов. По любым вопросам можешь писать мне в [телеграм](https://t.me/tUnknownLegend)

2023-09-07 20:08 UTC, tUnknownLegend commented on tests/letters.js
> +	QUnit.test('Возвращает пустую строку', function (assert) {
давай тогда уже и давать на вход пустую строку `''`

2023-09-07 20:08 UTC, tUnknownLegend commented on source/letters.js
> +const letters = (input, mode) => {
так же подумай о том, что будет, если будут переданы input и mode не того типа, который предполагается

2023-09-08 09:25 UTC, muslimitsuhide commented on source/letters.js
> +'use strict';
включается **строгий режим**, в данном режиме система будет явно выбрасывать ошибки, о которых в нестрогом режиме бы система никак не оповестила пользователя

2023-09-08 09:26 UTC, muslimitsuhide commented on source/letters.js
> +
26-ая строка как раз пустая же

2023-09-08 09:27 UTC, muslimitsuhide commented on tests/letters.js
> +	QUnit.test('Возвращает пустую строку', function (assert) {
согласен, исправлю

2023-09-08 09:27 UTC, muslimitsuhide commented on tests/letters.js
> +	QUnit.test('Удаляет повторяющиеся специальные символы', function (assert) {
согласен, исправлю

2023-09-08 09:30 UTC, muslimitsuhide commented on tests/letters.js
> +	QUnit.test('Правильно обрабатывает строки с символами разных языков', function (assert) {
окей, избавлюсь от этого теста

2023-09-08 10:21 UTC, muslimitsuhide commented on source/letters.js
> +const letters = (input, mode) => {
- хорошо, добавлю 
- отличие заключается в работе с контекстом. контекст обычных функций зависит от места вызова, а контекст стрелочных функций зависит от того места, где они были определены. Также со стрелочными функциями код становится более современным и читаемым
- будет нехорошо) добавлю проверку

2023-09-08 10:29 UTC, muslimitsuhide commented on source/letters.js
> +        if (mode === true) {
- окей, подправлю 
- согласен
- оператор `==` сравнивает на равенство, а `===` на идентичность, также оператор `===`  не приводит два значения к одному типу, как это делает оператор `==`.

2023-09-08 17:04 UTC, tUnknownLegend requested changes
нужно еще немного исправить и дописать тестов

2023-09-08 17:04 UTC, tUnknownLegend commented on source/letters.js
> +    return pureArray.join('');
Можно подумать над тем, чтобы это сделать прям внутри if'ов и не создавать лишнюю переменную `filterMode`. Если прям заморочиться можно обёрточную функцию еще написать, чтобы не было копи пасты .join и filter, но она будет const в отличии от let filterMode.

Но это уже не сильно критично, в целом и так норм

2023-09-08 17:10 UTC, tUnknownLegend commented on source/letters.js
> +        throw new Error('Type error. Enter the correct data type');
и давай опишем в JSDoc, что у нас функция умеет кидать ошибки https://jsdoc.app/tags-throws.html

2023-09-09 22:17 UTC, muslimitsuhide commented on source/letters.js
> +    const array = input.split('');
забыл в ифе проверку для input добавить) исправлю

2023-09-10 15:02 UTC, tUnknownLegend requested changes
еще немного мелких правок

2023-09-10 15:02 UTC, tUnknownLegend commented on source/letters.js
> +        if (typeof input !== 'string' || typeof mode !== 'boolean' && typeof mode !== 'undefined') {
с проверкой string не все так однозначно) если передать input как new String(), то будет как бы string, но typeof new String() === 'object'. [Можно говорить](https://google.github.io/styleguide/jsguide.html#disallowed-features-wrapper-objects), что использование new String не стоит того и не менять код, но тогда надо добавить соответствующий тест

2023-09-10 18:57 UTC, tUnknownLegend approved these changes

2023-09-10 18:57 UTC, tUnknownLegend commented on tests/letters.js
> +        assert.strictEqual(letters(null), '');
про отступы относилось ко всему) поправь в остальных местах, пожалуйста

2023-09-10 18:58 UTC, muslimitsuhide commented on tests/letters.js
> +        assert.strictEqual(letters(null), '');
хм, у меня они норм отображались(

2023-09-10 19:03 UTC, tUnknownLegend commented on tests/letters.js
> +        assert.strictEqual(letters(null), '');
чтобы не было проблем такого характера советую перед отправкой на ревью заходить измененные файлы в ПРе и лишний раз все просматривать. Постоянно у себя так что-то нахожу)

2023-09-10 19:05 UTC, tUnknownLegend approved these changes
огонь, ставлю аппрув. Жди ревью от старшего ментора)

2023-09-10 22:25 UTC, DPeshkoff requested changes
Привет! Поздравляю с переходом на второй семестр)

Хорошее решение получилось, но у меня есть пара замечаний. Если возникнут вопросы - можешь писать в [Telegram](t.me/DmPesh)

2023-09-10 22:25 UTC, DPeshkoff commented on source/letters.js
> +    if (typeof input !== 'string' || typeof mode !== 'boolean' && typeof mode !== 'undefined') {
Упс! 

![изображение](https://github.com/frontend-park-mail-ru/homework_2023_2/assets/31134795/5afd937a-9f4c-4dbd-a0a1-8d4662f11341)

У тебя в тестах только тест на капибару, но это могут быть и валидные строки... непорядок! Давай подумаем, как это починить)

2023-09-10 22:25 UTC, DPeshkoff commented on source/letters.js
> +        return '';
Лучше [так](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Error)

2023-09-10 22:25 UTC, DPeshkoff commented on source/letters.js
> +            filterMode = (element) => array.lastIndexOf(element) === array.indexOf(element);
А мы разве сюда попадем?)

2023-09-10 22:25 UTC, DPeshkoff commented on source/letters.js
> +    switch (mode) {
Можно тернарником, если убрать default)

2023-09-12 08:07 UTC, muslimitsuhide commented on source/letters.js
> +        return '';
исправил

2023-09-12 08:07 UTC, muslimitsuhide commented on source/letters.js
> +            filterMode = (element) => array.lastIndexOf(element) === array.indexOf(element);
обсудили в лс

2023-09-12 08:08 UTC, muslimitsuhide commented on source/letters.js
> +    if (typeof input !== 'string' || typeof mode !== 'boolean' && typeof mode !== 'undefined') {
поправил

2023-09-12 11:37 UTC, DPeshkoff requested changes

2023-09-12 11:37 UTC, DPeshkoff commented on source/letters.js
> +        throw new Error('Type error. Enter the correct data type');
По стандарту можно заюзать [получше](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Error#%D1%82%D0%B8%D0%BF%D1%8B_%D0%BE%D1%88%D0%B8%D0%B1%D0%BE%D0%BA)

Обнови тут и не забудь в JSDoc)

2023-09-13 10:15 UTC, DPeshkoff approved these changes

2023-09-13 10:16 UTC, closed without merging