Мышляев Андрей
frontend-park-mail-ru/homework_2023_2 pull request #21
Opened 2023-09-07 14:49 UTC by Gokert

2023-09-07 18:41 UTC, Ivan-Bir commented
Привет!
Добро пожаловать на курс по фронтенд-разработке 👋
Я буду проверять твое дз0. Ниже я оставлю комментарии по коду. Можно отвечать здесь или написать мне в телеграмм @Ivanchello_br.

2023-09-07 18:48 UTC, Ivan-Bir requested changes
Молодец, микроправки и аппрувлю

2023-09-07 18:48 UTC, Ivan-Bir commented on source/rle.js
> +const rle = (string) => {
Хорошие разработчики документируют свой код.
Давай добавим JSDoc к функции https://jsdoc.app/about-getting-started.html

2023-09-07 18:48 UTC, Ivan-Bir commented on tests/rle.js
> +		assert.strictEqual(rle('///**--+?'), '/3*2-2+?');
Отлично, но функцию могут вызвать и без агрументов. Давай это тоже учтём и напишем тест

2023-09-08 10:46 UTC, Ivan-Bir requested changes

2023-09-08 10:46 UTC, Ivan-Bir commented on source/rle.js
> +* */
если бы твоя функция была () => void, то ок. Но это же не так)
Давай оформим доку правильно

2023-09-08 10:46 UTC, Ivan-Bir commented on source/rle.js
> +const rle = (string='') => {
1. Предлагаю возвращать null из функции, если что-то пошло не так. Потому что довольно часто функции вызываются в условных выражениях. if (func()) {...}, а такой каст пустой строки к false работает, но не когда используется оператор ?? https://learn.javascript.ru/nullish-operators
2. Не хватает пробелов вокруг =

2023-09-08 19:42 UTC, Ivan-Bir requested changes

2023-09-08 19:42 UTC, Ivan-Bir commented on source/rle.js
> +const rle = (string = '') => {
Мы можем не выполнять функцию целиком, если её вызвали без параметров, а сразу вернуть null, не тратя ресурсы на лишние операции. Тогда и значение по-умолчанию не потребуется

2023-09-08 19:42 UTC, Ivan-Bir commented on source/rle.js
> +/** This function returns a new compressed string using the RLE algorithm. */
В JSDoc для функций описываются её аргументы и возвращаемое значение
Давай всё-таки сделаем как полагается
https://habr.com/ru/articles/572968/

2023-09-08 19:42 UTC, Ivan-Bir commented on source/rle.js
> +    return result || null;
В этом есть необходимость?

2023-09-08 20:40 UTC, Ivan-Bir commented
Если нужно повторное ревью, то можно сразу писать в тг

2023-09-09 13:40 UTC, Ivan-Bir approved these changes

2023-09-10 22:52 UTC, DPeshkoff requested changes
Привет! Поздравляю с переходом на второй семестр)

Классное решение получилось, но у меня есть пара замечаний. Если возникнут вопросы - можешь писать в [Telegram](t.me/DmPesh)

2023-09-10 22:52 UTC, DPeshkoff commented on source/rle.js
> +'use strict';
Распиши, пожалуйста, что это за строчка и зачем она нужна)

2023-09-10 22:52 UTC, DPeshkoff commented on source/rle.js
> +    if (!string) {
А если это вообще не строка, а, например, объект типа `Date`? Предлагаю проверять, а то небезопасный код какой-то, взорвется еще!

2023-09-10 22:52 UTC, DPeshkoff commented on source/rle.js
> +        return null;
Предлагаю выбрасывать годную [ошибку](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Error)

2023-09-11 13:26 UTC, Gokert commented on source/rle.js
> +'use strict';
Директива 'use strict' предназначена для включения строгого режима обработки кода. Строгий режим запрещает использование устаревших конструкций языка, а также вводит новые зарезервированные слова.

2023-09-12 11:38 UTC, DPeshkoff commented on source/rle.js
> +        return null;
up? или распиши текстом, почему хочешь возвращать в этом кейсе null)

2023-09-13 10:17 UTC, closed without merging