Алешин Илья(вариант 19)
frontend-park-mail-ru/homework_2023_2 pull request #22
Opened 2023-09-07 15:44 UTC by ilyaaid

2023-09-08 18:23 UTC, F4lkr4m commented
Привет! Добро пожаловать на курс фронтенда! Я буду проверять твое ДЗ №0! Далее в комментариях оставлю свои вопросы по коду) По любым вопросам можешь меня пинговать [здесь](https://t.me/Falkr4m)

2023-09-08 18:45 UTC, F4lkr4m reviewed
У тебя интересное решение этой задачи - мне понравилось
Когда поправишь замечания можешь мне написать в телегу или тегнуть тут

2023-09-08 18:45 UTC, F4lkr4m commented on source/sorting.js
> +"use strict";
Можешь рассказать для чего используется use strict?

2023-09-08 18:45 UTC, F4lkr4m commented on source/sorting.js
> +function sorting(objects, fields) {
Здесь ты использовал объявление функции через ключевое слова function - можешь, пожалуйста, переписать функцию на стрелочный вариант, а также рассказать чем отличается такая запись от стрелочной записи?

2023-09-08 18:45 UTC, F4lkr4m commented on source/sorting.js
> +    .slice()
Для чего тут используется .slice()? Мне кажется он лишний

2023-09-08 18:45 UTC, F4lkr4m commented on source/sorting.js
> +      objects.sort((a, b) => {
`.sort()` изменяет исходный массив, лучше соблюдать чистоту функций и сделать копию

2023-09-08 18:45 UTC, F4lkr4m commented on source/sorting.js
> +        if (a[field] >= b[field]) {
Мне кажется было бы неплохо обработать случай, когда не получается получить свойство из объекта

2023-09-08 18:45 UTC, F4lkr4m commented on source/sorting.js
> +function sorting(objects, fields) {
Также не забываем про документацию для других разработчиков - JSDoc

2023-09-08 18:45 UTC, F4lkr4m commented on tests/sorting.js
> +  QUnit.test(
Молодец, что написал тесты!)

2023-09-08 18:45 UTC, F4lkr4m commented on source/sorting.js
> +        if (a[field] >= b[field]) {
Для более красивой записи можно использовать тернарный оператор

2023-09-08 18:59 UTC, F4lkr4m commented on source/sorting.js
> +}
Также не забываем про принятую у программистов традицию - пустая строка в конце файла

2023-09-08 19:00 UTC, F4lkr4m commented
Еще попрошу убрать вариант из названия пулл реквеста, фамилии и имени достаточно

2023-09-09 12:00 UTC, ilyaaid commented on source/sorting.js
> +"use strict";
Насколько я понял, эта команда нужна для того, чтобы нельзя было использовать устаревшие конструкции после ее написания.

2023-09-09 12:21 UTC, ilyaaid commented on source/sorting.js
> +function sorting(objects, fields) {
Вообще здесь стрелочная функция помогает только сократить код.
Другая особенность стрелочной функции - она не содержит объекта this. В каких-то случаях это может быть полезно.

2023-09-09 16:07 UTC, F4lkr4m commented on source/sorting.js
> +function sorting(objects, fields) {
Да, верно, она дергает внешний контекст, а также стрелочная функция не имеет внутри объекта arguments

2023-09-10 08:57 UTC, ilyaaid commented on source/sorting.js
> +        if (a[field] >= b[field]) {
Не знаю, как правильно будет обрабатывать случай, когда не получается достать свойство. Ведь функция автоматически отправляет такие объекты в конец. Никакого исключения не возникает, но можно делать просто предупреждение в виде console.log?

2023-09-10 09:33 UTC, ilyaaid commented
Исправил ошибки. Проверьте пожалуйста.

2023-09-10 13:39 UTC, F4lkr4m reviewed
Жду следующие правки! Если есть какие-то вопросы - пиши в тг

2023-09-10 13:39 UTC, F4lkr4m commented on source/sorting.js
> +
Между JSDoc и функцией не нужна пустая строчка

2023-09-10 13:39 UTC, F4lkr4m commented on source/sorting.js
> +  const array_cp = Array.from(array);
На JS пишем в camelCase

2023-09-10 13:39 UTC, F4lkr4m commented on source/sorting.js
> +  fields.reverse().forEach((field) => {
.reverse(), тоже меняет исходный массив - надо тоже сделать копию, можно тут сделать это с помощью spread оператора [...fields] или с помощью structuredClone (копирование с пересозданием объектов внутри - можешь почитать про функцию, если интересно)

2023-09-10 13:39 UTC, F4lkr4m commented on source/sorting.js
> +      if (!(field in a)) {
Можно просто проверять по доступу !a[field]. А также в таком случае, если одного из свойств нет внутри объекта - то выкинуть ошибку с помощью throw

2023-09-10 13:45 UTC, F4lkr4m commented
> Исправил ошибки. Проверьте пожалуйста.

Давай на ты лучше)

2023-09-10 21:19 UTC, ilyaaid commented
Запушил. Проверь, пожалуйста

2023-09-11 17:57 UTC, F4lkr4m commented on source/sorting.js
> +};
Тут не хватает пустой строки по окончании файла

2023-09-11 17:57 UTC, F4lkr4m commented on source/sorting.js
> +      if (!(field in a)) {
Давай все такие сделаем  !a[field], чтобы меньше скобочек было

2023-09-12 10:28 UTC, ilyaaid commented
Добавил обработку ключей со значениями undefined. При обработке исключение не выбрасывается. При этом такие ключи остаются в конце объекта при сортировке

2023-09-12 10:38 UTC, F4lkr4m commented
> Добавил обработку ключей со значениями undefined. При обработке исключение не выбрасывается. При этом такие ключи остаются в конце объекта при сортировке

Да, хорошо

2023-09-12 10:39 UTC, F4lkr4m commented on source/sorting.js
> +      if (!(field in a)) {
Было принято решение сделать обработку ключей с обработкой undefined значений, поэтому оставили здесь такую запись, как была

2023-09-12 10:42 UTC, F4lkr4m commented
lgtm

2023-09-12 12:00 UTC, DPeshkoff commented on index.html
> +    <script src="https://code.jquery.com/qunit/qunit-2.4.0.js"></script>
И тут

2023-09-12 12:00 UTC, DPeshkoff commented on source/sorting.js
> +"use strict";
Не только - как думаешь, почему вообще приняли решение сделать такую директиву?

2023-09-12 12:01 UTC, DPeshkoff commented on tests/max.js
> +"use strict";
Вообще в JS обычно оборачивают в одиночные кавычки - давай вернем и сделаем везде так)

2023-09-12 12:01 UTC, DPeshkoff commented on tests/sorting.js
> -			{prop1: 1, id: '2'},
Здесь не должно быть изменений в отступах

2023-09-12 12:01 UTC, DPeshkoff commented on tests/sorting.js
> +  );
А давай еще накинем тесты на некорректный ввод?

2023-09-12 20:29 UTC, ilyaaid commented on source/sorting.js
> +"use strict";
Чтобы программа принудительно останавливалась при использовании устаревших функций

2023-09-12 20:48 UTC, ilyaaid commented
Исправил. Проверь, пожалуйста

2023-09-13 15:52 UTC, DPeshkoff requested changes

2023-09-13 15:52 UTC, DPeshkoff commented on index.html
> +  <meta name="viewport" content="width=device-width" />
что за изменения)
выключи автолинтер IDE)

2023-09-13 15:52 UTC, DPeshkoff commented on source/sorting.js
> +        throw new Error("the key does not exist");
в js принято использовать одиночные кавычки, давай менять)

2023-09-13 15:52 UTC, DPeshkoff commented on source/sorting.js
> +    });
а что тут происходит? хочу комментарии)

2023-09-14 14:36 UTC, ilyaaid commented
Привет!
Исправил. Проверь, пожалуйста

2023-09-14 22:50 UTC, DPeshkoff approved these changes

2023-09-14 22:50 UTC, closed without merging