Кузнецов Александр
frontend-park-mail-ru/homework_2023_2 pull request #23
Opened 2023-09-07 17:59 UTC by almkuznetsov

2023-09-07 22:25 UTC, F4lkr4m commented
Привет! Добро пожаловать на курс фронтенда! Я буду проверять твое ДЗ №0! Далее в комментариях оставлю свои вопросы по коду) По любым вопросам можешь меня пинговать [здесь](https://t.me/Falkr4m)

2023-09-07 22:41 UTC, F4lkr4m reviewed
Когда поправишь замечания можешь мне написать в телегу или тегнуть тут

2023-09-07 22:41 UTC, F4lkr4m commented on source/chess.js
> +'use strict';
Для чего используется 'use strict'?

2023-09-07 22:41 UTC, F4lkr4m commented on source/chess.js
> +const chess = function (size) {
Здесь ты использовал запись функции через ключевое слово function, можешь, пожалуйста, переписать на стрелочный вариант, а также рассказать чем отличается стрелочная функция от такой записи?

2023-09-07 22:41 UTC, F4lkr4m commented on source/chess.js
> +    let firstField = '*';
Мне кажется стоит эти переменные назвать по типу BLACK_FIELD и WHITE FIELD - все таки они означают цвета поля для шахмат)

2023-09-07 22:41 UTC, F4lkr4m commented on source/chess.js
> +    let firstField = '*';
Помимо этого тут стоило бы использовать объявление переменной через const.
Кстати, можешь рассказать чем отличается объявление через ключевые слова var/let/const?

2023-09-07 22:41 UTC, F4lkr4m commented on source/chess.js
> +    for (let i = 0; i < size; i++) {
Тут ты проходишь по циклу для получения строк шахматной доски. Попробуй реализовать получение этих строк через массив - можешь использовать `Array.from` с аргументом по длине, а потом просто все собрать в строку с помощью метода `join`.

2023-09-07 22:41 UTC, F4lkr4m commented on source/chess.js
> +    for (let i = 0; i < size; i++) {
Также чтобы код не повторялся можешь вынести получение строки со сдвигом и без в отдельную функцию

2023-09-07 22:41 UTC, F4lkr4m commented on source/chess.js
> +    if (size <= 1) return null;
Лучше тут не забывать про фигурные скобки - так будет более читабельно

2023-09-07 22:41 UTC, F4lkr4m commented on source/chess.js
> +        if (i % 2 == 0) field += evenLine;
Здесь можно сделать просто if (i % 2) и поменять случаи местами (результаты работы в зависимости от условия)

2023-09-07 22:41 UTC, F4lkr4m commented on tests/chess.js
> +		QUnit.test('Округление в большую сторону (доска 3 на 3 вместо 2.5 на 2.5)', function (assert) {
Молодец, что добавил тесты!

2023-09-07 22:41 UTC, F4lkr4m commented on source/chess.js
> +        if (i % 2 == 0) field += evenLine;
Здесь можно сделать просто if (i % 2) и поменять случаи местами

2023-09-07 22:41 UTC, F4lkr4m commented on source/chess.js
> +        if (i % 2 == 0) field += evenLine;
Здесь можно сделать просто if (i % 2) и поменять случаи местами (результаты работы в зависимости от условия)

2023-09-07 22:41 UTC, F4lkr4m commented on source/chess.js
> +};
Также не забываем про принятую у программистов традицию - пустая строка в конце файла

2023-09-07 22:41 UTC, F4lkr4m commented on source/chess.js
> +const chess = function (size) {
Давай еще для функции добавим JSDoc, чтобы была какая-то документация к функции)

2023-09-08 13:05 UTC, almkuznetsov commented on source/chess.js
> +'use strict';
Чтобы принудительно включить "современный режим" работы языка, который по умолчанию выключен для обеспечения совместимости.
Конкретно на работу этой функции он не повлияет, но, поскольку он был в примере и в учебнике, я решил, что постоянно держать его наверху может быть хорошей привычкой)

2023-09-08 13:09 UTC, almkuznetsov commented on source/chess.js
> +const chess = function (size) {
Переписал. Стрелочные функции это другой вид записи функций, который, как я понимаю, в основном используется для описания небольших функций, которые не имеют контекста. Поэтому, в принципе, отлично подходят для этого задания)

2023-09-08 14:10 UTC, almkuznetsov commented on source/chess.js
> +    let firstField = '*';
В первой версии программы этого сделать было нельзя, т.к. first и Second Field менялись по ходу выполнения. Но сейчас я переписал ее и теперь так сделал, да
Объявление через let - обычная переменная
через const - переменная (константа?) с неизменяемым значением
через var - старый способ с ограничениями (например, нет областей видимости)

2023-09-08 14:11 UTC, almkuznetsov commented on source/chess.js
> +    for (let i = 0; i < size; i++) {
Это я постарался сделать в новом коде, получилось несколько длинно, но получилось)

2023-09-08 14:11 UTC, almkuznetsov commented on source/chess.js
> +    if (size <= 1) return null;
Добавил

2023-09-08 14:12 UTC, almkuznetsov commented on source/chess.js
> +};
Она там определенно есть, в VS Code ее видно. А на гитхаб, почему-то не заливается...

2023-09-08 14:13 UTC, almkuznetsov commented on source/chess.js
> +};
Пришлось ставить две пустых строки, чтобы она тут отобразилась

2023-09-08 14:14 UTC, almkuznetsov commented
@F4lkr4m замечания исправлены, призываю на помощь)

2023-09-08 15:13 UTC, F4lkr4m commented on source/chess.js
> +    oddLine = Array.from({ length : size }, (size, i) => { if (i++ % 2) return WHITE_FIELD; else return BLACK_FIELD; } )
Тут нет инициализации переменной - программа не заработает - нужен рабочий вариант

2023-09-08 15:13 UTC, F4lkr4m commented on source/chess.js
> +    oddLine = Array.from({ length : size }, (size, i) => { if (i++ % 2) return WHITE_FIELD; else return BLACK_FIELD; } )
Советую вынести получение строки для шахматной доски в отдельную функцию, чтобы не повторять код. Еще кстати тебе не требуется объявление переменной i, индекс приходит в функции-колбеке, можешь использовать его сразу

2023-09-08 15:13 UTC, F4lkr4m commented on source/chess.js
> +    oddLine = Array.from({ length : size }, (size, i) => { if (i++ % 2) return WHITE_FIELD; else return BLACK_FIELD; } )
Еще было бы круто тут использовать тернарный оператор.

2023-09-08 15:13 UTC, F4lkr4m commented on source/chess.js
> +            field += evenLine.join("");
Лучше сразу переменные evenLine и oddLine - превратить в единую строку

2023-09-08 15:13 UTC, F4lkr4m commented on source/chess.js
> +        else {
Также не очень красиво выглядит использование else, лучше написать `if (i % 2) { //...; continue;} //... else actions`

2023-09-09 10:15 UTC, almkuznetsov commented on source/chess.js
> +            field += evenLine.join("");
> Лучше сразу переменные evenLine и oddLine - превратить в единую строку

Исправил все, кроме этого. Мы же не знаем заранее, четное количество строк или нечетное, а если их объединить, то сможем только четное количество строк задавать. Я понимаю что теоретически это можно сделать по-другому, но в данном случае не понимаю как доработать именно этот алгоритм до возможности такой реализации)

2023-09-09 10:17 UTC, almkuznetsov commented
@F4lkr4m Исправления готовы, призываю на помощь)

2023-09-09 15:47 UTC, F4lkr4m commented on source/chess.js
> +            field += evenLine.join("");
Тут просто был не понятен контекст, но все сделал как надо)

2023-09-09 16:02 UTC, F4lkr4m commented on source/chess.js
> +    let oddLine = makeLine(size, BLACK_FIELD)
На всякий случай обращаю внимание на объявление переменных еще раз

2023-09-09 16:02 UTC, F4lkr4m commented on source/chess.js
> +    if (size <= 1) { return null };
return на отдельной строке

2023-09-09 16:02 UTC, F4lkr4m commented on source/chess.js
> +        (i % 2)
В тернарнике не нужны скобки

2023-09-09 16:05 UTC, F4lkr4m commented
Снова пинганешь меня как сделаешь)

2023-09-10 08:24 UTC, almkuznetsov commented
@F4lkr4m Готово

2023-09-10 13:58 UTC, F4lkr4m reviewed
Жду исправлений, если будут вопросы пиши в [телеграм](https://t.me/Falkr4m)

2023-09-10 13:58 UTC, F4lkr4m commented on source/chess.js
> +    if (isWhite) { line.unshift(WHITE_FIELD);
Аааа, нет, так не надо хД 
Вот так лучше (только с отступами, а то тут просто неудобно это все делать) :
if (isWhite) {
   // ...action1;
   // ...action2;
}

2023-09-10 13:58 UTC, F4lkr4m commented on source/chess.js
> +        return null };
Тут тоже - закрывающаяся скобка на отдельной строке

2023-09-10 13:58 UTC, F4lkr4m commented on source/chess.js
> +            ? (field += evenLine)
Тут тоже не нужны скобки

2023-09-10 13:58 UTC, F4lkr4m commented on source/chess.js
> +            ? (field += evenLine)
Как и на следующей строке

2023-09-10 13:58 UTC, F4lkr4m commented on source/chess.js
> +const makeLine = (size, isWhite) => {
Давай сойдемся на названии переменной isWhiteFirst. а то isWhite не дает полноты понимания

2023-09-10 13:58 UTC, F4lkr4m commented on source/chess.js
> +const chess = (size) => {
Также было бы круто сделать проверку на то, что переменная size это число, а иначе выкинуть ошибку

2023-09-10 17:48 UTC, almkuznetsov commented
@F4lkr4m Проверку на size добавил, из-за этого немного изменил свои тесты. Остальные недочеты также исправил

2023-09-10 19:22 UTC, F4lkr4m commented on source/chess.js
> +    throw new Error('Size is not a round number!');
Отступ потерялся

2023-09-10 19:22 UTC, F4lkr4m commented on source/chess.js
> +    if (size % 1 !== 0 ) {
Тут ты проверяешь на то, что это не целое число. а если передать объект или строку вместо числа?

2023-09-10 19:22 UTC, F4lkr4m commented on source/chess.js
> +    if (size % 1 !== 0 ) {
А также пробельчик перед закрывающей круглой скобкой лишний

2023-09-10 20:09 UTC, F4lkr4m commented
lgtm

2023-09-10 23:17 UTC, DPeshkoff requested changes
Привет! Поздравляю с переходом на второй семестр)

Интересное решение получилось, но у меня есть пара замечаний. Если возникнут вопросы - можешь писать в [Telegram](t.me/DmPesh)

2023-09-10 23:17 UTC, DPeshkoff commented on source/chess.js
> +const WHITE_FIELD = '*'
Не забывай про точки с запятой! Несмотря на то, что парсер умеет автоматически их проставлять - иногда это приводит к странным результатам. 

<details><summary>Каким?</summary>
<p>
К примеру, тривиальный и понятный код:

![изображение](https://github.com/frontend-park-mail-ru/homework_2023_2/assets/31134795/3d22e9a8-baee-4bfb-886a-b4dfe665364a)

Внезапно падает:

![изображение](https://github.com/frontend-park-mail-ru/homework_2023_2/assets/31134795/582afa37-106b-4330-acaf-6a622c1cda61)

Почему так происходит, думаю, наглядно видно по тексту ошибки - он считает `[3]` частью `s`. Если при этом поставить ;, то код магически начинает работать)

![изображение](https://github.com/frontend-park-mail-ru/homework_2023_2/assets/31134795/9210ce09-d52b-40aa-9731-dd12424c685b)
</p>
</details> 

Давай везде проставим точки с запятой)

2023-09-10 23:17 UTC, DPeshkoff commented on source/chess.js
> +    const evenLine = makeLine(size, true);
Как будто лишние переменные - можно же на месте и вызывать)

2023-09-10 23:17 UTC, DPeshkoff commented on source/chess.js
> +    for (let i = 1; i <= size; i++) {
У нас уже есть строка - давай попробуем использовать какие-то из методов для повторения в строках?

2023-09-10 23:17 UTC, DPeshkoff commented on source/chess.js
> +        throw new Error('Size is not a round number!');
В стандарте прописаны годные [типы ошибок](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Error#%D1%82%D0%B8%D0%BF%D1%8B_%D0%BE%D1%88%D0%B8%D0%B1%D0%BE%D0%BA), давай используем

2023-09-11 07:53 UTC, almkuznetsov commented
@DPeshkoff 
Поправил замечания, реализовал алгоритм через функции над строками. Я правильно понимаю, что создание массива и повтор строки должны проходить быстрее, чем for по всему размеру? А то не совсем уверен, что это оптимизация с точки зрения скорости выполнения, все-таки функцию makeLine пришлось вызывать три раза вместо двух

2023-09-12 11:39 UTC, DPeshkoff commented
Не сказал бы, что мы выигрываем по скорости - на больших объемах циклы for лучше. Но здесь явно не такие, а читаемость кода - тоже важный аргумент, который нужно учитывать

2023-09-12 11:40 UTC, closed without merging