Белозеров Дмитрий
frontend-park-mail-ru/homework_2023_2 pull request #24
Opened 2023-09-07 18:19 UTC by Belozerovmsk

2023-09-07 19:39 UTC, tUnknownLegend commented
Привет, добро пожаловать на курс по фронтенд-разработке. Я буду проверять твое ДЗ 0. Ниже будут мои вопросы и комментарии по коду. Можно отвечать на них здесь или писать в [телеграм](https://t.me/tUnknownLegend)

2023-09-07 20:35 UTC, tUnknownLegend requested changes
Интересное решение, но требуются доработки. Подумай какие тесты еще можно добавить. По любым вопросам пиши в [телеграм](https://t.me/tUnknownLegend)

2023-09-07 20:35 UTC, tUnknownLegend commented on source/minmax.js
> +'use strict';
круто, что используешь `'use strict'`. Расскажи, пожалуйста, зачем нужна эта директива

2023-09-07 20:35 UTC, tUnknownLegend commented on source/minmax.js
> + * @param inputLine //  Input string
хорошо, что добавил JSDoc, но к сожалению он неверного формата(
почитай [здесь](https://learn.javascript.ru/comments) как правильно писать JSDoc

2023-09-07 20:35 UTC, tUnknownLegend commented on source/minmax.js
> +const minmax = inputLine => {
классно, что используешь стрелочную функцию. Расскажи, пожалуйста, как она отличается от "обычной"

2023-09-07 20:35 UTC, tUnknownLegend commented on source/minmax.js
> +const minmax = inputLine => {
параметры стрелочной функции [принято](https://learn.javascript.ru/coding-style) оборачивать в скобки

2023-09-07 20:35 UTC, tUnknownLegend commented on source/minmax.js
> +    const numbersLine = inputLine.split(' ').map(Number).filter(word => !isNaN(word));
здесь как будто бы происходит лишний обход массива. Вначале делаешь обход с `map`, потом с `filter`, хотя можно объединить в один

2023-09-07 20:35 UTC, tUnknownLegend commented on tests/minmax.js
> +	QUnit.test('minmax корректно работает с разными типами данных', function (assert) {
подумай над кейсами, когда на вход функции дается не `string`

2023-09-07 20:35 UTC, tUnknownLegend commented on source/minmax.js
> +    return (!inputLine || numbersLine.length === 0) ? [undefined, undefined] : [minValue, maxValue];
расскажи, пожалуйста, чем отличается `==` от `===`

2023-09-08 09:19 UTC, Belozerovmsk commented on source/minmax.js
> +'use strict';
Оно помогает избежать ошибок и улучшить качество кода. Принято использовать во всех новых проектах. Причины:
1) Запрещает использование необъявленных переменных.
2) Запрещает иметь одинаковые имена у параметров функций.
3) Запрещает изменение значений констант.
4) Улучшает производительность выполнения кода.
5) Запрещает использовать зарезервированные слова.

2023-09-08 09:25 UTC, Belozerovmsk commented on source/minmax.js
> +const minmax = inputLine => {
Стрелочной функции имеет более короткий синтаксис и не требует использования ключевого слова function. Вместо этого используется стрелка =>, а также отсутствует this (при обращении значение берется снаружи).

2023-09-08 09:27 UTC, Belozerovmsk commented on source/minmax.js
> +    return (!inputLine || numbersLine.length === 0) ? [undefined, undefined] : [minValue, maxValue];
Оператор == сравнивает значения переменных, приводя их к одному типу данных, если они различаются. Оператор === также сравнивает значения переменных, но не приводит их к одному типу данных. Если типы данных не совпадают, то оператор вернет false.

2023-09-08 16:42 UTC, tUnknownLegend reviewed
требуются небольшие правки и будет аппрув от меня)

2023-09-08 16:42 UTC, tUnknownLegend commented on source/minmax.js
> +    if (!inputLine || typeof inputLine !== "string") {
[лучше](https://stackoverflow.com/questions/4059147/check-if-a-variable-is-a-string-in-javascript) еще проверить instanceof string

2023-09-08 16:42 UTC, tUnknownLegend commented on source/minmax.js
> +    return numbersLine.length == 0 ? [undefined, undefined] : [Math.min(...numbersLine), Math.max(...numbersLine)];
ранее [писал](https://github.com/frontend-park-mail-ru/homework_2023_2/pull/24#discussion_r1319088402) про [truthy](https://developer.mozilla.org/en-US/docs/Glossary/Truthy), поправь, пожалуйста

2023-09-09 13:46 UTC, tUnknownLegend reviewed
все ок, только запутался в проверке string

2023-09-09 13:46 UTC, tUnknownLegend commented on source/minmax.js
> +    if (!inputLine || typeof inputLine !== "string" || inputLine instanceof String) {
```suggestion
    if (!inputLine || !(typeof inputLine === "string" || inputLine instanceof String)) {
```

2023-09-09 13:52 UTC, tUnknownLegend commented on source/minmax.js
> +    if (!inputLine || typeof inputLine !== "string" || inputLine instanceof String) {
давай добавим еще тест с new String(), чтобы не было никаких сомнений)

2023-09-10 14:43 UTC, tUnknownLegend requested changes
осталась одна небольшая проблемка. Держи мем про js, чтобы не было так грустно 
![image](https://github.com/frontend-park-mail-ru/homework_2023_2/assets/57019979/e9b21a23-490d-45a2-9ae4-6b5f3bc82e2d)

2023-09-10 14:43 UTC, tUnknownLegend commented on source/minmax.js
> +    if (!inputLine || !(typeof inputLine === "string" || inputLine instanceof String) || typeof inputLine === "object") {
если добавить тест с `inputLine = new String('1 1 1 1')`, то результат будет `undefind`, поэтому проверка на typof object лишняя. Все дело в том, что new String() возвращает object, а пустой объект - truthy. Тут есть два варианта: 
- отказаться от работы с new String(), т.е. всегда в таком случае возвращать `undefined`
- как-то это проверять, например заменить `!inputLine` на `inputLine == ''`. Обращаю внимание, что именно `==`, а не `===`

не забудь добавить тест с `inputLine = new String('1 1 1 1')`

2023-09-10 19:00 UTC, tUnknownLegend approved these changes
огонь, ставлю аппрув. Жди ревью от старшего ментора)

2023-09-10 22:32 UTC, DPeshkoff requested changes
Привет! Поздравляю с переходом на второй семестр)

Крутое решение получилось, лайк за строки, но у меня есть пара замечаний. Если возникнут вопросы - можешь писать в [Telegram](t.me/DmPesh)

2023-09-10 22:32 UTC, DPeshkoff commented on source/minmax.js
> +        return [undefined, undefined]
Не забывай про точки с запятой! Несмотря на то, что парсер умеет автоматически их проставлять - иногда это приводит к странным результатам. 

<details><summary>Каким?</summary>
<p>
К примеру, тривиальный и понятный код:

![изображение](https://github.com/frontend-park-mail-ru/homework_2023_2/assets/31134795/3d22e9a8-baee-4bfb-886a-b4dfe665364a)

Внезапно падает:

![изображение](https://github.com/frontend-park-mail-ru/homework_2023_2/assets/31134795/582afa37-106b-4330-acaf-6a622c1cda61)

Почему так происходит, думаю, наглядно видно по тексту ошибки - он считает `[3]` частью `s`. Если при этом поставить ;, то код магически начинает работать)

![изображение](https://github.com/frontend-park-mail-ru/homework_2023_2/assets/31134795/9210ce09-d52b-40aa-9731-dd12424c685b)
</p>
</details> 

Давай везде проставим точки с запятой)

А еще... как ты думаешь, стоит ли тут возвращать ошибку? Почему ты решил вернуть `[undefined, undefined]`?

2023-09-10 22:32 UTC, DPeshkoff commented on source/minmax.js
> +    if (inputLine == '' || !(typeof inputLine === "string" || inputLine instanceof String)) {
Вообще обычно используют одиночные кавычки, давай, раз уж в первой проверке одиночные, то и во второй сделаем)

```suggestion
    if (inputLine == '' || !(typeof inputLine === 'string' || inputLine instanceof String)) {
```

Кстати, можно проверять на [truthy](https://developer.mozilla.org/en-US/docs/Glossary/Truthy)

2023-09-10 22:32 UTC, DPeshkoff commented on source/minmax.js
> +            if (!isNaN(word)) {
Распиши, пожалуйста, чем `isNaN` отличается от `Number.isNaN` + почему ты выбрал именно такой вариант)

2023-09-11 19:12 UTC, Belozerovmsk commented on source/minmax.js
> +        return [undefined, undefined]
Я возвращаю```[undefined, undefined]``` т.к. заглянув в тесты мне показалось, что это будет правильным выбором концепции функции. С одной стороны мой код стал более устойчивым, с другой стороны - знать о поступающих неправильных аргументах функции бывает очень полезно.

2023-09-11 19:46 UTC, DPeshkoff commented on source/minmax.js
> +        return [undefined, undefined]
Предлагаю сделать выброс ошибки, кажется, что второй плюс важнее первого)

2023-09-11 20:50 UTC, Belozerovmsk commented on source/minmax.js
> +            if (!isNaN(word)) {
```isNaN``` пытается преобразовать переданный аргумент в число. А ```Number.isNaN```не преобразует переданный аргумент в число и возвращает true только в том случае, если переданный аргумент является NaN. Выбрал первый вариант, т.к. не знал о существовании второго) Можно ли считать, что методы в данном контексте будут равносильными(не может быть непредсказуемого поведения)?

2023-09-12 11:41 UTC, DPeshkoff approved these changes

2023-09-12 11:41 UTC, closed without merging