Банников Арсений (Вариант 16)
frontend-park-mail-ru/homework_2023_2 pull request #25
Opened 2023-09-07 20:39 UTC by uma-op

2023-09-09 07:18 UTC, F4lkr4m commented
Привет! Добро пожаловать на курс фронтенда! Я буду проверять твое ДЗ №0! Далее в комментариях оставлю свои вопросы по коду) По любым вопросам можешь меня пинговать [здесь](https://t.me/Falkr4m)

2023-09-09 07:48 UTC, F4lkr4m reviewed
Когда поправишь замечания можешь мне написать в телегу или тегнуть тут

2023-09-09 07:48 UTC, F4lkr4m commented on source/format.js
> +'use strict';
Можешь рассказать для чего используется  use strict?

2023-09-09 07:48 UTC, F4lkr4m commented on source/format.js
> +const format = (numbers, cols) => {
Здесь ты использовал стрелочную функцию, можешь рассказать, чем отличается стрелочная запись от записи через ключевое слово function?

2023-09-09 07:48 UTC, F4lkr4m commented on source/format.js
> +const format = (numbers, cols) => {
Также было бы круто добавить JSDoc для этой функции

2023-09-09 07:48 UTC, F4lkr4m commented on source/format.js
> +	numbers.forEach((element, i) => {
Здесь для накопления значения ты используешь переменную result и цикл forEach - это все круто, но еще круче будет использовать reduce который как раз таки позволяет производить накопление результата

2023-09-09 07:48 UTC, F4lkr4m commented on source/format.js
> +		if (i % cols != 0) {
Здесь можно написать просто `i % cols`

2023-09-09 07:48 UTC, F4lkr4m commented on source/format.js
> +		} else if (i != 0) {
Ну и тут просто `i`

2023-09-09 07:48 UTC, F4lkr4m commented on source/format.js
> +		let str_element = element.toString();
Тут задается переменная с помощью let, можешь рассказать чем отличается объявление переменной через let/const/var? И все таки что тут лучше использовать?)

2023-09-09 07:48 UTC, F4lkr4m commented on tests/format.js
> +	QUnit.test('format работает...', function (assert) {
Молодец, что добавил тесты!

2023-09-09 07:48 UTC, F4lkr4m commented on source/format.js
> +		let str_element = element.toString();
на JS пишут в стиле camelCase

2023-09-09 07:48 UTC, F4lkr4m commented on source/format.js
> +		if (i % cols != 0) {
Также можно вынести i % cols в отдельную переменную и обернуть в Boolean() - назвав isNotLastColumn - тогда будет сразу понятно, что если не последняя колонка, то доклеиваем пробел

2023-09-09 07:48 UTC, F4lkr4m commented on source/format.js
> +		} else if (i != 0) {
А тут обход случая если не первая строка, тоже можно обозвать в переменную

2023-09-12 11:13 UTC, uma-op commented on source/format.js
> +'use strict';
Эта строка включает строгий режим, он нужен для совместимости с более ранними стандартами JavaScript. Например, новые стандарты разрешают не использовать let при объявлении переменной, но с включенным строгим режимом это становится обязательным

2023-09-12 11:41 UTC, uma-op commented on source/format.js
> +const format = (numbers, cols) => {
> Здесь ты использовал стрелочную функцию, можешь рассказать, чем отличается стрелочная запись от записи через ключевое слово function?

Основное отличие в том, что стрелочная функция не создает себе контекст выполнения, то есть если мы будем использовать this внутри стрелочной функции, то значение this будет взято из контекста выше, например из обычной функции, в которой объявлена эта стрелочная

2023-09-12 11:48 UTC, uma-op commented on source/format.js
> +		let str_element = element.toString();
> Тут задается переменная с помощью let, можешь рассказать чем отличается объявление переменной через let/const/var? И все таки что тут лучше использовать?)

let и const действуют одинаково по области окружения, let создает обычную переменную, а const константную. Такие переменные видны только внутри своего блока, но переменные объявленные при помощи var будут видны и извне (кроме блока тела функции). Также var позволяет переобъявлять переменные.

2023-09-12 11:48 UTC, uma-op commented on tests/format.js
> +	QUnit.test('format работает...', function (assert) {
Спасибо)

2023-09-12 16:38 UTC, F4lkr4m reviewed
Как поправишь пингани меня в телеге или тегни тут

2023-09-12 16:38 UTC, F4lkr4m commented on source/format.js
> +const format = (numbers, cols) => {
Верно, помимо этого еще это более короткая запись, что удобно. Также в связи с отсутствием внутреннего контекста у стрелочных функций отсутствует свойство arguments

2023-09-12 16:38 UTC, F4lkr4m commented on source/format.js
> + * @param {number} cols - Число колонок в таблице
Тут не хватает возвращаемого значения в описании

2023-09-12 16:38 UTC, F4lkr4m commented on source/format.js
> + * @param {Array} numbers - Исходный массив чисел
Массив чего? Нужен тип для элемента массива

2023-09-12 16:38 UTC, F4lkr4m commented on source/format.js
> +		let strElement = element.toString();
Все круто объяснил про объявление переменной через let/const/var? Но тут ты используешь let, может есть что то более подходящее для данного случая? Также смотри подобное по коду далее

2023-09-12 16:38 UTC, F4lkr4m commented on source/format.js
> +	widths.fill(0);
fill можно использовать на строчке, где создается массив

2023-09-12 16:38 UTC, F4lkr4m commented on source/format.js
> +const format = (numbers, cols) => {
Было бы еще круто добавить проверку входных аргументов на то что это массив и что это число, в случае неверного входного параметра выкинуть ошибку

2023-09-12 21:51 UTC, F4lkr4m commented on source/format.js
> + * @param {number} cols - Число колонок в таблице
Теперь не хватает описания на throws ошибки

2023-09-12 21:51 UTC, F4lkr4m commented on source/format.js
> +		typeof cols !== "bigint" &&
Bigint - для количества колонок - это сурово, но если все таки решил учитывать bigint давай это еще учтем в JSDoc

2023-09-12 21:51 UTC, F4lkr4m commented on source/format.js
> +		!(cols instanceof Number) &&
проверка с помощью instanceof в данном случае избыточна, хватит и typeof

2023-09-12 21:51 UTC, F4lkr4m commented on source/format.js
> +		!(cols instanceof Number) &&
Если уберешь instanceof то можно сделать проверку if (...) { - в одну строчку

2023-09-13 07:09 UTC, F4lkr4m commented
lgtm

2023-09-13 14:52 UTC, DPeshkoff requested changes
Привет! Поздравляю с переходом на второй семестр)

Интересное решение получилось, но у меня есть пара замечаний. Если возникнут вопросы - можешь писать в [Telegram](t.me/DmPesh)

2023-09-13 14:52 UTC, DPeshkoff commented on source/format.js
> +		throw new TypeError("numbers: Array of numbers expected");
А сейчас пропускает массивы, в которых элементами могут быть кто угодно, а не только numbers - непорядок!

2023-09-13 14:52 UTC, DPeshkoff commented on source/format.js
> +	if (typeof cols !== "number") {
В JS приняты одиночные кавычки, давай поменяем?

2023-09-13 14:52 UTC, DPeshkoff commented on source/format.js
> +		const isNotLastColumn = Boolean(i % cols);
А зачем так? Можно [проще](https://a.jscourse.com/ru/article/falsy-and-truthy-values)

2023-09-13 14:52 UTC, DPeshkoff commented on tests/format.js
> +		assert.strictEqual(format(input, 3), expected);
Нужны еще тесты на некорректный ввод

2023-09-14 11:32 UTC, DPeshkoff approved these changes

2023-09-14 11:32 UTC, closed without merging

2023-09-15 18:37 UTC, ZhukDmitryOlegovich commented on source/format.js
> +	if (!numbers.every((number) => {return typeof number === 'number'})) {
Используй короткую запись там где можешь - [без фигурных скобок](https://learn.javascript.ru/arrow-functions-basics#:~:text=%D0%B1%D1%8B%D0%B2%D0%B0%D1%8E%D1%82%20%D0%B4%D0%B2%D1%83%D1%85%20%D1%82%D0%B8%D0%BF%D0%BE%D0%B2%3A-,%D0%91%D0%B5%D0%B7%20%D1%84%D0%B8%D0%B3%D1%83%D1%80%D0%BD%D1%8B%D1%85%20%D1%81%D0%BA%D0%BE%D0%B1%D0%BE%D0%BA,-%3A%20(...args)%20%3D%3E%20expression)

2023-09-15 18:37 UTC, ZhukDmitryOlegovich commented on source/format.js
> +	const cols_error = new TypeError('cols: Non negative number was expected');
Ошибки обычно не создают просто так а делают сразу `throw new TypeError(...)`

А то что ниже два ифа которые возвращают одну и туже ошибку - объедини в один с помощью ИЛИ

2023-09-15 18:37 UTC, ZhukDmitryOlegovich commented on source/format.js
> +	let widths = Array(cols).fill(0);
`widths` не изменяется в ходе работы - следует использовать `const`

2023-09-15 18:37 UTC, ZhukDmitryOlegovich commented on source/format.js
> +	numbers.forEach((element, i) => {
Стоит привести массив чисел к массиву строк примерно так
```js
const strNumbers = numbers.map((number) => number.toString());
```
потому что на числа после этого нам впринципе всё равно - дальше мы хотим только строки с таблицу собрать

+- на синтаксис - кстати если массив это `numbers` - то один элемент - это не `element`, а `number` - крч `s` убрать

2023-09-15 18:37 UTC, ZhukDmitryOlegovich commented on source/format.js
> +		let prefix = " ".repeat(widths[i % cols] - strElement.length);
Можно сделать - [mdn padStart](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/String/padStart)
```js
const cell = strNumber.padStart(widths[i % cols], ' ');
```

2023-09-15 18:37 UTC, ZhukDmitryOlegovich commented on source/format.js
> +		return result + prefix + strElement;
А вообще чтобы не клеить строчки - не думать где `\n`, где пробел, а где вообще не ставить пробел
```js
return Array.from(
    {length: Math.ceil(strNumbers.length / cols)}, 
    (_, i) => strNumbers
        .slice(i * cols, (i + 1) * cols)
        .map((strNumber) => strNumber.padStart(widths[i % cols], ' ')
    ).join(' '),
).join('\n');
```