Давыдов Максим
frontend-park-mail-ru/homework_2023_2 pull request #26
Opened 2023-09-07 21:00 UTC by kek-flip

Выполнил ДЗ

2023-09-09 21:13 UTC, ivanstrilets commented
Привет!
Добро пожаловать на курс по фронтенд-разработке 👋
Я буду проверять твое ДЗ-0. Ниже я буду оставлять комментарии по коду. Желательно на них отвечать

Первым делом исправь пожалуйста свой PR, into должен быть не master

2023-09-09 21:56 UTC, kek-flip commented
> Привет! Добро пожаловать на курс по фронтенд-разработке 👋 Я буду проверять твое ДЗ-0. Ниже я буду оставлять комментарии по коду. Желательно на них отвечать
> 
> Первым делом исправь пожалуйста свой PR, реши конфликты путем правильного оформления самого PR

Исправил

2023-09-10 09:51 UTC, ivanstrilets commented on source/tree.js
> +
Давай добавим JSDoc

2023-09-10 09:52 UTC, ivanstrilets commented
На мой взгляд не хватает файла с тестами

2023-09-10 11:59 UTC, kek-flip commented
Добавил тесты и JSDoc

2023-09-10 18:46 UTC, ivanstrilets commented on source/tree.js
> + * @returns {string} строка с ёлочкой
функция возвращает не только string

2023-09-11 07:52 UTC, kek-flip commented on source/tree.js
> + * @returns {string} строка с ёлочкой
Добавил еще один возвращаемый тип

2023-09-11 09:01 UTC, ivanstrilets commented on source/tree.js
> + * @returns {string} строка с ёлочкой
давай обьеденим @returns по аналогии https://jsdoc.app/tags-returns.html

2023-09-11 09:10 UTC, kek-flip commented on source/tree.js
> + * @returns {string} строка с ёлочкой
Объединил

2023-09-11 09:45 UTC, ivanstrilets approved these changes

2023-09-12 12:04 UTC, DPeshkoff requested changes
Привет! Поздравляю с переходом на второй семестр)

Классное решение получилось, но у меня есть пара замечаний. Если возникнут вопросы - можешь писать в [Telegram](t.me/DmPesh)

2023-09-12 12:04 UTC, DPeshkoff commented on source/tree.js
> +'use strict'
Распиши, пожалуйста, что делает эта строчка?

2023-09-12 12:04 UTC, DPeshkoff commented on tests/tree.js
> +
Давай добавим тесты на некорректный ввод?

2023-09-12 12:04 UTC, DPeshkoff commented on source/tree.js
> +    if (height < 3) {
А что будем делать, если height не будет числом? Давай проверять!

2023-09-13 16:02 UTC, kek-flip commented on source/tree.js
> +'use strict'
Эта строчка активирует "современный режим" работы. Современный режим нужен для работы старых функций языка. Эта необходимость появилась после внесения изменений в язык, не поддерживающих обратную совместимость.

2023-09-13 16:03 UTC, kek-flip commented
Я не пропал - у меня сейчас дни с кучей пар. К концу недели исправлю все недочеты.

2023-09-15 19:25 UTC, DPeshkoff approved these changes

2023-09-15 19:25 UTC, closed without merging