Безруков Георгий
frontend-park-mail-ru/homework_2023_2 pull request #27
Opened 2023-09-07 21:19 UTC by dnonakolesax

2023-09-09 21:07 UTC, ivanstrilets commented
Привет!
Добро пожаловать на курс по фронтенд-разработке 👋
Я буду проверять твое ДЗ-0. Ниже я буду оставлять комментарии по коду. Желательно на них отвечать

2023-09-10 10:06 UTC, ivanstrilets commented on source/chess.js
> +    if (size % 1 != 0) {
более верным будет использовать строгое сравнение

2023-09-10 10:06 UTC, ivanstrilets commented on source/chess.js
> +            desk = (i+j) % 2 == 0 ? desk + '*' : desk + ' '
Тут тоже исправь сравнение, и было бы неплохо использовать переменную desk единожды, например подумать в сторону оператора +=

2023-09-11 12:41 UTC, dnonakolesax commented on source/chess.js
> +    if (size % 1 != 0) {
исправил

2023-09-11 12:41 UTC, dnonakolesax commented on source/chess.js
> +            desk = (i+j) % 2 == 0 ? desk + '*' : desk + ' '
исправил

2023-09-11 19:08 UTC, ivanstrilets approved these changes

2023-09-12 12:13 UTC, DPeshkoff requested changes
Привет! Поздравляю с переходом на второй семестр)

Классное решение получилось, но у меня есть пара замечаний. Если возникнут вопросы - можешь писать в [Telegram](t.me/DmPesh)

2023-09-12 12:13 UTC, DPeshkoff commented on source/chess.js
> +        return null
Предлагаю вместо этого выбрасывать [ошибку](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Error)

2023-09-12 12:13 UTC, DPeshkoff commented on source/chess.js
> +        for (let j = 0; j < size; j++) {
А можем ли мы как-то поиспользовать методы строк языка?)

2023-09-12 12:13 UTC, DPeshkoff commented on source/chess.js
> +    if (isNaN(size)) {
Распиши, а чем `isNaN` отличается от `Number.isNaN`?

2023-09-12 12:13 UTC, DPeshkoff commented on source/chess.js
> +    if (size % 1 !== 0) {
0 может быть скастовано в [falsy](https://developer.mozilla.org/en-US/docs/Glossary/Falsy)

2023-09-13 01:04 UTC, dnonakolesax commented on source/chess.js
> +'use strict'
Эта строчка включает "строгий режим", который позволяет выдавать исключения в случае таких ошибок, которые раньше игнорировались. Например, без этого режима можно присвоить значение необъявленной переменной, и тогда будет создана новая глобальная переменная, тогда как в "строгом режиме" будет ReferenceError.

2023-09-13 01:04 UTC, dnonakolesax commented on source/chess.js
> +        return null
исправил

2023-09-13 01:05 UTC, dnonakolesax commented on source/chess.js
> +let chess = size => {
let - переменная в области видимости блока, var - переменная в области видимости функции (вроде как устаревшее решение), const - переменная в области видимости блока, которая не может быть перезаписана (например, если это объект класса, можно поменять одно из полей, но нельзя поменять сам объект на другой). Насчёт let в функции промахнулся, следовало использовать const, исправил.

2023-09-13 01:05 UTC, dnonakolesax commented on source/chess.js
> +    let desk = ""
исправил

2023-09-13 01:05 UTC, dnonakolesax commented on source/chess.js
> +        for (let j = 0; j < size; j++) {
исправил

2023-09-13 01:06 UTC, dnonakolesax commented on source/chess.js
> +    if (isNaN(size)) {
isNaN предварительно кастит не число в число, при этом надо учитывать, что в процессе каста true/false станут 1/0, null станет 0, пустая строка также станет 0. Number.isNaN работает только с числами, если ему отдать, например, строку, то он вернёт false.

2023-09-13 01:07 UTC, dnonakolesax commented on source/chess.js
> +    if (size % 1 !== 0) {
исправил

2023-09-13 10:18 UTC, DPeshkoff approved these changes

2023-09-13 10:18 UTC, closed without merging