Красноперов Алексей  (Вариант 8)
frontend-park-mail-ru/homework_2023_2 pull request #28
Opened 2023-09-07 21:28 UTC by SanExpett

2023-09-10 21:13 UTC, ZhukDmitryOlegovich commented on tests/sort.js
> +		//assert.strictEqual(sort('космический корабль летит на марс'), 'Абклорь Амрс Aн Еиийккмоссч Еилтт');
очевидная ошибка здесь и то что ты выше указал - поправь и всё

2023-09-10 21:13 UTC, ZhukDmitryOlegovich commented on source/sort.js
> +const sort = function (str) {
Используй стрелочные функции https://learn.javascript.ru/arrow-functions-basics

2023-09-10 21:13 UTC, ZhukDmitryOlegovich commented on source/sort.js
> +	if ( (isEnglish(str) ^ isRussian(str)) && str.trim().length != 0 ) { // только русские или только английские буквы + проверям, что не из пробелов/пустая
вообще ты интересно так усложнил сам себе задачу добавив обработки алфавитов и тп - наверное из-за сломанного теста

можешь выпилить проверку на алфавиты и лишние пробелы и упростить себе задачу - либо оставить и дальше будем жить и ревьюить более сложную версию задачи - даю возможность не усложнять себе жизнь

2023-09-10 21:13 UTC, ZhukDmitryOlegovich commented on source/sort.js
> +		for (let i = 0; i < words.length; i++) {
этот `for` стоит заменить на вызов `words.map`

2023-09-10 21:13 UTC, ZhukDmitryOlegovich commented on source/sort.js
> +	if ( (isEnglish(str) ^ isRussian(str)) && str.trim().length != 0 ) { // только русские или только английские буквы + проверям, что не из пробелов/пустая
`^` - XOR в js - операция только над целыми числами и для булианов применять не хорошо - используй `!==`

2023-09-10 21:13 UTC, ZhukDmitryOlegovich commented on source/sort.js
> +	if ( (isEnglish(str) ^ isRussian(str)) && str.trim().length != 0 ) { // только русские или только английские буквы + проверям, что не из пробелов/пустая
по ДЗ0 надо проверять типы входных данных - добавь проверку что str это строка

2023-09-10 21:13 UTC, ZhukDmitryOlegovich commented on source/sort.js
> +			words[i] = words[i][0].toUpperCase() + words[i].slice(1).toLowerCase(); //первая прописная, остальные строчные
- [ ] вынеси отдельно функцию `capitalize` - которая будет делать первую букву прописной, остальные строчные (+ не забудь кейс с пустой строкой - например используй `charAt`)
- [ ] вынеси отдельно функцию которая сортирует две строки - например так и назови `localeCompare` - чтобы не повторять дважды эту конструкцию

2023-09-10 21:13 UTC, ZhukDmitryOlegovich commented on source/sort.js
> +	    return 'Incorrect string'
нехорошо как ошибку возвращать строку - возвращай либо null, либо пробрасывай ошибку

2023-09-10 21:13 UTC, ZhukDmitryOlegovich commented on source/sort.js
> +}
пустая строка в конце нужна =(

2023-09-10 21:28 UTC, ZhukDmitryOlegovich commented
Некорректное название ПРа. Оно должно быть «Фамилия Имя»

2023-09-11 21:23 UTC, ZhukDmitryOlegovich requested changes

2023-09-11 21:23 UTC, ZhukDmitryOlegovich commented on source/sort.js
> +	if (typeof str === 'string' && str.length !== 0){ // проверяем тип и что не пустая
Для вспомогательной функции типы можно не проверять - надо делать только для основной ибо ДЗ0

2023-09-11 21:23 UTC, ZhukDmitryOlegovich commented on source/sort.js
> +	return strArray.sort(function (a, b) {return a.localeCompare(b);});
расскажи в чем разница между function declaration и arrow function - https://learn.javascript.ru/arrow-functions-basics и убери function

2023-09-11 21:23 UTC, ZhukDmitryOlegovich commented on source/sort.js
> +	return strArray.sort(function (a, b) {return a.localeCompare(b);});
Сделай [без фигурных скобок](https://learn.javascript.ru/arrow-functions-basics#:~:text=%D0%B1%D1%8B%D0%B2%D0%B0%D1%8E%D1%82%20%D0%B4%D0%B2%D1%83%D1%85%20%D1%82%D0%B8%D0%BF%D0%BE%D0%B2%3A-,%D0%91%D0%B5%D0%B7%20%D1%84%D0%B8%D0%B3%D1%83%D1%80%D0%BD%D1%8B%D1%85%20%D1%81%D0%BA%D0%BE%D0%B1%D0%BE%D0%BA,-%3A%20(...args)%20%3D%3E%20expression)

2023-09-11 21:23 UTC, ZhukDmitryOlegovich commented on source/sort.js
> +		return sortedWords.join(' ');
сделай так чтобы данные сразу перетекали из одного состояние во второе-в третье - то есть без использования промежуточных переменных и присваивания в переменные - чтобы с 17 строки был `return` и понеслась =)

2023-09-11 21:23 UTC, ZhukDmitryOlegovich commented on source/sort.js
> +	    return null
надо выбрасывать ошибку всё таки - [TypeError](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/TypeError)

2023-09-12 11:31 UTC, SanExpett commented on source/sort.js
> +	return strArray.sort(function (a, b) {return a.localeCompare(b);});
1) можно не писать return в однострочных стрелочных функциях, return произойдет неявно
2) более краткий синтаксис 
3) argiuments недоступен в стрелочных функциях 
4) this привязывается не к вызывающему функцию объекту, а к окружению, в котором функция была определена

2023-09-12 19:59 UTC, ZhukDmitryOlegovich commented on source/sort.js
> +	if ( typeof str === 'string' ) { // проверяем тип
сделай ранний выход - если str не строка - то выкинуть TypeError ошибку и весь последующий код уже в блок этого ифа не оборачивать - уменьшиться вложенность - станет проще

2023-09-12 20:28 UTC, ZhukDmitryOlegovich commented on source/sort.js
> +const localeCompare = (strArray) => strArray.sort( (a, b) => a.localeCompare(b) ); // сортировка по алфавиту
```suggestion
const localeCompare = (a, b) => a.localeCompare(b); // сортировка по алфавиту
```
давай так - а ниже явно sort вызывать - чтобы не получалось что большой кусок кода обернут в `localeCompare(arr.blablabla)`  и было `arr.blablabla.sort(localeCompare)`

2023-09-12 20:39 UTC, SanExpett commented on source/sort.js
> +const localeCompare = (strArray) => strArray.sort( (a, b) => a.localeCompare(b) ); // сортировка по алфавиту
тогда непонятно какие a, b передавать в localeCompare

2023-09-12 20:56 UTC, ZhukDmitryOlegovich commented on source/sort.js
> +	}).sort(localeCompare).join(' ');
а сделай внутри map тоже без return

не бойся каждый вызов на новую строку переносить, по типу
```js
return str.replace(/\s+/g, ' ')
	.trim()
	.split(' ')
	.map(...
```

2023-09-13 06:56 UTC, ZhukDmitryOlegovich approved these changes

2023-09-13 10:48 UTC, DPeshkoff requested changes
Привет! Поздравляю с переходом на второй семестр)

Интересное решение получилось, но у меня есть пара замечаний. Если возникнут вопросы - можешь писать в [Telegram](t.me/DmPesh)

2023-09-13 10:48 UTC, DPeshkoff commented on source/sort.js
> +'use strict';
Распиши, пожалуйста, что делает эта строчка?

2023-09-13 10:48 UTC, DPeshkoff commented on source/sort.js
> +	if ( typeof str !== 'string' ) { // проверяем тип
Упс! 

![изображение](https://github.com/frontend-park-mail-ru/homework_2023_2/assets/31134795/5afd937a-9f4c-4dbd-a0a1-8d4662f11341)

При этом это валидные строки... непорядок! Давай подумаем, как это починить)

2023-09-13 10:48 UTC, DPeshkoff commented on source/sort.js
> +		throw new TypeError('Аргумент должен быть строкой'); // добавил ранний выход с выбрасыванием TypeError
Такой комментарий из кода понятен - такие можно не оставлять)

2023-09-13 10:48 UTC, DPeshkoff commented on source/sort.js
> +
Давай добавим перенос строки в конце файла

2023-09-13 10:48 UTC, DPeshkoff commented on tests/sort.js
> +	});
Давай напишем тесты на некорректный ввод)

2023-09-14 09:46 UTC, SanExpett commented on source/sort.js
> +'use strict';
Включает строгий режим работы. В нем будут выбрасываться ошибки на некоторые небезопасные конструкции, которые были бы валидны без него.

2023-09-14 11:37 UTC, DPeshkoff approved these changes

2023-09-14 11:38 UTC, closed without merging