Гнатенко Татьяна
frontend-park-mail-ru/homework_2023_2 pull request #29
Opened 2023-09-07 21:46 UTC by Tanya-g99

2023-09-08 07:02 UTC, johnSamilin commented
Привет, добро пожаловать на курс по фронтенд-разработке. Я буду проверять твое ДЗ 0.
Если у меня появятся комментарии к коду, то я опишу их здесь. Можешь отвечать на них тут же, а чтобы что-то уточнить - [телеграм](https://t.me/WatasheeBaka)

2023-09-08 07:12 UTC, johnSamilin requested changes

2023-09-08 07:12 UTC, johnSamilin commented on source/euclid.js
> +const euclid = (...numbers) => {
Допиши пожалуйста JSDoc для этой функции

2023-09-08 07:12 UTC, johnSamilin commented on source/euclid.js
> +	numbers.forEach((num) => {
А можно ли переписать этот цикл, используя метод reduce? Получилось бы чуть удобней и меньше переменных объявлять

2023-09-08 07:12 UTC, johnSamilin commented on source/euclid.js
> +};
В конец файла стоит добавлять пустую строку чтобы в будущем было чуть меньше изменений

2023-09-08 07:12 UTC, johnSamilin commented on source/euclid.js
> +		while (num && nod) {
А что если одним из аргументов окажется не число, а строка\функция\null?

2023-09-08 07:12 UTC, johnSamilin commented on tests/euclid.js
> +		assert.strictEqual(euclid(2), 2, "euclid(2) === 2");
в этом тесте достаточно одной проверки, мы ведь уже убедились в правильности работы с одним аргументом

2023-09-08 07:12 UTC, johnSamilin commented on source/euclid.js
> +		while (num && nod) {
или, например, кто-то передаст массив с числами вместо того, чтобы передавать их отдельными аргументами

2023-09-12 19:35 UTC, johnSamilin requested changes

2023-09-12 19:35 UTC, johnSamilin commented on source/euclid.js
> + * @param {...number} numbers - Числа, для которых нужно вычислить наибольший общий делитель
Здесь не нужен rest-оператор, это же описание типа

2023-09-12 19:35 UTC, johnSamilin commented on source/euclid.js
> +	if (!numbers.every((arg) => Number.isInteger(arg) && arg > 0 && arg !== Number.MAX_VALUE)) {
Во-первых, здесь проще было бы использовать метод some, чтобы сэкономить пару циклов. Во-вторых, отлично что ты знаешь про every! В третьих, сравнение с MAX_VALUE вроде бы не имеет смысла, тогда уж с MAX_SAFE_INTEGER

2023-09-12 19:35 UTC, johnSamilin commented on tests/euclid.js
> +			assert.throws(() => euclid([1, 2, 3]), new TypeError("expected sequence of natural numbers"))
Давай разрешим пользователю вот такой сценарий. Иногда бывает удобно передать в функцию переменную, в которой лежит массив с числами, не деструктурируя его лишний раз

2023-09-13 12:09 UTC, johnSamilin approved these changes

2023-09-13 14:48 UTC, DPeshkoff commented on source/euclid.js
> +			|| numbers.some(
Семантически лучше some или every?)

2023-09-13 14:49 UTC, DPeshkoff commented on tests/euclid.js
> +
Давай вынесем повторяющиеся ошибки и текст в константу для этого тесткейса

2023-09-16 16:58 UTC, Tanya-g99 commented on source/euclid.js
> +'use strict';
Включает строгий режим. Ошибки в коде преобразуются в исключения, то есть запрещает некоторый синтаксис

2023-09-16 17:00 UTC, Tanya-g99 commented on source/euclid.js
> +	}
В функцию может быть передан массив, поэтому я в первом блоке его достаю, а затем идет уже блок проверок массива чисел. И чтобы не было дублирования кода все проверки массива чисел идут во втором блоке и после первого.

2023-09-16 17:08 UTC, Tanya-g99 commented on source/euclid.js
> +			|| numbers.some(
Some и every - это как or и and.  Every проверяет все ли элементы удовлетворяют условию и если встречается элемент, который не удовлетворяет, то выбрасывает false. Some проверяет есть ли какой-нибудь элемент, удовлетворяющий условию, и если находит такой, то возвращает true. 
Считаю, что мне тут больше подходит every, потому что как раз нужно проверить все ли элементы являются натуральными числами.
Мне вернуть every?

2023-09-16 20:18 UTC, DPeshkoff commented on source/euclid.js
> +			|| numbers.some(
если нетрудно - было бы круто)

2023-09-16 20:55 UTC, johnSamilin commented on source/euclid.js
> +			|| numbers.some(
не стану спорить, просто хотел объяснить повод, по которому я завел речь про some и every. мне кажется, логичней как раз some, потому что условие говорит о том, что *если аргумент не массив, у него нулевая длина или в нем есть ненатуральные числа, то выкинь исключение*

2023-09-16 22:11 UTC, Tanya-g99 commented on source/euclid.js
> +			|| numbers.some(
Но при нахождении ненатурального числа some выкинет true, а при нулевой длине массива false

2023-09-17 15:48 UTC, DPeshkoff approved these changes

2023-09-17 15:48 UTC, closed without merging