Дмитриев Александр Web-22
frontend-park-mail-ru/homework_2023_2 pull request #3
Opened 2023-09-05 21:39 UTC by BincomAD

Дмитриев Александр Web-22

2023-09-06 03:08 UTC, LDK28 commented
Привет! Я ментор программы Фронтенд разработки. Я буду проверять твое дз, так что в следующих комментариях опешу свои вопросики по коду :)

2023-09-06 03:10 UTC, LDK28 commented on source/roman.js
> +function roman(input) {
Почему бы здесь не использовать стрелочную функцию? И в чем их разница?

2023-09-06 03:20 UTC, LDK28 commented on source/roman.js
> +        for (const num of romanNum) {
Попробуй, пожалуйста, использовать встроенные в js методы массивов https://learn.javascript.ru/array-methods

2023-09-06 03:20 UTC, LDK28 commented on source/roman.js
> +        for (let i = 0; i < input.length; i++) {
Здесь также лучше использовать встроенные в js методы массивов https://learn.javascript.ru/array-methods

2023-09-06 03:21 UTC, LDK28 commented on source/roman.js
> +            if (nextRomanVal && curRomanVal < nextRomanVal) {
Здесь можно написать в одну строчку, используя тернарный оператор https://learn.javascript.ru/ifelse#uslovnyy-operator

2023-09-06 06:37 UTC, LDK28 commented on tests/roman.js
>  });
По "канону" в конце файликов нужно оставлять пустую строку :)

2023-09-06 06:41 UTC, LDK28 commented on source/roman.js
> +    if (Number(input)) {
Во всех ли случаях сработает корректно эта проверка?

2023-09-06 06:44 UTC, LDK28 commented on source/roman.js
> +        if (!/^[IVXLCDMivxlcdm]+$/.test(input)) {
Не совсем очевидная проверка, ее лучше вынести в начало функции, чтобы все ошибочные выходы были без совершения лишних действий, ну и плюс это повысит читаемость кода

2023-09-06 06:59 UTC, LDK28 commented on source/roman.js
> +'use strict';
Для чего используется use strict?

2023-09-06 07:03 UTC, LDK28 commented
Когда поправишь замечания, можешь тегнуть меня тут или в написать в тг https://t.me/dkey28

Также для себя можешь резолвить замечания/вопросы, когда решишь их

2023-09-06 11:43 UTC, LDK28 commented
Поменяй, пожалуйста, название ПР на "Фамилия Имя", чтобы нам в дальнейшем было проще его проверять

2023-09-06 20:05 UTC, BincomAD commented on source/roman.js
> +function roman(input) {
Нет необходимости ее использовать, мне кажется более удобный и читаемый вариант с обычной функцией. Основная их разница в контексте, у стрелочной функции отсутствует собственный this, она ссылается на this внешней функции.

2023-09-06 20:41 UTC, BincomAD commented on source/roman.js
> +    if (Number(input)) {
Нет, потому что может быть строка в которой будет float и Number( ) сможет ее обработать, при этом по условию нам такое число не подходит.

2023-09-06 20:50 UTC, BincomAD commented on source/roman.js
> +    if (Number(input)) {
Так же при 0, если попадет на вход 0, то мы попадем в else, хотя 0 является числом

2023-09-06 20:52 UTC, BincomAD commented on source/roman.js
> +'use strict';
Для включения в скрипте "Современного режима"

2023-09-06 21:01 UTC, BincomAD commented on source/roman.js
> +        for (let i = 0; i < input.length; i++) {
Не совсем понимаю, как и где тут применить методы масивов:(

2023-09-07 10:04 UTC, LDK28 commented on source/roman.js
> +function roman(input) {
Да, все верно, но давай все таки использовать стрелочную функцию, она более современная и меньше кода пишется

2023-09-07 10:10 UTC, LDK28 commented on source/roman.js
> +    if (Number(input)) {
Тогда нужно написать проверки для подобных случаев 
https://learn.javascript.ru/types-intro#type-typeof

2023-09-07 10:12 UTC, LDK28 commented on source/roman.js
> +        for (let i = 0; i < input.length; i++) {
Прошу прощения, я поторопился, тут они и в правду не очень нужны 😅

2023-09-07 13:38 UTC, LDK28 commented on source/roman.js
> + * @param {number} number - Арабское число
Не совсем понятно, почему два аргумента, плюс название не совпадает с тем, что принимает функция. Если ты хочешь описать, что аргумент может быть двух типов, то надо написать `@param {(string|number)}` ну и дальше уже текстом описать что к чему

2023-09-07 13:38 UTC, LDK28 commented on source/roman.js
> + * @returns {number} - Вернет результат перевода из римского числа
Аналогично с возвращаемым значением. Оно априори может быть только одним

2023-09-07 13:38 UTC, LDK28 commented on source/roman.js
> +        if (input <= 0 || input >= 3999 || !Number.isInteger(Number(input))) {
Проверки на ошибочные аргументы надо вынести на самый верх функции, чтобы никаких лишних действий в таком случае не совершалось.

Другой вопрос, насколько эта проверка полна?
Даю подсказку, что если input = [1]

2023-09-07 13:44 UTC, BincomAD commented on source/roman.js
> +        if (input <= 0 || input >= 3999 || !Number.isInteger(Number(input))) {
Если input = 1, то мы в любом случае входим в условие и выдаем в ответе I

2023-09-07 13:50 UTC, BincomAD commented on source/roman.js
> +        if (input <= 0 || input >= 3999 || !Number.isInteger(Number(input))) {
А, что-то выкинул из головы массив, извиняюсь)

2023-09-07 14:11 UTC, LDK28 commented on source/roman.js
> + * @param {number|string} number - Изначальеное число
После типа в jsdoc пишется название агрумента и потом его описание

То есть, в твоем случае должно быть 
`* @param {number|string} input - Изначальеное число`

2023-09-07 14:41 UTC, LDK28 commented on source/roman.js
> +    if (Number(input) || input === 0 || Number.isInteger(Number(input))) {
Кажется, что первая проверка не нужна, так как ее выполняет последняя. Только надо их со второй местами поменять, чтобы не крашнулось

2023-09-08 11:04 UTC, Sarafa2n requested changes

2023-09-08 11:04 UTC, Sarafa2n commented on source/roman.js
> +    if (!/^[IVXLCDMivxlcdm0123456789]+$/.test(input) || typeof input !== 'number' && typeof input !== 'string') {
https://learn.javascript.ru/regexp-introduction - насчет регулярки
А что будет если передадут `new Number()` или `new String()`

2023-09-08 11:04 UTC, Sarafa2n commented on source/roman.js
> +        return "Error";
Если ошибка лучше кидать `throw`

2023-09-08 11:04 UTC, Sarafa2n commented on source/roman.js
> +        const romanNum = [
Это можно вынести в глобальную константу

2023-09-08 11:04 UTC, Sarafa2n commented on source/roman.js
> +    if (Number.isInteger(Number(input))) {
а может переводы перенести в отдельные функции, а то roman большой получается

2023-09-08 11:04 UTC, Sarafa2n commented on source/roman.js
> +        return out
а если переделать на `reduce` ?

2023-09-08 11:04 UTC, Sarafa2n commented on source/roman.js
> +        }
А зачем тебе две одинаковых константы ?

2023-09-08 11:04 UTC, Sarafa2n commented on source/roman.js
> +        }
опять таки `reduce`

2023-09-08 11:04 UTC, Sarafa2n commented on tests/roman.js
> +
а если я закину undef null NaN  ? 
Добавь больше тестов, подумай какие кейсы могут быть еще

2023-09-08 21:54 UTC, BincomAD commented on source/roman.js
> +        }
Не совсем понимаю, как здесь переделать на reduce

2023-09-08 21:58 UTC, BincomAD commented on source/roman.js
> +        return "Error";
Испрвил

2023-09-08 21:58 UTC, BincomAD commented on source/roman.js
> +    if (!/^[IVXLCDMivxlcdm0123456789]+$/.test(input) || typeof input !== 'number' && typeof input !== 'string') {
Регулярку сократил. Если передать new Number() или new String() то выкинет throw "Error", так их тип - Object, а не string или number

2023-09-08 22:03 UTC, BincomAD commented on tests/roman.js
> +
Добавил тесты

2023-09-08 22:03 UTC, BincomAD commented on source/roman.js
> +        return out
Переделал)

2023-09-09 11:10 UTC, Sarafa2n requested changes

2023-09-09 11:10 UTC, Sarafa2n commented on source/roman.js
> +            throw "Error";
посмотри какие есть классы для ошибок, к примеру `new Error`

2023-09-09 11:10 UTC, Sarafa2n commented on source/roman.js
> +    if (!/^[IVXLCDM\d]+$/i.test(input) || typeof input !== 'number' && typeof input !== 'string') {
<img width="215" alt="image" src="https://github.com/frontend-park-mail-ru/homework_2023_2/assets/32399246/340bdade-6ffa-4e7b-b1eb-eda0f7d92e38">

Писал же что не все учел

2023-09-09 11:10 UTC, Sarafa2n commented on source/roman.js
> +    }
а тут что не переделал ? на `reduce`

2023-09-09 11:10 UTC, Sarafa2n commented on source/roman.js
> +const romanNum = [
https://learn.javascript.ru/variables#konstanty-v-verhnem-registre

2023-09-09 11:10 UTC, Sarafa2n commented on source/roman.js
> +const romanToNumber = input => {
давай скобки добавим, по стайл гайдам будем делать)

2023-09-09 11:10 UTC, Sarafa2n commented on tests/roman.js
> +		assert.throws(function() {roman('VK-Park')});
у тебя на все одна ошибка, давай их разделим по семантике и будем проверять что ошибка совпадает с ожидаемой

2023-09-10 12:05 UTC, BincomAD commented on tests/roman.js
> +		assert.throws(function() {roman('VK-Park')});
Все исправил)

2023-09-11 08:34 UTC, BincomAD commented
@Sarafa2n прошу посмотреть коммит, по возможности)

2023-09-11 16:45 UTC, Sarafa2n commented on source/roman.js
> +
Это можно убрать в функцию  `numberToRoman`

2023-09-11 16:46 UTC, Sarafa2n commented on source/roman.js
> +        input = input.toUpperCase();
так делать не оч хорошо, ты мутируешь данные, почитай что такое чистая функция

2023-09-11 16:47 UTC, Sarafa2n commented on source/roman.js
> +        return romanToNumber(input);
давай сделаем вид следующий `return smth ? romanTonumber(input) : ... `
так короче и понятнее

2023-09-11 16:47 UTC, Sarafa2n commented on source/roman.js
> +    if (!/^[IVXLCDM\d]+$/i.test(input) || typeof input !== 'number' && typeof input !== 'string'  && !(input instanceof Number) && !(input instanceof String)) {
большое условие в одну строку не оч, сделай переносы

2023-09-11 16:47 UTC, Sarafa2n commented on source/roman.js
> +        return romNum[input[i + 1]] && romNum[curr] < romNum[input[i + 1]] ? out -= romNum[curr] : out += romNum[curr];
тут тоже сделай переносы

2023-09-11 18:05 UTC, BincomAD commented
@Sarafa2n готово

2023-09-12 07:47 UTC, Sarafa2n requested changes

2023-09-12 07:47 UTC, Sarafa2n commented on source/roman.js
> +}
в конце файла нет пустой строки, нужно бы добавить

2023-09-12 07:47 UTC, Sarafa2n commented on source/roman.js
> +        return romNum[newInput[i + 1]] && romNum[curr] <
а что тут не как здесь ? 
<img width="389" alt="image" src="https://github.com/frontend-park-mail-ru/homework_2023_2/assets/32399246/a4aa533d-42ba-4a44-a1b1-4a6884ad0d86">

2023-09-12 10:07 UTC, BincomAD commented on source/roman.js
> +}
Git убирает, добавил еще одну строчку)

2023-09-12 10:07 UTC, BincomAD commented on source/roman.js
> +        return romNum[newInput[i + 1]] && romNum[curr] <
Сделал так же

2023-09-12 12:03 UTC, BincomAD commented
@Sarafa2n готово

2023-09-12 14:05 UTC, Sarafa2n requested changes

2023-09-12 14:05 UTC, Sarafa2n commented on source/roman.js
> +    let newInput = input.toUpperCase();
const

2023-09-12 18:17 UTC, BincomAD commented
@Sarafa2n готово

2023-09-12 18:51 UTC, closed without merging