Степаненко Андрей, Вариант 12
frontend-park-mail-ru/homework_2023_2 pull request #30
Opened 2023-09-07 21:52 UTC by 1qwaka

2023-09-08 09:29 UTC, Krasava872 commented on source/minmax.js
> +    if (numbers.length == 0)
Некорректный оператор сравнения.

2023-09-08 09:56 UTC, Krasava872 commented
Я один из менторов программы Фронтенд разработки, будут вопросы пиши в [телегу](https://t.me/KrasavtsevSS)

2023-09-09 20:16 UTC, 1qwaka commented on source/minmax.js
> +    if (numbers.length == 0)
поменял на ===

2023-09-09 20:17 UTC, 1qwaka commented on tests/minmax.js
> +	QUnit.test('minmax игнорирует числа, которые стоят вплотную к словам', function (assert) {
поменял, чтобы считывало числа везде

2023-09-09 20:19 UTC, 1qwaka commented on source/minmax.js
> +function minmax(str) {
Добавил jsdoc
Знаю, что такой вид определения функции позволяет вызывать ее в коде раньше, чем она определена, в данном случае не дает преимуществ, просто мне так привычнее

2023-09-09 20:21 UTC, 1qwaka commented on source/minmax.js
> +        .filter(num => !Number.isNaN(num));
исправил на один проход через цикл, не очень понял какой метод можно использовать для одновременной фильтрации и преобразования элементов

2023-09-09 20:21 UTC, 1qwaka commented on source/minmax.js
> +        return minAndMax;
добавил фигурные скобки

2023-09-09 23:58 UTC, Krasava872 requested changes

2023-09-09 23:58 UTC, Krasava872 commented on source/minmax.js
> +    for (const numStr of numberStrings) {
Перепиши на метод reduce, на каждой итерации ты сможешь выбирать пополнять тебе коллекцию данных или нет.

2023-09-09 23:58 UTC, Krasava872 commented on source/minmax.js
> +    if (numbers.length === 0) {
Всё ещё можно упростить условие, и когда в условии одна операция можно писать без скобок, просто не должно быть переносов строк.

2023-09-09 23:58 UTC, Krasava872 commented on source/minmax.js
>      const minAndMax = [ undefined, undefined ];
Значение этой переменной используется на 12 строчке, лучше перенести объявление переменной выше и сразу её использовать во всех местах.

2023-09-09 23:58 UTC, Krasava872 commented on source/minmax.js
>  'use strict';
А для чего эта строчка? Можем её убрать?

2023-09-09 23:58 UTC, Krasava872 commented on source/minmax.js
>  function minmax(str) {
Что будет если вместо строки передать сюда пустой массив?

2023-09-10 11:04 UTC, 1qwaka commented on source/minmax.js
>  function minmax(str) {
Выдаст ошибку по причине отсутствия метода `match` у массива

2023-09-10 11:15 UTC, 1qwaka commented on source/minmax.js
>  'use strict';
В данном случае можем убрать, эта строка была добавлена в одном из стандартов для сохранения обратной совместимости, то есть она отключает некоторые старые "фичи". Я их в данном скрипте не использую, но рекомендуется всегда писать use strict во избежание ошибок

2023-09-10 11:15 UTC, 1qwaka commented on source/minmax.js
>      const minAndMax = [ undefined, undefined ];
исправил

2023-09-10 11:16 UTC, 1qwaka commented on source/minmax.js
> +    if (numbers.length === 0) {
исправил

2023-09-10 11:16 UTC, 1qwaka commented on source/minmax.js
> +    for (const numStr of numberStrings) {
переписал не reduce

2023-09-10 20:46 UTC, Krasava872 requested changes

2023-09-10 20:46 UTC, Krasava872 commented on source/minmax.js
>  function minmax(str) {
Давай тогда добавим проверку на входные типы аргументов.

2023-09-11 18:12 UTC, Krasava872 requested changes

2023-09-11 18:12 UTC, Krasava872 commented on source/minmax.js
> +    if (!(str instanceof String)) throw TypeError("str argument should be a String");
Ну в проверке явно ошибка, в js срока чащще всего является примитивом, у тебя сейчас даже тесты падают. Эту проверку пройдет строка созданная только через конструктор, что используется крайне редко. Надо переделать

2023-09-11 20:26 UTC, Krasava872 approved these changes

2023-09-13 10:53 UTC, DPeshkoff requested changes
Привет! Поздравляю с переходом на второй семестр)

Классное решение получилось, но у меня есть пара замечаний. Если возникнут вопросы - можешь писать в [Telegram](t.me/DmPesh)

2023-09-13 10:53 UTC, DPeshkoff commented on source/minmax.js
> +function minmax(str) {
А какие в языке есть способы создания функций и чем они отличаются? Почему выбрал именно такой?

2023-09-13 10:53 UTC, DPeshkoff commented on source/minmax.js
> +    if (!(typeof str === 'string' || str instanceof String)) throw TypeError("str argument should be a String");
Вообще в языке приняты одиночные кавычки, давай поменяем)

2023-09-13 10:53 UTC, DPeshkoff commented on source/minmax.js
> +    if (!numberStrings) return minAndMax;
Предлагаю везде обернуть в {} и вынести на новую строчку такие однострочные проверки - это улучшит читаемость кода

2023-09-13 10:53 UTC, DPeshkoff commented on tests/minmax.js
> +	});
Давай добавим тесты на некорректный ввод)

2023-09-14 11:38 UTC, DPeshkoff commented on source/minmax.js
> +function minmax(str) {
up)

2023-09-14 11:39 UTC, DPeshkoff requested changes

2023-09-14 22:52 UTC, DPeshkoff requested changes

2023-09-14 22:52 UTC, DPeshkoff commented on source/minmax.js
> +function minmax(str) {
Выглядит как юзкейс для стрелочный функции - аргумент "так привычнее" не очень хороший, инструменты существуют для того, чтобы их использовать в правильное время

2023-09-15 05:15 UTC, 1qwaka commented on source/minmax.js
> +function minmax(str) {
Понял, исправил

2023-09-15 19:27 UTC, DPeshkoff approved these changes

2023-09-15 19:28 UTC, closed without merging