Гуков Леонид
frontend-park-mail-ru/homework_2023_2 pull request #31
Opened 2023-09-07 21:56 UTC by DQWR

2023-09-07 21:56 UTC, BincomAD commented
Леня Воронин был оппом и мы его грохнули

2023-09-08 10:55 UTC, GreatFix commented
Привет! Welcome to курс по фронтенд-разработке. Я буду проверять твое ДЗ 0.
Если у меня появятся комментарии к коду, то я опишу их здесь. 

Можешь отвечать на них тут же, но если что, я доступен в [телеге](https://t.me/FixFive)

2023-09-08 11:11 UTC, GreatFix requested changes

2023-09-08 11:11 UTC, GreatFix commented on tests/chess.js
> +// QUnit.test('Строку нельзя использовать как входные данные', function (assert) {
Ни здесь ни на будущей твоей работе будет недопустимо добавлять в коммит закомментированный код. Это не редкая и нормальная ситуация, важно просто это исправлять. Например, когда создаешь PR/MR, стоит беглым взглядом пройтись по своему коду в нем, насколько бы ты в нем не был уверен.

2023-09-08 11:11 UTC, GreatFix commented on source/chess.js
> +const chess = (N) => {;
Здесь  `;` пожалуй лишнее) (на 3 строке)

2023-09-08 13:13 UTC, DQWR commented on source/chess.js
> +    let chessboard = '';
сначала поставить проверку входных параметров

2023-09-08 13:14 UTC, DQWR commented on tests/chess.js
> +// QUnit.test('Строку нельзя использовать как входные данные', function (assert) {
да, я специально оставил этот код закомментированным, потому что у меня был вопрос, но он уже решился)

2023-09-08 13:15 UTC, DQWR commented on source/chess.js
> +            chessboard += '*';
окей, выглядит страшно, но сделаю

2023-09-08 13:15 UTC, DQWR commented on source/chess.js
> +const chess = (N) => {;
ещё не дошел до этого, в плане изучения js, но попробую

2023-09-08 13:23 UTC, GreatFix commented on tests/chess.js
> +// QUnit.test('Строку нельзя использовать как входные данные', function (assert) {
Ты полностью удалил тест, может вернешь его? Он был хороший. (только можно рядом с остальными расположить, а не снаружи)

2023-09-08 13:25 UTC, DQWR commented on tests/chess.js
> +// QUnit.test('Строку нельзя использовать как входные данные', function (assert) {
не, там ошибка была в том, что входные данные могут быть, как число так и строка, то-есть 3 или '3', я в chess.js делал проверку на строку, чтобы этот тест пройти, но из-за того что могут быть строчные входные данные - программа ломалась

2023-09-08 13:28 UTC, GreatFix commented on tests/chess.js
> +// QUnit.test('Строку нельзя использовать как входные данные', function (assert) {
Так ты же ведь написал проверку `N % 1 !== 0`, которая не пропустит буквы, но пропускает строки из цифр, типа "123"

2023-09-08 13:30 UTC, DQWR commented on tests/chess.js
> +// QUnit.test('Строку нельзя использовать как входные данные', function (assert) {
точно.....у меня почему-то из головы это вылетело, спасибо большое, щас залью с тестом

2023-09-08 13:36 UTC, DQWR commented on tests/chess.js
> +// QUnit.test('Строку нельзя использовать как входные данные', function (assert) {
залил

2023-09-08 13:44 UTC, GreatFix commented on tests/chess.js
> +		const result = chess('ABRAKADABRA');
Давай еще и форматирование в порядок приведем)

2023-09-08 13:48 UTC, GreatFix commented on source/chess.js
> +};
давай добавим пустую строку в конце файла. Обычно это делается автоматически с помощью линтёров, но здесь их нет, поэтому поработаем ручками, за то запомним.

2023-09-08 13:58 UTC, DQWR commented on source/chess.js
> +};
у меня почему-то гит обрезает последнюю строку, он же вроде так и должен делать

2023-09-09 09:50 UTC, GreatFix approved these changes

2023-09-10 23:22 UTC, DPeshkoff requested changes
Привет! Поздравляю с переходом на второй семестр)

Крутое решение получилось, но у меня есть пара замечаний. Если возникнут вопросы - можешь писать в [Telegram](t.me/DmPesh)

2023-09-10 23:22 UTC, DPeshkoff commented on source/chess.js
> +  if (N <= 1 || N % 1 !== 0) return null;
1) А если N - не число? Если там вообще бесконечность? 

2) В стандарте есть [встроенные ошибки](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Error), давай используем

3) Предлагаю вынести на новую строчку и добавить {}

2023-09-10 23:22 UTC, DPeshkoff commented on source/chess.js
> +      for (let j = 0; j < N; j++) {
У нас есть строка - предлагаю использовать кое-что покруче, например, методы строк или перебирающие методы

2023-09-10 23:22 UTC, DPeshkoff commented on tests/chess.js
> +		assert.strictEqual(expected, null);
А можно прям тут вызвать, на 42 строчке, и не создавать лишнюю переменную)

2023-09-11 21:30 UTC, DQWR commented on tests/chess.js
> +		assert.strictEqual(expected, null);
согласен, думал так прикольнее выглядить будет)

2023-09-11 21:30 UTC, DQWR commented on source/chess.js
> +      for (let j = 0; j < N; j++) {
я добавил в новой версии forEach, как раз это один из возможных перебирающих методов

2023-09-11 21:31 UTC, DQWR commented on source/chess.js
> +  if (N <= 1 || N % 1 !== 0) return null;
добавил проверку на бесконечность и добавил TypeError

2023-09-12 11:43 UTC, DPeshkoff requested changes

2023-09-12 11:43 UTC, DPeshkoff commented on source/chess.js
> +/**
А в каком режиме кода мы находимся? Почему ты выбрал именно такой? Какие вообще есть?)

2023-09-12 11:43 UTC, DPeshkoff commented on source/chess.js
> +};
Новую строку в конце файла потерял)

2023-09-12 18:24 UTC, DQWR commented on source/chess.js
> +/**
ну как мне подсказал гугл, есть два основных режима strict mode и sloppy mode, разница в том, что первый режим не даёт разработчику допускать ошибки, второй же режим, вообще не оповещает об ошибках, если не использовать strict mode, то автоматически будет sloppy mode, значит у меня и был этот режим, но в новом коммите я всё добавил

2023-09-13 10:19 UTC, DPeshkoff commented on source/chess.js
> +};
Скорее всего дело с настройками IDE, git тут не при чем. Покопайся, посмотри, нехорошо так)

2023-09-13 10:24 UTC, DPeshkoff approved these changes

2023-09-13 10:25 UTC, closed without merging