Ильинский Владислав
frontend-park-mail-ru/homework_2023_2 pull request #32
Opened 2023-09-07 22:44 UTC by Vilinvil

Вариант 2 web22

2023-09-11 07:24 UTC, GreatFix requested changes
Привет! Welcome to курс по фронтенд-разработке. Я буду проверять твое ДЗ 0.
У меня появились комментарии к коду, описал их здесь.
Можешь отвечать на них тут же, но если что, я доступен в телеге

2023-09-11 07:24 UTC, GreatFix commented on source/euclid.js
> +    if (args.length === 0 || !Number.isInteger(args[0])) return NaN;
Также проверку стоит доработать так, чтобы проверялись все параметры, а не только первый

2023-09-11 07:24 UTC, GreatFix commented on source/euclid.js
> +            [a, b] = [b, a % b];
Параметры функции не принято изменять, давай объявим локальные переменные

2023-09-11 07:24 UTC, GreatFix commented on source/euclid.js
> +            [a, b] = [b, a % b];
И давай попробуем назвать переменные так, чтобы стало понятней, чем каждая является

2023-09-11 07:24 UTC, GreatFix commented on .idea/.gitignore
> +# Default ignored files
Давай уберем с коммита изменения, не относящиеся  к заданию

2023-09-11 07:25 UTC, GreatFix commented
Давай добавим тесты на отрицательные числа

2023-09-12 09:16 UTC, Vilinvil commented on source/euclid.js
> +    const calcGCD = (a, b) => {
Вообще я хотел добиться того, чтобы это было вспомогательной внутренней функцией и к ней нельзя было получить доступ извне. Также я не хотел внутри неё еще раз проверять на коректность аргументы, т.к. сделал это в ф-ции eucli. Почитал про модули, сделал через них это.

2023-09-12 09:24 UTC, Vilinvil commented on source/euclid.js
> +            [a, b] = [b, a % b];
Тут же копируются параметры, зачем нам лишние переменные и почему их нельзя изменять?

2023-09-12 10:19 UTC, GreatFix commented on source/euclid.js
> +            [a, b] = [b, a % b];
Я написал "не принято", а не "нельзя". Это усложняет чтение кода и может ввести коллег в заблуждение или вообще к неожиданным поведениям, если параметры объекты. Данная функция простенькая, поэтому здесь это не так заметно. Но, изменять параметры не стоит и в таких функциях, чтобы было единообразно.

2023-09-12 10:23 UTC, GreatFix commented on source/euclid.js
> +            if (!Number.isInteger(current)) return NaN;
Если проверишь параметры выше, в случае некорректных параметров, не будет вызвано Math.abs и reduce, а также избежишь возможных ошибок. По скорости нет значимой разницы

2023-09-12 21:24 UTC, Vilinvil commented on source/euclid.js
> +            [a, b] = [b, a % b];
Исправил, но выглядит как-то теперь странновато, посмотри, пожалуйста, на ф-цию calcGCD, так?

2023-09-13 09:29 UTC, GreatFix requested changes
В целом все гуд, осталось чуть доработать

2023-09-13 09:29 UTC, GreatFix commented on index.html
> +    import {euclid} from "./source/euclid.js";
Решение с модулем не обязательное, но хорошее. Давай тогда просто заимпортишь функцию внутри tests/euclid.js , а здесь удалишь этот script.

2023-09-13 09:29 UTC, GreatFix commented on source/euclid.js
> +    while (secondNumber !== 0) {
Можешь доработаешь условие так, чтобы для случая 1,1 не было лишних вычислений?

2023-09-13 10:59 UTC, Vilinvil commented on index.html
> +    import {euclid} from "./source/euclid.js";
Я импортирую здесь euclid, т.к. если импортировать его в test/euclid.js, то это сделает тестовый файл модулем, тогда при импорте уже тестового модуля в index.html у него будет своя область видимости, и его не будет видно в тестовой библиотеке. Я попытался найти как это пофиксить, но безуспешно. Ты знаешь как решить этот вопрос?

2023-09-13 11:10 UTC, Vilinvil commented on source/euclid.js
> +    let GCD = args.reduce((gcd, current) => {
Да, здесь лучше const. Const переменная не может изменить объект, на который ссылается, но по ней также можно изменить сам объект. let переменная может сменить объект, на который ссылается

2023-09-13 11:20 UTC, Vilinvil commented on index.html
> +    <meta charset="utf-8">
Что ты имеешь ввиду под форматированием в тестах? Там у меня диф, т.к. я заменил просто euclid функцию на window.euclidGlobal

2023-09-13 11:35 UTC, GreatFix commented on index.html
> +    import {euclid} from "./source/euclid.js";
Попробуй `<script src="tests/euclid.js" type="module"></script>`

2023-09-13 11:37 UTC, GreatFix commented on index.html
> +    <meta charset="utf-8">
а, ну да, когда заюзаешь импорт внутри тестов, просто вернешь название функции как было

2023-09-13 11:39 UTC, GreatFix commented on source/euclid.js
> +'use strict'
Для чего предназначена эта строка и как она сочетается с модулями?

2023-09-13 11:56 UTC, Vilinvil commented on index.html
> +    import {euclid} from "./source/euclid.js";
У меня так шиза разовьется. Я пробовал так до этого через некоторое количество ошибок дошел до того, что в index.html просто не отображались тесты euclid, я поэтому и подумал, что проблема в области видимости. А теперь вставил и работает, видимо еще где-то ошибка была

2023-09-13 13:19 UTC, GreatFix commented on .gitignore
> +.idea
Лишний diff

2023-09-13 13:19 UTC, GreatFix commented on source/euclid.js
> +    while (secondNumber !== 0) {
Нет, я имел в виду сделать  поместить условие до цикла. Значимой разницы в скорости и правда нет, это просто как практика. Чтобы в более сложных функциях помнит о таком

2023-09-13 15:32 UTC, Vilinvil commented on source/euclid.js
> +'use strict'
Строгий режим, делает некоторые ошибки исключениями, например запрещает использовать аргументы функции с одинаковыми названиями, запрещает некоторые использования языка приводящие к уязвимостям, улучшает применение некоторых оптимизаций... И да в модулях он включен автоматически

2023-09-13 15:35 UTC, Vilinvil commented
ты имеешь ввиду использовать проверки для крайних случаев, чтобы выходить из ф-ции без её выполнения до конца?

2023-09-13 15:35 UTC, Vilinvil commented on source/euclid.js
> +    while (secondNumber !== 0) {
ты имеешь ввиду использовать проверки для крайних случаев, чтобы выходить из ф-ции без её выполнения до конца?

2023-09-13 15:39 UTC, Vilinvil commented on .gitignore
> +.idea
Тут не совсем понимаю, это просьба больше конкретно к выкладыванию .gitignore в задачах учебных, где он особо не нужен? Просто в обычной разработке выкладывание .gitignore в репу скорее плюс, т.к. так другие люди использующие проект при сборке его, тестировании и т.д. не будут не нужные файлы залиавать в гит

2023-09-13 16:28 UTC, GreatFix commented on .gitignore
> +.idea
Конкретно в этом PR не нужно было лишние файлы изменять, в проекте уже можно и нужно заполнять gitignore

2023-09-13 16:29 UTC, GreatFix commented on source/euclid.js
> +};
Давай добавим пустую строку в конце файлов source/euclid.js и tests/euclid.js и на этом вроде все

2023-09-13 16:31 UTC, GreatFix commented on index.html
> +    import {euclid} from "./source/euclid.js";
ну еще не раз столкнешься с таким))

2023-09-13 16:32 UTC, GreatFix requested changes
.

2023-09-13 16:51 UTC, Vilinvil commented on source/euclid.js
> +};
![image](https://github.com/frontend-park-mail-ru/homework_2023_2/assets/98636591/d5ad20c9-e866-4897-bce8-001530512944)
Не знаю, почему её в гите нет, у меня отображается и изменений нет

2023-09-13 16:51 UTC, Vilinvil commented on source/euclid.js
> +};
И также в файле тестов

2023-09-13 16:57 UTC, GreatFix commented on source/euclid.js
> +};
через git status не видит?

2023-09-13 18:16 UTC, Vilinvil commented on source/euclid.js
> +};
нет

2023-09-13 19:07 UTC, GreatFix commented on source/euclid.js
> +};
Ну возможно формат файла какой-то другой, раз это устраивает твое idea, то и меня устроит )

2023-09-13 19:09 UTC, GreatFix commented on .gitignore
> +.idea
Осталось это

2023-09-13 19:19 UTC, Vilinvil commented on .gitignore
> +.idea
done

2023-09-13 19:21 UTC, GreatFix approved these changes
Хорош, вопросов не имею

2023-09-14 11:41 UTC, DPeshkoff requested changes
Привет! Поздравляю с переходом на второй семестр)

Классное решение получилось, но у меня есть пара замечаний. Если возникнут вопросы - можешь писать в [Telegram](t.me/DmPesh)

2023-09-14 11:41 UTC, DPeshkoff commented on index.html
> +
Здесь не нужна пустая строчка

2023-09-14 11:41 UTC, DPeshkoff commented on source/euclid.js
> +/**
Какие есть режимы работы в языке? Какой здесь? Распиши

2023-09-14 11:41 UTC, DPeshkoff commented on source/euclid.js
> +export const euclid = (...args) => {
Почему export?

2023-09-14 11:41 UTC, DPeshkoff commented on source/euclid.js
> + * @throws {Error|TypeError} throw TypeError if at least one of the passed arguments is not an integer and
На два блока throws

2023-09-14 11:41 UTC, DPeshkoff commented on source/euclid.js
> +    args.forEach((item, i) => {
every

2023-09-14 11:41 UTC, DPeshkoff commented on source/euclid.js
> +};
Можно без лишней переменной

2023-09-14 11:41 UTC, DPeshkoff commented on tests/euclid.js
> +import {euclid} from "../source/euclid.js";
А зачем?

2023-09-14 12:10 UTC, Vilinvil commented on source/euclid.js
> +/**
Обсуждали здесь
https://github.com/frontend-park-mail-ru/homework_2023_2/pull/32#discussion_r1324707028

2023-09-14 12:11 UTC, Vilinvil commented on source/euclid.js
> +export const euclid = (...args) => {
Я хочу использовать euclid функцию снаружи, а calcGCD сделать внутренней, чтобы её нельзя было использовать снаружи.

2023-09-14 12:19 UTC, Vilinvil commented on tests/euclid.js
> +import {euclid} from "../source/euclid.js";
Ответил тут https://github.com/frontend-park-mail-ru/homework_2023_2/pull/32#discussion_r1325854096

2023-09-14 12:48 UTC, Vilinvil commented on source/euclid.js
> +    args.forEach((item, i) => {
Если писать через every:
 if (!args.every(Number.isInteger)) {
        throw TypeError(`args consist non integer element`);
    }
    То мы теряем информацию о том, что за элемент является не числом, и какой у него индекс, что не очень удобно.

2023-09-14 12:51 UTC, Vilinvil commented on source/euclid.js
> +};
Можно, раньше разделил, т.к. внутри reduce было более сложное выражение, которое плохо иначе читалось

2023-09-14 22:54 UTC, DPeshkoff approved these changes

2023-09-14 22:54 UTC, DPeshkoff commented on source/euclid.js
> +    args.forEach((item, i) => {
убедительно

2023-09-14 22:54 UTC, closed without merging