Тарба Александр
frontend-park-mail-ru/homework_2023_2 pull request #33
Opened 2023-09-07 22:45 UTC by sachatarba

2023-09-08 07:13 UTC, johnSamilin commented
Привет, добро пожаловать на курс по фронтенд-разработке. Я буду проверять твое ДЗ 0.
Если у меня появятся комментарии к коду, то я опишу их здесь. Можешь отвечать на них тут же, а чтобы что-то уточнить - [телеграм](https://t.me/WatasheeBaka)

2023-09-08 07:23 UTC, johnSamilin requested changes

2023-09-08 07:23 UTC, johnSamilin commented on source/plain.js
> +const plain = function (array) {
Допиши пожалуйста JSDoc для этой функции

2023-09-08 07:23 UTC, johnSamilin commented on source/plain.js
> +    for (let elm of array) {
А можно ли тут воспользоваться методами массива для перебора элементов?

2023-09-08 07:23 UTC, johnSamilin commented on source/plain.js
> +};
В конец файла всегда стоит добавлять пустую строчку. Так, если кто-то будет менять этот файл, то изменений будет чуть меньше

2023-09-08 07:23 UTC, johnSamilin commented on source/plain.js
> +    let res = [];
А почему `res` объявлена как `let`?

2023-09-08 07:23 UTC, johnSamilin commented on source/plain.js
> +        return array;
возможно стоит как-то просигнализировать о том, что функция получила на вход аргументы неожиданного типа

2023-09-08 07:23 UTC, johnSamilin commented on source/plain.js
> +        if (elm instanceof Array) {
А есть ли еще какой-то способ проверить, является ли массив массивом?

2023-09-08 07:23 UTC, johnSamilin commented on source/plain.js
> +'use strict';
Хорошо, что ты знаешь об этой инструкции, а какие преимущества она тебе дает конкретно здесь?

2023-09-08 09:52 UTC, sachatarba commented on source/plain.js
> +        if (elm instanceof Array) {
Есть метод Array.isArray(elm)

2023-09-08 09:54 UTC, sachatarba commented on source/plain.js
> +        return array;
Это не проверка аргументов, а условие выхода из рекурсии, если элемент не является массивом, то просто возвращаю сам элемент, иначе надо обрабатывать элемент как массив.

2023-09-08 09:58 UTC, sachatarba commented on source/plain.js
> +'use strict';
Эта инструкция позволяет включить современный "строгий" режим и использовать современные возможности JS, например, он автоматически включается при использовании классов, конкретно в данной задаче его возможности, вроде, не используются, но он предостерегает он возможных ошибок

2023-09-08 10:15 UTC, sachatarba commented on source/plain.js
> +const plain = function (array) {
Дописал

2023-09-08 10:15 UTC, sachatarba commented on source/plain.js
> +    for (let elm of array) {
Исправил на const

2023-09-08 10:18 UTC, sachatarba commented on source/plain.js
> +    let res = [];
Поменял на const

2023-09-08 14:31 UTC, johnSamilin commented on source/plain.js
> +    let res = [];
а в чем разница? может все-таки правильней было let?

2023-09-08 21:09 UTC, sachatarba commented on source/plain.js
> +    let res = [];
let служит для объявления переменной, const для объявления констант, это значит, что объявив идентификатор через const мы не сможем присвоить ему новое значение, но при этом сможем изменять его содержимое в случае js. Так как в данном коде нет необходимости в присваивание res новых значений, целесообразно объявить данный идентификатор как const

2023-09-08 22:08 UTC, sachatarba commented on source/plain.js
> +    array.forEach((elm) => {
Переписал, используя reduce

2023-09-11 07:54 UTC, johnSamilin approved these changes

2023-09-13 14:57 UTC, DPeshkoff requested changes
Привет! Поздравляю с переходом на второй семестр)

Интересное решение получилось, но у меня есть пара замечаний. Если возникнут вопросы - можешь писать в [Telegram](t.me/DmPesh)

2023-09-13 14:57 UTC, DPeshkoff commented on source/plain.js
> +const plain = function (array) {
А какие есть способы задать функцию в языке? Чем они отличаются? Почему выбрал именно такой?

2023-09-13 14:57 UTC, DPeshkoff commented on source/plain.js
> +    if (!Array.isArray(array)) {
А где тогда проверка на некорректный ввод?)

2023-09-13 14:57 UTC, DPeshkoff commented on source/plain.js
> +    return res;
Можно сразу вернуть, без const

2023-09-13 14:57 UTC, DPeshkoff commented on tests/plain.js
> +	QUnit.test('Сохраняет порядок в вложенных массивах (другой порядок обхода)', function (assert) {
Нужны еще тесты на некорректный ввод)

2023-09-14 10:30 UTC, sachatarba commented on source/plain.js
> +const plain = function (array) {
Функции можно задать при помощи function declaration, function expression и стрелочной функции. Между этими способами есть некоторые отличия, но одно из основных, что при использовании function declaration функция может быть вызвана до ее объявления в пределах ее области видимости. Стрелочные функции используются часто для написания кода в функциональном стиле, например, даже внутри функции plain используется такая стрелочная функция в качестве аргумента callback-вызова reduce. Конкретно в данном примере большой разницы в выборе того или иного способа задания функции нет, поэтому я выбрал тот, что более привычен.

2023-09-14 10:34 UTC, sachatarba commented on source/plain.js
> +    return res;
Мне показалось, что return многострочного выражения, содержащего какую-то рекурсивную логику, будет не очень хорошо выглядеть, поэтому я решил хотя бы как-то это разделить.

2023-09-14 11:19 UTC, sachatarba commented on source/plain.js
> +    if (!Array.isArray(array)) {
добавлена проверка

2023-09-14 11:19 UTC, sachatarba commented on tests/plain.js
> +	QUnit.test('Сохраняет порядок в вложенных массивах (другой порядок обхода)', function (assert) {
добавил тесты

2023-09-14 11:42 UTC, DPeshkoff requested changes

2023-09-14 11:42 UTC, DPeshkoff commented on source/plain.js
> +const plain = function (array) {
Здесь нам не нужен this, здесь как раз лучше стрелочная функция

2023-09-14 11:42 UTC, DPeshkoff commented on source/plain.js
> +    const _plain = (array) => {
А зачем нам функция в функции? Можем без этого?

2023-09-14 12:39 UTC, sachatarba commented on source/plain.js
> +    const _plain = (array) => {
В какой-то момент разработки проверка на условие выхода из рекурсии была перенесена до вызова функции в принципе, и теперь уже можно было обойтись без этого. Но раньше мне надо было как-то определять является ли переданный аргумент не массивом, что означало, что необходимо выйти из рекурсии. И как отделять ситуацию условия выхода из рекурсии от ситуации неверно переданных аргументов, не используя функцию обертки и каких-то костылей, я не придумал.

2023-09-14 12:43 UTC, sachatarba commented on source/plain.js
> +const plain = function (array) {
Переделал на стрелочную функцию, но не совсем понял разницы. Стрелочная функция тоже имеет доступ к this, просто this, как я понял, будет определяться на основе функции, в которой вызывается стрелочная. Внутри функции мы его не используем, поэтому поведение в этом аспекте будет одинаковое

2023-09-14 12:45 UTC, sachatarba commented on source/plain.js
> +    const _plain = (array) => {
Сейчас уже можно было не проверять в принципе, поэтому я убрал внутреннюю функцию)

2023-09-14 22:57 UTC, DPeshkoff commented on source/plain.js
> +const plain = function (array) {
функция-стрелка не создает собственный контекст this, она использует внешний
здесь нам собственный и не нужен, поэтому стрелка предпочтительней

2023-09-14 22:58 UTC, DPeshkoff requested changes

2023-09-14 22:58 UTC, DPeshkoff commented on source/plain.js
> +        throw new TypeError("argument is not Array");
В JS приняты одиночные кавычки, давай поправим везде

2023-09-14 22:58 UTC, DPeshkoff commented on source/plain.js
> +    return res;
Можно без лишней константы - сразу вернуть в return

2023-09-14 23:27 UTC, sachatarba commented on source/plain.js
> +        throw new TypeError("argument is not Array");
исправил

2023-09-14 23:28 UTC, sachatarba commented on source/plain.js
> +    return res;
сделал без лишней константы

2023-09-15 19:28 UTC, DPeshkoff approved these changes

2023-09-15 19:28 UTC, closed without merging