Made sorting function
frontend-park-mail-ru/homework_2023_2 pull request #34
Opened 2023-09-07 23:23 UTC by Gallaann

All initial tests are performed

2023-09-08 17:28 UTC, F4lkr4m commented
Привет! Добро пожаловать на курс фронтенда! Я буду проверять твое ДЗ №0! Далее в комментариях оставлю свои вопросы по коду) По любым вопросам можешь меня пинговать [здесь](https://t.me/Falkr4m)

2023-09-08 18:03 UTC, F4lkr4m reviewed
Когда поправишь замечания можешь мне написать в телегу или тегнуть тут

2023-09-08 18:03 UTC, F4lkr4m commented on source/sorting.js
> +                if (compare !== 0) {
Здесь можно использовать просто `if (compare) { //... } ` - но знаю что выглядит не очень красиво. Вместо этого тебе предлагаю сразу после того как ты получил свойства(propertyA, propertyB) - осуществить проверку равны ли эти свойства - если равны, то можно будет сразу прыгнуть на следующую итерацию, а при обработке типов уже не нужны будут эти проверки

2023-09-08 18:03 UTC, F4lkr4m commented on tests/sorting.js
> +	QUnit.test('sorting не изменяет корректно отсортированный массив', function (assert) {
Молодец, что добавил тесты!

2023-09-09 20:46 UTC, Gallaann commented on source/sorting.js
> +'use strict';
Исходя из названия, можно предположить, что это более строгий режим, добавляющий ограничения и вводящий новые правила.

---
Данный режим преобразует mistakes (допустимые ошибки) в error (недопустимые ошибки), заставляя интерпретатор выбрасывать исключения. Таким образом, например, не получится использовать необъявленную переменную, следовательно, избавляет от ошибок из-за случайных глобальных переменных.
А еще оптимизирует код, запрещая использовать некоторые устаревшие конструкции.

2023-09-09 21:09 UTC, Gallaann commented on source/sorting.js
> +const sorting = function (objects, keys) {
Данная запись короче, чем обычная функция, но отличие не только в этом.

---
#### Не имеет собственного контекста выполнения (**_this_**):
> Если используется **_this_**, то значение берется снаружи.
> Это может быть родительский класс, родительская функция или глобальный контекста.
---
#### Отсутствие собственного контекста ведет к невозможности их вызова с **_new_**
---
#### Отсутствие собственного контекста ведет к отсутствию у них **arguments**

2023-09-09 21:25 UTC, Gallaann commented on source/sorting.js
> +        for (let key of keys) {
`let` - обычное объявление переменной

`const` - объявление константной переменной
> Значение данной переменной нельзя будет изменение по ходу программы 
###### _В данном случае используется для наглядности_

`var` - устаревший способ объявления переменных
- Не ограничен блоком видимости, соответсвенно может быть глобальной переменной
- Позволяет повторное объявление переменной
- Интерпретатором объявляется в начале скрипта/функции

2023-09-10 08:17 UTC, F4lkr4m commented on source/sorting.js
> +        for (let key of keys) {
Все отлично расписал, но вот почему объявляешь key, через let?

2023-09-10 08:17 UTC, F4lkr4m commented on source/sorting.js
> +    const sortedObjects = objects.slice();
.slice() - это нормальный способ скопировать, еще можно сделать это через конструкцию [...objects], а также через метод structuredClone. В первых двух случаях ссылки на объекты внутри массива останутся на оригиналы, во втором случае он создаст полностью новые объекты, но там есть нюансы по копированию. Это так, для общего развития.
Я бы наверное посоветовал написать через spreadOperator(...), так просто красивее, но и текущий - рабочий вариант

2023-09-10 08:17 UTC, F4lkr4m commented on source/sorting.js
> +                return 0;
Лучше тут поменять результат при ошибке, так как ожидается на выходе по описанию массив, но а тут прилетает 0. Лучше - выкидывать ошибку через throw, тогда можно будет ловить с помощью try catch снаружи

2023-09-10 08:17 UTC, F4lkr4m commented on source/sorting.js
> +                    return (propertyA - propertyB);
Тут скобочки не нужны

2023-09-10 08:17 UTC, F4lkr4m commented on source/sorting.js
> +            if (!sortedObjects.some(object => object.hasOwnProperty(key))) {
Тут стоит object перед стрелочкой взять в скобки

2023-09-10 14:53 UTC, Gallaann commented on source/sorting.js
> +        for (let key of keys) {
Есть несколько причин:
1. Переменная должна быть локальной.
2. Переменная должна быть переопределяемой.

Исходя из `1` нам не подходит `var`, поскольку переменная будет доступна и вне цикла `for`.
Изходя из `2` нам не подходит `const`.
___
Если вопрос касается повторного объявления, то этого не произойдет, посколько объявление в цикле происходит единожды, а затем новые значения только присваиваются на каждой итерации.

2023-09-10 19:37 UTC, F4lkr4m commented
lgtm

2023-09-10 23:27 UTC, DPeshkoff requested changes
Привет! Поздравляю с переходом на второй семестр)

Крутое решение получилось, но у меня есть пара замечаний. Если возникнут вопросы - можешь писать в [Telegram](t.me/DmPesh)

2023-09-10 23:27 UTC, DPeshkoff commented on index.html
> +<!--<script src="source/max.js"></script>-->
Давай вернем, как было - здесь не нужны изменения

2023-09-10 23:27 UTC, DPeshkoff commented on tests/sorting.js
> -
Здесь не нужны изменения с оригинальным кодом, давай вернем так, как было)

2023-09-10 23:27 UTC, DPeshkoff commented on source/sorting.js
> +                case 'string':
Ой! 

![изображение](https://github.com/frontend-park-mail-ru/homework_2023_2/assets/31134795/5afd937a-9f4c-4dbd-a0a1-8d4662f11341)

При этом это валидные строки... непорядок! Давай подумаем, как это починить)

2023-09-11 00:27 UTC, Gallaann commented on tests/sorting.js
> -
Это произошло, потому что я изменил собственный тест, который вставил посреди изначальных тестов, я ничего не убирал)
Это видно, если сравнить удаленные и добавленные строки. Честно, не понимаю почему так...

P.S. Изменил тест, потому что изначальная логика была в том, чтобы не трогать массив, если ключа нет, а сейчас он возвращает ошибку, вот ее и нужно уже было ловить этим тестом, а не сравнивать ожидаемый результат и реальный.

2023-09-11 19:47 UTC, DPeshkoff approved these changes

2023-09-11 19:47 UTC, closed without merging