Архаров Никита
frontend-park-mail-ru/homework_2023_2 pull request #35
Opened 2023-09-07 23:37 UTC by bqback

2023-09-08 07:25 UTC, johnSamilin commented
Привет, добро пожаловать на курс по фронтенд-разработке. Я буду проверять твое ДЗ 0.
Если у меня появятся комментарии к коду, то я опишу их здесь. Можешь отвечать на них тут же, а чтобы что-то уточнить - [телеграм](https://t.me/WatasheeBaka)

2023-09-08 07:32 UTC, johnSamilin requested changes

2023-09-08 07:32 UTC, johnSamilin commented on source/rle.js
> +    for (let i = 0; i < input.length; i++) {
Попробуй переписать этот цикл , используя такие методы как `split` и `reduce`. Возможно будет даже удобней

2023-09-08 07:32 UTC, johnSamilin commented on source/rle.js
> +};
В конце файла стоит добавлять пустую строчку, чтобы в будущем было чуть меньше изменений

2023-09-08 07:32 UTC, johnSamilin commented on source/rle.js
> +        if (input.charAt(i) == currChar)
Скажи пожалуйста, знаешь ли ты разницу между == и ===?

2023-09-08 09:46 UTC, bqback commented on source/rle.js
> +    let count = 0;
В современном синтаксе переменные объявляются так, пользы от редекларации и независимости от скоупа, которую даёт `var` я в этом примере не вижу.

2023-09-08 09:49 UTC, bqback commented on source/rle.js
> +        if (input.charAt(i) == currChar)
=== вроде как применяется для строгого сравнения, без конвертирования типов. Если я добавлю обработку массивов (https://github.com/frontend-park-mail-ru/homework_2023_2/pull/35#discussion_r1319479993), можно оставить `==`? Или лучше всё-таки использовать `===`?

2023-09-08 11:05 UTC, bqback commented on source/rle.js
> +const rle = (input) => {
Не уверен! Подозреваю, что для массива надо добавить `...` куда-то (в аргумент стрелочной функции?), и там уже для каждого элемента проверять, строка он или число, т. к. для чисел RLE (в представленном виде, без разделителей) вряд ли будет иметь смысл.

2023-09-08 14:40 UTC, johnSamilin commented on source/rle.js
> +const rle = (input) => {
Если добавишь код, который будет бросать исключение, если у нас пришли какие-то неподходящие аргументы, будет здорово

2023-09-08 20:43 UTC, bqback commented on source/rle.js
> +const rle = (input) => {
По итогу решил пропускать только строки на ввод, т. к. для списков хотелось бы придумать решение, сохраняющее произвольную вложенность (`['AAA', ['BBB', 'CCC']] -> ['A3', ['B3', 'C3']]`, например), но я не придумал (и не нашёл), как можно было бы лаконично это сделать. В новом коммите добавлена проверка типа с throw и assert с несколькими не строковыми типами.

2023-09-11 08:00 UTC, johnSamilin approved these changes

2023-09-13 15:06 UTC, DPeshkoff requested changes
Привет! Поздравляю с переходом на второй семестр)

Классное решение получилось, но у меня есть пара замечаний. Если возникнут вопросы - можешь писать в [Telegram](t.me/DmPesh)

2023-09-13 15:06 UTC, DPeshkoff commented on source/rle.js
> +'use strict';
Распиши, что делает эта строчка)

2023-09-13 15:06 UTC, DPeshkoff commented on source/rle.js
> + * @throws {TypeError}
А при каких условиях? Давай допишем

2023-09-13 15:06 UTC, DPeshkoff commented on source/rle.js
> +
Здесь не нужна строчка

2023-09-13 15:28 UTC, DPeshkoff commented on source/rle.js
> +'use strict';
up, жажду текстовое описание)

2023-09-13 15:29 UTC, bqback commented on source/rle.js
> +'use strict';
Здесь комментом или прям в коде?

2023-09-14 11:43 UTC, DPeshkoff commented on source/rle.js
> +'use strict';
Здесь

2023-09-14 12:03 UTC, bqback commented on source/rle.js
> +'use strict';
Ограничивает и делает менее неоднозначным поведение JS, переводя тихие ошибки в эксплицитные (либо в SyntaxError, либо в ошибки при исполнении), также позволяет писать более безопасный код, запрещая небезопасное поведение.

2023-09-14 22:59 UTC, DPeshkoff approved these changes

2023-09-14 23:00 UTC, closed without merging