Панькин Глеб
frontend-park-mail-ru/homework_2023_2 pull request #36
Opened 2023-09-08 01:15 UTC by MrDjeb

Сдаю на проверку ДЗ#0.

2023-09-10 14:01 UTC, LDK28 commented on index.html
Когда поправишь замечания или если возникнут вопросы или сложности, можешь тегнуть меня тут или написать в тг https://t.me/dkey28

Также для себя можешь резолвить замечания/вопросы, когда решишь их, чтобы не мешались :)

2023-09-11 12:06 UTC, MrDjeb commented on index.html
@LDK28  Прошу проверить изменения.

1. Изменил возвращаемое значение plain на TypeError, в случае передачи не массива.
2. Добавил тестов на эту ошибку.
3. Сделал описание теста более понятным.

2023-09-11 12:17 UTC, LDK28 approved these changes

2023-09-13 15:08 UTC, DPeshkoff requested changes
Привет! Поздравляю с переходом на второй семестр)

Интересное решение получилось, но у меня есть пара замечаний. Если возникнут вопросы - можешь писать в [Telegram](t.me/DmPesh)

2023-09-13 15:08 UTC, DPeshkoff commented on source/plain.js
> +'use strict';
Распиши, зачем нужна эта строчка)

2023-09-13 15:08 UTC, DPeshkoff commented on source/plain.js
> +        throw new TypeError("Input must be an array");
В JS используются одиночные кавычки, давай везде заюзаем)

2023-09-13 15:08 UTC, DPeshkoff commented on source/plain.js
> + * @throws Выдасть ошибку TypeError, если передан НЕ массив.
Нужно указать тип ошибки

2023-09-13 15:08 UTC, DPeshkoff commented on tests/plain.js
> +});
Нужна новая строка

2023-09-13 22:24 UTC, MrDjeb commented on source/plain.js
> +'use strict';
Эта строчка активирует строгий режим ко всему скрипту. Аналогично, можно включить строгий режим только для отдельных функции. Классы и модули автоматически включают его.

По самой сути эта директива влияет на синтаксис и поведение среды исполнения. Ключевой смысл - это ограничение свободы, что упрощает написание безопасного JavaScript. К примеру, среда не закрывает глаза на некритичные ошибки и выдаёт соответствующие исключения. Строгий режим запрещает некоторые старые конструкции языка (требует, чтобы имена аргументов в объявлении функций встречались только один раз; запрещает создание глобальных переменных и т.д.) И в следствие, он оптимизирует быстроту выполнения JS.

2023-09-13 22:35 UTC, MrDjeb commented
@DPeshkoff Прошу проверить изменения.

2023-09-14 11:44 UTC, DPeshkoff approved these changes

2023-09-14 11:44 UTC, closed without merging