Кирилл Лукьянов
frontend-park-mail-ru/homework_2023_2 pull request #37
Opened 2023-09-08 07:28 UTC by Antihoman

2023-09-11 10:14 UTC, GreatFix requested changes
Привет! Welcome to курс по фронтенд-разработке. Я буду проверять твое ДЗ 0.
У меня появились комментарии к коду, описал их здесь.
Можешь отвечать на них тут же, но если что, я доступен в [телеге](https://t.me/FixFive)

2023-09-11 10:14 UTC, GreatFix commented on source/roman.js
> +function roman(input) {
Может добавим проверку входных параметров этой и нижним функциям ?

2023-09-11 10:14 UTC, GreatFix commented on source/roman.js
> +        const romanns = [
Корректно ли название переменной?

2023-09-11 10:14 UTC, GreatFix commented on tests/roman.js
> +		assert.strictEqual(roman('mmxvii'), 2017);
Если попробуй обратно преобразовать, то тест не пройдет, как можем это исправить? 		`assert.strictEqual(roman(roman('mmxvii')), 'mmxvii');` (добавь кстати такой тест)

2023-09-11 10:14 UTC, GreatFix commented on source/roman.js
> +        for (const n of romanns) {
т.к. romanns это массив, давай попробуем использовать здесь его методы для итерации

2023-09-13 13:43 UTC, GreatFix requested changes
Некоторые комменты с первой проверки не были исправлены, добавил еще несколько

2023-09-13 13:43 UTC, GreatFix commented on source/roman.js
> +        return 'Неправильный формат ввода';
Давай выбросим здесь ошибку. Попробуй найти здесь подходящую https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error

2023-09-13 13:43 UTC, GreatFix commented on source/roman.js
> +    romanNumber = romanNumber.toLowerCase();
Давай не будем мутировать параметры функции, а объявим локальные. Это упрощает чтение кода, к тому же необходимый пункт, чтобы функция стала чистой  (если например мутируется объект)

2023-09-13 13:43 UTC, GreatFix commented on source/roman.js
> +    for (let i = 0; i < romanNumber.length; i++) {
Попробуй реализовать это через reduce (обрати внимание на 3 и 4 параметр принимаемой им функции)

2023-09-13 13:43 UTC, GreatFix commented on source/roman.js
> +    for (let i = 0; i < romanNumber.length; i++) {
И кстати romanNumber строка, а reduce метод массива, поэтому придется преобразовать к нему

2023-09-13 13:43 UTC, GreatFix commented on source/roman.js
> +    ROMAN_NUMERAL_VALUES.forEach(romanNumeral => {
И здесь попробуй reduce

2023-09-13 13:48 UTC, GreatFix commented on source/roman.js
> +    if (isNaN(convertedNumber) || convertedNumber <= 0) {
Точно ли необходима эта проверка? Разве выше уже не проверено? Но все же если romanToArabic может вернуть неправильное значение, разве не стоит внутри romanToArabic выбросить ошибку?

2023-09-15 12:38 UTC, GreatFix requested changes
Уже гораздо лучше, добавил пару комментов и еще пара прошлых осталось

2023-09-15 12:38 UTC, GreatFix commented on source/roman.js
> + * @throws {Error} - Вызывает ошибку, если входные данные неверного формата или отрицательные числа.
Тут написать TypeError, вместе Error

2023-09-15 12:38 UTC, GreatFix commented on source/roman.js
> +    romanNumber = romanNumber.toLowerCase();
Все еще мутируешь, сделай c`onst romanChars = romanNumber.toLowerCase();.split('');` и код сократишь и изменять параметры не будешь

2023-09-15 18:49 UTC, GreatFix requested changes

2023-09-15 18:49 UTC, GreatFix commented on tests/roman.js
> +		assert.throws(function () {
- Вынеси в отдельный блок с тестами
- Напиши тесты под ошибки чуть получше, можешь или в других по глянуть или в интернете найти
- давай другие типы данных, типа infinity, null, Nan

2023-09-15 18:49 UTC, GreatFix commented on tests/roman.js
> +		assert.strictEqual(roman(roman('mmxvii')), 'MMXVII');
Почему в функцию передается в нижнем регистре, а результат получается в верхнем ?

2023-09-15 18:49 UTC, GreatFix commented on tests/roman.js
> +	QUnit.test('roman правильно определяет, что было передано на вход', function (assert) {
Почему тесты с 52 по 56 строку нельзя поместить в блок, который в 20 строке находится ?

2023-09-15 20:32 UTC, GreatFix approved these changes
Гуд, у меня вопросов не осталось

2023-09-15 20:32 UTC, GreatFix commented on source/roman.js
> +        } else {
Кстати, в таких случаях можно else Не писать и просто вернуть значение, типо:
If(...) {
   return case1;
}

Return case2;

2023-09-16 20:25 UTC, DPeshkoff requested changes
Привет! Поздравляю с переходом на второй семестр)

Классное решение получилось, но у меня есть пара замечаний. Если возникнут вопросы - можешь писать в [Telegram](t.me/DmPesh)

2023-09-16 20:25 UTC, DPeshkoff commented on index.html
> -	<title>Домашнее задание: пример</title>
Кажется, нужно сменить target-ветку с [frontend-park-mail-ru:master](https://github.com/frontend-park-mail-ru/homework_2023_2/tree/master) на [frontend-park-mail-ru:variant-3](https://github.com/frontend-park-mail-ru/homework_2023_2/tree/variant-3)

2023-09-16 20:25 UTC, DPeshkoff commented on source/roman.js
> +const ROMAN_TO_ARABIC = {
А в каком режиме выполняется данный код? Какие вообще есть режимы исполнения кода в JS?

2023-09-16 20:25 UTC, DPeshkoff commented on source/roman.js
> +function roman(input) {
Распиши, какие есть способы задать функцию в языке и почему выбрал именно такой)

2023-09-16 20:25 UTC, DPeshkoff commented on source/roman.js
> +    if ((!isAR && !isRN) || input === '') {
Вместо проверки на пустую строку - можно на [falsy](https://developer.mozilla.org/ru/docs/Glossary/Falsy)

2023-09-16 20:54 UTC, Antihoman commented on source/roman.js
> +const ROMAN_TO_ARABIC = {
Данный код выполнен в стандартном режиме, то есть нестрогом, всего существует строгий и нестрогий режимы

2023-09-16 20:58 UTC, Antihoman commented on source/roman.js
> +function roman(input) {
Функции можно задать просто объявлением, но также с помощью переменной, стрелочной и с помощью конструкта, использовал первый способ в связи с его легко читаемостью и использовванием, но не могу не отметить, что использование стрелочной функции в моем случае сократоло бы код, так как в функциях используется всего одно выражение и это бы сократило пару строчек кода

2023-09-16 20:58 UTC, Antihoman commented on index.html
> -	<title>Домашнее задание: пример</title>
Готово

2023-09-16 20:58 UTC, Antihoman commented on source/roman.js
> +    if ((!isAR && !isRN) || input === '') {
Готово

2023-09-17 16:13 UTC, DPeshkoff requested changes

2023-09-17 16:13 UTC, DPeshkoff commented on source/roman.js
> +const ROMAN_TO_ARABIC = {
Давай поменяем на строгий. 

А еще распиши, в чем разница)

2023-09-17 16:13 UTC, DPeshkoff commented on source/roman.js
> +function roman(input) {
Стрелочные функции лучше, потому что что-то такое с this там есть. Распишешь, что?)

2023-09-17 16:13 UTC, DPeshkoff commented on tests/sorting.js
Давай подльем коммиты из оригинальной ветки, у тебя тут диффа быть не должно

2023-09-17 18:56 UTC, Antihoman commented on tests/sorting.js
Разница между строги и нестрогим режимом в более строгой обработке ошибок и поведении this, а именно this не будет видна в глобальной области и нельзя удалять ф-и с помощью delete

2023-09-17 21:34 UTC, DPeshkoff requested changes

2023-09-17 21:34 UTC, DPeshkoff commented on source/roman.js
> +"use strict";
Одиночные кавычки в JS)

2023-09-17 21:34 UTC, DPeshkoff commented on source/roman.js
> +function roman(input) {
up)

2023-09-17 21:51 UTC, Antihoman commented on source/roman.js
> +"use strict";
this внутри стрелочной функции ссылается на this из окружающего контекста ,то есть на this, который существует там, где стрелочная функция была создана. Это сделано для того, чтоб не испортить this, который существует в глобальной области видимости

2023-09-18 16:51 UTC, DPeshkoff commented on source/roman.js
> +"use strict";
здесь нам не нужен новый this, давай стрелочную)

2023-09-18 16:53 UTC, Antihoman commented on source/roman.js
> +"use strict";
Так я уже переделал на стрелочные)

2023-09-18 17:04 UTC, DPeshkoff approved these changes

2023-09-18 17:04 UTC, closed without merging