Евсюков Дмитрий
frontend-park-mail-ru/homework_2023_2 pull request #38
Opened 2023-09-08 10:00 UTC by Dmitry-Evsyukov

2023-09-08 16:29 UTC, Krasava872 commented
Привет! Добро пожаловать на курс по Front-end разработке)
Я один из менторов данного курса, начинаю проверять твое ДЗ-0. 
Ниже я оставлю комментарии по коду. Если будут вопросы пиши в [телегу](https://t.me/KrasavtsevSS).

2023-09-08 16:55 UTC, Krasava872 requested changes

2023-09-08 16:55 UTC, Krasava872 commented on .idea/.gitignore
В коммит явно попали лишние файлы.

2023-09-08 16:55 UTC, Krasava872 commented on source/get.js
> +'use strict';
Можем убрать эту строчку?

2023-09-08 16:55 UTC, Krasava872 commented on source/get.js
> +    if (properties.length == 0) {
Операция сравнения лишняя. Гуглим falsy типы.

2023-09-08 16:55 UTC, Krasava872 commented on source/get.js
> +function getImpl(object, properties) {
Почему используешь тут Function Declaration?

2023-09-08 16:55 UTC, Krasava872 commented on source/get.js
> +    if (object[properties[0]] != undefined) {
Зачем тут сравнение с приведением типов?

2023-09-08 16:55 UTC, Krasava872 commented on source/get.js
> +function getImpl(object, properties) {
Что будет если передать в аргументы undefined? Или совсем их не передавать?

2023-09-08 16:55 UTC, Krasava872 commented on source/get.js
> +        return getImpl(object[properties[0]], properties.slice(1))
Magic numbers плохая практика. Нужно исправить.

2023-09-08 16:55 UTC, Krasava872 commented on source/get.js
> +    if (query == '.') {
Аналогичный вопрос, почему тут такой оператор сравнения?

2023-09-08 16:55 UTC, Krasava872 commented on source/get.js
> +function get(object, query) {
Что будет если передать в аргументы undefined? Или совсем их не передавать?

2023-09-08 16:55 UTC, Krasava872 commented on source/get.js
> +    const properties = query.slice(1).split('.');
Всё те же Magic numbers)

2023-09-08 16:55 UTC, Krasava872 commented on source/get.js
Опиши для функций JsDoc

2023-09-09 15:51 UTC, Dmitry-Evsyukov commented on source/get.js
> +'use strict';
use strict используют, чтобы включить "строгие" настройки языка, чтобы сложнее было написать плохой код, рекомендуют включать всем новичкам. Не совсем понятно, риторический ли вопрос, но я знаю, что его можно включать в отдельной функции или если использовать классы и модули, то он включается по умолчанию. В данном случае, мне кажется, следует оставить

2023-09-09 15:55 UTC, Dmitry-Evsyukov commented on source/get.js
> +function getImpl(object, properties) {
Function Declaration мне кажется лушче читаемой, плюс неизвестно, откуда мы ее вызовем, FD позволяет вызывать функции до объявления

2023-09-09 15:58 UTC, Dmitry-Evsyukov commented on source/get.js
> +    if (object[properties[0]] != undefined) {
Исправил на строгое

2023-09-09 15:59 UTC, Dmitry-Evsyukov commented on source/get.js
> +function get(object, query) {
Ран-тайм ошибка, добавил проверку и тесты на этот кейс

2023-09-09 16:58 UTC, Krasava872 commented on source/get.js
> +function getImpl(object, properties) {
Ну, в данном случае известно где ты её будешь вызвать) Плюс расскажи в какой области видимости будет данная функция?

2023-09-09 17:18 UTC, Krasava872 requested changes

2023-09-09 17:18 UTC, Krasava872 commented on source/get.js
> +function get(object, query) {
Уже лучше, но что будет если передать в функцию false, или null?

2023-09-09 17:18 UTC, Krasava872 commented on .idea/.gitignore
Лишние файлы всё ещё остались)

2023-09-09 17:18 UTC, Krasava872 commented on source/get.js
> +    for (const index in properties) {
Зря переделал рекурсивный подход, теперь твоя функция будет перебирать и перечисляемые свойства из прототипов что не всегда нужно)

2023-09-09 18:09 UTC, Dmitry-Evsyukov commented on source/get.js
> +function getImpl(object, properties) {
В глобальной, если вопрос не содержит подвоха

2023-09-09 20:36 UTC, Krasava872 requested changes

2023-09-09 20:36 UTC, Krasava872 commented on source/get.js
> +        if (object && object.hasOwnProperty(property)) {
Отлично, но, если нам все же нужны свойства прототипов? Добавь возможность вызывать функцию в разных режимах, с чтением вглубь прототипов, и чтением собственных свойств.

2023-09-09 20:36 UTC, Krasava872 commented on tests/get.js
> +	QUnit.test('get работает правильно с перечисляемыми свойствами прототипов', function (assert) {
Ну и реализуй более наглядный пример объекта с собственными свойствами и его чтение, и пример с чтением по прототипам.

2023-09-09 20:58 UTC, Dmitry-Evsyukov commented on source/get.js
> +        if (object && object.hasOwnProperty(property)) {
Добавил возможность подать flag, который по умолчанию false, изменил соответствующий тест

2023-09-09 20:59 UTC, Dmitry-Evsyukov commented on source/get.js
> +    if (query == '.') {
Исправил на строгое, чтобы не мучаться с приведением типов

2023-09-09 21:36 UTC, Krasava872 requested changes

2023-09-09 21:36 UTC, Krasava872 commented on source/get.js
>  const DOT_SYMBOL = '.';
Действительно ли корректно объявлять данные константы здесь?

2023-09-09 21:36 UTC, Krasava872 commented on tests/get.js
>  			foo: {
Что то странное с отступами

2023-09-10 06:52 UTC, Dmitry-Evsyukov commented on source/get.js
>  const DOT_SYMBOL = '.';
Может быть, лучше будет, если объявить их внутри самой функции, чтобы они не попали в другие файлы

2023-09-10 07:08 UTC, Dmitry-Evsyukov commented on tests/get.js
>  			foo: {
Везде только табы без пробелов, аналогично,  как в примере tests/max.js

2023-09-10 07:18 UTC, Krasava872 approved these changes

2023-09-10 23:43 UTC, DPeshkoff requested changes
Привет! Поздравляю с переходом на второй семестр)

Крутое решение получилось, но у меня есть пара замечаний. Если возникнут вопросы - можешь писать в [Telegram](t.me/DmPesh)

2023-09-10 23:43 UTC, DPeshkoff commented on source/get.js
> +function get(object, query, flag = false) {
Распиши, пожалуйста, какие еще бывают виды функций в языке? Почему выбрал именно такую? В чем отличия?

2023-09-10 23:43 UTC, DPeshkoff commented on source/get.js
> +    if (!query || !object) {
А если query не строка, а object не объект? Предлагаю проверить)

2023-09-10 23:43 UTC, DPeshkoff commented on source/get.js
> +            return object[property]
Не забывай про точки с запятой! Несмотря на то, что парсер умеет автоматически их проставлять - иногда это приводит к странным результатам. 

<details><summary>Каким?</summary>
<p>
К примеру, тривиальный и понятный код:

![изображение](https://github.com/frontend-park-mail-ru/homework_2023_2/assets/31134795/3d22e9a8-baee-4bfb-886a-b4dfe665364a)

Внезапно падает:

![изображение](https://github.com/frontend-park-mail-ru/homework_2023_2/assets/31134795/582afa37-106b-4330-acaf-6a622c1cda61)

Почему так происходит, думаю, наглядно видно по тексту ошибки - он считает `[3]` частью `s`. Если при этом поставить ;, то код магически начинает работать)

![изображение](https://github.com/frontend-park-mail-ru/homework_2023_2/assets/31134795/9210ce09-d52b-40aa-9731-dd12424c685b)
</p>
</details> 

Давай везде проставим точки с запятой)

2023-09-10 23:43 UTC, DPeshkoff commented on source/get.js
> +        return undefined;
Я бы здесь выбрасывал ошибку, благо в JS это [удобно](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Error)

2023-09-11 15:42 UTC, Dmitry-Evsyukov commented on source/get.js
> +function get(object, query, flag = false) {
Выбрал Function Declaration, потому что у нее простой и читаемый синтаксис и её можно вызвать до объявления.
Еще есть Function Expression, ее в отличие от первой можно передать в качестве агрумента в другую функцию и сделать анонимной, если не присвоить имя.
И еще есть стрелочная функция, она более компактна, нет ключевого function в объявлении и имена, из-за этого ухудшается читаемость кода. Еще у нее нет контекста this, а значит, она не может выступать в роли конструктора объекта или его методов

2023-09-11 15:44 UTC, Dmitry-Evsyukov commented on source/get.js
> +        return undefined;
Теперь выбрасываю TypeError в случае неправильного аргумента или его отсутствия, добавил тесты

2023-09-11 19:48 UTC, DPeshkoff commented on source/get.js
> +function get(object, query, flag = false) {
Выглядит, как юзкейс для стрелочной функции - нам же не особо нужен свой this)

2023-09-12 11:43 UTC, DPeshkoff requested changes
up)

2023-09-12 14:56 UTC, Dmitry-Evsyukov commented on source/get.js
> +function get(object, query, flag = false) {
Поменял на стрелочную функцию

2023-09-13 10:25 UTC, DPeshkoff approved these changes

2023-09-13 10:26 UTC, closed without merging