Остромецкий Дмитрий
frontend-park-mail-ru/homework_2023_2 pull request #39
Opened 2023-09-08 10:02 UTC by wergit13

2023-09-09 10:36 UTC, ZhukDmitryOlegovich commented on source/filter.js
> +        throw new Error("expected Array");
1. Добавить проверку на то что text это текст
2. Добавить фигурные скобки после if - код стайл https://learn.javascript.ru/coding-style#rukovodstva-po-stilyu-koda

2023-09-09 10:36 UTC, ZhukDmitryOlegovich commented on source/filter.js
> +    var map = {
1. `map` не обновляется - можно вынести из тела функции
2. `var` использовать не корректно

Каверзный вопрос: почему использовать `var` не корректно? Что надо использовать? Почему? И что - есть другие какие-то виды объявления переменных?

2023-09-09 10:36 UTC, ZhukDmitryOlegovich commented on source/filter.js
> +    let resArr = Array();
1. Массивы принято создавать не так, а `let resArr = [];`
2. Эта переменная не обновляется - замени на const

2023-09-09 10:36 UTC, ZhukDmitryOlegovich commented on source/filter.js
> +        if(symbolPoses[i] == "<" && (i + 1 != symbolPoses.length ? (symbolPoses[i+1] == ">") : false)){
1. Используй `===` вместо `==`
2. В js можно не бояться выхода за границы массива в проверке на равенство - будет возвращен `undefined` который не будет равен `">"` - поэтому условие можно будет упростить

2023-09-09 10:36 UTC, ZhukDmitryOlegovich commented on source/filter.js
> +            let posibleTag = text.slice(symbolPoses[i].index + 1, symbolPoses[i+1].index);
Понимаю что ты хочешь взять текст между тегами - попробуй для этого сделать вначале не `text.matchAll(/[&"<>']/g)` а `text.split(/([&"<>'])/g)` и работать только с тем массивом что придет

2023-09-09 10:36 UTC, ZhukDmitryOlegovich commented on source/filter.js
> +}
Отсутствие пустой строки в конце файла =(

2023-09-09 11:57 UTC, wergit13 commented on source/filter.js
> +    var map = {
`var` это устаревшее объявление переменной, переменные объявленные через `var` не имеют блочной видимости и инициализируются в начале исполнения функции. В современном стандарте принято объявлять переменные через `let` и  `const`.

2023-09-09 12:27 UTC, wergit13 commented on source/filter.js
> +            let posibleTag = text.slice(symbolPoses[i].index + 1, symbolPoses[i+1].index);
Если заменять на `split` то все равно придется оставить `matchAll` чтобы запомнить символы. Также из-за `split` надо будет проверять такие случаи как символы рядом и символы в конце и в начале строки

2023-09-09 12:29 UTC, wergit13 commented on source/filter.js
> +        if(symbolPoses[i] == "<" && (i + 1 != symbolPoses.length ? (symbolPoses[i+1] == ">") : false)){
`symbolPoses[i]`  это не строка, а объект который также хранит индекс матча регекса, для использования `===` можно только кастовать к строке.

2023-09-09 12:33 UTC, ZhukDmitryOlegovich commented on source/filter.js
> +            let posibleTag = text.slice(symbolPoses[i].index + 1, symbolPoses[i+1].index);
Запоминать ничего не надо - это особенность split по регуляркам с групапами - на нечетных местах в массиве будет то что попало в группу - то есть спец символы, а на четных - обычные строк
```js
'<strong>Hello, <em>World!</em></strong> 1 + 2 < 4!'.split(/([&"<>'])/g)
// return: ['', '<', 'strong', '>', 'Hello, ', '<', 'em', '>', 'World!', '<', '/em', '>', '', '<', '/strong', '>', ' 1 + 2 ', '<', ' 4!']
```

2023-09-09 12:38 UTC, ZhukDmitryOlegovich commented on source/filter.js
> +        if(symbolPoses[i] == "<" && (i + 1 != symbolPoses.length ? (symbolPoses[i+1] == ">") : false)){
В таких случаях принято либо явно вызывать toString, либо достать значение из `symbolPoses[i][0]` потому что это просто массив с доп параметрами

2023-09-09 16:37 UTC, ZhukDmitryOlegovich reviewed
Итого за счет того что поменял на `split` код резко стал проще + внутри `for` можно оставить один `if` в котором проходят все проверки на то нужно ли пропустить экранирование тега

Сделай это и всё что написал в тредах - и с меня апрув =)

2023-09-09 16:37 UTC, ZhukDmitryOlegovich commented on source/filter.js
> +  };
Прогони линтер по файлу или руками пройдись - тут два пробела перед скобкой ненужной

\+ пробелы перед открывающей фигурной скобкой - пробел после for - и что-то мб пропустил - должен быть код стайл https://learn.javascript.ru/coding-style#rukovodstva-po-stilyu-koda

2023-09-09 16:37 UTC, ZhukDmitryOlegovich commented on source/filter.js
> +    if (!Array.isArray(tags)){
Добавь проверку что "все элементы в массиве - строки" в этом же `if` - через `every` или `some`

\+ тест на это

2023-09-09 16:37 UTC, ZhukDmitryOlegovich commented on source/filter.js
> +const filter = (text, tags = []) => {
Напиши jsdoc с описанием что это за функция (из условия задачи можно взять), какие типы у параметров и их описание

2023-09-09 16:37 UTC, ZhukDmitryOlegovich commented on source/filter.js
> +    let resArr = text.split(/([&"<>'])/g);
Поменяй на `const`

Каверзный вопрос: но почему? ниже же есть `resArr[i] = map[resArr[i]]` - в массиве что-то меняется, но он остается "константным" - как так?

2023-09-09 16:37 UTC, ZhukDmitryOlegovich commented on source/filter.js
> +        if(map[resArr[i]] !== undefined){
поменяй условие на обратное и делай `continue` (а после того как поменяешь на forEach - `return`) чтобы не делать дальше вложенный `if` и не увеличивать вложенность

2023-09-09 16:37 UTC, ZhukDmitryOlegovich commented on source/filter.js
> +                tags.includes(resArr[i+1].startsWith("/") ? resArr[i+1].slice(1) : resArr[i+1])
Хочу извращений в угоду меньшего объема кода =)
```suggestion
                tags.includes(resArr[i+1].slice(+resArr[i+1].startsWith("/")))
```

2023-09-09 16:37 UTC, ZhukDmitryOlegovich commented on source/filter.js
> +        if(map[resArr[i]] !== undefined){
А вообще - это проверка вовсе не нужна если сделать в цикле выше `i+=2` и начать с `i=1` - потому что каждый четный точно будет в `map`

2023-09-09 16:50 UTC, ZhukDmitryOlegovich commented on source/filter.js
> +  };
вот пример как должны стоять пробелы
```js
for (let i = 0; i < arr.length; i++) {
    if (a !== b && !Array.isArray(tags)) {
        // ...
    }
}
```

2023-09-09 21:01 UTC, wergit13 commented on source/filter.js
> +    let resArr = text.split(/([&"<>'])/g);
Из стандарта
> The property of a const object can be changed but it cannot be changed to a reference to the new object
Можем менять поля объекта, но саму переменную переприсвоить не можем

2023-09-10 06:39 UTC, ZhukDmitryOlegovich reviewed
Круто - код выглядит классно, мне нравиться

Точечные фиксы по мелочам чтобы я мог спать спокойно и с меня апрув (кажется я это уже писал - хммм... ох уж это дежавю)

upd: как будет готово и я буду сколько-то не отвечать - пиши @ZhukDO

2023-09-10 06:39 UTC, ZhukDmitryOlegovich commented on source/filter.js
> +  if (!(typeof text === "string")) {
```suggestion
  if (typeof text !== "string") {
```

2023-09-10 06:39 UTC, ZhukDmitryOlegovich commented on source/filter.js
> +  const resArr = text.split(/([&"<>'])/g);
```suggestion
  const resArr = text.split(/([&"<>'])/);
```
для `split` не влияет регулярка с `global` флаг или без него

2023-09-10 06:39 UTC, ZhukDmitryOlegovich commented on source/filter.js
> +    throw new Error("expected String");
```suggestion
    throw new TypeError("expected String");
```
https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/TypeError

2023-09-10 06:39 UTC, ZhukDmitryOlegovich commented on source/filter.js
> +    throw new Error("expected Array of strings");
```suggestion
    throw new TypeError("expected Array of strings");
```

2023-09-10 06:39 UTC, ZhukDmitryOlegovich commented on tests/filter.js
> +	});
Создай тест в котором показывается что вернет например
```js
const input = '<strong>Hello, <em>World!</em></strong> 1 + 2 < 4!';
const output = filter(input, ['em']);
```
то есть какие-то теги есть - каких-то нет

2023-09-10 06:43 UTC, ZhukDmitryOlegovich commented on source/filter.js
> +    let resArr = text.split(/([&"<>'])/g);
Всё так - можно ещё это прочитать https://t.me/makingweb/148

2023-09-10 06:44 UTC, ZhukDmitryOlegovich commented on source/filter.js
> +      resArr[i] == "<" && resArr[i + 2] == ">" &&
```suggestion
      resArr[i] === "<" && resArr[i + 2] === ">" &&
```
потому что теперь это точно строки и не будет заставлять того кто это будет читать задаваться вопросом "а почему не 3" -> "тут не в точности это строка"

2023-09-10 06:52 UTC, ZhukDmitryOlegovich commented on source/filter.js
> +      resArr[i] == "<" && resArr[i + 2] == ">" &&
По сути приемлемо писать `==` только при проверке сразу и на null и на undefined и даже когда был объект лучше/понятнее было бы достать конкретное значение из объекта - потому что там иначе происходила конвертация массива в строку, а это не имеет особо смысла

Но это просто - справочная информация =)

2023-09-10 07:10 UTC, ZhukDmitryOlegovich commented on source/filter.js
> + * @param {Array<string>} tags - список разрешенных тегов
```suggestion
 * @param {string[]} [tags=[]] - список разрешенных тегов
```
`Array` писать правильно - мне нравиться больше такая запись + указание дефолтного значения у `tags`

2023-09-10 20:07 UTC, ZhukDmitryOlegovich approved these changes

2023-09-10 23:36 UTC, DPeshkoff requested changes
Привет! Поздравляю с переходом на второй семестр)

Классное решение получилось, но у меня есть пара замечаний. Если возникнут вопросы - можешь писать в [Telegram](t.me/DmPesh)

2023-09-10 23:36 UTC, DPeshkoff commented on source/filter.js
> +"use strict";
1) Предлагаю использовать одиночные кавычки - так читаемее)

2) Распиши, пожалуйста, что это за строчка и зачем она нужна)

2023-09-10 23:36 UTC, DPeshkoff commented on source/filter.js
> +const map = {
map - не очень логичное название, давай назовем так, чтобы было понятно, что это за map такой

2023-09-10 23:36 UTC, DPeshkoff commented on source/filter.js
> + * @returns {string} отфильтрованный текст
В JSDoc надо включать и то, что функция выбрасывает

2023-09-10 23:36 UTC, DPeshkoff commented on source/filter.js
> +  if (typeof text !== "string") {
А если будет так?

![изображение](https://github.com/frontend-park-mail-ru/homework_2023_2/assets/31134795/5afd937a-9f4c-4dbd-a0a1-8d4662f11341)

При этом это валидные строки... непорядок! Давай подумаем, как это починить)

2023-09-12 18:52 UTC, wergit13 commented on source/filter.js
> +"use strict";
Строчка переводит исполнение кода в строгий режим, соответвующий новому стандарту языка и соответственно названию имеет строгие требования к коду, заставляет явно инициализовать переменные, выбрасывает ошибки на вызовы которые в старом стандарте бы прошли.

2023-09-13 10:26 UTC, DPeshkoff approved these changes

2023-09-13 10:27 UTC, closed without merging