Капитанов Даниил
frontend-park-mail-ru/homework_2023_2 pull request #4
Opened 2023-09-06 10:06 UTC by SmileyTheSmile

2023-09-06 14:40 UTC, tUnknownLegend commented
Привет, добро пожаловать на курс по фронтенд-разработке. Я буду проверять твое ДЗ 0. Ниже будут мои вопросы и комментарии по коду. Можно отвечать на них здесь или писать в [телеграм](https://t.me/tUnknownLegend)

2023-09-06 15:30 UTC, tUnknownLegend requested changes
Интересное решение, но требуется доработка. Не забудь написать тесты и оформить [JSDoc](https://learn.javascript.ru/comments). По любым вопросам ты всегда можешь обратиться мне в [телеграм](https://t.me/tUnknownLegend)

2023-09-06 15:30 UTC, tUnknownLegend commented on source/rle.js
> +const rle = function (s) {
постарайся называть переменные так, чтобы было понятно зачем они нужны. Однобуквенный нейминг, к сожалению, не позволяет это сделать. Это относится ко всему коду

2023-09-06 15:30 UTC, tUnknownLegend commented on source/rle.js
> +    for (var i = 0, a = 0, b = ''; i <= s.length; i++) {
По этой строке есть несколько комментариев:
- постарайся не использовать С-style for, а место этого воспользоваться встроенными функциями JS 
- почитай чем var [отличается](https://learn.javascript.ru/var) от let и const

2023-09-06 15:30 UTC, tUnknownLegend commented on source/rle.js
> +        if (s.charAt(i) == s.charAt(i + 1))
напиши, пожалуйста, почему решил применить метод `charAt`, а не обычные квадратные скобки `s[i]` или метод `at`?

2023-09-06 15:30 UTC, tUnknownLegend commented on source/rle.js
> +}
в конце файла принято оставлять пустую строку

2023-09-06 15:30 UTC, tUnknownLegend commented on source/rle.js
> +const rle = function (s) {
помимо этого, подумай, что будет, если в качестве `s` передадут не `string`, а какой-то другой тип данных

2023-09-08 10:27 UTC, SmileyTheSmile commented on source/rle.js
> +const rle = function (s) {
1) Стрелочные более удобны для простых однострочных выражений, но в принципе и то, и то эквивалентно. Я посчитал, что код по-понятнее если тут явно указать, что это функция.
2) "Strict mode makes it easier to write "secure" JavaScript.
Strict mode changes previously accepted "bad syntax" into real errors."
Короче делает синтаксис точнее.

2023-09-08 10:39 UTC, SmileyTheSmile commented on source/rle.js
> +        if (s.charAt(i) == s.charAt(i + 1))
== не проверяет одинаковость типов, а ======== проверяет.
Если я правильно понял, `if (s.charAt(i) == s.charAt(i + 1))` эквивалентно `if (s[i] === s[i])`, так что заменю на это.

2023-09-08 16:12 UTC, tUnknownLegend commented on source/rle.js
> +const rle = function (s) {
у стрелочных функций есть несколько принципиальных отличий от обычных, напиши их, пожалуйста

2023-09-08 16:17 UTC, SmileyTheSmile commented on source/rle.js
> +        if (s.charAt(i) == s.charAt(i + 1))
Ну, возвращение новой строки это тоже тут неуместно, так что не эквивалентно.

2023-09-08 16:25 UTC, SmileyTheSmile commented on source/rle.js
> +        if (s.charAt(i) == s.charAt(i + 1))
При обычных всегда нужны скобки, в стрелочных в одной строке можно без них, у стрелочных this зависит от контекста выполнения и нет объекта arguments.

2023-09-08 16:31 UTC, tUnknownLegend requested changes
нужно еще кое-что поправить

2023-09-08 16:31 UTC, tUnknownLegend commented on source/rle.js
> +}
проблема все еще не решена...

2023-09-08 16:31 UTC, tUnknownLegend commented on source/max.js
> +const maxLame = function (numbers) {
если нет - надо удалить все изменения

2023-09-08 16:31 UTC, tUnknownLegend commented on source/rle.js
> +    if (!(typeof stringToCompress === 'string')){
[лучше](https://stackoverflow.com/questions/4059147/check-if-a-variable-is-a-string-in-javascript) еще проверить instanceof

2023-09-08 16:31 UTC, tUnknownLegend commented on tests/rle.js
> +	QUnit.test('Цифры', function (assert) {
уже не цифры)

2023-09-08 16:31 UTC, tUnknownLegend commented on tests/rle.js
> +	QUnit.test('inf', function (assert) {
обман! этот тест проверят null

2023-09-08 16:31 UTC, tUnknownLegend commented on tests/rle.js
> +	QUnit.test('null', function (assert) {
а тут Infinity)

2023-09-08 16:31 UTC, tUnknownLegend commented on source/rle.js
> +    const replacementFunc = function(match, symbol1) {
почему здесь решил не использовать стрелочную функцию?

2023-09-08 16:31 UTC, tUnknownLegend commented on source/rle.js
> +function rle(stringToCompress) {
почему здесь решил не использовать стрелочную функцию?

2023-09-08 16:31 UTC, tUnknownLegend commented on tests/rle.js
> +	QUnit.test('Много групп', function (assert) {
проверяет ли разные вещи этот тест и 'Несколько групп'? Мне думаю, что одно и тоже

2023-09-08 16:42 UTC, SmileyTheSmile commented on source/rle.js
> +    const replacementFunc = function(match, symbol1) {
Думал код будет поприятнее, но в принципе да, так лучше

2023-09-08 16:42 UTC, SmileyTheSmile commented on source/rle.js
> +}
клянусь богом она там была, это все они

2023-09-08 16:43 UTC, SmileyTheSmile commented on source/rle.js
> +function rle(stringToCompress) {
Здесь точно по-красивее обычной функцией

2023-09-08 16:47 UTC, SmileyTheSmile commented on source/rle.js
> +    if (!(typeof stringToCompress === 'string')){
Если сверять со String , то входные строки игнорятся, потому что они типа string
    Если сверять со string, string не существует.
    instanceof будет работать только если каждуюю входную строку создавать через new String()
    if (!(stringToCompress instanceof String)){
        return null
    }

2023-09-09 13:22 UTC, tUnknownLegend commented on source/rle.js
> +    if (!(typeof stringToCompress === 'string')){
смотри, `new String()` возвращает валидный string, но сейчас у тебя он будет считаться не валидным. Можно говорить о том, что не надо использовать `new String()`, но это уже другая история. Так что условия лучше добавить

2023-09-09 13:31 UTC, tUnknownLegend commented on source/rle.js
> +function rle(stringToCompress) {
мы все же из других соображений исходим когда код пишем)

вот [тут](https://github.com/frontend-park-mail-ru/homework_2023_2/pull/4#discussion_r1320064245) просил все же написать конкретные отличия, все еще жду ответа)

Конкретно тут да, разницы особой нет, но хотелось бы убедиться, что ты понимаешь чем они отличаются кроме синтаксиса

2023-09-09 13:35 UTC, tUnknownLegend requested changes
в целом все ок, осталось решить вопросы с string, стрелочной функцией и файлом max.js. Перечитай старые комменты, пожалуйста

2023-09-09 13:53 UTC, tUnknownLegend commented on source/rle.js
> +    if (!(typeof stringToCompress === 'string')){
давай еще добавим тест с new String(), чтобы не было сомнений

2023-09-10 14:26 UTC, SmileyTheSmile commented on source/rle.js
> +const rle = function (s) {
Я наверное забыл отправить комментарий, уже писал это.
Стрелочные функции можно писать без скобок, если выражение в одной строке, в стрелочных this зависит от контекста, стрелочные нельзя использовать в качестве конструктора типа new Func() и в обычных можно обратиться к объекту arguments, в отличие от стрелочных.

2023-09-10 14:28 UTC, SmileyTheSmile commented on source/rle.js
> +function rle(stringToCompress) {
Написал разницу выше, этот комментарий был написан после того как я комментарий про разницу писал, не знаю почему тот не отправился.

2023-09-10 14:28 UTC, SmileyTheSmile commented on source/max.js
> +const maxLame = function (numbers) {
Вернул к исходному виду.

2023-09-10 14:32 UTC, SmileyTheSmile commented on source/rle.js
> +    if (!(typeof stringToCompress === 'string')){
Использовал и то и то.

2023-09-10 15:16 UTC, tUnknownLegend requested changes
изменения в max.js убрать пока не удалось) Чтобы проверить есть ли изменения можно зайти во вкладку Files changed и там не должно быть этого файла совсем
![image](https://github.com/frontend-park-mail-ru/homework_2023_2/assets/57019979/16566f0e-cc63-4ad9-a097-25d8577f379d)

2023-09-10 15:16 UTC, tUnknownLegend commented on tests/rle.js
> +		assert.strictEqual(rle(new String("ADDD")), "AD3");
давай еще добавим тесты с двумя пустыми строками:
 - обычной `''`
 - new String()

2023-09-10 18:53 UTC, tUnknownLegend approved these changes
Аппрув, но верни, пожалуйста, max.js. Просто зайди в [исходный код](https://github.com/frontend-park-mail-ru/homework_2023_2/tree/variant-11) и скопируй оттуда код, ничего больше делать не надо)

2023-09-10 19:45 UTC, tUnknownLegend approved these changes
огонь, ставлю аппрув. Жди ревью от старшего ментора)

2023-09-10 20:17 UTC, DPeshkoff requested changes
Привет! Поздравляю с переходом на второй семестр)

Классное решение получилось, но у меня есть пара замечаний. Если возникнут вопросы - можешь писать в [Telegram](t.me/DmPesh)

2023-09-10 20:17 UTC, DPeshkoff commented on source/rle.js
> +        return null
Как будто бы лучше здесь выбрасывать ошибку, а не возвращать `null`, как думаешь?

2023-09-10 20:17 UTC, DPeshkoff commented on source/rle.js
> +    const regex = new RegExp(/(.)\1+/, 'g')
Не забывай про точки с запятой! Несмотря на то, что парсер умеет автоматически их проставлять - иногда это приводит к странным результатам. К примеру, тривиальный и понятный код:

![изображение](https://github.com/frontend-park-mail-ru/homework_2023_2/assets/31134795/3d22e9a8-baee-4bfb-886a-b4dfe665364a)

Внезапно падает:

![изображение](https://github.com/frontend-park-mail-ru/homework_2023_2/assets/31134795/582afa37-106b-4330-acaf-6a622c1cda61)

Почему так происходит, думаю, наглядно видно по тексту ошибки - он считает `[3]` частью `s`. Если при этом поставить ;, то код магически начинает работать)

![изображение](https://github.com/frontend-park-mail-ru/homework_2023_2/assets/31134795/9210ce09-d52b-40aa-9731-dd12424c685b)

Давай везде проставим точки с запятой)

2023-09-10 22:49 UTC, DPeshkoff requested changes

2023-09-10 22:49 UTC, DPeshkoff commented on source/rle.js
> +        throw new TypeError("Введенный тип не является строкой.");
Одиночные кавычки и лучше без точки)

2023-09-11 07:40 UTC, closed without merging