Variant 6
frontend-park-mail-ru/homework_2023_2 pull request #40
Opened 2023-09-08 11:20 UTC by AlexnadrLarin

2023-09-10 10:12 UTC, ivanstrilets commented
Привет!
Добро пожаловать на курс по фронтенд-разработке 👋
Я буду проверять твое ДЗ-0. Ниже я буду оставлять комментарии по коду. Желательно на них отвечать

Давай для начала исправим наш PR, устрани проблему с конфликтами, ты указал неверно ветку

2023-09-13 16:39 UTC, AlexnadrLarin commented
Здравствуйте, изменил ветку.

2023-09-14 17:44 UTC, ivanstrilets commented on source/tree.js
> +    } else {
при подобном логическом ветвлении можно не использовать else

2023-09-14 17:44 UTC, ivanstrilets commented on source/tree.js
> +const tree = function (N) {
давай аргументы функции писать не буквами а описывающими аргумент словами или словом если это локанично, так же добавь, пожалуйста, JSDoc

2023-09-14 17:44 UTC, ivanstrilets commented on source/tree.js
> +    const max_width = 2 * num - 3;
в js чаще встретишь требование использовать camelCase, давай сразу привыкать к good practices

2023-09-14 17:44 UTC, ivanstrilets commented on source/tree.js
> +      sum += " ".repeat((max_width - 1) / 2) + "|" +
можно использовать интерполяционную строку, с ней будет читабельней код, так же относится к работе со строками в цикле

2023-09-14 17:44 UTC, ivanstrilets commented on tests/tree.js
> +	QUnit.test('Ёлочка высотой 6', function (assert) {
давай добавим тесты на ошибочный ввод

2023-09-15 15:16 UTC, AlexnadrLarin commented
Спасибо за замечания, исправил.

2023-09-15 18:55 UTC, ivanstrilets commented on source/tree.js
> + * @returns {string} - Строка с ёлочкой
у нас функция может возвращать не только string, давай отразим это в @returns

2023-09-15 20:14 UTC, AlexnadrLarin commented on source/tree.js
> + * @returns {string} - Строка с ёлочкой
Исправил

2023-09-17 09:05 UTC, ivanstrilets commented on source/tree.js
> + * @returns {string} - Строка с ёлочкой
опиши более точно @returns со string согласен, c object не согласен

2023-09-17 11:18 UTC, AlexnadrLarin commented on source/tree.js
> + * @returns {string} - Строка с ёлочкой
Хорошо, исправил

2023-09-18 08:42 UTC, ivanstrilets approved these changes

2023-09-18 16:22 UTC, DPeshkoff commented on index.html
> +	<script src="tests/tree.js"></script>
Здесь не нужны изменения, давай вернем, как было

2023-09-18 16:22 UTC, DPeshkoff commented on source/tree.js
> +/**
Какие режимы исполнения кода есть в JS? Распиши, почему выбрал именно такой и чем они отличаются

2023-09-18 16:23 UTC, DPeshkoff commented on source/tree.js
> +    const heightNum = Number(height);
А если будет NaN? Нужны проверки и тесты на проверки

2023-09-18 16:23 UTC, DPeshkoff commented on source/tree.js
> +const tree = function (height) {
Какие есть способы задать функцию? Распиши, чем они отличаются и почему выбрал такой

2023-09-18 16:23 UTC, DPeshkoff commented on source/tree.js
> + * @returns {string, null} - Строка с ёлочкой
как будто через запятую и то, и то - лучше |

2023-09-18 16:24 UTC, DPeshkoff commented on tests/tree.js
> +		assert.strictEqual(tree('fadsfsdf'), expected);
Нет, expected - ошибка, а не null

2023-09-23 03:58 UTC, AlexnadrLarin commented on source/tree.js
> +/**
Есть строгий и обычный режим. Строгий режим вносит изменения в семантику JS, то есть не пропускает ошибки и выдает соответствующие исключения. Не обратил внимания на выбор режима.

2023-09-23 12:53 UTC, AlexnadrLarin commented on source/tree.js
> +const tree = function (height) {
- Объявление функции: функции, объявленные через ключевое слово function, создаются до выполнения программы, поэтому их можно вызвать до их фактического места в коде. 
- Функциональное выражение: функции, объявленные как переменная, создаются только тогда, когда встречается строка кода, где они определены. Поэтому вызвать переменную-функцию до ее объявления будет невозможно.
- Стрелочные функции: это сокращенный синтаксис для объявления функций. Они имеют некоторые отличия, к примеру автоматическое связывание контекста this и более компактный синтаксис.

2023-09-23 12:55 UTC, AlexnadrLarin commented on source/tree.js
> +const tree = function (height) {
Выбрал 2 способ, так как больше всего работал с ним.

2023-09-23 13:00 UTC, AlexnadrLarin commented on tests/tree.js
> +		assert.strictEqual(tree('fadsfsdf'), expected);
Мне нужно искусственно обозначить ошибку? Ведь программа в этом случае выводит null.

2023-09-23 13:00 UTC, AlexnadrLarin commented on source/tree.js
> +    const heightNum = Number(height);
Программа выведет null.

2023-09-23 13:32 UTC, AlexnadrLarin commented on source/tree.js
> + * @returns {string, null} - Строка с ёлочкой
Хорошо, исправил.

2023-09-23 13:32 UTC, AlexnadrLarin commented on index.html
> +	<script src="tests/tree.js"></script>
Исправил.

2023-09-23 13:43 UTC, AlexnadrLarin commented on source/tree.js
> +    const heightNum = Number(height);
Добавил тест на это.

2023-09-23 18:40 UTC, DPeshkoff requested changes

2023-09-23 18:40 UTC, DPeshkoff commented on source/tree.js
> +const tree = function (height) {
Такой аргумент - не очень, лучше выбирать то, что нужно под конкретную задачу. 

Здесь лучше стрелочные, потому что нам не нужен свой контекст this

2023-09-23 18:40 UTC, DPeshkoff commented on tests/tree.js
> +		assert.strictEqual(tree('fadsfsdf'), expected);
В идеале она должна выбрасывать Error, потому что программист ошибся и передал неверный аргумент

2023-09-24 09:24 UTC, AlexnadrLarin commented
Спасибо за замечания, исправил!

2023-09-24 22:04 UTC, DPeshkoff approved these changes

2023-09-24 22:04 UTC, closed without merging