Данильченко Александр
frontend-park-mail-ru/homework_2023_2 pull request #41
Opened 2023-09-08 11:59 UTC by kingjoram

вариант 2

2023-09-09 11:08 UTC, ZhukDmitryOlegovich commented on source/euclid.js
> +	for (let i = 1; i < numbers.length; i++ ) {
Используй в решение `reduce`

2023-09-09 11:08 UTC, ZhukDmitryOlegovich commented on source/euclid.js
> +		return 'Uncorrect';
Строка мне точно не нравиться как факт ошибки - подумай что по математике тут подходит

2023-09-09 11:08 UTC, ZhukDmitryOlegovich commented on source/euclid.js
> +			return 'Uncorrect';
Давай поддержим такой ответ для нулей https://en.wikipedia.org/wiki/Greatest_common_divisor#:~:text=gcd(a%2C%200)%20%3D%20gcd(0%2C%20a)%20%3D%20%7Ca%7C
ps: а вот кейс что все нули - обработай как удобнее

2023-09-09 11:10 UTC, ZhukDmitryOlegovich commented on source/euclid.js
> +const NOD = function(x, y) {
И использование function для безымянной функции считается устаревших в том плане что есть стрелочные функции

https://learn.javascript.ru/arrow-functions-basics

2023-09-10 17:31 UTC, kingjoram commented on source/euclid.js
> +const NOD = function(x, y) {
исправлено

2023-09-10 17:31 UTC, kingjoram commented on source/euclid.js
> +	for (let i = 1; i < numbers.length; i++ ) {
исправлено

2023-09-10 18:20 UTC, ZhukDmitryOlegovich commented on source/euclid.js
> +const gcd = (x, y) => {
Сделай реализацию в одну строчку

2023-09-10 18:20 UTC, ZhukDmitryOlegovich commented on source/euclid.js
> +const euclid = function(...numbers) {
Используй стрелочную функцию вместо function https://learn.javascript.ru/arrow-functions-basics

2023-09-10 18:20 UTC, ZhukDmitryOlegovich commented on source/euclid.js
> +	let result = numbers.reduce((first, second) => {
Какие ещё есть способы создать переменную кроме let? Какой тут использовать правильнее?

2023-09-10 18:20 UTC, ZhukDmitryOlegovich commented on source/euclid.js
> +		return gcd(Math.abs(first), Math.abs(second));
Расскажи почему first всегда будет положительным числом + убери abs + переименую first и second во что-то информативнее что обычно используют в reduce

2023-09-10 18:20 UTC, ZhukDmitryOlegovich commented on source/euclid.js
> +	if(numbers.length < 2) {
Этот if погоды не делает - а вот например проверка что все входные значения конечные числа - нужна из-за ДЗ0

2023-09-10 18:35 UTC, kingjoram commented on source/euclid.js
> +	let result = numbers.reduce((first, second) => {
можно еще использовать var, const. var, в целом, то же самое, но это устаревший способ.

2023-09-10 19:25 UTC, kingjoram commented on source/euclid.js
> +const gcd = (x, y) => {
всю функцию? там же еще и while...

2023-09-10 20:02 UTC, ZhukDmitryOlegovich commented on source/euclid.js
> +	let result = numbers.reduce((first, second) => {
> var, в целом, то же самое

поясни в чел "целостьность" =) Он плох не потому что абстрактные люди сказали что его придумали позже, а в другом - приведи пример почему var хуже для использования в коде чем let в плане читаемости и понимания кода

> Какой тут использовать правильнее?

И на это ответ хочу

2023-09-10 20:11 UTC, kingjoram commented on source/euclid.js
> +	let result = numbers.reduce((first, second) => {
var допускает повторные объявления, эти переменные вне блоков. это может помешать читаемости кода, а иногда и его логики работы(не ожидаешь, что переменную можно вызвать вне своего блока), поэтому лучше использовать let.
в данном примере можно использовать и const, потому что мы 1 раз присваиваем значение при определении

2023-09-10 20:13 UTC, kingjoram commented on source/euclid.js
> +		return gcd(Math.abs(first), Math.abs(second));
first(сейчас уже previousValue) будет всегда >0 из-за логики работы gcd, она всегда возвращает неотрицательное значение. вот second может быть отрицательным, потому что в него мы записываем значения из массива

2023-09-10 20:41 UTC, kingjoram commented on source/euclid.js
> +const gcd = (x, y) => {
так у меня там while и return, а без фигурных скобок только 1 строку можно.

2023-09-10 21:39 UTC, kingjoram commented on source/euclid.js
> +	if(numbers.length < 2) {
number.IsFinite у меня всегда возвращает false. неважно, что передавал

2023-09-10 21:47 UTC, ZhukDmitryOlegovich commented on source/euclid.js
> +const gcd = (x, y) => {
> Существует реализация gcd в один тернарный оператор и рекурсивный вызов - его я и хочу увидеть

2023-09-10 21:48 UTC, ZhukDmitryOlegovich commented
Так как сейчас час ночи - то я расскажу что сильно посмеялся с названия последних двух коммитов =)

2023-09-10 21:52 UTC, kingjoram commented
я в тильте. 
есть, оказывается  названиеПеременной.isFinite и Number.Finite(value). первое не работало, а я не понимал в чем проблема.

2023-09-10 21:55 UTC, kingjoram commented
а нужно ли делать в euclid не через const result ... return result, а сразу через return? просто второе выглядит некрасиво

2023-09-10 21:59 UTC, ZhukDmitryOlegovich commented on source/euclid.js
> +	if (numbers.some((number) => !Number.isFinite(number) ? true : false)) {
```suggestion
	if (numbers.some((number) => !Number.isFinite(number))) {
```
бесполезное `... ? true : false` - расскажи почему

2023-09-10 21:59 UTC, ZhukDmitryOlegovich commented on source/euclid.js
> +		return "Infinity number";
```suggestion
		throw new TypeError("Not finite numbers");
```
плохой тон - лучше ошибку выбрасывать или null на крайняк

2023-09-10 21:59 UTC, ZhukDmitryOlegovich commented on source/euclid.js
> +	return result;
- [ ] `index` можно не указывать
- [ ] можно убрать `return` и фигурные скобки и сразу возвращать значение
- [ ] можно заменить `const result = ...; return result;` на `return ...;`
а можно - значит нужно - ведь упростится код

2023-09-10 21:59 UTC, ZhukDmitryOlegovich commented on source/euclid.js
> +const gcd = (x, y) => {
https://www.google.com/search?q=gcd+one+line

2023-09-10 21:59 UTC, ZhukDmitryOlegovich commented on source/euclid.js
> +	if (numbers.some((number) => !Number.isFinite(number) ? true : false)) {
а ещё я тут подумал - могут же быть ещё дробные числа - поменяй на `Number.isInteger()` + тест поправь на проверку этого + не забудь о `NaN`

2023-09-10 22:01 UTC, ZhukDmitryOlegovich commented on source/euclid.js
> +	return result;
https://github.com/frontend-park-mail-ru/homework_2023_2/pull/41#issuecomment-1712950237

не мона, а нуна =) - круто что сам заметил

Если будут какие-то вопросы/непонятки/сложности - пиши спрашивай, я тут чтобы помочь разобраться - в тильт не падай

2023-09-10 22:02 UTC, kingjoram commented on source/euclid.js
> +	if (numbers.some((number) => !Number.isFinite(number) ? true : false)) {
первая половина. у нас же isFinite итак возвращает bool, который мы потом инвертируем

2023-09-10 22:04 UTC, ZhukDmitryOlegovich commented on source/euclid.js
> +const gcd = (x, y) => y == 0 ? x : gcd(y, 	x % y)
всё верно, но проверка на 0 не нужна - он сам будет `false` - а всё остальное `true` + форматирование - убрать затесавшийся таб
```suggestion
const gcd = (x, y) => y ? gcd(y, x % y) : x;
```

2023-09-10 22:08 UTC, kingjoram commented on source/euclid.js
> +	if (numbers.some((number) => !Number.isFinite(number) ? true : false)) {
я же правильно понял, что встроенного isInteger() нет? на learn javascript нет.

а NaN уже включен в проверку isFinite

2023-09-10 22:11 UTC, ZhukDmitryOlegovich commented on source/euclid.js
> +	if (numbers.some((number) => !Number.isFinite(number) ? true : false)) {
learnjs это всё таки больше про научить, а для найти есть mdn https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isInteger

2023-09-10 22:11 UTC, kingjoram commented on source/euclid.js
> +	return result;
у них просто 2 одинаковых названия. один на метод переменной, другой на статический метод класса

2023-09-10 22:23 UTC, ZhukDmitryOlegovich commented on source/euclid.js
> +	return result;
у кого два одинаковых названия? какие названия? мысль потерял

2023-09-10 22:27 UTC, kingjoram commented on source/euclid.js
> +	return result;
лучше не продолжать, а то у меня уже жижа в голове, я запутался. кода как-то очень мало стало, я в шоке вообще сижу

2023-09-10 22:28 UTC, ZhukDmitryOlegovich reviewed
Давай - хочу апрув поставить =)

2023-09-10 22:28 UTC, ZhukDmitryOlegovich commented on source/euclid.js
> +	return numbers.reduce((previousValue, current) => gcd(previousValue, Math.abs(current)), 0);
А - я понял кажется что тебе не нравилось - такая длинная неудобная конструкция

Но сейчас будет фокус

```suggestion
	return numbers.map(Math.abs).reduce(gcd, 0);
```

https://youtu.be/mZIE-K0z1ZM?si=oUYdREnAbl6yLGFT =)

2023-09-10 22:28 UTC, ZhukDmitryOlegovich commented on source/euclid.js
> +const euclid = (...numbers) => {
Добавить jsdoc

2023-09-10 22:38 UTC, kingjoram commented on source/euclid.js
> +	return numbers.reduce((previousValue, current) => gcd(previousValue, Math.abs(current)), 0);
так, с помощью map мы создаем новый массив, где на каждый элемент применили Math.abs (т.е. преобразовали изначальный массив по модулю). и на этот новый полученный массив накинули reduce. 
но вот я не понял, из-за чего пропали аргументы, которые передаются в gcd.
он же не просто на автомате закидывает первые 2 аргумента в нашу функцию?

2023-09-10 22:42 UTC, ZhukDmitryOlegovich commented on source/euclid.js
> +	return numbers.reduce((previousValue, current) => gcd(previousValue, Math.abs(current)), 0);
> он же не просто на автомате закидывает первые 2 аргумента в нашу функцию?

=)

просто) в том же самом порядке - это же та же самая функция что ты создавал до этого - первый проп - акумилирующееся значение, второй - очередной элемент массива, третий - индекс массива и четвертый - сам массив

gcd - это функция - у неё первый параметр это x, второй y - остальные ей не интересны

ты например можешь вызвать по этому 
```js
gcd(6, 8, 'biba', {boba: 1})
```
и тебе вернет 2

2023-09-10 22:49 UTC, kingjoram commented on source/euclid.js
> +const euclid = (...numbers) => {
описание же не на английском надо было писать?

2023-09-10 22:51 UTC, ZhukDmitryOlegovich commented on source/euclid.js
> +const euclid = (...numbers) => {
меня jsdoc на английском бесит, но и так и так приму - лучше конечно на русском - ты же для меня/себя/других его пишешь, а мы не англосаксы ))))))

2023-09-10 22:51 UTC, kingjoram commented on source/euclid.js
> +	return numbers.reduce((previousValue, current) => gcd(previousValue, Math.abs(current)), 0);
да, я проверил. в старом виде(без map) убрал обозначения аргументов. работало правильно для всего, кроме отрицательных чисел, как и ожидалось

2023-09-10 22:54 UTC, ZhukDmitryOlegovich commented on source/euclid.js
> + * @param {numbers} numbers - любое количество чисел
```suggestion
 * @param {...number} numbers - любое количество чисел
```

2023-09-10 22:54 UTC, ZhukDmitryOlegovich commented on source/euclid.js
> + * @param  {number} x, y - два числа, для которых ищется НОД
```suggestion
 * @param {number} x - число, для которого ищется НОД
 * @param {number} y - число, для которого ищется НОД
```

2023-09-10 22:57 UTC, ZhukDmitryOlegovich commented on source/euclid.js
> + * @param {...numbers} numbers - любое количество чисел
```suggestion
 * @param {...number} numbers - любое количество чисел
```
это названия типа данных `number` - как `string` или `boolean`

2023-09-10 22:57 UTC, ZhukDmitryOlegovich commented on source/euclid.js
> +const gcd = (x, y) => y ? gcd(y, x % y) : x
```suggestion
const gcd = (x, y) => y ? gcd(y, x % y) : x;
```

2023-09-10 22:58 UTC, ZhukDmitryOlegovich commented on source/euclid.js
> +const euclid = (...numbers) => {
а убери как и тут фигурные скобки и замени if тернарным оператором

2023-09-10 23:04 UTC, ZhukDmitryOlegovich commented on source/euclid.js
> +const euclid = (...numbers) => {
что-то типо 
```js
const euclid = (... numbers) =>
	objects.every(...)
		? numbers.map(...)
		: null;
```

2023-09-10 23:10 UTC, ZhukDmitryOlegovich commented on source/euclid.js
> +const euclid = (...numbers) => numbers.some((number) => !Number.isInteger(number)) ? null : numbers.map(Math.abs).reduce(gcd, 0);
сори, но я табы хочу https://github.com/frontend-park-mail-ru/homework_2023_2/pull/41#discussion_r1320880231 а то строчка длинная

2023-09-10 23:12 UTC, kingjoram commented on source/euclid.js
> +const euclid = (...numbers) => numbers.some((number) => !Number.isInteger(number)) ? null : numbers.map(Math.abs).reduce(gcd, 0);
да я пока пытался разобраться не заметил коммент

2023-09-10 23:12 UTC, ZhukDmitryOlegovich commented on source/euclid.js
> +				: numbers.map(Math.abs).reduce(gcd, 0);
```suggestion
const euclid = (...numbers) => 
	numbers.some((number) => !Number.isInteger(number)) 
		? null 
		: numbers.map(Math.abs).reduce(gcd, 0);
```
и я тебя отпускаю с миром

2023-09-10 23:16 UTC, kingjoram commented on source/euclid.js
> +				: numbers.map(Math.abs).reduce(gcd, 0);
в предыдущем комменте было по 2 таба =)

все, спасибо, что помог во многом, да еще и проверял сейчас очень быстро)

2023-09-10 23:17 UTC, ZhukDmitryOlegovich approved these changes

2023-09-10 23:17 UTC, ZhukDmitryOlegovich commented on source/euclid.js
> +		: numbers.map(Math.abs).reduce(gcd, 0);
```suggestion
/**
 * Нахождение НОД для двух чисел
 *
 * @param {number} x - число, для которого ищется НОД
 * @param {number} y - число, для которого ищется НОД
 * @returns {number} x - НОД для двух чисел
 */
const gcd = (x, y) => y ? gcd(y, x % y) : Math.abs(x);

/**
 * Нахождение НОД для любого количества чисел
 *
 * @param {...number} numbers - любое количество чисел
 * @returns {number} НОД для любого количества чисел
*/
const euclid = (...numbers) => 
	numbers.every(Number.isInteger) 
		? numbers.reduce(gcd, 0) 
		: null;
```
но как и обещал - с меня апрув =)

2023-09-11 00:04 UTC, DPeshkoff requested changes
Привет! Поздравляю с переходом на второй семестр)

Классное решение получилось, но у меня есть пара замечаний. Если возникнут вопросы - можешь писать в [Telegram](t.me/DmPesh)

2023-09-11 00:04 UTC, DPeshkoff commented on source/euclid.js
> +'use strict';
Распиши, пожалуйста, что это за строчка и зачем она нужна)

2023-09-11 00:33 UTC, kingjoram commented on source/euclid.js
> +'use strict';
это строка включает строгий режим, который в какой-то мере "наказывает" за плохой код:
1. кидает ошибки, если не объявлять переменную(через const, let, var) 
2. параметры функций должны иметь разные названия
и тд.
в целом, помогает более надежный код)

2023-09-11 19:27 UTC, DPeshkoff approved these changes
Аппрув!

2023-09-11 19:27 UTC, closed without merging