Гришина Анна
frontend-park-mail-ru/homework_2023_2 pull request #42
Opened 2023-09-08 12:52 UTC by Kayetana

2023-09-08 15:39 UTC, Krasava872 commented
Привет! Добро пожаловать на курс по Front-end разработке)
Я один из менторов данного курса, начинаю проверять твое ДЗ-0. 
Ниже я оставлю комментарии по коду. Если будут вопросы пиши в [телегу](https://t.me/KrasavtsevSS).

2023-09-08 16:21 UTC, Krasava872 requested changes

2023-09-08 16:21 UTC, Krasava872 commented on source/get.js
> +let get = (object, pathToProperty) => {
Опиши JsDoc для функции, и почему здесь используешь let?

2023-09-08 16:21 UTC, Krasava872 commented on source/get.js
> +let get = (object, pathToProperty) => {
И что произойдет если не передать один из аргументов? Или сразу оба? Или в любой из аргументов передать undefined?

2023-09-08 16:21 UTC, Krasava872 commented on source/get.js
> +    let propertyNames = pathToProperty.slice(1).split('.');
Почему тут let?

2023-09-08 16:21 UTC, Krasava872 commented on source/get.js
> +    let propertyNames = pathToProperty.slice(1).split('.');
В коде лучше не использовать Magic numbers. Гуглим и переделываем)

2023-09-08 16:21 UTC, Krasava872 commented on source/get.js
> +    let propertyValue = propertyNames.reduce((previous, propertyName) =>
Почему и тут let? И нужна ли здесь в целом переменная?

2023-09-08 16:21 UTC, Krasava872 commented on tests/get.js
Добавь тесты покрывающие отсутствие аргументов, или когда аргументы равны undefined

2023-09-08 16:21 UTC, Krasava872 commented on source/get.js
> +'use strict';
А что это? Можем убрать эту строчку?

2023-09-09 08:45 UTC, Kayetana commented on source/get.js
> +'use strict';
Эта строка применяет к скрипту строгий режим.
Строгий режим повышает безопасность кода, бросает исключения в случае синтаксических ошибок, которые в нестрогом режиме были бы проигнорированы.
Если правильно поняла, то убрать эту строку можно, но для того, чтобы писать более качественный код, лучше ее оставить)

2023-09-09 13:11 UTC, Krasava872 commented
Вижу исправления но на комментарии тоже желательно ответить)

2023-09-09 20:34 UTC, Kayetana commented on source/get.js
> +let get = (object, pathToProperty) => {
Добавила JsDoc и заменила let на const

2023-09-09 20:35 UTC, Kayetana commented on source/get.js
> +    let propertyNames = pathToProperty.slice(1).split('.');
Исправила на const

2023-09-09 20:36 UTC, Kayetana commented on source/get.js
> +    let propertyValue = propertyNames.reduce((previous, propertyName) =>
Исправила на const и убрала лишнюю переменную propertyValue

2023-09-09 20:41 UTC, Kayetana commented on source/get.js
> +let get = (object, pathToProperty) => {
Добавила проверку типов переданных аргументов. Если какой-то из аргументов не передан, он будет иметь тип undefined. В этом случае функция бросает TypeError

2023-09-09 20:47 UTC, Krasava872 commented on source/get.js
> +let get = (object, pathToProperty) => {
А почему заменила, в чем разница?

2023-09-09 20:48 UTC, Krasava872 commented on source/get.js
> +    let propertyNames = pathToProperty.slice(1).split('.');
А тут почему именно const?

2023-09-09 21:03 UTC, Kayetana commented on source/get.js
> +let get = (object, pathToProperty) => {
let нужно использовать только тогда, когда значение переменной меняется. Во всех остальных случаях const

2023-09-09 21:16 UTC, Krasava872 requested changes

2023-09-09 21:16 UTC, Krasava872 commented on source/get.js
> +    if (typeof object !== 'object' || typeof pathToProperty !== 'string') {
А что будет если передать в object null?

2023-09-09 21:16 UTC, Krasava872 commented on tests/get.js
> +	QUnit.test('get правильно работает с невалидными символами', function (assert) {
Не хватает тестов со другими типами данных)

2023-09-09 21:16 UTC, Krasava872 commented on source/get.js
> +    return propertyNames.reduce((previous, propertyName) =>
Да отлично, но одно но, сейчас возвращаются все перечисляемые свойства, в теории мы можем захватить что не нужное из прототипа, это желательно доработать

2023-09-09 21:38 UTC, Krasava872 requested changes

2023-09-09 21:38 UTC, Krasava872 commented on source/get.js
> +const PATH_START_INDEX = 1;
Почему именно в этом месте объявлена константа?

2023-09-10 19:24 UTC, Kayetana commented on tests/get.js
> +	QUnit.test('get правильно работает с невалидными символами', function (assert) {
Добавила тесты

2023-09-10 19:33 UTC, Kayetana commented on source/get.js
> +    return propertyNames.reduce((previous, propertyName) =>
Почитала про прототипы. Если у объекта отсутствует требуемое свойство, то оно будет взято из прототипа. Поэтому добавила проверку .hasOwnProperty(), чтобы возвращать только собственные свойства объекта и отфильтровывать унаследованные.

2023-09-10 19:35 UTC, Kayetana commented on source/get.js
> +const PATH_START_INDEX = 1;
Перенесла объявление константы в функцию, потому что она нужна только внутри этой функции

2023-09-10 20:59 UTC, Krasava872 requested changes

2023-09-10 20:59 UTC, Krasava872 commented on source/get.js
> +    if (typeof object !== 'object' || typeof pathToProperty !== 'string' || object === null || pathToProperty === null) {
Условие явно можно сократить, сейчас так же будет ошибка если передать в pathToProperty, false

2023-09-10 20:59 UTC, Krasava872 commented on source/get.js
> +        previous === undefined || !previous.hasOwnProperty(propertyName) ? undefined : previous[propertyName], object);
Отлично, но иногда нам может и понадобиться возможность получать значения из прототипов, попробуй дописать функцию что бы мы могли вызывать её в разных режимах чтения свойств. Ну и допиши для этих вызовов тесты.

2023-09-10 21:10 UTC, Kayetana commented on source/get.js
> +    if (typeof object !== 'object' || typeof pathToProperty !== 'string') {
Поняла ошибку. typeof null будет равно object, поэтому нужно по-другому сделать проверку.
Сейчас исправлю

2023-09-10 21:53 UTC, Krasava872 requested changes

2023-09-10 21:53 UTC, Krasava872 commented on source/get.js
> + * @throws {TypeError} - Arguments must be of type Object and String.
Добавь новый параметр в описание)

2023-09-10 21:55 UTC, Kayetana commented on source/get.js
> +        previous === undefined || !previous.hasOwnProperty(propertyName) ? undefined : previous[propertyName], object);
Добавила возможность получать значения свойств прототипов, для этого нужно передать в функцию третьим параметром true. Тесты тоже добавила

2023-09-10 21:58 UTC, Kayetana commented on source/get.js
> +    if (typeof object !== 'object' || typeof pathToProperty !== 'string' || object === null || pathToProperty === null) {
Сократила условие, добавила еще тесты с false

2023-09-10 22:05 UTC, Kayetana commented on source/get.js
> + * @throws {TypeError} - Arguments must be of type Object and String.
Точно! добавила

2023-09-10 22:09 UTC, Krasava872 approved these changes

2023-09-11 00:07 UTC, DPeshkoff requested changes
Привет! Поздравляю с переходом на второй семестр)

Классное решение получилось, но у меня есть пара замечаний. Если возникнут вопросы - можешь писать в [Telegram](t.me/DmPesh)

2023-09-11 00:07 UTC, DPeshkoff commented on source/get.js
> +    if (typeof object !== 'object' || typeof pathToProperty !== 'string' || !object || !pathToProperty) {
Упс! 

![изображение](https://github.com/frontend-park-mail-ru/homework_2023_2/assets/31134795/5afd937a-9f4c-4dbd-a0a1-8d4662f11341)

При этом это валидные строки... непорядок! Давай подумаем, как это починить)

2023-09-11 00:07 UTC, DPeshkoff commented on source/get.js
> +        throw new TypeError("Invalid argument type");
Предлагаю одиночные кавычки - так лучше читается и чаще используются именно они)

2023-09-11 14:41 UTC, Kayetana commented on source/get.js
> +    if (typeof object !== 'object' || typeof pathToProperty !== 'string' || !object || !pathToProperty) {
Разобралась с разными способами сделать проверку типов.

1. typeof - работает для примитивных типов
typeof 'str' === 'string'   // true
Однако если создать строку, число или логический тип через конструктор, то это будет объект.
typeof new String('str') === 'object'   // true

2. instanceof - работает для объектов
'str' instanceof String   // false
new String('str') instanceof String   // true

Поэтому придется сочетать обе проверки.

3. Есть другой способ - использовать функцию Object.prototype.toString.
Она работает и для примитивов, и для объектов

Object.prototype.toString.call('str')   // [object String]
Object.prototype.toString.call(new String('str'))   // [object String]

2023-09-11 14:43 UTC, Kayetana commented on source/get.js
> +        throw new TypeError("Invalid argument type");
Исправила

2023-09-11 19:26 UTC, DPeshkoff approved these changes
Супер!

2023-09-11 19:26 UTC, closed without merging