Variant 1
frontend-park-mail-ru/homework_2023_2 pull request #43
Opened 2023-09-08 13:16 UTC by TheVovchenskiy

Коноплюк Владимир

2023-09-09 10:57 UTC, ZhukDmitryOlegovich commented on tests/zip.js
> +QUnit.module("Тестируем функцию zip", function () {
Верни то форматирование что было =)

Не хочется чтобы диф раздувался и хочется чтобы форматирование во всем репе было одинаковое 

https://learn.javascript.ru/coding-style#rukovodstva-po-stilyu-koda

2023-09-09 10:57 UTC, ZhukDmitryOlegovich commented on source/zip.js
> +const zip = (...objects) => Object.assign({}, ...objects.reverse());
Я бы сам так написал =)

Но так как это ДЗ0 и не может быть всё так просто, то
1. Допиши проверку что все входные элементы в `objects` объекты
2. Напиши 2 теста: что кто-то не объект и кто-то null
3. Напиши jsdoc

И если всё ок, то с меня апрув =)

2023-09-10 11:42 UTC, ZhukDmitryOlegovich commented on source/zip.js
> +};
1. [ ] Добавь jsdoc
2. [ ] Сделай чтобы стрелочная функция была без блока -> используй тернирник

2023-09-10 20:07 UTC, ZhukDmitryOlegovich approved these changes

2023-09-11 00:12 UTC, DPeshkoff requested changes
Привет! Поздравляю с переходом на второй семестр)

Крутое решение получилось, но у меня есть пара замечаний. Если возникнут вопросы - можешь писать в [Telegram](t.me/DmPesh)

2023-09-11 00:12 UTC, DPeshkoff commented on source/zip.js
> +"use strict";
1) Распиши, пожалуйста, что означает эта строчка)

2) Вообще в JS принято использовать одиночные кавычки - давай сделаем с ними)

2023-09-11 00:12 UTC, DPeshkoff commented on source/zip.js
> +const zip = (...objects) =>
Если объектов нет вовсе - выглядит, как ошибка, которую можно и throw'нуть

2023-09-11 00:12 UTC, DPeshkoff commented on source/zip.js
> +	objects.every((element) => typeof element === "object")
Сюда попадет `new Date()`:

![изображение](https://github.com/frontend-park-mail-ru/homework_2023_2/assets/31134795/35c184b5-4c21-440d-9410-8ed1b9c3868c)

Давай подумаем, как его [убрать](https://learn.javascript.ru/native-prototypes#object-prototype)

2023-09-11 00:12 UTC, DPeshkoff commented on tests/zip.js
> +"use strict";
Жестоко, давай вернем)

2023-09-11 13:25 UTC, TheVovchenskiy commented on source/zip.js
> +"use strict";
Эта директива нужна, чтобы явно "включить" возможность использовать новые возможности языка, которые отключены по умолчанию

2023-09-11 16:07 UTC, TheVovchenskiy commented on source/zip.js
> +	objects.every((element) => typeof element === "object")
В телегу написал, но продублирую здесь: я не совсем понимаю, в чем здесь проблема. Имеется в виду, что встроенные прототипы тоже надо копировать в новый объект?

2023-09-12 11:46 UTC, DPeshkoff requested changes

2023-09-12 11:46 UTC, DPeshkoff commented on source/zip.js
> +			element.__proto__ === Object.prototype
Вообще только в ES6 разобрались и стандартизовали __proto__ - лучше использовать [это](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Object/getPrototypeOf)

2023-09-12 12:57 UTC, TheVovchenskiy commented on source/zip.js
> +			element.__proto__ === Object.prototype
Исправил

2023-09-13 10:27 UTC, DPeshkoff approved these changes

2023-09-13 10:28 UTC, closed without merging