Томская Ульяна
frontend-park-mail-ru/homework_2023_2 pull request #44
Opened 2023-09-08 13:40 UTC by tomsuliana

Homework №0 done, variant 3

2023-09-08 17:37 UTC, Krasava872 commented
Привет! Добро пожаловать на курс по Front-end разработке)
Я один из менторов данного курса, начинаю проверять твое ДЗ-0. 
Ниже я оставлю комментарии по коду. Если будут вопросы пиши в [телегу](https://t.me/KrasavtsevSS).

2023-09-08 19:30 UTC, Krasava872 requested changes

2023-09-08 19:30 UTC, Krasava872 commented on source/roman.js
> +    return /^[IVXLCDMivxlcdm]+$/.test(str);
Аналогично, можно упростить регулярку, используя regex flags

2023-09-08 19:30 UTC, Krasava872 commented on source/roman.js
> +    } else if (isArabic(number)){
Излишнее усложнение кода. Вверху у нас есть return, если мы проходим первое условие, то выполнение блока закончиться выводом результата функции, до блока else мы не дойдём.

2023-09-08 19:30 UTC, Krasava872 commented on source/roman.js
> +        for (let i = 0; i < number.length; i++){
Давай попробуем избавиться здесь от цикла for? Какие варианты реализации видишь? Ну или этот цикл тут подходит лучше всего?

2023-09-08 19:30 UTC, Krasava872 commented on source/roman.js
> +    } else {
Аналогично else if на 45 строке

2023-09-08 19:30 UTC, Krasava872 commented on source/roman.js
> +            while ( number >= value ){
Цикл в цикле очень плохая практика, на ровном месте усложняешь алгоритм, попробуй переписать

2023-09-08 19:30 UTC, Krasava872 commented on tests/roman.js
Покрыты не все кейсы, например если передать 'DM', выведется числовой результат. Хотя это не валидные данные.

2023-09-08 19:30 UTC, Krasava872 commented on source/roman.js
Напиши JsDoc для функций

2023-09-08 20:19 UTC, tomsuliana commented on source/roman.js
> +'use strict';
Эта директива активирует строгий режим во всём скрипте. Если ее не написать то некоторые ошибки в коде могут быть проигнорированы и код будет выполняться дальше с непредсказуемым результатом.

2023-09-08 20:40 UTC, tomsuliana commented on source/roman.js
> +function isArabic(str) {
Function Declaration является предпочтительнее при объявлении функции. Такие функции видны во всём блоке + они более читабельны.

2023-09-08 20:55 UTC, tomsuliana commented on source/roman.js
> +function isRoman(str){
Function Declaration является предпочтительнее при объявлении функции. Такие функции видны во всём блоке + они более читабельны.

2023-09-09 13:13 UTC, Krasava872 commented on source/roman.js
> +function isArabic(str) {
А получется в каком именно сейчас блоке видны твои функции?

2023-09-09 13:21 UTC, tomsuliana commented on source/roman.js
> +function isArabic(str) {
Сейчас мои функции видны внутри всего файла roman.js

2023-09-09 13:37 UTC, tomsuliana commented on source/roman.js
> +        for (let i = 0; i < number.length; i++){
Мне кажется, что цикл for тут будет уместнее всего, так как нам требуется перебрать все символы по порядку и при этом в каждой итерации смотреть на следующий символ.

2023-09-09 13:41 UTC, tomsuliana commented on source/roman.js
> +    const RomanMap = new Map([
В данном случае нужна структура, которая будет хранить пары ключ-значение, а Map к тому же имеет встроенный метод get.

2023-09-09 13:46 UTC, Krasava872 commented on source/roman.js
> +function isArabic(str) {
А за пределами файла?

2023-09-09 13:49 UTC, Krasava872 commented on source/roman.js
> +function isRoman(str){
Закрою этот комментарий, вопрос с функциями решаем в предыдущем)

2023-09-09 13:50 UTC, Krasava872 commented on source/roman.js
> +    const RomanMap = new Map([
Хорошо, какие ещё структуры знаешь в языке и какие могли бы подойти под те же критерии?

2023-09-09 13:52 UTC, Krasava872 commented on source/roman.js
> +        for (let i = 0; i < number.length; i++){
Ну верно нам нужно перебирать определённый набор элементов, какие ещё способы перебора знаешь?

2023-09-09 18:05 UTC, tomsuliana commented on source/roman.js
> +function isArabic(str) {
А за пределами файла функции не видны.

2023-09-09 18:44 UTC, tomsuliana commented on source/roman.js
> +        for (let i = 0; i < number.length; i++){
Цикл ForEach или for( let char of number) или явно вызвать итератор, но во всех этих случаях мы не сможет заглянуть в следующий элемент. Также есть цикл while и возможность привести строку к массиву символов и перебирать его, но это все не очень уместно.

2023-09-09 18:59 UTC, Krasava872 commented on source/roman.js
> +function isArabic(str) {
Тогда каким образом они вызываются в твоих тестах?)

2023-09-09 19:05 UTC, Krasava872 commented on source/roman.js
> +        for (let i = 0; i < number.length; i++){
А почему именно не уместно? Ну и для того что бы взять следующий элемент массива от текущей итерации, достаточно к текущему индексу на итерации прибавить единицу, изучи методы, все основные методы перебора позволяют тебе манипуляции с индексами. Думаю тут все же возможно и нужно переделать цикл)

2023-09-09 19:39 UTC, tomsuliana commented on tests/roman.js
В процессе исправления была найдена ошибка в исходных тестах, в примере где на вход подавалось "iiii" ожидался ответ 4, хотя это не валидные данные.

2023-09-09 19:41 UTC, tomsuliana commented on source/roman.js
> +    const RomanMap = new Map([
Ещё есть Object, но у него нет встроенного метода get. Также можно попробовать массив из пар или Set пар, но во всех случаях придется специально прописывать метод получения нужного значения по ключу.

2023-09-09 19:44 UTC, tomsuliana commented on source/roman.js
> +function isArabic(str) {
Ну получается что область видимости этих функций - вся программа

2023-09-09 19:47 UTC, Krasava872 commented on source/roman.js
> +function isArabic(str) {
Именно, как считаешь функции написанные для решения вспомогательных задач для другой функции, должны лежать в общей памяти и быть доступны везде?

2023-09-09 19:49 UTC, Krasava872 commented on source/roman.js
> +    const RomanMap = new Map([
Ну думаю лучше повторить теорию про [объекты](https://learn.javascript.ru/object), в js для объектов не нужен метод который просто возвращает значение без преобразований)

2023-09-09 19:51 UTC, Krasava872 commented on tests/roman.js
Да, отлично что заметила

2023-09-09 19:58 UTC, Krasava872 commented on tests/roman.js
Отбой, говорят конкретно IIII верно, хотя я сам в шоке)

2023-09-09 20:19 UTC, Krasava872 commented on tests/roman.js
В общем, ты откапала мамонта, поздравляю) Оказывается у римской системы счисления есть два подхода, сложения и вычитания, погугли про это, занятное чтиво) Решение такое, При переводе с арабских цифр в римские, мы используем устоявшийся формат, 4 это IV, но если с римского мы укажем либо IIII либо IV, то должны получить ответ 4

2023-09-09 21:10 UTC, tomsuliana commented on source/roman.js
> +        for (let i = 0; i < number.length; i++){
Ну например когда я пытаюсь прибавить 1 к индексу в цикле for(let i in number) мне пишет undefined. Поэтому смогла сделать только while.

2023-09-09 21:20 UTC, Krasava872 commented on source/roman.js
> +        for (let i = 0; i < number.length; i++){
Ну это логично, ты разобралась почему именно пишет undefined?

2023-09-09 22:16 UTC, tomsuliana commented on source/roman.js
> +        for (let i = 0; i < number.length; i++){
Ну потому что в  for in работает не с индексом, а со значением, поэтому не получится достать соседний элемент. Я не понимаю какой тогда цикл использовать.

2023-09-09 23:37 UTC, Krasava872 requested changes

2023-09-09 23:37 UTC, Krasava872 commented on source/roman.js
> +    let isArabic = (str) => {
Так, а почему по итогу перенесла функцию? и почему теперь тут стрелочная объявленная через let?

2023-09-09 23:37 UTC, Krasava872 commented on source/roman.js
> +            while (i < number.length){
Давай переделаем цикл на метод reduce у массива, предварительно преобразовав numbers в массив

2023-09-09 23:37 UTC, Krasava872 commented on source/roman.js
> +            for (let key in RomanNum){
Тут тоже, давай делать через reduce

2023-09-09 23:37 UTC, Krasava872 commented on source/roman.js
Лучше убрать лишние пустые строки

2023-09-09 23:37 UTC, Krasava872 commented on tests/roman.js
Добавь больше тестов с неправильными данными по типу DM, VM и так далее, и больше тестов с принципом сложения VIIII, XIIII, XVIIII и так далее.

2023-09-09 23:37 UTC, Krasava872 commented on tests/roman.js
И обязательно отобрази тестами максимально возможное римское число

2023-09-10 00:03 UTC, Krasava872 commented on source/roman.js
> +const roman = (number) => {
Что произойдет если передать пустой массив?

2023-09-10 15:17 UTC, tomsuliana commented on source/roman.js
> +    let isArabic = (str) => {
Перенесла функции для того, чтобы они были доступны только в данном блоке(функции roman), а стрелочная форма для краткости.

2023-09-10 20:52 UTC, Krasava872 requested changes

2023-09-10 20:52 UTC, Krasava872 commented on source/roman.js
> +        if (str == ""){
Можно записать проверку проще

2023-09-10 20:52 UTC, Krasava872 commented on source/roman.js
> +            let arabic_result = number.split('').reduce(function(sum, current, index){
Нам теперь точно нужна тут переменная?

2023-09-10 20:52 UTC, Krasava872 commented on source/roman.js
> +            let roman_result = Object.keys(RomanNum).reduce(function(sum, current){
Аналогично, возможно тут можно удалить лишний код

2023-09-10 21:49 UTC, Krasava872 requested changes
Осталось только решить проблему в случае вызова функции с пустым массивом.

2023-09-10 21:50 UTC, Krasava872 commented
Не забывай отвечать на вопросы в комментариях.

2023-09-11 16:08 UTC, tomsuliana commented on source/roman.js
> +const roman = function (number) {
Да, можем заменить на стрелочную, наверное для краткости

2023-09-11 16:08 UTC, tomsuliana commented on source/roman.js
> +const roman = (number) => {
Теперь делаю проверку и на пустой массив, отразила в тестах

2023-09-11 17:54 UTC, Krasava872 commented on source/roman.js
> +const roman = function (number) {
Опиши разницу между стрелочной функцией и функциональным выражением

2023-09-11 18:03 UTC, Krasava872 requested changes

2023-09-11 18:03 UTC, Krasava872 commented on source/roman.js
> +        if (str.length == 0){
Можно сократить условие

2023-09-11 22:46 UTC, Krasava872 requested changes

2023-09-11 22:46 UTC, Krasava872 commented on source/roman.js
> +        let type = typeof str;
Почему let?

2023-09-11 22:46 UTC, Krasava872 commented on source/roman.js
> +        if (str && (type == 'string' ||  type == 'number')){
Если передать строку в объектной обёртке new String('123'), выведет invalid input, нужно и это поправить

2023-09-11 22:46 UTC, Krasava872 commented on source/roman.js
> +     * @param {string} str - Число для перевода в другую систему
На вход принимаем явно не только строку но и число

2023-09-12 06:08 UTC, tomsuliana commented on source/roman.js
> +        let type = typeof str;
Заменила на const, потому что функция не будет изменяться во время работы программы

2023-09-12 08:00 UTC, Krasava872 requested changes

2023-09-12 09:03 UTC, tomsuliana commented on source/roman.js
> +        let type = typeof str.valueOf();
Исправила на const, потому что она не меняется

2023-09-12 09:19 UTC, Krasava872 approved these changes

2023-09-13 14:30 UTC, DPeshkoff requested changes
Привет! Поздравляю с переходом на второй семестр)

Интересное решение получилось, но у меня есть пара замечаний. Если возникнут вопросы - можешь писать в [Telegram](t.me/DmPesh)

2023-09-13 14:30 UTC, DPeshkoff commented on source/roman.js
> +        if (str && (type == 'string' ||  type == 'number')){
Упс! 

![изображение](https://github.com/frontend-park-mail-ru/homework_2023_2/assets/31134795/5afd937a-9f4c-4dbd-a0a1-8d4662f11341)

При этом это валидные строки... непорядок! Давай подумаем, как это починить)

2023-09-13 14:30 UTC, DPeshkoff commented on source/roman.js
> +        if (str && typeof str.valueOf() == 'string'){
И тут)

2023-09-13 14:30 UTC, DPeshkoff commented on source/roman.js
> +            return /^M{0,3}(CM|CD|D?C{0,3})?(XC|XL|L?X{0,3})?(IX|IV|V?I{0,4})?$/i.test(str);
Страшная регулярка - мы не можем разве упростить?)

2023-09-13 14:30 UTC, DPeshkoff commented on source/roman.js
> +            return number.split('').reduce(function(sum, current, index){
А какие в языке есть способы создать функцию? Почему ты выбрала именно такой?

2023-09-13 14:30 UTC, DPeshkoff commented on source/roman.js
> +                }
Да тут и тернарником можно)

2023-09-13 14:30 UTC, DPeshkoff commented on source/roman.js
> +            return "invalid input"
Предлагаю выбрасывать [ошибку](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Error)

2023-09-13 14:31 UTC, DPeshkoff commented on source/roman.js
> +            return "invalid input"
Не забывай про точки с запятой! Несмотря на то, что парсер умеет автоматически их проставлять - иногда это приводит к странным результатам. 

<details><summary>Каким?</summary>
<p>
К примеру, тривиальный и понятный код:

![изображение](https://github.com/frontend-park-mail-ru/homework_2023_2/assets/31134795/3d22e9a8-baee-4bfb-886a-b4dfe665364a)

Внезапно падает:

![изображение](https://github.com/frontend-park-mail-ru/homework_2023_2/assets/31134795/582afa37-106b-4330-acaf-6a622c1cda61)

Почему так происходит, думаю, наглядно видно по тексту ошибки - он считает `[3]` частью `s`. Если при этом поставить ;, то код магически начинает работать)

![изображение](https://github.com/frontend-park-mail-ru/homework_2023_2/assets/31134795/9210ce09-d52b-40aa-9731-dd12424c685b)
</p>
</details> 

Давай везде проставим точки с запятой)

2023-09-13 21:03 UTC, tomsuliana commented on source/roman.js
> +        if (str && (type == 'string' ||  type == 'number')){
Не совсем понимаю проблему, у меня обрабатывается случай задания строки через new String и это отражено в тестах, например: assert.strictEqual(roman(new String('123')), 'CXXIII');

2023-09-13 21:05 UTC, tomsuliana commented on source/roman.js
> +            return /^M{0,3}(CM|CD|D?C{0,3})?(XC|XL|L?X{0,3})?(IX|IV|V?I{0,4})?$/i.test(str);
У меня, к сожалению, нет идей, как сделать регулярку проще и при этом валидировать правильность задания римских чисел

2023-09-13 21:09 UTC, tomsuliana commented on source/roman.js
> +            return number.split('').reduce(function(sum, current, index){
Есть способы Function declaration, Function Expression, Arrow Function. Теперь заменила на стрелочный способ для краткости

2023-09-14 11:45 UTC, DPeshkoff commented on source/roman.js
> +            return /^M{0,3}(CM|CD|D?C{0,3})?(XC|XL|L?X{0,3})?(IX|IV|V?I{0,4})?$/i.test(str);
Здесь можно без лишних групп, но ладно, пойдет)

2023-09-14 11:46 UTC, DPeshkoff approved these changes

2023-09-14 11:46 UTC, closed without merging