Роман Сулайманов
frontend-park-mail-ru/homework_2023_2 pull request #45
Opened 2023-09-08 14:01 UTC by Romanlock

2023-09-09 09:36 UTC, ZhukDmitryOlegovich commented
Некорректное название ПРа. Оно должно быть «Фамилия Имя»

2023-09-09 10:38 UTC, ZhukDmitryOlegovich commented on source/max.js
> -const max = numbers => Math.max(...numbers);
Ты видимо поменял форматирование файлов - на винде и на линуксе разные концы строк `\n\r` и `\n` - сделай так чтобы диф стал нормальным

2023-09-09 10:50 UTC, ZhukDmitryOlegovich commented on tests/plainify.js
> +});
Добавь 2 теста
1. С пустым объектом 
2. С объектом такого вида
```js
const nested = Object.create(null);
nested.a = {};
nested.a.b = 1;
```

2023-09-09 10:50 UTC, ZhukDmitryOlegovich commented on source/plainify.js
> +}
Сделай чтобы стрелочная функция сразу возвращала значение - без `return` конструкции https://learn.javascript.ru/arrow-functions-basics

2023-09-09 10:50 UTC, ZhukDmitryOlegovich commented on source/plainify.js
> +    if (!(object instanceof Object)) return TypeError;
Каверзный вопрос: Есть ещё способ проверить тип переменной через `typeof`. А в чем отличия от такого способа проверка на объект?

2023-09-09 11:45 UTC, Romanlock commented on source/plainify.js
> +    if (!(object instanceof Object)) return TypeError;
typeof вернёт строку с типом объекта, например: "number", "undefined", "object". В отличие от typeof, в общем случае instanceof PARAM определяет, является ли переданный объект, объектом, созданным при помощи конструктора объектов PARAM. В данной задаче instanceof Object определяет, создан ли параметр с помощью стандартного конструктора объектов, таким образом мы проверяем, является ли PARAM Object-ом.

2023-09-09 12:45 UTC, ZhukDmitryOlegovich commented on source/plainify.js
> +    if (!(object instanceof Object)) return TypeError;
Всё так, но существуют примеры когда объекты специально создаются без prototype (дабы например обойти всякие блокировщики) и делается это через `Object.create(null)` - поправь свой код так чтобы с объектом созданным таким образом функция корректно работала

2023-09-11 21:16 UTC, ZhukDmitryOlegovich approved these changes

2023-09-13 15:17 UTC, DPeshkoff requested changes
Привет! Поздравляю с переходом на второй семестр)

Интересное решение получилось, но у меня есть пара замечаний. Если возникнут вопросы - можешь писать в [Telegram](t.me/DmPesh)

2023-09-13 15:17 UTC, DPeshkoff commented on source/max.js
> -'use strict';
Этот файл не нужно менять - давай вернем как было)

2023-09-13 15:17 UTC, DPeshkoff commented on source/plainify.js
> +'use strict';
Распиши, что делает эта строчка

2023-09-13 15:17 UTC, DPeshkoff commented on source/plainify.js
> +    (object !== null && typeof object === 'object') ? buildPlainObject(object) : TypeError
Не выглядит как plain-объект:

<img width="351" alt="Снимок экрана 2023-09-13 в 18 16 39" src="https://github.com/frontend-park-mail-ru/homework_2023_2/assets/31134795/0b9017f0-e672-410c-9415-d73680380db7">

2023-09-13 15:17 UTC, DPeshkoff commented on tests/max.js
> -		assert.strictEqual(max([ 1, 2, 3 ]), 3, 'max([1, 2, 3]) === 3');
Здесь не нужны изменения

2023-09-13 15:17 UTC, DPeshkoff commented on tests/plainify.js
> -				baz: 42
Здесь - тоже

2023-09-14 23:01 UTC, DPeshkoff requested changes

2023-09-14 23:01 UTC, DPeshkoff commented on source/plainify.js
> +'use strict';
up

2023-09-14 23:01 UTC, DPeshkoff commented on source/plainify.js
> +    Object.prototype.toString.call(object) === '[object Object]' ? buildPlainObject(object) : TypeError
ошибки лучше не возвращать, а throw'ать
не забудь занести в JSDoc

2023-09-15 19:29 UTC, DPeshkoff approved these changes

2023-09-15 19:29 UTC, closed without merging