Кириллова Христина
frontend-park-mail-ru/homework_2023_2 pull request #46
Opened 2023-09-08 14:05 UTC by khristina455

2023-09-08 17:13 UTC, Krasava872 commented
Привет! Добро пожаловать на курс по Front-end разработке)
Я один из менторов данного курса, начинаю проверять твое ДЗ-0. 
Ниже я оставлю комментарии по коду. Если будут вопросы пиши в [телегу](https://t.me/KrasavtsevSS).

2023-09-08 17:27 UTC, Krasava872 requested changes

2023-09-08 17:27 UTC, Krasava872 commented on source/tree.js
> +'use strict';
Зачем нам эта строка?

2023-09-08 17:27 UTC, Krasava872 commented on source/tree.js
> +    if (typeof height != "number" && !(typeof height == "string" && !isNaN(height))) {
Лишние проверки, если нам в функции нужен строго тип number можно записать проверку короче.

2023-09-08 17:27 UTC, Krasava872 commented on source/tree.js
> +    let result = " ".repeat(height - 2) + "|" + " ".repeat(height - 2) + "\n";
Magic numbers плохая практика. Не понимаю что за цифры и почему они тут именно такие) Гуглим и переделываем.

2023-09-08 17:27 UTC, Krasava872 commented on source/tree.js
> +        result = " ".repeat(i) + "*".repeat(2 * height - 3 - 2 * i) + " ".repeat(i) + "\n" + result;
Те же Magic numbers)

2023-09-08 17:27 UTC, Krasava872 commented on source/tree.js
> +    for(let i = 0; i < height - 1; ++i) {
В целом использование стандартных циклов в данной задаче котируется. Но, если придумаешь способ реализовать это через нативные методы перебора у массивов, будет плюсом)

2023-09-08 17:27 UTC, Krasava872 commented on source/tree.js
> +    if (typeof height != "number" && !(typeof height == "string" && !isNaN(height))) {
А можем заменить здесь сравнение на !==?

2023-09-08 17:37 UTC, khristina455 commented on source/tree.js
> +    if (typeof height != "number" && !(typeof height == "string" && !isNaN(height))) {
Но судя по тестам функция и со строками должна работать

2023-09-08 17:52 UTC, Krasava872 commented on source/tree.js
> +    if (typeof height != "number" && !(typeof height == "string" && !isNaN(height))) {
Верно, и учитывая это в условии все ещё есть лишние проверки)

2023-09-09 07:56 UTC, khristina455 commented on source/tree.js
> +'use strict';
директива, которая включает строгий режим. Он выбрасывает ошибки на конструкции, которое ранние стандарты js пропускали

2023-09-09 13:35 UTC, Krasava872 commented
Почти идеально) И ещё на все комментарии нужно ответить.

2023-09-09 19:39 UTC, khristina455 commented on source/tree.js
> +    if (typeof height != "number" && !(typeof height == "string" && !isNaN(height))) {
Да, можно и нужно, потому что !== строгое неравенство, а строгие сравнения нужно всегда использовать из-за неявной кастовки в js

2023-09-09 20:16 UTC, khristina455 commented on source/tree.js
> +    for(let i = 0; i < height - 1; ++i) {
Считаю, что цикл перебора в массиве здесь не нужен, потому что здесь нужно просто число, которое инкрементируется, а его начальное значение завист от входных данных

2023-09-09 20:30 UTC, Krasava872 requested changes

2023-09-09 23:01 UTC, Krasava872 requested changes

2023-09-10 20:42 UTC, Krasava872 requested changes

2023-09-10 20:42 UTC, Krasava872 commented on source/tree.js
> +const level = (strings, character, amountOfChar, amountOfSpace) => {
Лучше перенести узконаправленную функцию в другую область видимости, что бы она не была доступна в глобальной.

2023-09-10 20:42 UTC, Krasava872 commented on source/tree.js
> +    const baseOfTree = 2 * (height - trunkHeight) - 1; //кол-во звездочек на нижнем уровне елки, так как на n уровне 2 * n - 1 число звездочек
Комментарии теперь можно и убрать, код читается гораздо проще.

2023-09-10 22:32 UTC, Krasava872 approved these changes

2023-09-11 00:14 UTC, DPeshkoff requested changes
Привет! Поздравляю с переходом на второй семестр)

Хорошее решение получилось, но у меня есть пара замечаний. Если возникнут вопросы - можешь писать в [Telegram](t.me/DmPesh)

2023-09-11 00:14 UTC, DPeshkoff commented on source/tree.js
> +    if (isNaN(height) || height === Infinity || height === "") {
А если будет -Infinity? Вообще в языке есть функция, которая может проверить и то, и то, найдешь ее?)

2023-09-11 00:14 UTC, DPeshkoff commented on source/tree.js
> +        return " ".repeat(amountOfSpace) + `${character}`.repeat(amountOfChar) + " ".repeat(amountOfSpace);
Вообще в JS принято использовать одиночные кавычки. Предлагаю поменять, мелочь, а более читаемо)

2023-09-11 05:29 UTC, khristina455 commented on source/tree.js
> +    if (isNaN(height) || height === Infinity || height === "") {
Number.isFinite()

2023-09-11 05:32 UTC, khristina455 commented on source/tree.js
> +        return " ".repeat(amountOfSpace) + `${character}`.repeat(amountOfChar) + " ".repeat(amountOfSpace);
Поменяла

2023-09-11 19:24 UTC, DPeshkoff commented on source/tree.js
> +    if (isNaN(height) ||  height === '' || !isFinite(height)) {
[isFinite уже проверяет на NaN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/isFinite)

Кстати, распиши, пожалуйста, в реплае, чем отличается Number.isFinite от isFinite)

2023-09-12 07:51 UTC, khristina455 commented on source/tree.js
> +    if (isNaN(height) ||  height === '' || !isFinite(height)) {
isFinite конвертирует к number, а Number.isFinite нет. Тое сть во втором случае, если тип не number, то функция всегда возвращает false

2023-09-12 11:47 UTC, DPeshkoff approved these changes

2023-09-12 11:47 UTC, closed without merging