Variant 7
frontend-park-mail-ru/homework_2023_2 pull request #47
Opened 2023-09-08 14:15 UTC by wonderf00l

Зубков Максим WEB-21

2023-09-08 20:18 UTC, Kostich31 requested changes

2023-09-08 20:18 UTC, Kostich31 commented on tests/plain.js
> +    QUnit.test('Работает с единственным элементом', function (assert) {
Одинаковые названия для нескольких тестов. Давай добавим дополнительную информацию. Например, про уровень вложенности

2023-09-08 20:18 UTC, Kostich31 commented on source/plain.js
> +const plain = function (nestedArray) {
В чем разница между объявлением функции через function и через стрелку?

2023-09-08 20:18 UTC, Kostich31 commented on source/plain.js
> +    nestedArray.forEach(arrayItem => Array.isArray(arrayItem) ? unpackedArray = unpackedArray.concat(plain(arrayItem)) : unpackedArray.push(arrayItem))
Давай перепишем функцию с использованием reduce https://learn.javascript.ru/array-methods

2023-09-08 20:18 UTC, Kostich31 commented on source/plain.js
> +    let unpackedArray = []
Отсутствует проверка на тип переданного аргумента.

2023-09-08 20:18 UTC, Kostich31 commented on tests/plain.js
> +        assert.deepEqual(plain([['abcde'], [['f'], [null, false], [NaN, NaN], NaN], -Infinity, [undefined], [1, 2]]), ['abcde', 'f', null, false, NaN, NaN, NaN, -Infinity, undefined, 1, 2]);
Отсутствуют тесты с негативными сценариями. Добавь тесты с другими типами данных.

2023-09-08 20:31 UTC, Kostich31 commented
Привет, добро пожаловать на курс по фронтенд-разработке. Я буду проверять твое ДЗ 0. Ниже будут мои вопросы и комментарии по коду.

2023-09-09 16:03 UTC, wonderf00l commented on source/plain.js
> +const plain = function (nestedArray) {
Стрелочная функция не создает собственный контекст исполнения, она использует контекст исполнения внешней функции. Например: значение this, объект arguments стрелочная функция берет из функции, в которой была определена.

2023-09-09 16:23 UTC, Kostich31 requested changes

2023-09-09 16:23 UTC, Kostich31 commented on source/plain.js
> +const plain = function (nestedArray) {
Давай замени function на стрелочное объявление. Так код будет выглядеть короче.

2023-09-09 16:23 UTC, Kostich31 commented on source/plain.js
> +    console.log(nestedArray)
Ненужный вывод в консоль

2023-09-09 16:23 UTC, Kostich31 commented on source/plain.js
> +// const plain = function (nestedArray) {
Лишний закомментированный код

2023-09-09 16:23 UTC, Kostich31 commented on source/plain.js
> +    if (Array.isArray(nestedArray)) {
Может быть возвращать ошибку или null, если был передан неверный тип входного параметра? Если решишь взять ошибку, не забудь добавить тег @throws в документацию с описанием ошибки.

2023-09-09 16:23 UTC, Kostich31 commented on source/plain.js
> +    if (Array.isArray(nestedArray)) {
И можно поместить внутрь if-а !Array.isArray(nestedArray), чтобы убрать лишний else и сразу возвращать массив

2023-09-09 18:10 UTC, Kostich31 requested changes

2023-09-09 18:10 UTC, Kostich31 commented on source/plain.js
> + * @return {Array} unpackedArray Результирующий массив, включающий все элементы исходного.
Укажи второй тип для возвращаемого значения {Array|null}

2023-09-09 18:10 UTC, Kostich31 commented on source/plain.js
> +    const plainInner = (nestedArray) => nestedArray.reduce((unpackedArray, arrayValue) => unpackedArray.concat(Array.isArray(arrayValue) ? plainInner(arrayValue) : arrayValue), [])
Кажется, что более понятным вариантом будет поместить проверку Array.isArray(nestedArray) вверх, а после сразу возвращать результат работы reduce без создания функции plainInner:
`return nestedArray.reduce((unpackedArray, arrayValue) => unpackedArray.concat(Array.isArray(arrayValue) ? plainInner(arrayValue) : arrayValue), [])`

2023-09-09 18:38 UTC, Kostich31 requested changes

2023-09-09 18:38 UTC, Kostich31 commented on source/plain.js
> +}
Добавь пустую строку в конце файла

2023-09-09 20:29 UTC, Kostich31 approved these changes

2023-09-11 00:16 UTC, DPeshkoff requested changes
Привет! Поздравляю с переходом на второй семестр)

Крутое решение получилось, но у меня есть пара замечаний. Если возникнут вопросы - можешь писать в [Telegram](t.me/DmPesh)

2023-09-11 00:16 UTC, DPeshkoff commented on source/plain.js
> +'use strict';
Распиши, пожалуйста, что это за строчка и зачем она нужна)

2023-09-11 00:16 UTC, DPeshkoff commented on tests/plain.js
> -		assert.deepEqual(plain([]), [], 'Работает с пустым массивом');
Здесь не должно быть изменений в отступах, предлагаю вернуть, как было)

2023-09-11 21:34 UTC, wonderf00l commented on source/plain.js
> +'use strict';
Директива 'use strict' информирует интерпретатор JavaScript о необходимости применения правил Strict для всего файла или функции, в которой он появляется.
Строгий режим нужен для: предотвращения ошибок, упрощения отладки, улучшения производительности, введения запрета на использование неактуальных библиотек, функций. Как-то так)

2023-09-12 11:48 UTC, DPeshkoff approved these changes
Ладно, с отступами надо настроить конфигурацию, если что

Остальное гуд)

2023-09-12 11:48 UTC, DPeshkoff commented on tests/plain.js
> -		assert.deepEqual(plain([]), [], 'Работает с пустым массивом');
Отступ не вернулся, у тебя IDE очень хочет поменять)

2023-09-12 11:49 UTC, closed without merging