Added function inverse
frontend-park-mail-ru/homework_2023_2 pull request #48
Opened 2023-09-08 14:33 UTC by UmalatDukuev

2023-09-09 09:36 UTC, ZhukDmitryOlegovich commented
Некорректное название ПРа. Оно должно быть «Фамилия Имя»

2023-09-09 09:56 UTC, UmalatDukuev commented
> Некорректное название ПРа. Оно должно быть «Фамилия Имя»

Поправил

2023-09-09 09:59 UTC, ZhukDmitryOlegovich commented on tests/inverse.js
> +		assert.deepEqual(inverse([1, 2, 3, 4, undefined]), []);
В задание ничего не сказано про тип данных в массиве и по духу задачи - элементы могу быть любыми - не только числа. Поэтому этот тест кейс стоит убрать / перепридумать и так же поправить логику работы

#undefinedТожеЗначение

2023-09-09 10:02 UTC, UmalatDukuev commented on tests/inverse.js
> +		assert.deepEqual(inverse([1, 2, 3, 4, undefined]), []);
С тест кейсом понял. 
Поправить логику работы - имеется в виду, убрать в коде проверку undefined'a?

2023-09-09 10:02 UTC, ZhukDmitryOlegovich commented on source/inverse.js
> +    let numbers = arguments[0];
Использование `function` и `arguments` для безымянной функции считается устаревших в том плане что есть стрелочные функции и пропы в ней 

https://learn.javascript.ru/arrow-functions-basics

2023-09-09 10:03 UTC, ZhukDmitryOlegovich commented on tests/inverse.js
> +		assert.deepEqual(inverse([1, 2, 3, 4, undefined]), []);
Да, убрать проверку на undefined 

Можешь в этот тесткейсе например добавить проверку что будут меняться объекты или массивы

2023-09-09 10:06 UTC, ZhukDmitryOlegovich commented on tests/max.js
> +	QUnit.test('Возвращает максимальное из трёх положительных чисел1s', function (assert) {
Верни как было, чтобы диф не раздувать

2023-09-09 10:07 UTC, ZhukDmitryOlegovich commented on source/inverse.js
> +            let subarray = numbers.splice(numbers.length - ind, ind)
А что вообще такое `splice`? Это же не `slice`. Расскажи чем отличается и почему решил его использовать?

2023-09-09 10:08 UTC, ZhukDmitryOlegovich commented on source/inverse.js
> +};
Отсутствие пустой строки в конце файла =(

2023-09-09 10:10 UTC, ZhukDmitryOlegovich commented on tests/inverse.js
> +	QUnit.test('Все элементы функции должны быть инициализированы', function (assert) {
Отсутствие код-стайла. https://learn.javascript.ru/coding-style#rukovodstva-po-stilyu-koda

```js
	/* Дополнительные тесты */
	QUnit.test('Все элементы функции должны быть инициализированы', function (assert) {
```

2023-09-09 10:13 UTC, ZhukDmitryOlegovich commented on source/inverse.js
> +	        let reversedSubarray = numbers.slice(ind).reverse();
Коварные вопросы: В документации написано что `reverse` изменяет положение элементов в исходном массиве? Разве не получается так что тот массив что передали на вход функции измениться? Ведь мутировать входные данные в такой функции точно нельзя

2023-09-10 15:58 UTC, ZhukDmitryOlegovich commented on source/max.js
> +const inverse = (array, ind) => {
у тебя теперь inverse и max дважды в двух файлах определены

2023-09-10 16:00 UTC, ZhukDmitryOlegovich commented on source/max.js
> +let numbers = array.slice();
Коварный вопрос: зачем делать slice без параметров? Такой же массив вернется, нет?

2023-09-10 16:01 UTC, ZhukDmitryOlegovich commented on source/max.js
> +            return numbers.slice(0, ind).concat(reversedSubarray);
в github видно что отступы - то табы, то пробелы - поддерживай кодстайл https://learn.javascript.ru/coding-style#rukovodstva-po-stilyu-koda

2023-09-10 16:01 UTC, UmalatDukuev commented on source/max.js
> +let numbers = array.slice();
Да. Это копирование массива, чтобы не мутировать исходный.

2023-09-10 16:02 UTC, UmalatDukuev commented on source/max.js
> +const inverse = (array, ind) => {
Да, я не до конца поправил еще. Подожди немного, пожалуйста

2023-09-10 16:11 UTC, UmalatDukuev commented on source/max.js
> +            return numbers.slice(0, ind).concat(reversedSubarray);
Я не знаю, почему, но у меня этот let reversedSubarray в гите с отступом показывается. Я уже несколько раз пуши попробовал, не сдвигается.
![image](https://github.com/frontend-park-mail-ru/homework_2023_2/assets/106022065/aa9b85e6-62f2-43d9-b986-34f53faca2ad)

2023-09-10 16:12 UTC, UmalatDukuev commented on source/max.js
> +let numbers = array.slice();
Так ведь можно делать?

2023-09-10 16:12 UTC, UmalatDukuev commented on source/max.js
> +const inverse = (array, ind) => {
Вроде бы исправил всё. Можно проверять, я думаю...

2023-09-10 16:13 UTC, ZhukDmitryOlegovich commented on source/max.js
> +            return numbers.slice(0, ind).concat(reversedSubarray);
в правом нижнем углу измени чтобы табы определялись от контента в файле

потом сделай ctrl + A, Tab, Shift + Tab и табы/пробелы везде должны стать одинаковыми

2023-09-10 16:21 UTC, UmalatDukuev commented on source/max.js
> +            return numbers.slice(0, ind).concat(reversedSubarray);
А кроме этого нужно ещё что-нибудь поправить?

2023-09-10 16:23 UTC, ZhukDmitryOlegovich commented on source/max.js
> +let numbers = array.slice();
Да, хотел понять уточнить правильно ли ты понимаешь что делаешь =)

2023-09-10 16:25 UTC, ZhukDmitryOlegovich commented on source/max.js
> +            return numbers.slice(0, ind).concat(reversedSubarray);
ну отступы должны быть правильные - можно линтер намутить https://learn.javascript.ru/coding-style#rukovodstva-po-stilyu-koda

а так мне ещё не нравиться три пустые строки в конце файла - должна быть одна =) особенно в тех файлах в которых это единственное измение

2023-09-10 16:27 UTC, UmalatDukuev commented on source/max.js
> +let numbers = array.slice();
Такс. Это про объявление функции и копирование массива? 
Про объявление ещё гляну, а копировать так нельзя?

2023-09-10 16:27 UTC, UmalatDukuev commented on source/max.js
> +let numbers = array.slice();
А, не увидел на что это ответ. Тогда окей, спасибо

2023-09-10 16:38 UTC, ZhukDmitryOlegovich commented on source/max.js
> +            let subarray2 = numbers.slice(0, len - ind);
1. [ ] Расскажи о том что будет если в `slice` положить отрицательные числа и что будет если не указывать второй аргумент - и поменяй код в соответствие с этим знанием
2. [ ] Расскажи как ещё можно создать переменные кроме как с помощью `let` - и поменяй код в соответствие с этим знанием
3. [ ] Ответь на неотвеченные "Каверзные вопросы" выше
4. [ ] Единообразно напиши код в обоих блоках условия от "ind >= 0" (и возможно ты увидишь что-то общее)

2023-09-10 16:40 UTC, UmalatDukuev commented on source/max.js
> +            let subarray2 = numbers.slice(0, len - ind);
Насчёт неотвеченного каверзного вопросы. Он был про splice. Я глянул получше, понял, что можно без него. Поэтому теперь код без splice'ов.

2023-09-10 16:41 UTC, UmalatDukuev commented on source/max.js
> +            let subarray2 = numbers.slice(0, len - ind);
А его отличие от slice в том, что splice меняет исходный массив, а slice копирует. В этом плане наверное и лучше slice, чтобы не трогать исходники

2023-09-10 16:50 UTC, ZhukDmitryOlegovich commented on source/max.js
> +            let subarray2 = numbers.slice(0, len - ind);
> splice меняет исходный массив, а slice копирует

Точнее было бы сказать что с помощью `splice` можно удалить/добавить заменить отрезок даных в массиве, а `slice` возвращает отрезок, но в общем - ок. Лучше бы конечно в том треде (коменте, как оно называется - не помню) и ответил, но ладно

2023-09-10 16:51 UTC, ZhukDmitryOlegovich commented on source/inverse.js
> +            let subarray = numbers.splice(numbers.length - ind, ind)
ответ https://github.com/frontend-park-mail-ru/homework_2023_2/pull/48#discussion_r1320810997
уточнение https://github.com/frontend-park-mail-ru/homework_2023_2/pull/48#discussion_r1320814965

2023-09-10 16:52 UTC, UmalatDukuev commented on source/max.js
> +            let subarray2 = numbers.slice(0, len - ind);
Да,  извини😄

2023-09-10 16:52 UTC, UmalatDukuev commented on source/max.js
> +            return numbers.slice(0, ind).concat(reversedSubarray);
поправлю

2023-09-10 17:10 UTC, ZhukDmitryOlegovich commented on source/max.js
> +            let subarray2 = numbers.slice(0, len - ind);
Завтра я смогу посмотреть мне думается только уже вечером - сейчас есть ещё наверное два часа - если сейчас будешь править сейчас, то отпишись пж - быстренько всё мне распишешь/поправишь и мы разайдемся с апрувом уже сегодня =)

2023-09-10 17:12 UTC, UmalatDukuev commented on source/max.js
> +            let subarray2 = numbers.slice(0, len - ind);
Я просто не дома уже
А есть ли разница между аппрувом сегодня и завтра?

2023-09-10 17:24 UTC, ZhukDmitryOlegovich commented on source/max.js
> +            let subarray2 = numbers.slice(0, len - ind);
Нет, просто сейчас было время - а так я могу спокойно убрать ноут и пойти своими делами заниматься - спс что написал =)

2023-09-10 17:26 UTC, UmalatDukuev commented on source/max.js
> +            let subarray2 = numbers.slice(0, len - ind);
Хорошо, спасибо, что глянул. Я тогда к завтрашнему вечеру доработаю то, что нужно

2023-09-10 22:01 UTC, UmalatDukuev commented on source/inverse.js
> +	        let reversedSubarray = numbers.slice(ind).reverse();
Да, reverse меняет исходный массив. Поэтому я в начале функции скопировал исходный массив array в массив numbers с помощью slice, чтобы работать не с исходником. Просто ответил это в другом комменте.

2023-09-10 22:16 UTC, ZhukDmitryOlegovich commented on source/inverse.js
> +	        let reversedSubarray = numbers.slice(ind).reverse();
То есть исходный массив array не поменяется, а массив numbers от это строки измениться?

```js
let reversedSubarray = numbers.slice(ind).reverse();
```

2023-09-10 22:39 UTC, UmalatDukuev commented on source/max.js
> +            let subarray2 = numbers.slice(0, len - ind);
1) Если в slice передать отрицательные аргумент n, он скопирует последние n элементов. В коде поправил.
2) Про создание переменных предполагаю, что речь про const. Надеюсь да, тк в коде я поменял.
3)+
4)+
5) Я поправил else так, чтобы использовать не 2 массива, а один, слегка оптимизировал. Думал, может даже получилось бы не разделять на меньше больше нуля, но вроде бы я логично реализовал. Если нет, то не помешает еще подсказка)

2023-09-10 22:48 UTC, ZhukDmitryOlegovich commented on source/max.js
> +			return numbers.slice(0, len+ind).reverse().concat(subarray);
тут можно сделать
```suggestion
			return numbers.slice(0, ind).reverse().concat(subarray);
```
и произойдет тоже самое - https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/slice

и да, к какой мысли я веду - вне зависимости от того ind положительный или отрицательный создаешь два массива `numbers.slice(ind)` и `numbers.slice(0, ind)` и в зависимости от знака `ind` один из массивов переворачиваешь и склеиваешь в том же порядке - вот именно то что я написал буквами я и хочу увидеть в коде

2023-09-10 22:52 UTC, UmalatDukuev commented on source/max.js
> +			return numbers.slice(0, len+ind).reverse().concat(subarray);
да, сейчас попробую

2023-09-10 23:13 UTC, UmalatDukuev commented on source/max.js
> +			return numbers.slice(0, len+ind).reverse().concat(subarray);
Сделал

2023-09-10 23:30 UTC, ZhukDmitryOlegovich commented on source/max.js
> +let numbers = array.slice();
```suggestion
	let numbers = array.slice();
```

2023-09-10 23:31 UTC, ZhukDmitryOlegovich commented on source/max.js
> +		let subarray2 = numbers.slice(0, ind)
const предпочтительнее let ибо явно дает понять будущим разработчикам что переменная не будет изменена и в обратную сторону - использование let вместо const показывает что переменная будет изменена

2023-09-10 23:32 UTC, ZhukDmitryOlegovich commented on source/max.js
> +		const len = numbers.length;
переменная не используется

2023-09-10 23:33 UTC, ZhukDmitryOlegovich commented on source/max.js
> +		}
Сделай чтобы внутри if происходил только реверс того или иного массива, а return шел после него - чтобы показать единую колею данных + это описательно будет проще

2023-09-10 23:35 UTC, ZhukDmitryOlegovich commented on source/max.js
> +	if (ind) {
если хочешь оставить этот if, то сделай ранний return и дальше блок кода без else

то есть из `if (A) { B1,B2,...,return Bn } else { return C }` сделать `if (!A) { return C } B1,B2,...,return Bn`

2023-09-11 11:18 UTC, UmalatDukuev commented on source/inverse.js
> +	        let reversedSubarray = numbers.slice(ind).reverse();
Да, это же вспомогательный массив.  Мы же для изменений его и создали

2023-09-11 11:19 UTC, UmalatDukuev commented on source/inverse.js
> +	        let reversedSubarray = numbers.slice(ind).reverse();
Хотя он объявлен как const

2023-09-11 11:19 UTC, UmalatDukuev commented on source/max.js
> +		}
сделал

2023-09-11 11:19 UTC, UmalatDukuev commented on source/max.js
> +	if (ind) {
сделал

2023-09-11 21:10 UTC, ZhukDmitryOlegovich commented on source/inverse.js
> +	        let reversedSubarray = numbers.slice(ind).reverse();
> https://github.com/frontend-park-mail-ru/homework_2023_2/pull/48#discussion_r1321389396

а это не верно =) массив numbers не поменяется от этой строки - теперь вопрос - почему?)

2023-09-11 21:14 UTC, ZhukDmitryOlegovich requested changes
Поправь то что осталось в открытых комментах (тредах?) выше и вот новое

2023-09-11 21:14 UTC, ZhukDmitryOlegovich commented on source/max.js
> +const inverse = (array, ind) => {
Нужна jsdoc

2023-09-11 21:14 UTC, ZhukDmitryOlegovich commented on source/max.js
> +const inverse = (array, ind) => {
Так как это ДЗ0 - надо добавить проверку что входные данные верны

2023-09-11 21:14 UTC, ZhukDmitryOlegovich commented on source/max.js
> +const inverse = (array, ind) => {
вынеси эту функцию в отдельный файл `source/inverse.js`

2023-09-11 21:16 UTC, UmalatDukuev commented on source/inverse.js
> +	        let reversedSubarray = numbers.slice(ind).reverse();
Тут не поменяется, потому что slice скопирует numbers в reversesSubarray
Но я про другую строчку, в if (!ind) я применяю reverse уже к numbers. И возможно он там изменится

2023-09-11 21:29 UTC, UmalatDukuev commented on source/max.js
> +const inverse = (array, ind) => {
проверить является ли array массивом и является index числом?

2023-09-11 21:30 UTC, UmalatDukuev commented on source/max.js
> +const inverse = (array, ind) => {
кроме новых, я все сделал вроде бы

2023-09-11 21:38 UTC, ZhukDmitryOlegovich commented on source/inverse.js
> +	        let reversedSubarray = numbers.slice(ind).reverse();
> И возможно он там изменится
```js
number.reverse()
```
точно изменит порядок элементов в массиве number

2023-09-11 21:39 UTC, ZhukDmitryOlegovich commented on source/max.js
> +const inverse = (array, ind) => {
> кроме новых, я все сделал вроде бы

раз https://github.com/frontend-park-mail-ru/homework_2023_2/pull/48#discussion_r1320530991 и два https://github.com/frontend-park-mail-ru/homework_2023_2/pull/48#discussion_r1320885739 не сделал

2023-09-11 21:41 UTC, ZhukDmitryOlegovich commented on source/max.js
> +const inverse = (array, ind) => {
да, но index могли не передать + почему бы не переименовать ind в index раз это оно и есть + тебе возможно помогут [дефолтные параметры](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Default_parameters)

2023-09-11 21:48 UTC, UmalatDukuev commented on source/max.js
> +const inverse = (array, ind) => {
ну насчет непереданного index , у меня ж есть проверка if (!ind)
Это не считается или как?
ind переименовал в index
проверки сейчас добавлю

2023-09-11 21:52 UTC, UmalatDukuev commented on source/max.js
> +const inverse = (array, ind) => {
Такие проверки?

![image](https://github.com/frontend-park-mail-ru/homework_2023_2/assets/106022065/ea2109a0-0db1-4eff-aed7-8f16428cfc84)

2023-09-11 21:52 UTC, ZhukDmitryOlegovich commented on source/max.js
> +const inverse = (array, ind) => {
> ну насчет непереданного index , у меня ж есть проверка if (!ind)
Это не считается или как?

```js
inverse([1,2,3], false);
inverse([1,2,3], '');
inverse([1,2,3], null);
```

примеры не корректных записей которые пройду проверку и данные - а должно выбрасывать ошибку

2023-09-11 21:54 UTC, ZhukDmitryOlegovich commented on source/max.js
> +const inverse = (array, ind) => {
> https://github.com/frontend-park-mail-ru/homework_2023_2/pull/48#discussion_r1322108543

нет, надо в начале функции делать проверки на типы и надо выбрасывать ошибки

2023-09-11 21:56 UTC, UmalatDukuev commented on source/max.js
> +const inverse = (array, ind) => {
ну вот я только что залил новую версию.
правильно ли там?
и правильно ли я jsdoc написал?

2023-09-11 22:00 UTC, ZhukDmitryOlegovich commented on source/inverse.js
> +const inverse = (array, index) => {
```suggestion
/**
 * описание функции бла бла бла <-
 * @param {Array} array инвертируемый массив
 * @param {number} index индекс, от(до) которого идет инверсия
 * @returns {Array} возвращаемый массив
 */
const inverse = (array, index) => {
```

2023-09-11 22:00 UTC, UmalatDukuev commented on source/max.js
> +const inverse = (array, ind) => {
> > [#48 (comment)](https://github.com/frontend-park-mail-ru/homework_2023_2/pull/48#discussion_r1322108543)
> 
> нет, надо в начале функции делать проверки на типы и надо выбрасывать ошибки

ну я проверяю index после проверки, что он есть.
поэтому эта проверка типа не в самом начале

2023-09-11 22:00 UTC, ZhukDmitryOlegovich commented on source/max.js
> +const inverse = (array, ind) => {
https://github.com/frontend-park-mail-ru/homework_2023_2/pull/48#discussion_r1322114005

2023-09-11 22:03 UTC, ZhukDmitryOlegovich commented on source/max.js
> +const inverse = (array, ind) => {
> ну я проверяю index после проверки, что он есть.
поэтому эта проверка типа не в самом начале

ты как-то выборочно читаешь что я пишу

https://github.com/frontend-park-mail-ru/homework_2023_2/pull/48#discussion_r1322108616

вот тесты будут проходить, хотя должна возвращаться ошибка + надо выкидывать ошибку (throw)https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError

2023-09-11 22:34 UTC, UmalatDukuev commented on source/max.js
> +const inverse = (array, ind) => {
По-моему поправил проверки. Глянь, пожалуйста

2023-09-11 22:35 UTC, UmalatDukuev commented on source/max.js
> +const inverse = (array, ind) => {
а, только у меня не throw.

2023-09-11 22:38 UTC, UmalatDukuev commented on source/max.js
> +const inverse = (array, ind) => {
вот теперь вроде лучше

2023-09-11 22:39 UTC, ZhukDmitryOlegovich commented on source/max.js
> +const inverse = (array, ind) => {
Если до 2 пришлешь - допроверю, а может и апрувну

2023-09-11 22:40 UTC, UmalatDukuev commented on source/max.js
> +const inverse = (array, ind) => {
Уже прислал

2023-09-11 22:42 UTC, ZhukDmitryOlegovich commented on source/inverse.js
> +	if (typeof(index) === "undefined") {
плохая проверка - в index клади по дефолту 0 (что такое дефолт - тут https://github.com/frontend-park-mail-ru/homework_2023_2/pull/48#discussion_r1322101023), первый if в функции проверяет arra, потом проверяешь index и только после этого начинаешь массивы копировать и тд и тп - сначала данные проверь

+ опять форматирование по бороде пошло - где-то пробелы, где-то табы - настой vs code - он вообще сам все конфиги сохраняет

2023-09-11 22:43 UTC, ZhukDmitryOlegovich commented on source/inverse.js
> +	}
```suggestion
	(index >= 0 ? subarray1 : subarray2).reverse();
```
можно ещё вот такие фокусы делать чтобы код был компактнее =)

2023-09-11 22:45 UTC, ZhukDmitryOlegovich commented on tests/inverse.js
> +		assert.deepEqual(inverse([ 1, 2, 3, 4, 5 ], false), [ 1, 2, 5, 4, 3 ]);
не надо изначальные тесты портить + добавь проверку что при таких входных данных должна выбрасываться ошибка - false не число

2023-09-11 22:55 UTC, ZhukDmitryOlegovich commented on source/max.js
> +const inverse = (array, ind) => {
5 минуточек осталось

2023-09-11 22:59 UTC, UmalatDukuev commented on source/inverse.js
> +	if (typeof(index) === "undefined") {
Вроде все поправил

2023-09-11 23:00 UTC, ZhukDmitryOlegovich commented on tests/inverse.js
> +		assert.deepEqual(inverse([ 1, 2, 3, 4, 5 ], false), [ 1, 2, 5, 4, 3 ]);
https://github.com/frontend-park-mail-ru/homework_2023_2/pull/48/commits/079e7baca465adbf83a276a174d37508995de731 половина успеха - осталось тест добавить

2023-09-11 23:00 UTC, ZhukDmitryOlegovich commented on tests/inverse.js
> +		assert.deepEqual(inverse([ 1, 2, 3, 4, 5 ], false), [ 1, 2, 5, 4, 3 ]);
и продолжим уже после того как я посплю =)

2023-09-11 23:01 UTC, UmalatDukuev commented on source/inverse.js
> +	if (typeof(index) === "undefined") {
Сейчас...
по-моему изменения не пушатся

2023-09-11 23:02 UTC, UmalatDukuev commented on source/inverse.js
> +	if (typeof(index) === "undefined") {
Вот. запушил

2023-09-11 23:04 UTC, UmalatDukuev commented on tests/inverse.js
> +		assert.deepEqual(inverse([ 1, 2, 3, 4, 5 ], false), [ 1, 2, 5, 4, 3 ]);
ахаххахах
Ладно. Доброй ночи

2023-09-12 07:17 UTC, ZhukDmitryOlegovich commented on source/inverse.js
> +    index >= 0 ? subarray1.reverse() : subarray2.reverse();
не, вот так тернарник использовать - это анти паттерн - потому что получается что ты его используешь не чтобы данные вернуть, а не используешь никак что возвращается - сделай я показал

2023-09-12 07:18 UTC, ZhukDmitryOlegovich commented on source/inverse.js
> +    const numbers = array.slice();
получается ты сейчас создаешь копию массива просто так - потому что с numbers ничего плохого (чтобы могло его изменить) не происходит

2023-09-12 07:18 UTC, ZhukDmitryOlegovich commented on source/inverse.js
> +    index >= 0 ? subarray1.reverse() : subarray2.reverse();
https://github.com/frontend-park-mail-ru/homework_2023_2/pull/48#discussion_r1322144220

2023-09-12 07:19 UTC, ZhukDmitryOlegovich commented on tests/inverse.js
> +/* Дополнительные тесты */
нужны тесты не неправильные входные данные

2023-09-12 07:20 UTC, ZhukDmitryOlegovich commented on source/inverse.js
> +    const subarray2 = numbers.slice(0, index)
назови их не 1 и 2 (они ещё в моей логике наоборот названы), а что-то типо "левый"/"правый"

2023-09-12 08:13 UTC, UmalatDukuev commented on source/inverse.js
> +    index >= 0 ? subarray1.reverse() : subarray2.reverse();
> не, вот так тернарник использовать - это анти паттерн - потому что получается что ты его используешь не чтобы данные вернуть, а не используешь никак что возвращается - сделай я показал

У меня там просто ошибку выдавало с твоим вариантом. Попробую ещё раз глянуть

2023-09-12 08:15 UTC, UmalatDukuev commented on source/inverse.js
> +    const numbers = array.slice();
Хорошо

2023-09-12 09:07 UTC, UmalatDukuev commented on source/inverse.js
> +    index >= 0 ? subarray1.reverse() : subarray2.reverse();
Вот это получается с той строчкой. Но я могу написать например const result = (index >= 0 ? subarray1 : subarray2).reverse(); и тогда оно работает. как будто без доп переменной result не получается. Пытаюсь исправить вот 

![image](https://github.com/frontend-park-mail-ru/homework_2023_2/assets/106022065/65b1f779-3586-4dfb-87d6-b4669bf5e1e8)

2023-09-12 09:20 UTC, UmalatDukuev commented on tests/inverse.js
> +/* Дополнительные тесты */
а как правильно написать ожидаемое значения для теста с неправильными входными данными. Он ничего не принимает из того, что я пишу. Тест всегда проваливается
![image](https://github.com/frontend-park-mail-ru/homework_2023_2/assets/106022065/ba6e5da5-a7f7-46e9-ad5b-62eda227e3ff)

2023-09-12 09:20 UTC, UmalatDukuev commented on tests/inverse.js
> +/* Дополнительные тесты */
Кроме вот этих тестов с исключениями и ошибки с тернарником я всё исправил пока что

2023-09-12 16:08 UTC, ZhukDmitryOlegovich requested changes
Вот это - и апрув

2023-09-12 16:08 UTC, ZhukDmitryOlegovich commented on tests/inverse.js
> +		assert.throws(inverse([ 1, 2, 3, 4, 5 ], false), TypeError('Parameter is not a number!'));
```suggestion
		assert.throws(() => inverse([ 1, 2, 3, 4, 5 ], false), TypeError('Parameter is not a number!'));
```
получается вместо того чтобы здесь вызывать и получать ошибку здесь - которую assert.throws перехватить не может, создается функа которая уже в try-catch вызывается внутри и делается проверка

а так - интернет всё знает https://www.google.com/search?q=js+assert.throws

2023-09-12 16:08 UTC, ZhukDmitryOlegovich commented on source/inverse.js
> +    const reversedSubarray = (index >= 0 ? rightSubarray : leftSubarray).reverse();
```suggestion
    (index >= 0 ? rightSubarray : leftSubarray).reverse();
```
нет смысла переменную создавать - она нигде не используется

2023-09-12 16:08 UTC, ZhukDmitryOlegovich commented on source/inverse.js
> + * @returns {array} возвращаемый массив
```suggestion
 * @param {Array} array инвертируемый массив
 * @param {number} index индекс, от(до) которого идет инверсия
 * @returns {Array} возвращаемый массив
```
https://www.google.com/search?q=jsdoc+any+array -> https://stackoverflow.com/questions/14611995/how-to-specify-an-array-of-objects-as-a-parameter-or-return-value-in-jsdoc

2023-09-12 16:08 UTC, ZhukDmitryOlegovich commented on source/inverse.js
> +        throw new TypeError('Parameter is not an array!');
```suggestion
const inverse = (array, index = 0) => {
    if (!Array.isArray(array)) {
        throw new TypeError('Parameter is not an array!');
```
ахахах - я что-то подумал - а почему "входной массив с абстрактными элементами" называется numbers?) давай его в array переименуем =)

2023-09-12 16:08 UTC, ZhukDmitryOlegovich commented on tests/inverse.js
> +		assert.throws(inverse([ 1, 2, 3, 4, 5 ], false), TypeError('Parameter is not a number!'));
+ добавь тест на то что первый аргумент не массив

2023-09-12 16:09 UTC, ZhukDmitryOlegovich commented on source/inverse.js
> +    index >= 0 ? subarray1.reverse() : subarray2.reverse();
очень странно - я вот в ошибку смотрю - и пишет что у number нет slice, а на тернарник никаким образом не ругается

2023-09-12 16:10 UTC, ZhukDmitryOlegovich commented on source/inverse.js
> +    index >= 0 ? subarray1.reverse() : subarray2.reverse();
Как будто ты файл не сохранил или типо того - не совпадает позиция строки с тем какая может быть ошибка

2023-09-12 19:52 UTC, ZhukDmitryOlegovich approved these changes

2023-09-12 19:52 UTC, ZhukDmitryOlegovich commented on source/inverse.js
> + * @returns {array} возвращаемый массив
```suggestion
 * @returns {Array} возвращаемый массив
```

2023-09-13 15:19 UTC, DPeshkoff requested changes
Привет! Поздравляю с переходом на второй семестр)

Классное решение получилось, но у меня есть пара замечаний. Если возникнут вопросы - можешь писать в [Telegram](t.me/DmPesh)

2023-09-13 15:19 UTC, DPeshkoff commented on source/inverse.js
> +/**
А какие ты знаешь режимы кода в JS? Почему выбрал такой?

2023-09-13 15:19 UTC, DPeshkoff commented on source/inverse.js
> + * @returns {array} возвращаемый массив
поддерживаю

2023-09-13 15:19 UTC, DPeshkoff commented on source/inverse.js
> +    if (typeof index !== "number") {
В JS приняты одиночные кавычки, давай поменяем

2023-09-13 15:19 UTC, DPeshkoff commented on source/inverse.js
> + * @param {number} index индекс, от(до) которого идет инверсия
throws в JSDoc

2023-09-13 20:04 UTC, UmalatDukuev commented on source/inverse.js
> +/**
Строгий режим является более безопасным в плане допуска неточностей, т.е. ошибки, которые проигнорировались бы в другом режиме, в этом необходимо исправлять. и в строгом режиме движок js проводит более "радикальную" оптимизацию, что повышает производительность.

Еще есть интерпретируемый(из удобств - позволяет сразу видеть изменения) , компилируемый(компиляция позволяет оптимизировать код) , отладочный, режим разработки, режим чтения.

2023-09-13 20:05 UTC, UmalatDukuev commented on source/inverse.js
> +/**
Привет. Спасибо)

2023-09-13 20:07 UTC, UmalatDukuev commented on source/inverse.js
> +/**
Остальные замечания я вроде исправил, сейчас запушу.

2023-09-14 11:47 UTC, DPeshkoff requested changes

2023-09-14 11:47 UTC, DPeshkoff commented on source/inverse.js
> +/**
Давай сделаем строгий режим

2023-09-15 19:30 UTC, DPeshkoff approved these changes

2023-09-15 19:30 UTC, closed without merging