HW-0
frontend-park-mail-ru/homework_2023_2 pull request #49
Opened 2023-09-08 15:05 UTC by kek-wait-w

Молдованов Алексей WEB-22

2023-09-08 15:24 UTC, ivanstrilets commented
Привет!
Добро пожаловать на курс по фронтенд-разработке 👋
Я буду проверять твое ДЗ-0. Ниже я буду оставлять комментарии по коду. Желательно на них отвечать

2023-09-08 15:26 UTC, ivanstrilets commented
у тебя некорректное название ПРа, пожалуйста ознакомься с правилами оформления

2023-09-08 15:37 UTC, ivanstrilets commented on README.md
> +
давай уберем это отсюда, этой правке тут не место =)

2023-09-08 15:37 UTC, ivanstrilets commented on source/max.js
> +
ты описал функцию anagram в файле которая предназначена для реализации max, пожалуйста раздели логику в по разным файлам

2023-09-08 15:37 UTC, ivanstrilets commented on source/max.js
> +}
соблюдай отступы в строках, так код ментально понятнее

2023-09-08 15:37 UTC, ivanstrilets commented on tests/anagram.js
> +		QUnit.test('Дополнительный тест 1', function (assert) {
Не явное название теста, опиши в строке что тест проверяет

2023-09-08 15:37 UTC, ivanstrilets commented on source/max.js
> +const anagram = (words) => {
давай добавим JSDoc для функции

2023-09-08 17:41 UTC, kek-wait-w commented on README.md
> +
Привет, а мне получается сделать новый ПР, если название некоректное, и можно же на ты обращаться?

2023-09-08 18:46 UTC, kek-wait-w commented on README.md
> +
Все, нашел кнопку)

2023-09-10 19:24 UTC, kek-wait-w commented on source/max.js
> +const anagram = (words) => {
Залил исправления, постарался все подправить

2023-09-11 08:52 UTC, ivanstrilets commented on README.md
> +
давай пустую строчку сверху тоже уберем, это не нужное изменение

2023-09-11 08:52 UTC, ivanstrilets commented on index.html
>  <script src="tests/max.js"></script>
tests/max.js удалил а скрипт оставил подключенным

2023-09-11 08:52 UTC, ivanstrilets commented on source/anagram.js
> +const groups = {};
не хватает отступа строки внутри функции anagram

2023-09-11 14:22 UTC, kek-wait-w commented on source/anagram.js
> +const groups = {};
Все подправил

2023-09-11 19:03 UTC, ivanstrilets approved these changes

2023-09-13 14:34 UTC, DPeshkoff requested changes
Привет! Поздравляю с переходом на второй семестр)

Классное решение получилось, но у меня есть пара замечаний. Если возникнут вопросы - можешь писать в [Telegram](t.me/DmPesh)

2023-09-13 14:34 UTC, DPeshkoff commented on index.html
> -<script src="source/max.js"></script>
Здесь не нужны изменения, давай вернем)

2023-09-13 14:34 UTC, DPeshkoff commented on source/anagram.js
> +'use strict';
Распиши, что делает эта строчка

2023-09-13 14:34 UTC, DPeshkoff commented on source/anagram.js
> +const anagram = (words) => {
А если на входе не массив? А если есть элементы не-строки? Нужны проверки + тесты на некорректный ввод

2023-09-13 14:34 UTC, DPeshkoff commented on source/anagram.js
> +    }
Да и тут лучше заюзать перебирающие методы

2023-09-13 14:34 UTC, DPeshkoff commented on source/anagram.js
> +};
Нужна новая строка в конце файла

2023-09-13 14:34 UTC, DPeshkoff commented on source/max.js
> -
Этот файл нужно вернуть)

2023-09-13 14:34 UTC, DPeshkoff commented on tests/anagram.js
> +		const expected = [];
Здесь не нужны новые переменные, оптимальнее будет в одну строчку при вызове

2023-09-17 11:27 UTC, kek-wait-w commented on source/anagram.js
> +'use strict';
Это установка, которая заставляет код обрабатываться в строгом режиме. Без этой установки код обрабатывается в неограниченном режиме.

2023-09-17 15:52 UTC, DPeshkoff approved these changes

2023-09-17 15:52 UTC, closed without merging