First attempt
frontend-park-mail-ru/homework_2023_2 pull request #50
Opened 2023-09-08 18:57 UTC by Lesnoi3283

2023-09-08 21:59 UTC, SergTyapkin requested changes

2023-09-08 21:59 UTC, SergTyapkin commented on source/minmax.js
> +  let arrToRet = [];
const

2023-09-08 21:59 UTC, SergTyapkin commented on source/minmax.js
> +const getNumbersArr = (str) => {
Нужен JSDoc

2023-09-08 21:59 UTC, SergTyapkin commented on source/minmax.js
> +      arrToRet.push(tmp);
Когда тебе надо преобразовать все элементы одного массива, и сделать таким образом новый массив, используй `Array.map()`, а не `Array.forEach()`

2023-09-08 21:59 UTC, SergTyapkin commented on source/minmax.js
> +    if (!isNaN(tmp)) {
Не забывай, что `isNaN(null) = false`, так что обычно вместе с `isNaN(some_var)` идёт `some_var !== null`. Подумай сам, нужно ли это тут, и может ли `tmp` быть равен `null`

2023-09-08 21:59 UTC, SergTyapkin commented on source/minmax.js
> +  if (typeof numbers === "string") {
Уменьши вложенность. Сделай проверку на то, что есть `number` - не строка, то функция возвращает `null` или выкидывает исключение, и после этого `return;`.

Таким образом весь код после этой проверки не нужно будет заворачивать внутрь блока кода от `if`

2023-09-08 21:59 UTC, SergTyapkin commented on source/minmax.js
> +      return [undefined, undefined];
Мне кажется, лучше два `null`, хотя это уже вопросы религии. 
Есть даже встроенный методы, вроде `Array.find()`, которые если не нашли элемент, возвращают `undefined`

2023-09-08 21:59 UTC, SergTyapkin commented on source/minmax.js
> +    numbersArr.forEach((element) => {
А давай перепишем это через `Array.reduce()`, где `accumulator` будет объектом, который хранит в себе и `min`, и `max`. Это может быть как объект, так и массив из двух элементов - сам подумай, что лучше

2023-09-08 21:59 UTC, SergTyapkin commented on source/minmax.js
> +const minmax = (numbers) => {
Тоже обязательно JSDoc

2023-09-10 11:39 UTC, Lesnoi3283 commented on source/minmax.js
> +    if (!isNaN(tmp)) {
tmp не может быть null, так как str.split() может вернуть пустые строки, но не null. А parseFloat('') возвращает NaN

2023-09-10 11:51 UTC, Lesnoi3283 commented on source/minmax.js
> +      return [undefined, undefined];
'Мне кажется, лучше два null'
По условию задачи сказано undefined)

2023-09-11 09:27 UTC, SergTyapkin commented on source/minmax.js
> +      return [undefined, undefined];
А ой)

2023-09-11 09:31 UTC, SergTyapkin commented on source/minmax.js
> + * @param {str} str - Строка
str - это не тип. Нужен `String`
Ну и в `@returns` тоже надо поправить тип

2023-09-11 09:41 UTC, SergTyapkin commented on source/minmax.js
> +  if (typeof numbers != "string") {
Строгое неравенство

2023-09-11 09:45 UTC, SergTyapkin commented on source/minmax.js
> +    }, [Number.POSITIVE_INFINITY, Number.NEGATIVE_INFINITY]);
Для этих целей лучше использовать `[Infinity, -Infinity]`. Это более читаемо. Сейчас не смысла использовать `Number.POSITIVE_INFINITY` вместо `Infinity`. Просто `Infinity` - это одно из полей глобального объекта `Window` (как и все глобальные переменные в JS), и в ES5 оно было изменяемым. Потому рекомендовалось использовать константы из Number. Теперь же смысла в этом нет, и лучше их не использовать для чистоты кода

2023-09-11 09:49 UTC, SergTyapkin commented on source/minmax.js
> +    (acc, curVal) => {
Эту стрелочную функцию можно переписать короче. 

Смотри, вот это:
```JS
(some) => {
    return {
        my_field: some
    };
};
```
Эквивалентно вот этому:
```JS
(some) => ({
    my_field: some
});
```
В общем скобочки вокруг функции заменяют `return` и это помогает, если ты сразу возвращаешь что-либо, без предварительных многострочных вычислений. Используй это

2023-09-11 16:13 UTC, SergTyapkin requested changes

2023-09-11 16:13 UTC, SergTyapkin commented on source/minmax.js
> + * @returns {(number)[]} - массив чисел Float
Тут не обязательны скобки

2023-09-11 16:13 UTC, SergTyapkin commented on source/minmax.js
> + * @param {String} str - Строка
Если начал везде писать типы с маленькой буквы - пиши везде с маленькой :)

2023-09-11 16:13 UTC, SergTyapkin commented on source/minmax.js
> - * Если строка не содержит чисел - возвращается [undefined, undefined].
А вот эту строчку зря убрал) Она как раз очень хорошо объясняла, почему там может быть undefined. Просто до этого, получается, типизация просто не верная была

2023-09-11 16:13 UTC, SergTyapkin commented on source/minmax.js
> +    ], [Infinity, -Infinity]);
Красотища)

2023-09-11 16:24 UTC, SergTyapkin approved these changes

2023-09-13 14:42 UTC, DPeshkoff requested changes
Привет! Поздравляю с переходом на второй семестр)

Интересное решение получилось, но у меня есть пара замечаний. Если возникнут вопросы - можешь писать в [Telegram](t.me/DmPesh)

Еще нужны тесты - в том числе и на некорректный ввод

2023-09-13 14:42 UTC, DPeshkoff commented on source/minmax.js
> +"use strict";
Распиши, что делает эта строчка

2023-09-13 14:42 UTC, DPeshkoff commented on source/minmax.js
> +  const strs = str.split(" ");
Лучше одиночные кавычки, давай везде поменяем

2023-09-13 14:42 UTC, DPeshkoff commented on source/minmax.js
> +  const arrToRetCleaned = arrToRetDirty.filter((el) => !isNaN(el));
А чем isNaN отличается от Number.isNaN? Почему выбрал именно такой вариант?

2023-09-13 14:42 UTC, DPeshkoff commented on source/minmax.js
> +  if (typeof numbers !== "string") {
Упс! 

![изображение](https://github.com/frontend-park-mail-ru/homework_2023_2/assets/31134795/5afd937a-9f4c-4dbd-a0a1-8d4662f11341)

При этом это валидные строки... непорядок! Давай подумаем, как это починить)

2023-09-13 14:42 UTC, DPeshkoff commented on source/minmax.js
> +    return [undefined, undefined];
Выглядит, как повод выбросить [ошибку](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Error)

2023-09-13 14:42 UTC, DPeshkoff commented on source/minmax.js
> +};
Новая строка в конце файла)

2023-09-13 18:38 UTC, Lesnoi3283 commented on source/minmax.js
> +"use strict";
Это строгий режим кодинга

2023-09-14 11:48 UTC, DPeshkoff requested changes

2023-09-14 11:48 UTC, DPeshkoff commented on source/minmax.js
> +  const arrToRetCleaned = arrToRetDirty.filter((el) => !isNaN(el));
Хочу ответ)

2023-09-14 11:48 UTC, DPeshkoff commented on source/minmax.js
> +  if (typeof numbers !== "string" && !(numbers instanceof String)) {
В  JS одиночные кавычки

2023-09-14 15:23 UTC, Lesnoi3283 commented on source/minmax.js
> +  const arrToRetCleaned = arrToRetDirty.filter((el) => !isNaN(el));
isNan пытается преобразовать полученный аргумент в число, если получилось - вернет false. Если нет - true. Number.isNaN вернет true только для самого значения NaN (для строки тоже будет false). Мне нужно сохранить в массиве все, что является или может являться числом. Хотя после примененной ранее операции parseFloat нет разницы в выборе между isNaN и Number.isNaN, так в массиве будут лежаить либо числа (бесконечность тоже число), либо NaN. Написал isNaN потому что оно просто короче))

2023-09-14 23:03 UTC, DPeshkoff requested changes

2023-09-14 23:03 UTC, DPeshkoff commented on source/minmax.js
> +  const arrToRetCleaned = arrToRetDirty.filter((el) => !isNaN(el));
выглядит как то, что мы можем убрать лишнюю попытку каста под капотом, раз оно уже число)

2023-09-15 05:02 UTC, Lesnoi3283 commented on source/minmax.js
> +  const arrToRetCleaned = arrToRetDirty.filter((el) => !isNaN(el));
Аргумент, сегодня сделаю

2023-09-15 19:31 UTC, DPeshkoff approved these changes

2023-09-15 19:31 UTC, closed without merging