Демирев Никита
frontend-park-mail-ru/homework_2023_2 pull request #51
Opened 2023-09-08 19:41 UTC by NickDemiman

# Вариант 13
*Readme*-файл заменил на файл **варианта**

2023-09-08 20:31 UTC, Kostich31 commented
Привет, добро пожаловать на курс по фронтенд-разработке. Я буду проверять твое ДЗ 0. Ниже будут мои вопросы и комментарии по коду.

2023-09-09 09:50 UTC, Kostich31 requested changes

2023-09-09 09:50 UTC, Kostich31 commented on source/get.js
> +    if (path == '')
Недостаточная проверка входных аргументов. obj может быть только объектом, а path может быть только строкой

2023-09-09 09:50 UTC, Kostich31 commented on source/get.js
> +const get = (obj, path) => {
Нужно добавить JSDoc к функции https://jsdoc.app/about-getting-started.html

2023-09-09 09:50 UTC, Kostich31 commented on source/get.js
> +const get = (obj, path) => {
Забыл добавить режим 'use strict'. Расскажи, для чего он нужен

2023-09-09 09:50 UTC, Kostich31 commented on source/get.js
> +    let pieces = path.split('.').slice(1);
Не самое информативное название для переменной. Может быть больше подойдет listOfProperty? А вместо path, например, pathToProperty

2023-09-09 09:50 UTC, Kostich31 commented on source/get.js
> +    let new_obj = obj;
В данном случае new_obj будет содержать ссылку на obj, что может повлечь изменение входных данных. Нужно сделать глубокое копирование, чтобы избежать этого. https://learn.javascript.ru/object-copy

2023-09-09 09:50 UTC, Kostich31 commented on source/get.js
> +    let new_obj = obj;
В JavaScript принято именовать функции, переменные, классы с использованием camelCase

2023-09-09 09:53 UTC, Kostich31 requested changes

2023-09-09 09:53 UTC, Kostich31 commented on source/get.js
> +    if (path == '.')
Расскажи, в чем разница между == и ===

2023-09-09 11:43 UTC, Kostich31 requested changes

2023-09-09 11:43 UTC, Kostich31 commented on source/get.js
> +}
Не забывай добавлять пустую строку в конце файла

2023-09-09 14:33 UTC, NickDemiman commented on source/get.js
> +    if (path == '.')
## Объекты
- == проверяет ссылки
- === проверяет типы
## Базовые типы
- == приводит разные типы к числовому
- === не приводит разные типы к числовому, из-за чего, если начать сравнивать, например 0 и false - то выдаст false

2023-09-09 14:39 UTC, NickDemiman commented on source/get.js
> +const get = (obj, path) => {
Режим изменяет поведение интерпретатора таким образом, что вместо того чтобы пропускать ошибки, он начинает выбрасывать исключения.

2023-09-09 14:48 UTC, Kostich31 commented on source/get.js
> +    if (path == '.')
не забудь исправить на строгое равенство

2023-09-09 15:27 UTC, Kostich31 requested changes

2023-09-09 15:27 UTC, Kostich31 commented on source/get.js
> +        throw new Error("Неверный тип pathToProperty")
Логичней будет указать TypeError и добавить его к тегу @throws в документации

2023-09-09 16:14 UTC, Kostich31 approved these changes

2023-09-11 00:22 UTC, DPeshkoff requested changes
Привет! Поздравляю с переходом на второй семестр)

Классное решение получилось, но у меня есть пара замечаний. Если возникнут вопросы - можешь писать в [Telegram](t.me/DmPesh)

2023-09-11 00:22 UTC, DPeshkoff commented on README.md
> +# frontend-homework, вариант №13
Вообще можно поменять target branch на `frontend-park-mail-ru:variant-13`, тогда не будет лишних изменений)

2023-09-11 00:22 UTC, DPeshkoff commented on source/get.js
> +    if (typeof object !== 'object')
Давай добавим {} для того, чтобы лучше читалось)

2023-09-11 00:22 UTC, DPeshkoff commented on source/get.js
> +        throw new TypeError("Неверный тип object")
Лайк за TypeError, но в языке обычно используются одиночные кавычки - давай поменяем?)

2023-09-11 00:22 UTC, DPeshkoff commented on source/get.js
> +    if (typeof pathToProperty !== 'string')
Упс! 

![изображение](https://github.com/frontend-park-mail-ru/homework_2023_2/assets/31134795/5afd937a-9f4c-4dbd-a0a1-8d4662f11341)

При этом это валидные строки... непорядок! Давай подумаем, как это починить)

2023-09-11 00:22 UTC, DPeshkoff commented on source/get.js
> +    let splitedPathToProperty = pathToProperty.split('.').slice(1);
Распиши, пожалуйста, почему не const? В чем отличия между let, const и var? Какая специфика?)

2023-09-12 11:50 UTC, DPeshkoff requested changes
Эх, у тебя решение тоже не на той ветке
Это вообще критично, потому что в рабочих проектах ошибка с веткой может привести к плохим последствиям - давай ты вынесешь свое решение в корректную ветку `NickDemiman:variant-13`

2023-09-12 12:01 UTC, NickDemiman commented
> Эх, у тебя решение тоже не на той ветке Это вообще критично, потому что в рабочих проектах ошибка с веткой может привести к плохим последствиям - давай ты вынесешь свое решение в корректную ветку `NickDemiman:variant-13`

Я создал новую ветку, но в пулреквесте я не могу сменить source ветку с мастера на новую, могу поменять только таргет ветку.

2023-09-12 13:35 UTC, NickDemiman commented on source/get.js
> +    if (typeof pathToProperty !== 'string')
исправил

2023-09-12 13:35 UTC, NickDemiman commented on README.md
> +# frontend-homework, вариант №13
поменял

2023-09-13 15:26 UTC, DPeshkoff commented
Давай тогда новый МР создадим)

2023-09-13 18:53 UTC, NickDemiman commented
> Давай тогда новый МР создадим)

Создал новый 
https://github.com/frontend-park-mail-ru/homework_2023_2/pull/62

2023-09-15 19:35 UTC, closed without merging