Крылов Александр
frontend-park-mail-ru/homework_2023_2 pull request #55
Opened 2023-09-10 14:33 UTC by ShelbyKS

2023-09-11 10:28 UTC, GreatFix requested changes
Привет! Welcome to курс по фронтенд-разработке. Я буду проверять твое ДЗ 0.
У меня появились комментарии к коду, описал их здесь.
Можешь отвечать на них тут же, но если что, я доступен в [телеге](https://t.me/FixFive)

2023-09-11 10:28 UTC, GreatFix commented on source/inverse.js
> +const inverse = function(arr, num = 0) {
Давай добавим описание предназначения функции и его параметров с помощью jsdoc

2023-09-11 10:28 UTC, GreatFix commented on source/inverse.js
> +    return num >= 0 ? [...arr.slice(0, num), ...arr.slice(num).reverse()] :
Когда такая длинная строка, тернарный оператор лишь усложняет чтение кода, давай юзнем if

2023-09-11 10:28 UTC, GreatFix commented on source/inverse.js
> +    return num >= 0 ? [...arr.slice(0, num), ...arr.slice(num).reverse()] :
Круто, что ты заюзал встроенные методы массивов. Но заданием является повторение реализация этого метода (reverse), поэтому давай ты не будешь его использовать, а напишешь свою логику

2023-09-11 10:28 UTC, GreatFix commented on source/inverse.js
> +const inverse = function(arr, num = 0) {
А что будет, если первым параметров передать {} или null ? Давай добавим проверку входных параметров и выброс исключений, если они некорректны

2023-09-11 10:28 UTC, GreatFix commented on tests/inverse.js
>  });
Давай добавим тесты на некорректные параметры

2023-09-11 10:28 UTC, GreatFix commented on source/inverse.js
> +const inverse = function(arr, num = 0) {
function ты уже заюзал, хорошо, давай теперь теперь попробуем сделать стрелочной функцией

2023-09-18 09:17 UTC, GreatFix requested changes
Круто, давай еще доработаем

2023-09-18 09:17 UTC, GreatFix commented on source/inverse.js
> +    } else {
else не обязателен в данном случае. Можешь просто напсиать 
if() {
...
return
}
.....
return;

2023-09-18 09:17 UTC, GreatFix commented on tests/inverse.js
> +  		assert.throws(function() { inverse([1], 'some string'); }, TypeError('Второй аргумент должен быть числом'));
Давай добавим тест с вещественным числом в 2 параметре

2023-09-18 09:17 UTC, GreatFix commented on source/inverse.js
> + * @throws {Error} - Если первый аргумент не является массивом или второй аргумент не является числом.
В коде бросается ошибка TypeError , а здесь написано Error

2023-09-18 09:17 UTC, GreatFix commented on source/inverse.js
> +
Давай добавим быстрый возврат результата для случаев, когда не требуются сложная логика. 
Например:
- Все значения массива одинаковы
- Длина массива 1

2023-09-18 09:17 UTC, GreatFix commented on source/inverse.js
> +    if (!(typeof num === 'number' || num instanceof Number)){
А как быть в тех случаях, когда num больше, чем длина массива?

2023-09-18 11:00 UTC, ShelbyKS commented on source/inverse.js
> +    if (!(typeof num === 'number' || num instanceof Number)){
Благодаря методам массивов ошибки не происходит. Есть тест, который это проверяет

2023-09-18 11:07 UTC, GreatFix commented on source/inverse.js
> +    if (!(typeof num === 'number' || num instanceof Number)){
Интересует ли нас только ошибка или стоит задумываться об оптимизации? Например, сколько будет выполняться функция, если передать num=1000000000

2023-09-18 13:46 UTC, GreatFix requested changes
Осталось отрефакторить

2023-09-18 13:46 UTC, GreatFix commented on source/inverse.js
> +    if(arr.length === 1) {
Выполнится ли это условие когда нибудь, после того, как не выполнится верхнее ?

2023-09-18 13:46 UTC, GreatFix commented on source/inverse.js
> +        return arr
Давай проставим ; везде, где пропущено

2023-09-18 13:46 UTC, GreatFix commented on source/inverse.js
> +        return arr.slice(0, num).concat(arr.slice(num).reduce((accumulator, value) => {
Ну результат переворачивания можно сохранить сначала в переменную, чтобы лучше читалось

2023-09-18 13:50 UTC, ShelbyKS commented on source/inverse.js
> +    if(arr.length === 1) {
нет, поставлю выше

2023-09-18 13:54 UTC, ShelbyKS commented on source/inverse.js
> +    if (!((typeof num === 'number' || num instanceof Number) && (num % 1 === 0 || Number.isInteger(num)))) {
да, одна лишняя проверка на целостность

2023-09-18 13:57 UTC, ShelbyKS commented on source/inverse.js
> +        return arr.slice(0, num).concat(arr.slice(num).reduce((accumulator, value) => {
Ты, кажется, наоборот просил избегать создания лишних переменных

"Попробуй с помощью методова массивов избавится от использования цикла for и отдельной переменной"

2023-09-18 14:07 UTC, GreatFix commented on source/inverse.js
> +        return arr.slice(0, num).concat(arr.slice(num).reduce((accumulator, value) => {
Там было "Отдельной переменной"
А я прошу просто записать результат в переменную;

Память тратится одинаково(хотя это меня сильно не беспокоит никогда в вебе), а вот читаемость гораздо лучше

2023-09-18 16:40 UTC, GreatFix commented on source/inverse.js
> +        return arr.slice(0, num).concat(arr.slice(num).reduce((accumulator, value) => {
Ну как ты мог заметить, ничего не изменилось, просто появилась переменная. Я имел в виду вынести именно результат переворачивания, так : 
```
 const reversed = arrNums.slice(num).reduce((accumulator, value) => {
            return [value, ...accumulator];
        }, []);
return arrNums.slice(0, num).concat(reversed);
```

2023-09-18 16:42 UTC, GreatFix commented on source/inverse.js
> +        return arr.slice(0, num).concat(arr.slice(num).reduce((accumulator, value) => {
Еще лучше, если: 
```
const reversed = numbers.slice(reverseIndex).reduce((acc, number) =>  ([number, ...acc]), []);
return numbers.slice(0, reverseIndex).concat(reversed);
```

2023-09-18 16:45 UTC, GreatFix commented on source/inverse.js
> +        return arr.slice(0, num).concat(arr.slice(num).reduce((accumulator, value) => {
Если бы требовалось оптимизировать, можно было бы так, чтобы массив каждый раз не создавать: 
```
const reversed = numbers.slice(reverseIndex).reduce((acc, number) =>  {
    acc.push(number);
    return acc
}, []);

return numbers.slice(0, reverseIndex).concat(reversed);
```

Хотя для оптимизации лучше юзать обычный for цикл))

2023-09-18 16:51 UTC, GreatFix commented on source/inverse.js
> +        return arr.slice(0, num).concat(arr.slice(num).reduce((accumulator, value) => {
Стоп, с названием numbers я не прав, почему  все время то думал, что это массив чисел. Верни тогда arr, как было, соре)

2023-09-19 14:13 UTC, DPeshkoff requested changes
Привет! Поздравляю с переходом на второй семестр)

Хорошее решение получилось, но у меня есть пара замечаний. Если возникнут вопросы - можешь писать в [Telegram](t.me/DmPesh)

2023-09-19 14:13 UTC, DPeshkoff commented on source/inverse.js
> +/**
В каком режиме работает этот код? Какие режимы ты знаешь, в чем их отличия? Распиши

2023-09-19 14:13 UTC, DPeshkoff commented on source/inverse.js
> +
Здесь не нужна пустая строка

2023-09-19 17:15 UTC, ShelbyKS commented on source/inverse.js
> +/**
Мой код работает в «грязном» режиме (не строгом). 
В таком режиме синтаксические правила языка не так строги, а когда происходят некоторые ошибки, система никак не оповещает о них пользователя. Это способно привести к неожиданным результатам выполнения кода.

В строгом режиме исключение будет выдано в следующих случаях: 

- попытка присваивания значения свойству, предназначенному только для чтения, вроде некоего неперезаписываемого глобального свойства;
- Попытка записи значения в свойство, у которого есть лишь геттер;
- Попытка записи чего-либо в свойство нерасширяемого объекта.
- Строгий режим запрещает назначать объекту свойства с одинаковыми именами. 
- Строгий режим включается автоматически при использовании import export а также в классах

2023-09-19 17:16 UTC, ShelbyKS commented on source/inverse.js
> +
Убрал

2023-09-19 19:48 UTC, DPeshkoff commented on source/inverse.js
> +/**
Давай сделаем строгий)

2023-09-19 20:05 UTC, ShelbyKS commented on source/inverse.js
> +/**
добавил

2023-09-19 20:10 UTC, DPeshkoff approved these changes

2023-09-19 20:10 UTC, closed without merging