Makarenko Gleb
frontend-park-mail-ru/homework_2023_2 pull request #56
Opened 2023-09-10 22:16 UTC by Glibusss

2023-09-10 22:28 UTC, Glibusss commented on source/tree.js
> +const invalidNumberValue = (value) =>
Коли я всё сломал, напишу заново.
Arrow function - более современное объявление функции из ES6. У него нельзя переопределить this, оно всегда зависит от контекста выполнения в отличии от обычного function declaration. Также если мы сразу возвращаем изначение, то в arrow function не требуется писать return

2023-09-10 22:34 UTC, Glibusss commented on source/tree.js
> +/**
Ну и естественно по поводу strict mode. Здесь мне его не обязательно использовать(хоть он и позволяет писать более современный код).
Ограничивает следующие вещи: 
1)Hoisting переменных запрещен
2)Параметры функций и свойства объекта запрещено называть одинаково
3)Нельзя перезаписывать значения, предназначенные для чтения (arguments, NaN etc)
4)Зарезервированными словами нельзя пользоваться

Ну и напоследок - "Тихие ошибки" превращаются в исключения и останавливают работу кода

2023-09-10 22:34 UTC, Glibusss commented on source/tree.js
> +/**
А необязательно использовать потому что этого всего нет

2023-09-10 22:57 UTC, DPeshkoff commented on source/tree.js
> +const invalidNumberValue = (value) =>
Не стоит использовать force push - он перезатирает историю в origin-ветке. Достаточно просто запушить новые коммиты в ту же ветку, не затирая старые - тогда все будет работать хорошо, pull request сам обновится, потому что он всегда смотрит в origin-ветку.

2023-09-11 05:55 UTC, Glibusss commented on source/tree.js
> +const invalidNumberValue = (value) =>
Теперь буду знать

2023-09-11 10:12 UTC, LDK28 commented on source/tree.js
> +/**
Как бы да и как бы нет, use strict помогает избежать ошибок, которые можно было совершить в старых версиях js. Даже если ты уверен, что у тебя их нет, они все равно могут закрасться, поэтому надо все равно писать use strict вначале скриптов :)

2023-09-11 10:16 UTC, Glibusss commented on source/tree.js
> +/**
Сделал

2023-09-11 10:19 UTC, LDK28 commented on source/tree.js
> + * Функция проверяет, является ли переданный аргумент невалидным числом.
Что значит "невалидное число"?

2023-09-11 10:19 UTC, LDK28 commented on tests/tree.js
> -QUnit.module('Тестируем функцию tree', function () {
Как-то неправильно добавились изменения, код не менялся, а изменения подсвечиваются. Такое бывает, когда перезатираешь коммиты много раз. В целом, не оч страшно, но попробуй пофиксить

2023-09-11 10:26 UTC, Glibusss commented on source/tree.js
> + * Функция проверяет, является ли переданный аргумент невалидным числом.
Расписал

2023-09-11 10:27 UTC, Glibusss commented on tests/tree.js
> -QUnit.module('Тестируем функцию tree', function () {
Да это из-за форматирования по-моему

2023-09-11 15:07 UTC, LDK28 requested changes

2023-09-11 15:07 UTC, LDK28 commented on tests/tree.js
> -QUnit.module('Тестируем функцию tree', function () {
Можно попробовать что-то такое https://stackoverflow.com/questions/17195861/undo-git-update-index-assume-unchanged-file
Давай пофиксим это, чтобы потом не было лишних вопросов

2023-09-11 17:15 UTC, Glibusss commented on tests/tree.js
> -QUnit.module('Тестируем функцию tree', function () {
Наконец-то пофиксил

2023-09-12 08:58 UTC, LDK28 approved these changes

2023-09-13 15:24 UTC, DPeshkoff requested changes
Привет! Поздравляю с переходом на второй семестр)

Интересное решение получилось, но у меня есть пара замечаний. Если возникнут вопросы - можешь писать в [Telegram](t.me/DmPesh)

2023-09-13 15:24 UTC, DPeshkoff commented on source/tree.js
> +"use strict";
Распиши, что делает эта строчка?

2023-09-13 15:24 UTC, DPeshkoff commented on source/tree.js
> +  if (invalidNumberValue(finalLength) || typeof line !== "string") return "";
1) в JS приняты одиночные кавычки
2) Упс! 

![изображение](https://github.com/frontend-park-mail-ru/homework_2023_2/assets/31134795/5afd937a-9f4c-4dbd-a0a1-8d4662f11341)

При этом это валидные строки... непорядок! Давай подумаем, как это починить)
3) Нужно разнести на новую строчку и обернуть в {}
4) Выглядит как кейс для выброса [ошибки](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Error)

2023-09-13 15:24 UTC, DPeshkoff commented on source/tree.js
> +const myPadStart = (line, finalLength, symbolToAdd = " ") => {
А зачем нужна эта функция? У строк есть такие методы

2023-09-13 15:24 UTC, DPeshkoff commented on source/tree.js
> +  }
Кто такой этот цикл while)
Есть же перебирающие методы

2023-09-13 15:24 UTC, DPeshkoff commented on source/tree.js
> +const myPadEnd = (line, finalLength, symbolToAdd = " ") => {
И этот [есть](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/String)

2023-09-13 15:24 UTC, DPeshkoff commented on source/tree.js
> +    myRepeat(" ", height - 2) + "|" + myRepeat(" ", height - 2) + "\n";
Тут тоже можно перебирающими методами

2023-09-13 15:24 UTC, DPeshkoff commented on source/tree.js
> +  !value || !isFinite(value) || isNaN(value);
1) isFinite уже проверяет на NaN
2) Распиши, чем отличаются Number.isFinite от isFinite и Number.isNaN от isNaN и почему ты выбрал именно эти?

2023-09-13 16:01 UTC, LDK28 commented on source/tree.js
> +const myPadEnd = (line, finalLength, symbolToAdd = " ") => {
> И этот [есть](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/String)

Это я погорячился, и предложил написать свою реализацию

2023-09-13 16:02 UTC, LDK28 commented on source/tree.js
> +const myPadStart = (line, finalLength, symbolToAdd = " ") => {
> А зачем нужна эта функция? У строк есть такие методы

Это я погорячился, и предложил написать свою реализацию

2023-09-13 17:13 UTC, Glibusss commented on source/tree.js
> +const myPadStart = (line, finalLength, symbolToAdd = " ") => {
Так а мне по итогу что делать?)

2023-09-13 17:17 UTC, Glibusss commented on source/tree.js
> +  !value || !isFinite(value) || isNaN(value);
С isNan нехорошо получилось, согласен
Но выбрал глобальный isFinite потому что Number.isFinite не преобразует значение в число, но нам это не нужно т.к. может быть подана строка, которая после преобразования является числом, а не NaN

2023-09-13 17:17 UTC, Glibusss commented on source/tree.js
> +  !value || !isFinite(value) || isNaN(value);
Аналогичная ситуация у isNaN

2023-09-13 17:23 UTC, Glibusss commented on source/tree.js
> +"use strict";
Ну эта директива "включает" строгий режим.
Сейчас это вроде как "стандарт".

Он позволяет обезопасить себя от ошибок которые могут возникнуть при
Использовании переменных до их объявления, удалении неудаляемых свойств объекта, неправильном использовании зарезервированных слов, одинаковом названии 2 и более параметров функции/свойств объекта, ну и "тихие" ошибки становятся исключением 

Позволяет писать более современный код, ну и избегать косяков, которые, возможно закрадутся в приложение

2023-09-13 17:38 UTC, Glibusss commented on source/tree.js
> +  if (invalidNumberValue(finalLength) || typeof line !== "string") return "";
Нашел очень элегантное решение

2023-09-13 17:56 UTC, Glibusss commented on source/tree.js
> +const myPadEnd = (line, finalLength, symbolToAdd = " ") => {
Что мне делать по итогу: оставить и сделать с перебирающими методами? Или в tree цепочку методов?

2023-09-14 11:51 UTC, DPeshkoff approved these changes

2023-09-14 11:51 UTC, closed without merging