Variant 19
frontend-park-mail-ru/homework_2023_2 pull request #57
Opened 2023-09-11 16:24 UTC by M0rdovorot

Илларионов Сергей WEB-21

2023-09-14 11:59 UTC, johnSamilin commented
Привет, добро пожаловать на курс по фронтенд-разработке. Я буду проверять твое ДЗ 0.
Если у меня появятся комментарии к коду, то я опишу их здесь. Можешь отвечать на них тут же, а чтобы что-то уточнить - [телеграм](https://t.me/WatasheeBaka)

2023-09-15 06:15 UTC, johnSamilin commented
Старайся всегда писать осмысленные сообщения для коммитов, так даже тебе самому будет проще понять, что в нем сделано

2023-09-15 06:58 UTC, johnSamilin requested changes

2023-09-15 06:58 UTC, johnSamilin commented on source/sorting.js
> +function sorting(plainArray, nameArray) {
Допиши, пожалуйста, JSDoc для функции

2023-09-15 06:58 UTC, johnSamilin commented on source/sorting.js
> +      console.log(key in item);
console.log стоит убирать, если он служит целям отладки. в консоли должны быть только важные сообщения

2023-09-15 06:58 UTC, johnSamilin commented on source/sorting.js
> +    for (let key of nameArray) {
это очень сложный алгоритм. проверку на то, что элемент есть в массиве, можно выполнить и с помощью других способов. например, специального метода массива

2023-09-15 06:58 UTC, johnSamilin commented on source/sorting.js
> +  if (!nameArray.reduce((res, current) => {
здесь очень много лишних итераций. эти проверки можно провести в теле предыдущего цикла (или даже объединить все три (reduce, reduce и sort) в один)

2023-09-15 06:58 UTC, johnSamilin commented on source/sorting.js
> +      if (a[name] < b[name]) return 0;
кажется, здесь должно быть -1

2023-09-15 06:58 UTC, johnSamilin commented on source/sorting.js
> +      if (a[name] == b[name]) continue;
а здесь - 0

2023-09-16 12:49 UTC, M0rdovorot commented on source/sorting.js
> +function sorting(plainArray, nameArray) {
Дописал

2023-09-16 12:49 UTC, M0rdovorot commented on source/sorting.js
> +      console.log(key in item);
Случайно оставил, убрал

2023-09-16 12:49 UTC, M0rdovorot commented on source/sorting.js
> +      if (a[name] < b[name]) return 0;
Исправил

2023-09-16 12:51 UTC, M0rdovorot commented on source/sorting.js
> +      if (a[name] == b[name]) continue;
Здесь должно быть continue, т.к. если у объектов совпадают одни параметры по именам свойств, это не значит, что они равны, надо проверить их по остальным именам

2023-09-16 12:52 UTC, M0rdovorot commented on source/sorting.js
> +    for (let key of nameArray) {
Переделал

2023-09-16 21:18 UTC, johnSamilin commented on source/sorting.js
> +      if (a[name] == b[name]) continue;
справедливо :)

2023-09-16 21:21 UTC, johnSamilin commented on source/sorting.js
> +      if (!key in item) {
для большей ясности лучше добавить скобки: ```if (!(key in item))```

2023-09-16 21:45 UTC, M0rdovorot commented on source/sorting.js
> +      if (!key in item) {
Сделал

2023-09-18 16:49 UTC, DPeshkoff requested changes
Привет! Поздравляю с переходом на второй семестр)

Интересное решение получилось, но у меня есть пара замечаний. Если возникнут вопросы - можешь писать в [Telegram](t.me/DmPesh)

2023-09-18 16:49 UTC, DPeshkoff commented on source/sorting.js
> +    }
Вложенные циклы... жуть, давай заюзаем перебирающие методы языка - у нас ведь массив

2023-09-18 16:49 UTC, DPeshkoff commented on source/sorting.js
> +    }
тут тоже страшно

2023-09-18 16:49 UTC, DPeshkoff commented on source/sorting.js
> +function sorting(plainArray, nameArray) {
нужна валидация и тесты на некорректный ввод

2023-09-18 16:49 UTC, DPeshkoff commented on source/sorting.js
> +'use strict';
распиши, что делает эта строчка

2023-09-19 12:41 UTC, M0rdovorot commented on source/sorting.js
> +    }
Я так и не придумал, как можно упростить эту конструкцию. Я переделал на перебирающие методы, но осталось все равно то же самое. По ощущениям, что тут в любом случае необходим вложенный цикл, а со всякими другими методами выглядеть это будет не лучше.

2023-09-19 14:20 UTC, DPeshkoff requested changes

2023-09-19 14:20 UTC, DPeshkoff commented on index.html
> +<script src="source/sorting.js"></script>
Здесь не нужны изменения

2023-09-19 14:20 UTC, DPeshkoff commented on source/sorting.js
> +    plainArray.some(item => {return typeof item != "object"}) ||
В однострочных функциях можно без {} и return - оно сработает само

2023-09-19 14:20 UTC, DPeshkoff commented on source/sorting.js
> +    throw new TypeError("Wrong input")
Не забывай про точки с запятой! Несмотря на то, что парсер умеет автоматически их проставлять - иногда это приводит к странным результатам. 

<details><summary>Каким?</summary>
<p>
К примеру, тривиальный и понятный код:

![изображение](https://github.com/frontend-park-mail-ru/homework_2023_2/assets/31134795/3d22e9a8-baee-4bfb-886a-b4dfe665364a)

Внезапно падает:

![изображение](https://github.com/frontend-park-mail-ru/homework_2023_2/assets/31134795/582afa37-106b-4330-acaf-6a622c1cda61)

Почему так происходит, думаю, наглядно видно по тексту ошибки - он считает `[3]` частью `s`. Если при этом поставить ;, то код магически начинает работать)

![изображение](https://github.com/frontend-park-mail-ru/homework_2023_2/assets/31134795/9210ce09-d52b-40aa-9731-dd12424c685b)
</p>
</details> 

Давай везде проставим точки с запятой)

2023-09-19 14:20 UTC, DPeshkoff commented on source/sorting.js
> +    nameArray.some(name => {return typeof name != "string"})) {
![изображение](https://github.com/frontend-park-mail-ru/homework_2023_2/assets/31134795/5afd937a-9f4c-4dbd-a0a1-8d4662f11341)

При этом это валидные строки... непорядок! Давай подумаем, как это починить)

2023-09-19 14:20 UTC, DPeshkoff commented on source/sorting.js
> +  if (nameArray.length == 0 || plainArray.length == 0) return plainArray;
В {} и с переносом на новую строчку

Проверки строгие должны быть везде)

2023-09-19 14:20 UTC, DPeshkoff commented on source/sorting.js
> +  console.log(typeof plainArray, typeof nameArray)
Это лишнее

2023-09-19 14:20 UTC, DPeshkoff commented on source/sorting.js
> +    for (let name of nameArray) {
Здесь можно перебирающим, в этом будет упрощение для чтения, как мне кажется)

2023-09-19 14:20 UTC, DPeshkoff commented on tests/sorting.js
> +		}, TypeError("Wrong input"))
А если на входе вообще не массив?

2023-09-19 22:47 UTC, M0rdovorot commented on source/sorting.js
> +function sorting(plainArray, nameArray) {
Функцию можно объявить несколькими способами: 
- FD (function declaration). В отличие от других такую функцию можно вызвать в той же области видимости до ее объявления. Синтаксис: function идентификатор (параметры) {тело функции}
- FE (function expression) или анонимная функция. Ее объявляют как часть какого-либо выражения. Синтаксис: function (параметры) {тело функции}
- NFE (named fucntion expression). Синтаксис такой же как и FD. Отличие от FE заключается в том, что может обращаться к себе при рекурсивном вызове
- AF (Arrow function) или стрелочная функция. Отличие от предыдущих заключается в том какое значение получает ключевое слово this. В стрелочной функции this получит значение окружающей области видимости, в других же функциях оно получит значение в зависимости от контекста.
Такую функцию я использовал, потому что она нужна мне в глобальной области видимости, чтобы использовать ее в другом файле. А значение this меня не волнует, т.к. не использую его

2023-09-19 22:51 UTC, M0rdovorot commented on source/sorting.js
> +    for (let name of nameArray) {
Сделал

2023-09-19 22:54 UTC, M0rdovorot commented on tests/sorting.js
> +		}, TypeError("Wrong input"))
Выше был тест, где initial = 9

2023-09-19 22:54 UTC, M0rdovorot commented on source/sorting.js
> +  console.log(typeof plainArray, typeof nameArray)
Забыл убрать)

2023-09-19 22:54 UTC, M0rdovorot commented on source/sorting.js
> +  if (nameArray.length == 0 || plainArray.length == 0) return plainArray;
Исправил

2023-09-19 22:54 UTC, M0rdovorot commented on source/sorting.js
> +    nameArray.some(name => {return typeof name != "string"})) {
Исправил

2023-09-19 22:55 UTC, M0rdovorot commented on source/sorting.js
> +    throw new TypeError("Wrong input")
Исправил

2023-09-19 22:55 UTC, M0rdovorot commented on source/sorting.js
> +    plainArray.some(item => {return typeof item != "object"}) ||
Исправил

2023-09-19 22:55 UTC, M0rdovorot commented on source/sorting.js
> +  if (plainArray == null || nameArray == null || typeof plainArray != "object" || typeof nameArray != "object" ||
Исправил

2023-09-20 11:20 UTC, DPeshkoff requested changes

2023-09-20 11:20 UTC, DPeshkoff commented on source/sorting.js
> +function sorting(plainArray, nameArray) {
sorting тоже лучше стрелочной - там тоже не нужен this

2023-09-20 21:37 UTC, DPeshkoff approved these changes

2023-09-20 21:37 UTC, closed without merging