Спирин Михаил Variant 9
frontend-park-mail-ru/homework_2023_2 pull request #58
Opened 2023-09-11 18:01 UTC by Jarosin

Спирин Михаил Павлович

2023-09-14 12:01 UTC, johnSamilin commented
Привет, добро пожаловать на курс по фронтенд-разработке. Я буду проверять твое ДЗ 0.
Если у меня появятся комментарии к коду, то я опишу их здесь. Можешь отвечать на них тут же, а чтобы что-то уточнить - [телеграм](https://t.me/WatasheeBaka)

2023-09-15 07:22 UTC, johnSamilin commented
Поправь, пожалуйста, название PR. Оно должно содержать имя и фамилию

2023-09-15 09:42 UTC, johnSamilin requested changes

2023-09-15 09:42 UTC, johnSamilin commented on source/anagram.js
> +let countLetters = (word) => {
Добавь, пожалуйста, JSDoc для всех функций

2023-09-15 09:42 UTC, johnSamilin commented on source/anagram.js
> +    //word = word.toLowerCase();
комментарии лучше убирать совсем, если только они здесь не служат для какой-то определенной цели. в таком случае нужно комментировать, почему они оставлены

2023-09-15 09:42 UTC, johnSamilin commented on source/anagram.js
> +    let letterCount = [];
скажи пожалуйста, а почему эта переменная объявлена как let?

2023-09-15 09:42 UTC, johnSamilin commented on source/anagram.js
> +        letterCount[word[i]] = letterCount[word[i]] + 1 || 1;
у letterCount неправильный тип. она объявлена как массив, а используется как объект

2023-09-15 09:42 UTC, johnSamilin commented on source/anagram.js
> +            return false;
классно, что ты используешь тут ранний выход

2023-09-15 09:42 UTC, johnSamilin commented on source/anagram.js
> +    if (words === null)
а как же другие типы? например, что будет, если аргументом придет число или boolean?

2023-09-15 09:42 UTC, johnSamilin commented on source/anagram.js
> +    words.sort();
а зачем их сортировать и по какому принципу?

2023-09-15 09:42 UTC, johnSamilin commented on source/anagram.js
> +    for (let i = 0; i < words?.length; i++) {
возможно здесь подошел бы forEach или reduce, как ты считаешь?

2023-09-15 09:42 UTC, johnSamilin commented on source/anagram.js
> +        if (words[i] == null) {
здесь тоже нужна более широкая проверка

2023-09-15 09:42 UTC, johnSamilin commented on source/anagram.js
> +                words[j] = null;
нельзя мутировать входные данные. это может привести к неожиданным последствиям. если действительно нужно удалять уже проверенное слово, то стоит скопировать words в локальную переменную и работать уже с ней

2023-09-15 16:01 UTC, Jarosin commented on source/anagram.js
> +let countLetters = (word) => {
Добавил документацию

2023-09-15 16:01 UTC, Jarosin commented on source/anagram.js
> +    //word = word.toLowerCase();
Убрал ненужные комменты

2023-09-15 16:07 UTC, Jarosin commented on source/anagram.js
> +    let letterCount = [];
Let по scope'у меньше, чем var, что однозначно плюс, ибо эта переменная снаружи нигде не используется. 
Const не подходит так как это не константа.

2023-09-15 16:07 UTC, Jarosin commented on source/anagram.js
> +        letterCount[word[i]] = letterCount[word[i]] + 1 || 1;
Поправил

2023-09-15 16:08 UTC, Jarosin commented on source/anagram.js
> +    if (words === null)
Добавил проверку на тип в runtime

2023-09-15 16:12 UTC, Jarosin commented on source/anagram.js
> +    words.sort();
![image](https://github.com/frontend-park-mail-ru/homework_2023_2/assets/52870557/fb306512-7b19-449e-a079-561b2a5da118)
Указано в задании. Полагаю, что имеется в виду лексикографический порядок(?) Плюс это упрощает написание тестов(пропадает зависимость от изначального порядка слов)

2023-09-15 16:14 UTC, Jarosin commented on source/anagram.js
> +    for (let i = 0; i < words?.length; i++) {
Насколько я понимаю, ни foreach, ни reduce не позволяют мне менять массив по которому я итерируюсь, из-за чего я не могу помечать уже проверенные слова.

2023-09-15 16:14 UTC, Jarosin commented on source/anagram.js
> +        if (words[i] == null) {
Добавил

2023-09-15 16:15 UTC, Jarosin commented on source/anagram.js
> +                words[j] = null;
Добавил копирование

2023-09-15 16:16 UTC, Jarosin commented on source/anagram.js
> +            return false;
:3

2023-09-16 21:30 UTC, johnSamilin requested changes

2023-09-16 21:30 UTC, johnSamilin commented on source/anagram.js
> + * @returns {array|string}
для возвращаемого значения тоже нужно описание

2023-09-16 21:30 UTC, johnSamilin commented on source/anagram.js
> +    word = word.toLowerCase()
мутирование агрумента все еще осталось

2023-09-16 21:30 UTC, johnSamilin commented on source/anagram.js
> +    let letterCount = [];
это константа, потому что нигде не переназначается. добавлять элементы в массив, объявленный как const или поля в объект, ничего не помешает. зато ты точно сможешь быть уверен в том, что нигде в коде нет ее переназначения

2023-09-16 21:30 UTC, johnSamilin commented on source/anagram.js
> + * @param {?string} secondWord
еще в JSDoc добавляется @throws с описанием ошибки и условий ее появления

2023-09-16 21:30 UTC, johnSamilin commented on source/anagram.js
> +    for (let i = 0; i < words?.length; i++) {
так как ты копируешь inputWords в локальную переменную, ты уже можешь его менять как угодно

2023-09-17 15:30 UTC, Jarosin commented on source/anagram.js
> + * @returns {array|string}
Добавил

2023-09-17 15:30 UTC, Jarosin commented on source/anagram.js
> +    let letterCount = [];
Справедливо, пробежался по коду и расставил конст, где смог

2023-09-17 15:33 UTC, Jarosin commented on source/anagram.js
> +    word = word.toLowerCase()
Исправил

2023-09-17 15:47 UTC, Jarosin commented on source/anagram.js
> + * @param {?string} secondWord
Добавил

2023-09-17 16:13 UTC, Jarosin commented on source/anagram.js
> +    for (let i = 0; i < words?.length; i++) {
Справедливо, заменил for на foreach

2023-09-18 06:55 UTC, johnSamilin requested changes

2023-09-18 06:55 UTC, johnSamilin commented on source/anagram.js
> +    if (!Array.isArray(inputWords) || typeof inputWords[0] !== "string") {
а почему только первый элемент должен быть строкой?

2023-09-18 06:55 UTC, johnSamilin commented on source/anagram.js
> +    let anagramGroup = [];
anagramGroup тоже константа

2023-09-18 09:27 UTC, Jarosin commented on source/anagram.js
> +    if (!Array.isArray(inputWords) || typeof inputWords[0] !== "string") {
Забыл, что массивы не обязаны хранить один тип. Добавил проверку в foreach

2023-09-18 09:29 UTC, Jarosin commented on source/anagram.js
> +    let anagramGroup = [];
anagramGroup присваивается пустой массив на 99 строке

2023-09-18 17:23 UTC, Jarosin commented on source/anagram.js
> +    if (!Array.isArray(inputWords) || typeof inputWords[0] !== "string") {
Заменил for each на every

2023-09-18 18:37 UTC, johnSamilin approved these changes

2023-09-19 14:25 UTC, DPeshkoff requested changes
Привет! Поздравляю с переходом на второй семестр)

Классное решение получилось, но у меня есть пара замечаний. Если возникнут вопросы - можешь писать в [Telegram](t.me/DmPesh)

2023-09-19 14:25 UTC, DPeshkoff commented on source/anagram.js
> +'use strict';
Распиши, что делает эта строчка)

2023-09-19 14:25 UTC, DPeshkoff commented on source/anagram.js
> +
Здесь не нужна пустая строка

2023-09-19 14:25 UTC, DPeshkoff commented on source/anagram.js
> +function countLetters(wordInput) {
А почему function? Какие есть способы задать функцию в языке и в чем отличия? Распиши)

2023-09-19 14:25 UTC, DPeshkoff commented on source/anagram.js
> +    if (typeof wordInput !== "string") {
В JS приняты одиночные кавычки)

А еще проверка неполная - ![изображение](https://github.com/frontend-park-mail-ru/homework_2023_2/assets/31134795/5afd937a-9f4c-4dbd-a0a1-8d4662f11341)

При этом это валидные строки... непорядок! Давай подумаем, как это починить)

2023-09-19 14:25 UTC, DPeshkoff commented on source/anagram.js
> +        throw new TypeError("word must be string")
Не забывай про точки с запятой! Несмотря на то, что парсер умеет автоматически их проставлять - иногда это приводит к странным результатам. 

<details><summary>Каким?</summary>
<p>
К примеру, тривиальный и понятный код:

![изображение](https://github.com/frontend-park-mail-ru/homework_2023_2/assets/31134795/3d22e9a8-baee-4bfb-886a-b4dfe665364a)

Внезапно падает:

![изображение](https://github.com/frontend-park-mail-ru/homework_2023_2/assets/31134795/582afa37-106b-4330-acaf-6a622c1cda61)

Почему так происходит, думаю, наглядно видно по тексту ошибки - он считает `[3]` частью `s`. Если при этом поставить ;, то код магически начинает работать)

![изображение](https://github.com/frontend-park-mail-ru/homework_2023_2/assets/31134795/9210ce09-d52b-40aa-9731-dd12424c685b)
</p>
</details> 

Давай везде проставим точки с запятой)

2023-09-19 14:25 UTC, DPeshkoff commented on source/anagram.js
> +    for (let i = 0; i < word?.length; i++) {
А давай перебирающими методами?)

2023-09-19 14:25 UTC, DPeshkoff commented on source/anagram.js
> +        return false
Обернуть в {}

А еще можно проверять на [falsy](https://developer.mozilla.org/ru/docs/Glossary/Falsy)

2023-09-19 14:25 UTC, DPeshkoff commented on source/anagram.js
> +        throw new TypeError("word must be string")
Тут тоже со строками тот же вопрос)

2023-09-19 14:25 UTC, DPeshkoff commented on source/anagram.js
> +    if (firstWord?.length != secondWord?.length)
Проверки должны быть строгие

2023-09-19 14:25 UTC, DPeshkoff commented on source/anagram.js
> +    for (let letter in letterCountFirst) {
Перебирающие методы)

2023-09-19 14:25 UTC, DPeshkoff commented on tests/anagram.js
> +		}
Лучше [это](https://api.qunitjs.com/assert/throws/)

2023-09-19 16:22 UTC, Jarosin commented on source/anagram.js
> +'use strict';
Включает современный режим JS. Была добавлена, чтобы решить проблемы с обратной совместимостью.

2023-09-19 16:30 UTC, Jarosin commented on source/anagram.js
> +function countLetters(wordInput) {
function name() - это function declaration, позволяет использовать функцию в любом месте текущего блока.
let sayHi = func().... - это function expression, позволяет видеть функцию только после обьявления(+ ее можно подменить присвоив другую функцию)

2023-09-19 16:45 UTC, Jarosin commented on source/anagram.js
> +    if (typeof wordInput !== "string") {
new String(...) - это object, добавил везде проверку "... instanceof String"

2023-09-19 16:47 UTC, Jarosin commented on source/anagram.js
> +
Поправил

2023-09-19 17:07 UTC, Jarosin commented on source/anagram.js
> +    if (firstWord?.length != secondWord?.length)
Поправил

2023-09-19 17:07 UTC, Jarosin commented on source/anagram.js
> +    for (let letter in letterCountFirst) {
Сделал итерирование по обьекту

2023-09-19 17:25 UTC, Jarosin commented on tests/anagram.js
> +		}
Поправил

2023-09-19 17:36 UTC, Jarosin commented on source/anagram.js
> +        return false
Обернул, добавил проверку на falsy

2023-09-19 17:58 UTC, Jarosin commented on source/anagram.js
> +    for (let i = 0; i < word?.length; i++) {
Поправил

2023-09-19 19:51 UTC, DPeshkoff requested changes

2023-09-19 19:51 UTC, DPeshkoff commented on source/anagram.js
> +'use strict';
Ну, как раз это не то, что решит проблемы с ней)

Что конкретно включает строгий режим?

2023-09-19 19:51 UTC, DPeshkoff commented on source/anagram.js
> +function countLetters(wordInput) {
А почему здесь выбрал не стрелочную функцию? Чем они отличаются?

2023-09-19 19:51 UTC, DPeshkoff commented on tests/anagram.js
> +			TypeError
Можно new TypeError() и сразу с сообщением внутри, как и в коде, чтобы проверка была совсем полной

2023-09-19 20:28 UTC, Jarosin commented on source/anagram.js
> +function countLetters(wordInput) {
Стрелочная функция сравнима с лямбда функциями других языков - у нее нет имени, что может быть преимуществом, если мы не хотим её повторно использовать(можно дать ей имя присвоив ее переменной). Также есть фишки связанные с ООП: она пробрасывает arguments и this из внешней функции(так как не имеет своих) и потому не могут быть использованы как конструкторы и не имеют super.
Она в целом сравнима с function expression + фишки ооп

2023-09-19 20:31 UTC, Jarosin commented on tests/anagram.js
> +			TypeError
Поправил

2023-09-19 20:48 UTC, Jarosin commented on source/anagram.js
> +'use strict';
Строгий режим нужен, чтобы повысить безопасность кода. Он убирает много очень страшных конструкций, которые легко могли бы привести к ошибке, например 
![image](https://github.com/frontend-park-mail-ru/homework_2023_2/assets/52870557/a346abd8-1a8b-45e1-9529-f7a70d9a93db)
Также он не позволяет использовать переменные без объявления, явно выдает ошибку, если попытаться удалить/изменить неизменяемые поля объекта. + this перестает по умолчанию ссылатсья на глобальный объект

2023-09-19 22:42 UTC, DPeshkoff requested changes

2023-09-19 22:42 UTC, DPeshkoff commented on source/anagram.js
> +function countLetters(wordInput) {
Выглядит, что здесь лучше стрелочную, потому что все из списка отсутствующего в стрелочной функции нам и не нужно)

2023-09-20 09:01 UTC, Jarosin commented on source/anagram.js
> +function countLetters(wordInput) {
Поменял на стрелочную

2023-09-20 11:19 UTC, DPeshkoff approved these changes

2023-09-20 11:19 UTC, closed without merging