Variant 4
frontend-park-mail-ru/homework_2023_2 pull request #59
Opened 2023-09-11 18:57 UTC by rissenberg

Горшков Константин, WEB-21

2023-09-14 11:58 UTC, johnSamilin commented
Привет, добро пожаловать на курс по фронтенд-разработке. Я буду проверять твое ДЗ 0.
Если у меня появятся комментарии к коду, то я опишу их здесь. Можешь отвечать на них тут же, а чтобы что-то уточнить - [телеграм](https://t.me/WatasheeBaka)

2023-09-15 06:06 UTC, johnSamilin commented
Не нужно было загружать скриншот с результатом тестов, он здесь скорее для примера

2023-09-15 06:13 UTC, johnSamilin requested changes

2023-09-15 06:13 UTC, johnSamilin commented on tests/inverse.js
> +		assert.deepEqual(inverse([], 0), []);
еще нужны тесты на некорректный ввод: например, когда на входе не массив, а объект или что-то еще

2023-09-15 06:13 UTC, johnSamilin commented on source/inverse.js
> +'use strict';
А какие преимущества дает use strict конкретно в этом файле?

2023-09-15 06:13 UTC, johnSamilin commented on source/inverse.js
> +function inverse(array, value = 0) {
добавь, пожалуйста, JSDoc для этой функции

2023-09-15 06:13 UTC, johnSamilin commented on source/inverse.js
> +function inverse(array, value = 0) {
и давай поменяем название второго аргумента на какое-то более информативное, которое бы отражало его назначение

2023-09-15 06:13 UTC, johnSamilin commented on source/inverse.js
> +		right = array.length - 1;
во всех случаях из right вычитается единица. кажется, эту операцию можно провести один раз после всех if-ов

2023-09-15 06:13 UTC, johnSamilin commented on source/inverse.js
> +	} else {
а зачем тут дублирование ветки первого условия?

2023-09-15 06:13 UTC, johnSamilin commented on source/inverse.js
> +	while (left < right) {
while - довольно опасный цикл, есть более безопасные альтернативы среди встроенных методов массива. попробуй избавиться здесь от риска зацикливания

2023-09-16 20:56 UTC, rissenberg commented on source/inverse.js
> +'use strict';
В этом - никаких. Но я решил эту строку не стирать

2023-09-16 21:11 UTC, johnSamilin commented on source/inverse.js
> +'use strict';
хорошо, а можешь привести пример, зачем ее используют?

2023-09-16 21:15 UTC, johnSamilin requested changes

2023-09-16 21:15 UTC, johnSamilin commented on source/inverse.js
> +		let temp = array[left];
переменная temp не изменяется, так что лучше ее объявить как const

2023-09-16 21:15 UTC, johnSamilin commented on source/inverse.js
> +console.log(inverse([]));
кажется, это вывод для теста, лучше перед коммитом еще раз просматривать изменения и такие вещи убирать

2023-09-18 18:38 UTC, johnSamilin commented on source/inverse.js
> +'use strict';
@rissenberg хотелось бы получить ответ

2023-09-18 18:39 UTC, johnSamilin commented on screenshot.png
восстанови, пожалуйста, оригинальный скриншот

2023-09-19 15:16 UTC, rissenberg commented on screenshot.png
готово

2023-09-21 09:37 UTC, DPeshkoff requested changes
Привет! Поздравляю с переходом на второй семестр)

Классное решение получилось, но у меня есть пара замечаний. Если возникнут вопросы - можешь писать в [Telegram](t.me/DmPesh)

2023-09-21 09:37 UTC, DPeshkoff commented on source/inverse.js
> +'use strict';
Интересует тот же вопрос - чем нестрогий режим отличается от строгого? Хочу расписанный ответ реплаем сюда)

2023-09-21 09:37 UTC, DPeshkoff commented on source/inverse.js
> + * @throws {TypeError} Проверка типа входных данных
Желательно в доке расписать, когда ошибка выбрасывается)

2023-09-21 09:37 UTC, DPeshkoff commented on source/inverse.js
> +		throw new TypeError('Некоретный тип входных данных');
Я бы разделил на две разные ошибки с двумя разными комментариями

2023-09-21 09:37 UTC, DPeshkoff commented on source/inverse.js
> +function inverse(array, offset = 0) {
Распиши, какие есть способы задать функцию и чем они отличаются?

2023-09-21 09:37 UTC, DPeshkoff commented on source/inverse.js
> +	}
Можно тернарником и сразу на 17 строчке
заодно и константой сделаем

2023-09-21 09:37 UTC, DPeshkoff commented on source/inverse.js
> +}
Давай добавим перенос строки в конце файла

2023-09-21 09:37 UTC, DPeshkoff commented on source/inverse.js
> +	for (let i = 0; i < iterations; i++) {
Лучше перебирающими методами

2023-09-22 15:35 UTC, rissenberg commented on source/inverse.js
> + * @throws {TypeError} Проверка типа входных данных
почему то нет в сообщении выше комментариев, но вот:

строгий режим помогает избежать ошибок, предотвращает использование необъявленных переменных и старых небезопасных функций

2023-09-22 15:35 UTC, rissenberg commented on source/inverse.js
> +function inverse(array, offset = 0) {
1. с помощью ключевого слова function, как у меня

function имяФункции (параметры)  {}

2. с помощью анонимной функции, которую можно присвоить переменной. тогда ее можно использовать только после объявления

const имяПеременной = function (параметры)  {}

3. С помощью стрелочной функции. использование так же после объявления, используется в функциях без this

const имяФункции = (параметры) => {}

2023-09-23 18:37 UTC, DPeshkoff requested changes

2023-09-23 18:37 UTC, DPeshkoff commented on source/inverse.js
> +function inverse(array, offset = 0) {
здесь лучше стрелочная, потому что в ней есть еще одно отличие с this)

распиши, какое

и поменяй)

2023-09-23 18:37 UTC, DPeshkoff commented on source/inverse.js
> +'use strict';
распиши, в чем разница-то
ответа нет(

2023-09-23 19:53 UTC, rissenberg commented on source/inverse.js
> +'use strict';
строгий режим помогает избежать ошибок, предотвращает использование необъявленных переменных и старых небезопасных функций

2023-09-23 20:04 UTC, rissenberg commented on source/inverse.js
> +function inverse(array, offset = 0) {
стрелочные функции наследуют контекст от своего родителя, как и ключевое слово this будет ссылаться на объект, из которого вызывается родительская функция - это, в принципе, все описание для this

2023-09-23 20:44 UTC, DPeshkoff requested changes

2023-09-23 20:44 UTC, DPeshkoff commented on source/inverse.js
> +let inverse = (array, offset = 0) => {
Можно const

2023-09-23 20:47 UTC, rissenberg commented on source/inverse.js
> +let inverse = (array, offset = 0) => {
да, что то не подумал

2023-09-23 20:51 UTC, DPeshkoff approved these changes

2023-09-23 20:51 UTC, closed without merging