Чуйко Никита
frontend-park-mail-ru/homework_2023_2 pull request #6
Opened 2023-09-06 15:54 UTC by mafin1799

0 ДЗ

2023-09-06 16:22 UTC, tUnknownLegend commented
Привет, добро пожаловать на курс по фронтенд-разработке. Я буду проверять твое ДЗ 0. Ниже будут мои вопросы и комментарии по коду. Можно отвечать на них здесь или писать в [телеграм](https://t.me/tUnknownLegend)

2023-09-06 18:27 UTC, tUnknownLegend requested changes
Интересное решение, но требуется доработка. Обрати внимание на то, что нужно добавить тестов. Рекомендую вначале сделать именно это - проверить удовлетворяет ли код всем кейсам не будет составлять труда. Напомню, что каждый тест должен проверять различную ситуацию, однотипные тесты имеют мало смысла

2023-09-06 18:27 UTC, tUnknownLegend commented on source/set.js
> +        if (i === keys.length - 1) {
поясни, пожалуйста, почему не сделал for сразу до `keys.length - 1`? Заодно и вложенность if'ов ушла бы

2023-09-06 18:27 UTC, tUnknownLegend commented on source/set.js
> +    return object;
опять же вопрос как к 13 строке. Входные параметры не должны изменяться

2023-09-06 18:27 UTC, tUnknownLegend commented on source/set.js
> +};
в конце файла положено оставлять пустую строку

2023-09-06 18:27 UTC, tUnknownLegend commented on tests/set.js
> +	QUnit.test('set игнорирует пустые ключи', function (assert) {
еще нужны как минимум проверки для некорректных входных данных
  - null, undefined
  - неверный формат string
  - другие типы данных

2023-09-06 18:45 UTC, mafin1799 commented on source/set.js
> +'use strict';
включает строгий режим движка, запрещает опасные черты JavaScript
Введена в стандарте ECMAScript5

например может ругнуться на `() => { x = 5 }`

2023-09-06 18:49 UTC, mafin1799 commented on source/set.js
> +const set = (object, path, value) => {
В рамках применения this не будет создаваться новый контекст.
Позволяет не использовать ключевое слово return

2023-09-06 18:50 UTC, mafin1799 commented on source/set.js
> +    const keys = path.split('.');
просто сделать проверки типов внутри?
Тянуть PropTypes.js или писать на typescript тут не обязательно?

2023-09-06 19:26 UTC, mafin1799 commented on source/set.js
> +        } else if (field.length > 0) {
можно

2023-09-06 19:44 UTC, mafin1799 commented on source/set.js
> +    return object;
тут не понял.
есть тест который проверяет изменяется ли объект.

или тут имеется ввиду то что мы создаем новую копию сылку, не изменяя существующий объект?

2023-09-07 08:01 UTC, mafin1799 commented on tests/set.js
> +	QUnit.test('set игнорирует пустые ключи', function (assert) {
добавил добавление объекта по пути и undefined

2023-09-07 08:01 UTC, mafin1799 commented on source/set.js
> +};
добавил

2023-09-07 08:02 UTC, mafin1799 commented on source/set.js
> +    return object;
этот вопрос решили в телеге

2023-09-07 08:03 UTC, mafin1799 commented on source/set.js
> +        if (i === keys.length - 1) {
строгое сравнение без приведения типов. то есть мы проверяем идентичны ли сравниваемые сущности

2023-09-07 08:05 UTC, mafin1799 commented on source/set.js
> +    const keys = path.split('.');
добавил проверку на корректность параметров. в случае если все плохо будет возвращен исходный объект без изменений

2023-09-08 08:31 UTC, tUnknownLegend requested changes
Кое-что еще надо исправить

2023-09-08 08:31 UTC, tUnknownLegend commented on source/set.js
> +            if (i === keys.length - 1) {
похоже, что лучше вынести этот if за цикл, чтобы каждый раз не проверять это.  Чтобы "обрезать" последний элемент массива удобно использовать использовать [splice](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/splice)

2023-09-08 09:04 UTC, mafin1799 commented on source/set.js
> +'use strict';
при использовании ключевых слов import export

2023-09-08 09:08 UTC, mafin1799 commented on source/set.js
> +    if (keys.length === 0) {
!keys

2023-09-08 09:23 UTC, mafin1799 commented on tests/set.js
> +	QUnit.test('set и обьект', function (assert) {
сделал. Тут значение лола станет кек

2023-09-08 09:23 UTC, mafin1799 commented on source/set.js
> +            if (i === keys.length - 1) {
вообще вынес последний ключ

2023-09-08 09:23 UTC, mafin1799 commented on source/set.js
> +        let current = object;
переписал

2023-09-08 15:59 UTC, tUnknownLegend reviewed
Буквально одна формальная правка и будет аппрув от меня

2023-09-08 15:59 UTC, tUnknownLegend commented on source/set.js
> +'use strict';
а еще при использовании классов и т.п. https://learn.javascript.ru/strict-mode

2023-09-08 15:59 UTC, tUnknownLegend commented on tests/set.js
> +		assert.deepEqual(set({ foo: 'bar' }, '.foo', 'baz'), { foo: 'baz' });
давай вернем отступы как были, чтобы не мешалось на ревью

2023-09-08 16:01 UTC, tUnknownLegend commented on tests/set.js
> +		assert.deepEqual(set({ foo: 'bar' }, '.foo', 'baz'), { foo: 'baz' });
далее везде аналогично, где есть изменения в строках, которых не должно быть
![image](https://github.com/frontend-park-mail-ru/homework_2023_2/assets/57019979/113af4bd-fc63-4aef-8a40-a4eb4b6b16c7)

2023-09-10 15:06 UTC, tUnknownLegend approved these changes

2023-09-10 20:50 UTC, DPeshkoff requested changes
Привет! Поздравляю с переходом на второй семестр)

Крутое решение получилось, но у меня есть пара замечаний. Если возникнут вопросы - можешь писать в [Telegram](t.me/DmPesh)

2023-09-10 20:50 UTC, DPeshkoff commented on source/set.js
> +    if (!object || typeof object !== 'object' || typeof path !== 'string') {
Упс! 

![изображение](https://github.com/frontend-park-mail-ru/homework_2023_2/assets/31134795/5afd937a-9f4c-4dbd-a0a1-8d4662f11341)

При этом это валидные строки... непорядок! Давай подумаем, как это починить)

2023-09-10 20:50 UTC, DPeshkoff commented on source/set.js
> +        return object;
Выглядит, как ошибочная ситуация. Если мы вернем весь объект - мы не узнаем, что что-то пошло не так. Давай сделаем [так](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Error)

2023-09-10 20:50 UTC, DPeshkoff commented on tests/set.js
> +		assert.deepEqual(newObj, expected)
Не забывай про точки с запятой! Несмотря на то, что парсер умеет автоматически их проставлять - иногда это приводит к странным результатам. 

<details><summary>Каким?</summary>
<p>
К примеру, тривиальный и понятный код:

![изображение](https://github.com/frontend-park-mail-ru/homework_2023_2/assets/31134795/3d22e9a8-baee-4bfb-886a-b4dfe665364a)

Внезапно падает:

![изображение](https://github.com/frontend-park-mail-ru/homework_2023_2/assets/31134795/582afa37-106b-4330-acaf-6a622c1cda61)

Почему так происходит, думаю, наглядно видно по тексту ошибки - он считает `[3]` частью `s`. Если при этом поставить ;, то код магически начинает работать)

![изображение](https://github.com/frontend-park-mail-ru/homework_2023_2/assets/31134795/9210ce09-d52b-40aa-9731-dd12424c685b)
</p>
</details> 

Давай везде проставим точки с запятой)

2023-09-10 20:50 UTC, DPeshkoff commented on tests/set.js
> +		assert.deepEqual(obj, set({}, '.foo.bar', undefined))
Кажется, нужно поменять местами - [сначала actual, потом expected](https://api.qunitjs.com/assert/deepEqual/)

2023-09-10 20:50 UTC, DPeshkoff commented on source/set.js
> +    const keys = path.split('.').filter(key => key);
А если путь будет, но пустой? Что будем делать тогда?)

2023-09-10 20:50 UTC, DPeshkoff commented on source/set.js
> +const set = (object, path, value) => {
А если не будет value?

2023-09-11 08:31 UTC, mafin1799 commented on tests/set.js
> +		assert.deepEqual(newObj, expected)
окей)

2023-09-11 08:37 UTC, mafin1799 commented on source/set.js
> +        return object;
В таком случае стоит разделить ошибки, чтобы на каждую было отдельное сообщение\поведение?
+ Добавить сюда отсутствие value

2023-09-12 11:31 UTC, DPeshkoff commented on source/set.js
> +        return object;
Лучше разделить)

2023-09-13 10:28 UTC, mafin1799 commented on source/set.js
> +    if (!object || typeof object !== 'object' || typeof path !== 'string') {
`
else if (!(path instanceof String || typeof path === 'string')) {
        throw new Error('Путь должен быть строкой');
    }
    `

2023-09-13 10:30 UTC, mafin1799 commented on source/set.js
> +    const keys = path.split('.').filter(key => key);
получается при пустом пути будет добавление поля в объект?

2023-09-13 10:35 UTC, mafin1799 commented on source/set.js
> +    const keys = path.split('.').filter(key => key);
если путь пустой '', то идет добавление поля с ключом undefined поэтому ввел обработку ошибки если значение !path

2023-09-13 10:37 UTC, mafin1799 commented on source/set.js
> +const set = (object, path, value) => {
если value не передается то его значение undefined
тут нужна явная проверка на undefined так как значение null не запрещено для полей

2023-09-13 10:42 UTC, mafin1799 commented on source/set.js
> +const set = (object, path, value) => {
+ в связи с изменениями затер несколько тестов, так как они оказались лишенными смысла

2023-09-13 15:48 UTC, DPeshkoff requested changes

2023-09-13 15:48 UTC, DPeshkoff commented on source/set.js
> +            throw new Error('Путь должен быть строкой');
Лучше [так](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Error#%D1%82%D0%B8%D0%BF%D1%8B_%D0%BE%D1%88%D0%B8%D0%B1%D0%BE%D0%BA)

2023-09-13 15:48 UTC, DPeshkoff commented on source/set.js
> +            throw new Error('Путь должен быть')
Не забывай про точки с запятой! Несмотря на то, что парсер умеет автоматически их проставлять - иногда это приводит к странным результатам. 

<details><summary>Каким?</summary>
<p>
К примеру, тривиальный и понятный код:

![изображение](https://github.com/frontend-park-mail-ru/homework_2023_2/assets/31134795/3d22e9a8-baee-4bfb-886a-b4dfe665364a)

Внезапно падает:

![изображение](https://github.com/frontend-park-mail-ru/homework_2023_2/assets/31134795/582afa37-106b-4330-acaf-6a622c1cda61)

Почему так происходит, думаю, наглядно видно по тексту ошибки - он считает `[3]` частью `s`. Если при этом поставить ;, то код магически начинает работать)

![изображение](https://github.com/frontend-park-mail-ru/homework_2023_2/assets/31134795/9210ce09-d52b-40aa-9731-dd12424c685b)
</p>
</details> 

Давай везде проставим точки с запятой)

2023-09-13 15:48 UTC, DPeshkoff commented on source/set.js
> +    }
Здесь ловить не нужно

2023-09-13 15:48 UTC, DPeshkoff commented on tests/set.js
> +		assert.deepEqual(newObj, expected)
и не пофиксил)

2023-09-13 15:48 UTC, DPeshkoff commented on tests/set.js
> +	});
Нудны тесты на ловлю некорректного)

2023-09-13 16:36 UTC, mafin1799 commented on source/set.js
> +    }
просто выбрасывать throw без try/catch?

2023-09-13 16:42 UTC, mafin1799 commented on source/set.js
> +            throw new Error('Путь должен быть строкой');
в плане использовать конструктор TypeError для ошибок типов?

2023-09-13 16:43 UTC, mafin1799 commented on source/set.js
> +    }
тогда убрать блок try catch или что имеется ввиду?

2023-09-13 16:44 UTC, mafin1799 commented on tests/set.js
> +	});
передать некорретный объект?

2023-09-13 16:51 UTC, mafin1799 commented on source/set.js
> +    }
типа ловить на этом уровне е нужно, потому что условно где-то выше будет отлов ошибок куда улетят и эти?

2023-09-13 16:53 UTC, mafin1799 commented on source/set.js
> +            throw new Error('Путь должен быть строкой');
я просто слабо понимаю что нужно сделать.
в доке есть описание конструкторов конкретных ошибок
а что делать то?)

2023-09-14 11:23 UTC, DPeshkoff commented on source/set.js
> +            throw new Error('Путь должен быть строкой');
да

2023-09-14 11:23 UTC, DPeshkoff commented on source/set.js
> +    }
убрать

2023-09-14 11:23 UTC, DPeshkoff commented on tests/set.js
> +	});
да

2023-09-15 06:20 UTC, mafin1799 commented on tests/set.js
> +	});
так как я выбросил обработку try/catch я не могу на этом уровне работать с невалидным объектом, мне выдается только исключение, поэтому тест написал на то что выбрасывается исключение

2023-09-15 19:23 UTC, DPeshkoff requested changes

2023-09-15 19:23 UTC, DPeshkoff commented on tests/set.js
> +		assert.deepEqual(newObj, expected)
и снова без ;

2023-09-15 19:23 UTC, DPeshkoff commented on tests/set.js
> +			},
Можно просто new TypeError(сообщение)

2023-09-15 19:23 UTC, DPeshkoff commented on tests/set.js
> +			},
можно стрелочной

2023-09-15 19:23 UTC, DPeshkoff commented on index.html
А зачем в этом файле diff?

2023-09-16 07:47 UTC, mafin1799 commented on index.html
пофиксил

2023-09-16 07:47 UTC, mafin1799 commented on tests/set.js
> +			},
сделал

2023-09-16 07:48 UTC, mafin1799 commented on tests/set.js
> +			},
это просто гениально, как я не додумался(без сарказма)

2023-09-16 20:16 UTC, DPeshkoff approved these changes

2023-09-16 20:17 UTC, closed without merging