Фасхутдинов Азамат WEB-22
frontend-park-mail-ru/homework_2023_2 pull request #60
Opened 2023-09-11 22:15 UTC by HallowAz

2023-09-13 11:30 UTC, GreatFix requested changes
Привет! Welcome to курс по фронтенд-разработке. Я буду проверять твое ДЗ 0.
У меня появились комментарии к коду, описал их здесь.
Можешь отвечать на них тут же, но если что, я доступен в [телеге](https://t.me/FixFive)

2023-09-13 11:30 UTC, GreatFix commented on source/zip.js
> +function zip(...objects) {
Также стоит подумать, при каких значениях параметров можно вернуть значение не доходя до сложных вычисления (в данном случае до цикла)

2023-09-13 11:30 UTC, GreatFix commented on source/zip.js
> +'use strict'
Для чего предназначена эта строчка? Что-то изменится в рамках твоего кода, если уберешь ее?

2023-09-13 16:29 UTC, HallowAz commented on source/zip.js
> +        for (let key in object)
Причин нет, действительно лучше использовать const. let отличается от const тем, что let объявляет переменную, а const - константу... . Если необходимо пояснить и это, то переменная изменяется в процессе выполнения блока, а константа нет. В данном случае const использовать лучше, т.к. так можно дать понять тому, кто читает код, что менятся key не будет в процессе выполнения кода. В коммите поменял

2023-09-13 16:39 UTC, HallowAz commented on source/zip.js
> +'use strict'
Эта строчка необходима для соблюдения строго режима. Он отключает полную совместимость со старыми версиями JS. Нужен был, т.к. старая функциональность не менялась и ошибки, сделанные создателями оставались. Строгий режим вносит изменения в стандарт JS, накладывая дополнительные ограничения для избегания ошибок. Если я правильно помню, то в строгом режиме нельзя просто присвоить что-то переменной, не объявив её перед этим, а в нестрогом можно. Это один из примеров. В моём коде ничего не должно поменяться, т.к. строгий режим укладывается внутрь нестрогого.

2023-09-13 16:51 UTC, GreatFix requested changes
В целом хорошо, но можно еще доработать

2023-09-13 18:26 UTC, HallowAz commented on source/zip.js
> +const zip = (...objects) => {
В JS ведь нет отдельного типа массив. Массив - это объект. Я могу написать в типе Object?

2023-09-13 18:31 UTC, HallowAz commented on source/zip.js
> +    if (objects.length == 0) {
Если передан один объект

2023-09-13 18:49 UTC, HallowAz commented on source/zip.js
> +    let resObj = objects.reduce((props, object) => {
Не нужен, получается

2023-09-13 18:51 UTC, HallowAz commented on source/zip.js
> +            if (!(props.hasOwnProperty(key))) {
Но ведь у props есть прототипное свойство valueOf и оно будет учитываться, как уже имеющееся, если убрать hasOwnProperty. Тест упадёт

2023-09-13 18:55 UTC, GreatFix commented on source/zip.js
> +            if (!(props.hasOwnProperty(key))) {
А, да, сорри, чет затупил

2023-09-13 19:02 UTC, GreatFix approved these changes
У меня больше вопросов нет, спасибо

2023-09-13 19:18 UTC, GreatFix requested changes
Чет поторопился, поправь еще пару комментов

2023-09-13 19:18 UTC, GreatFix commented on index.html
> -
Кстати здесь не нужно было лишний раз удалять пустые строки

2023-09-13 19:18 UTC, GreatFix commented on source/max.js
> +const max = numbers => Math.max(...numbers);
Убери из diff файлы source/max.js и tests/max.js

2023-09-13 19:18 UTC, GreatFix commented on source/zip.js
> +}
Попробую пустую строчку добавить

2023-09-13 19:36 UTC, HallowAz commented on source/max.js
> +const max = numbers => Math.max(...numbers);
Наверное, я покажусь неопытным, так и есть. Но я не понимаю что такое diff

2023-09-13 19:54 UTC, GreatFix commented on source/max.js
> +const max = numbers => Math.max(...numbers);
Если коротко, Diff это все изменения, которые содержит твой commit по отношению к прошлому коммиту или PR по отношению к нацеленной ветке . Имел в виду просто убрать это из твоего пул реквеста, чтобы лишние файлы не изменялись

2023-09-13 21:40 UTC, GreatFix approved these changes

2023-09-14 11:53 UTC, DPeshkoff requested changes
Привет! Поздравляю с переходом на второй семестр)

Интересное решение получилось, но у меня есть пара замечаний. Если возникнут вопросы - можешь писать в [Telegram](t.me/DmPesh)

2023-09-14 11:53 UTC, DPeshkoff commented on source/zip.js
> +'use strict'
Не забывай про точки с запятой! Несмотря на то, что парсер умеет автоматически их проставлять - иногда это приводит к странным результатам. 

<details><summary>Каким?</summary>
<p>
К примеру, тривиальный и понятный код:

![изображение](https://github.com/frontend-park-mail-ru/homework_2023_2/assets/31134795/3d22e9a8-baee-4bfb-886a-b4dfe665364a)

Внезапно падает:

![изображение](https://github.com/frontend-park-mail-ru/homework_2023_2/assets/31134795/582afa37-106b-4330-acaf-6a622c1cda61)

Почему так происходит, думаю, наглядно видно по тексту ошибки - он считает `[3]` частью `s`. Если при этом поставить ;, то код магически начинает работать)

![изображение](https://github.com/frontend-park-mail-ru/homework_2023_2/assets/31134795/9210ce09-d52b-40aa-9731-dd12424c685b)
</p>
</details> 

Давай везде проставим точки с запятой)

2023-09-14 23:03 UTC, DPeshkoff commented on source/zip.js
> +    for (const object of objects) {
хочу ответ)

2023-09-14 23:36 UTC, HallowAz commented on source/zip.js
> +    for (const object of objects) {
но я же написал ответ...

@[HallowAz](https://github.com/HallowAz) HallowAz Pending
forEach выполняет функцию для каждого элемента массива. Reduce перебирает все элементы и может накапливать. filter возвращает только те элементы, которые вернули true внутри функции. map перебирает все элементы и трансформирует массив. every используется для проверки массива

2023-09-15 19:40 UTC, DPeshkoff commented on source/zip.js
> +    for (const object of objects) {
А почему здесь выбрал именно такой?

2023-09-15 20:13 UTC, HallowAz commented on source/zip.js
> +    for (const object of objects) {
Потому что это привычный формат, мне приятнее так читать и сразу понятно. Ещё такой формат явно показывает постоянность объекта (const), даёт понять, что изменяться он не будет

2023-09-16 17:40 UTC, GreatFix commented on source/zip.js
> +    for (const object of objects) {
Попробуй написать рядом на forEach и сравнить какой удобней и лучше читается

2023-09-16 17:47 UTC, GreatFix requested changes
Некоторые вещи были не замечены, добавил комменты после свежего взгляда

2023-09-16 17:47 UTC, GreatFix commented on source/zip.js
> +        if (typeof object !== 'object') {
typeof null тоже вернет "object", напиши более точную проверку на объект

2023-09-16 17:47 UTC, GreatFix commented on tests/zip.js
> +			zip(5, 'hello');
Добавь тесты на случаи:
- zip(()=>{})
- zip(null)
- zip(Number(1))

2023-09-16 20:29 UTC, DPeshkoff approved these changes

2023-09-16 20:29 UTC, closed without merging