Демирев Никита
frontend-park-mail-ru/homework_2023_2 pull request #62
Opened 2023-09-13 18:51 UTC by NickDemiman

Вариант 13

2023-09-14 11:50 UTC, DPeshkoff commented
Подлей мастер, чтобы был корректный diff)

2023-09-14 12:19 UTC, NickDemiman commented
> Подлей мастер, чтобы был корректный diff)

вы имеете ввиду, апдейтнуть текущую ветку изменениями с мастера? Я просто не совсем понял.

2023-09-14 23:04 UTC, DPeshkoff commented
да

2023-09-15 07:17 UTC, NickDemiman commented
> да

Я как бы залил, но при этом 

> да

Я сделал rebase, но в процессе, конфликты были только с index и readme

2023-09-15 18:44 UTC, NickDemiman commented
Поправил историю коммитов

2023-09-15 19:43 UTC, DPeshkoff requested changes

2023-09-15 19:43 UTC, DPeshkoff commented on source/get.js
> +'use strict'
Распиши, что делает эта строчка

2023-09-15 19:43 UTC, DPeshkoff commented on source/get.js
> +'use strict'
Не забывай про точки с запятой! Несмотря на то, что парсер умеет автоматически их проставлять - иногда это приводит к странным результатам. 

<details><summary>Каким?</summary>
<p>
К примеру, тривиальный и понятный код:

![изображение](https://github.com/frontend-park-mail-ru/homework_2023_2/assets/31134795/3d22e9a8-baee-4bfb-886a-b4dfe665364a)

Внезапно падает:

![изображение](https://github.com/frontend-park-mail-ru/homework_2023_2/assets/31134795/582afa37-106b-4330-acaf-6a622c1cda61)

Почему так происходит, думаю, наглядно видно по тексту ошибки - он считает `[3]` частью `s`. Если при этом поставить ;, то код магически начинает работать)

![изображение](https://github.com/frontend-park-mail-ru/homework_2023_2/assets/31134795/9210ce09-d52b-40aa-9731-dd12424c685b)
</p>
</details> 

Давай везде проставим точки с запятой)

2023-09-15 19:43 UTC, DPeshkoff commented on source/get.js
> +    let splitedPathToProperty = pathToProperty.split('.').slice(1);
А какие вообще есть идентификаторы переменных? Почему тут выбрал let?

2023-09-15 21:41 UTC, NickDemiman commented on source/get.js
> +'use strict'
Режим изменяет поведение интерпретатора таким образом, что вместо того чтобы пропускать ошибки, он начинает выбрасывать исключения.

2023-09-15 21:46 UTC, NickDemiman commented on source/get.js
> +    let splitedPathToProperty = pathToProperty.split('.').slice(1);
- let - определение переменной внутри блока.
- const - работает как *let*, но значение после инициализации нельзя изменять
- var - изначально инициализирует undefined и также прокидывается во внутренние блоки, так что может быть конфликт имен при определении переменной с таким же именем

2023-09-16 14:26 UTC, NickDemiman commented on source/get.js
> +'use strict'
Поправил

2023-09-16 20:27 UTC, DPeshkoff requested changes

2023-09-16 20:27 UTC, DPeshkoff commented on source/get.js
> +    let splitedPathToProperty = pathToProperty.split('.').slice(1);
Выглядит, как юзкейс для const)

2023-09-17 15:53 UTC, DPeshkoff approved these changes

2023-09-17 15:53 UTC, closed without merging