Герасин Антон
frontend-park-mail-ru/homework_2023_2 pull request #63
Opened 2023-09-16 20:39 UTC by Ant0nL0rd

ДЗ 1

2023-09-18 11:43 UTC, LDK28 requested changes

2023-09-18 11:43 UTC, LDK28 commented on source/set.js
Привет! Добро пожаловать на курс фронтенд разработки! Я ментор и буду проверять твое ДЗ. Ты написал отличный код, но есть что поправить, в следующих комментах все опишу

2023-09-18 11:43 UTC, LDK28 commented on source/set.js
> +'use strict';
Для чего используется use strict?

2023-09-18 11:43 UTC, LDK28 commented on source/set.js
> +  for (let i = 1; i < parts.length - 1; ++i) {
Лучше использовать перебирающие методы, например forEach

2023-09-18 11:43 UTC, LDK28 commented on source/set.js
> +  const parts = path.split('.');
А если parts будет объектом или массивом? Кажется, что будет ошибка. Надо сделать для этого исключения

2023-09-18 11:43 UTC, LDK28 commented on tests/set.js
> +		assert.deepEqual(set([], '.3', 33), object2);
Нужно написать тесты, когда на вход функции переданы некорректные типы аргументов

2023-09-18 11:43 UTC, LDK28 commented on index.html
Как поправишь, можешь тегнуть меня тут или в [телеграмме](https://t.me/dkey28)

2023-09-18 12:03 UTC, LDK28 commented on source/set.js
> +  for (let i = 1; i < parts.length - 1; ++i) {
Как-будто тут даже через reduce проще будет. Посмотри, может и в правду его лучше забрать будет

2023-09-21 21:50 UTC, Ant0nL0rd commented on source/set.js
> +  for (let i = 1; i < parts.length - 1; ++i) {
Сделал через reduce.

2023-09-21 21:50 UTC, Ant0nL0rd commented on source/set.js
> +  const parts = path.split('.');
Сделано.

2023-09-21 21:50 UTC, Ant0nL0rd commented on tests/set.js
> +		assert.deepEqual(set([], '.3', 33), object2);
Сделано.

2023-09-22 08:24 UTC, LDK28 requested changes

2023-09-22 08:24 UTC, LDK28 commented on tests/set.js
> +		assert.deepEqual(set([], '.3', 33), object2);
Надо еще написать тесты, чтобы были переданы непустые массивы, объекты, числа, строки, null, undefined

То есть тесты должны быть максимально исчерпывающими

2023-09-22 08:24 UTC, LDK28 commented on source/set.js
> +		} else {
Можно упростить до `else if`

2023-09-22 08:24 UTC, LDK28 commented on source/set.js
> +const set = (obj, path, value) => {
Как-будто надо и obj, и value тоже проверить на тип

2023-09-22 08:24 UTC, LDK28 commented on source/set.js
> +		throw new Error('Path argument must be a string');
Лучше TypeError

2023-09-22 08:34 UTC, Ant0nL0rd commented on source/set.js
> +'use strict';
Я думал, что "'use strict';" стоит использовать всегда, когда технология написания программы не подразумевает отсутствия этой директивы. Так более очевидно, что код подразумевает использование более свежих стандартов языка, использование современных фич, которые могут быть отключены некоторыми компиляторами по дефолту.

2023-09-22 19:15 UTC, Ant0nL0rd commented on tests/set.js
> +		assert.deepEqual(set([], '.3', 33), object2);
Сделано.

2023-09-22 19:16 UTC, Ant0nL0rd commented on source/set.js
> +		} else {
Сделано.

2023-09-22 19:16 UTC, Ant0nL0rd commented on source/set.js
> +const set = (obj, path, value) => {
Сделано.

2023-09-22 19:16 UTC, Ant0nL0rd commented on source/set.js
> +		throw new Error('Path argument must be a string');
Сделано.

2023-09-22 19:16 UTC, Ant0nL0rd commented
Сделано.

2023-09-23 22:59 UTC, LDK28 requested changes

2023-09-23 22:59 UTC, LDK28 commented on source/set.js
> + * @returns {Object} - The modified object.
Надо также описать throws

2023-09-23 22:59 UTC, LDK28 commented on source/set.js
> +	if (typeof obj !== 'object') {
Тут надо чуть аккуратнее выполнять проверку, так как `typeof new String()` или `typeof new Number()` вернет тоже `’object`

2023-09-24 08:24 UTC, Ant0nL0rd commented on source/set.js
> + * @returns {Object} - The modified object.
Исправил.

2023-09-24 08:25 UTC, Ant0nL0rd commented on source/set.js
> +	if (typeof obj !== 'object') {
Исправил.

2023-09-24 12:59 UTC, LDK28 approved these changes

2023-09-24 22:07 UTC, DPeshkoff requested changes
Привет! Поздравляю с переходом на второй семестр)

Классное решение получилось, но у меня есть пара замечаний. Если возникнут вопросы - можешь писать в [Telegram](t.me/DmPesh)

2023-09-24 22:07 UTC, DPeshkoff commented on source/set.js
> +  if (typeof path !== 'string') {
![изображение](https://github.com/frontend-park-mail-ru/homework_2023_2/assets/31134795/5afd937a-9f4c-4dbd-a0a1-8d4662f11341)

При этом это валидные строки... непорядок! Давай подумаем, как это починить)

2023-09-24 22:07 UTC, DPeshkoff commented on tests/set.js
> +		}, Error, 'Path argument must be a string');
Лучше проверять на конкретный инстанс - new TypeError('...')

2023-09-25 10:41 UTC, Ant0nL0rd commented on tests/set.js
> +		}, Error, 'Path argument must be a string');
Исправил.

2023-09-25 10:41 UTC, Ant0nL0rd commented on source/set.js
> +  if (typeof path !== 'string') {
Исправил.

2023-09-25 10:54 UTC, DPeshkoff approved these changes

2023-09-25 10:54 UTC, DPeshkoff requested changes

2023-09-25 10:54 UTC, DPeshkoff commented on tests/set.js
> +		}, 'value argument cannot be function, symbol, or undefined');
не так, сразу new Error() без функции

2023-09-25 19:04 UTC, Ant0nL0rd commented on tests/set.js
> +		}, 'value argument cannot be function, symbol, or undefined');
Сделано.

2023-09-25 19:08 UTC, DPeshkoff approved these changes

2023-09-25 19:08 UTC, closed without merging