Initial commit
frontend-park-mail-ru/homework_2023_2 pull request #64
Opened 2023-09-18 14:51 UTC by He11Coder

2023-09-19 22:15 UTC, CheerfulMushroom commented
Хола!
Приветствую тебя на курсе по фронтенд разработке! Я буду проверять твоё решение.
Ниже накидаю комментариев по коду. Можешь отвечать здесь или писать мне в телеграм (https://t.me/CheerfulMushroom)

2023-09-20 05:36 UTC, CheerfulMushroom commented on source/solve.js
> +                    return false;
Хотя в целом это вкусовщина. Оставляю на твоё усмотрение)

2023-09-20 21:47 UTC, He11Coder commented
Исправил)

2023-09-21 08:17 UTC, CheerfulMushroom commented
Ну будущее: не нужно нажимать "Resolve coversation" самому, это на мне лежит)

2023-09-21 10:23 UTC, CheerfulMushroom reviewed
Пару моментов ещё описал, про которые забыл

2023-09-21 10:23 UTC, CheerfulMushroom commented on source/solve.js
> +const isValid = function(expression) {
Блин, забыл добавить. Раз эта функция теперь не возвращает ничего, то имеет смысл её переименовать, а то название isValid подразумевает возврат true или false, а у тебя теперь ничего не возвращается и только ошибка может вылететь. Предлагаю какой-нибудь validateExpression

2023-09-21 10:23 UTC, CheerfulMushroom commented on source/solve.js
> + * @returns {boolean}
Но она же ничего не возвращает теперь 🤔

2023-09-21 16:02 UTC, He11Coder commented on source/solve.js
> +const isDigit = ch => ((ch >= '0') && (ch <= '9'));
Используем для краткости, например. Для создания анонимной, короткой функции, которую удобно передать в какую то другую функцию по типу того же Array.every(). В общем-то тут с этой целью и использовали. 

Плюс особенность стрелочных функций состоит в том, что она имеет доступ к аргументам скоупа, в котором она сама находится. Т.е. к примеру, можно обращаться к аргументам вызвавшей ее функции, без необходимости передавать их явно в стрелочную функцию. Это же относится и к this.
Проще говоря, у нее нет своего контекста.

2023-09-21 16:05 UTC, He11Coder commented
Исправил. В название коммита ссылка добавилась случайно из за "#2")

2023-09-21 20:59 UTC, CheerfulMushroom commented on source/solve.js
> + * @param {char} ch - some symbol
Не, symbol это тоже не то 🙃
Подсказка:  это один из 8 основных типов в js.

Ну и раз уж ты затронул Symbol, расскажи, что это за зверь такой и зачем он нужен)

2023-09-21 21:39 UTC, CheerfulMushroom reviewed
Так, финальный рывок и я передаю твоё ДЗ дальше по цепочке)
Если возникают вопросы, то пиши в телегу, Если я не сплю, то отвечаю оперативно. Ближайшие пару часов буду бодрствовать)

2023-09-21 21:39 UTC, CheerfulMushroom commented on source/solve.js
> +const validateExpression = function(expression) {
Переведи оставшиеся обычные функции на стрелочные

2023-09-21 21:39 UTC, CheerfulMushroom commented on source/solve.js
> +const validateExpression = function(expression) {
Вообще, как правило, старайся не использовать обычные функции, если можно просто использовать стрелочные. Рекомендую почитать https://stackoverflow.com/questions/22939130/when-should-i-use-arrow-functions-in-ecmascript-6, тут обсужждают, когда стоит использовать обычные функции, а когда стрелочные. Как можешь видеть, кейсов с обычными функциями не так много и они все завязаны на том, что в них будет разный this. Очевидно, не твой случай

2023-09-22 09:41 UTC, He11Coder commented on source/solve.js
> + * @param {char} ch - some symbol
Да, тут symbol действительно совсем не подходит. Он используется, как я понимаю, для создания уникальных идентификаторов или, проще говоря, ключей для объектов. Например, мы можем захотеть добавить поле id к какому-нибудь объекту из сторонней библиотеки и использовать его для наших нужд. Но залезть в реализацию класса мы не можем, однако можем использовать

2023-09-22 09:48 UTC, He11Coder commented
Сделано)

2023-09-22 09:57 UTC, CheerfulMushroom commented on source/solve.js
> + * @param {char} ch - some symbol
В целом так и есть. Они нужны для того, чтобы избежать коллизии при добавлении полей. Так сторонние библиотеки могут добавлять свои поля через Symbol, не боясь перетереть чужие значения. Но абсолютно скрытыми их назвать сложно, так как все символы объекта можно получить через `Object.getOwnPropertySymbols` :)

2023-09-22 10:19 UTC, DPeshkoff requested changes
Привет! Поздравляю с переходом на второй семестр)

Хорошее решение получилось, но у меня есть пара замечаний. Если возникнут вопросы - можешь писать в [Telegram](t.me/DmPesh)

2023-09-22 10:19 UTC, DPeshkoff commented on source/solve.js
> +'use strict';
Распиши, пожалуйста, что делает эта строчка?

2023-09-22 10:19 UTC, DPeshkoff commented on source/solve.js
> +    for (const current of expression) {
А давай сделаем перебирающим методом?

2023-09-22 10:19 UTC, DPeshkoff commented on source/solve.js
> +const validateExpression = expression => {
Аргументы стрелочной функции лучше оборачивать в скобки - так нагляднее и будет проще в дальнейшем)

2023-09-22 10:19 UTC, DPeshkoff commented on source/solve.js
> +        } else if (isOperator(current)) {
А как относишься к идее сделать switch? Хочешь поэкспериментировать?

2023-09-22 10:19 UTC, DPeshkoff commented on source/solve.js
> +    return eval(`const x = ${root}; ` + expression);
Кто такой eval?) Нехорошо его использовать

<details><summary>Почему плох даже экранируемый eval?</summary>
<p>

- eval медленный
- eval часто нельзя нормально минифицировать)
- через eval можно получить доступ к области видимости на момент ее вызова - и потенциально слить для third-party то, чего им знать не следует

Подробнее [тут](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/eval#never_use_eval!)
</p>
</details>

2023-09-22 10:19 UTC, DPeshkoff commented on tests/solve.js
> +		assert.throws(function() {solve('xx - 2*x + 4x', 1);}, Error);
Вместо Error лучше создавать инстанс с нужным сообщением ошибки

2023-09-22 10:19 UTC, DPeshkoff commented on tests/solve.js
> +		assert.throws(function() {solve('let arr = [];', 100500);}, Error);
Предлагаю еще тесты на тот кейс, если на вход solve подается вообще не строка

2023-09-23 18:40 UTC, DPeshkoff approved these changes

2023-09-23 18:40 UTC, closed without merging