Чинаев Алексей
frontend-park-mail-ru/homework_2023_2 pull request #7
Opened 2023-09-06 16:46 UTC by ellexo2456

Алексей Чинаев

2023-09-06 18:31 UTC, tUnknownLegend commented
Привет, добро пожаловать на курс по фронтенд-разработке. Я буду проверять твое ДЗ 0. Ниже будут мои вопросы и комментарии по коду. Можно отвечать на них здесь или писать в [телеграм](https://t.me/tUnknownLegend)

2023-09-06 18:33 UTC, tUnknownLegend commented
Сделай название ПР в формате Имя Фамилия. Так нам легче будет его проверить

2023-09-06 19:36 UTC, tUnknownLegend requested changes
Интересное решение, но требуется доработка. Так же необходимо оформить [JSDoc](https://learn.javascript.ru/comments). По любым вопросам пиши в [телеграм](https://t.me/tUnknownLegend)

2023-09-06 19:36 UTC, tUnknownLegend commented on source/letters.js
> +            words = words.filter((word, index) => words.indexOf(word) === index);
неплохое решение. А можно ли просто использовать Set здесь?

2023-09-06 19:36 UTC, tUnknownLegend commented on source/letters.js
> +                if (arr.indexOf(word) !== index) set.add(word);
подумай как здесь можно переписать код, чтобы убрать forEach ниже и не использовать removeAll функцию

2023-09-06 19:36 UTC, tUnknownLegend commented on source/letters.js
> +const letters = (words, op = null) => {
также подумай над тем, что будет происходить, если words не типа string

2023-09-06 19:36 UTC, tUnknownLegend commented on source/letters.js
> +console.log(letters(1332432))
это явно надо удалить) и в конце файла принято оставлять пустую строку

2023-09-06 19:36 UTC, tUnknownLegend commented on tests/letters.js
> +	QUnit.test('Корректно реагирует на неправильные данные', function (assert) {
напиши тесты на случаи с другими параметрами неверного типа, причем не только для первого параметра

2023-09-06 19:36 UTC, tUnknownLegend commented on tests/letters.js
> +	QUnit.test('Корректно реагирует на неправильные данные', function (assert) {
так же подумай над любыми другими случаями - чем больше разных ситуаций предусмотришь в тестах - тем лучше (в пределах разумного, разумеется)

2023-09-07 15:22 UTC, ellexo2456 commented on source/letters.js
> +'use strict';
нужен чтобы пользоваться современными стандартами js, в которые, насколько помню, входят в том числе и функции по типу forEach и filter и все стрелочные функции и тд

2023-09-07 15:22 UTC, ellexo2456 commented on source/letters.js
> +const removeAll = (words, word) => {
они короче, нет доступа к this и arguments и нельзя вызвать через new

2023-09-07 15:23 UTC, ellexo2456 commented on source/letters.js
> +            words = words.filter((word, index) => words.indexOf(word) === index);
ну можно конечно, но я подумал, что с этого не будет особого профита

2023-09-08 09:28 UTC, tUnknownLegend requested changes
Требуются небольшие доработки

2023-09-08 09:28 UTC, tUnknownLegend commented on source/letters.js
> +'use strict';
не совсем так, скорее [решает](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode#:~:text=Strict%20mode%20makes%20several%20changes%20to%20normal%20JavaScript%20semantics) легаси проблемы в языке. Напиши, пожалуйста, когда 'use strict' можно не писать, но решим будет строгим автоматически.

2023-09-08 09:28 UTC, tUnknownLegend commented on source/letters.js
> +
забыл написать в прошлый раз. Поменяй ветку в которую ты сделал ПР. Должна быть ветка твоего варианта, а не master. [Тут](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-base-branch-of-a-pull-request) написано как это сделать

2023-09-08 09:28 UTC, tUnknownLegend commented on source/letters.js
> +        console.log("incorrect type of param words")
а если будет не null, а function? Давай просто проверим string это или нет

2023-09-08 09:28 UTC, tUnknownLegend commented on source/letters.js
> +            array = array.filter(word => countEntries.get(word) === 1)
не забывай `;`. Везде по коду проверь, а лучше используй линтер. Вот [инфа](https://javascript.info/coding-style) про стайлинг в JS

2023-09-08 09:28 UTC, tUnknownLegend commented on source/letters.js
> +            let countEntries = new Map();
почитай про [объекты](https://learn.javascript.ru/object). Свойства константных объектов можно менять, поэтому тут должен быть const

2023-09-08 09:28 UTC, tUnknownLegend commented on source/letters.js
> +    return array.join('')
тут можно написать немного чище. Сделать array const и делать return внутри switch.

2023-09-08 09:28 UTC, tUnknownLegend commented on tests/letters.js
> +		assert.strictEqual(letters(234567890), '');
строки 62 и 63 никак не отличается с точки зрения языка - все типа number

2023-09-08 09:28 UTC, tUnknownLegend commented on tests/letters.js
> +		assert.strictEqual(letters(['p', 'r', 'o', 't', 'o', 't', 'y', 'p', 'e']), 'rye');
а что будет, если положить в массив несколько букв?

2023-09-08 10:24 UTC, ellexo2456 commented on source/letters.js
> +
use strict врубается автоматом при использовании классов и модулей

2023-09-08 10:25 UTC, ellexo2456 commented
дубль ещё раз

2023-09-08 16:09 UTC, tUnknownLegend requested changes
по решению все ок, добавь, пожалуйста, еще немного тестов. Например, еще проверку с некорректными типами данных, функцию какую-нибудь можно всунуть или объект

2023-09-08 16:09 UTC, tUnknownLegend commented on tests/letters.js
> +		assert.strictEqual(letters(['p', 'r', 'o', 't', 'o', 't', 'y', 'p', 'e']), '');
это был намек на то, что надо написать такой тест) 
https://github.com/frontend-park-mail-ru/homework_2023_2/pull/7#discussion_r1319601194

2023-09-08 16:09 UTC, tUnknownLegend commented on tests/letters.js
> +		assert.strictEqual(letters(['p', 'r', 'o', 't', 'o', 't', 'y', 'p', 'e']), '');
имелось ввиду что-то вроде `['sp', 'r', 'o', 't', '1o', 't', 'y', 'p', 'e']`

2023-09-09 16:34 UTC, ellexo2456 commented on tests/letters.js
> +		assert.strictEqual(letters(['p', 'r', 'o', 't', 'o', 't', 'y', 'p', 'e']), '');
я же написал в функции проверку на то, является ли аргумент words строкой, поэтому всё, что не строка будет оканчиваться retrun "". поэтому теперь тесты ['sp', 'r', 'o', 't', '1o', 't', 'y', 'p', 'e'] и ['p', 'r', 'o', 't', '1o', 't', 'y', 'p', 'e'] идентичны, потому что и то, и другое просто массивы

2023-09-10 15:10 UTC, tUnknownLegend requested changes

2023-09-10 15:10 UTC, tUnknownLegend commented on tests/letters.js
> +        assert.strictEqual(letters('prototype', ['4', '345']), '');
давай добавим еще один тест с new String()

2023-09-11 12:42 UTC, tUnknownLegend commented on source/letters.js
> +    if (typeof words !== "string" || words instanceof String) {
сейчас проверка не совсем верная, new String() не пройдет, так как будет типа object

2023-09-11 19:49 UTC, tUnknownLegend requested changes

2023-09-11 19:49 UTC, tUnknownLegend commented on source/letters.js
> +        return '';
лучше возвращать [error](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Error)

2023-09-11 19:49 UTC, tUnknownLegend commented on source/letters.js
> +console.log(letters('prototype'))
видимо забыл удалить. Так же в конце файла принято оставлять пустую строку

2023-09-11 19:49 UTC, tUnknownLegend commented on tests/letters.js
> -		assert.strictEqual(letters('hello world', false), 'he world');
давай вернем отступ какой он был

2023-09-12 06:28 UTC, ellexo2456 commented on source/letters.js
> +        return '';
тогда же получится, что функция иногда возвращает строку, а иногда error
это норм?

2023-09-12 06:32 UTC, ellexo2456 commented on tests/letters.js
> -		assert.strictEqual(letters('hello world', false), 'he world');
это автоформат
вообще странно, что в изначальном отступе  по два таба

2023-09-12 07:32 UTC, tUnknownLegend approved these changes
ставлю аппрув, но две мелкие правки еще нужно внести

2023-09-12 07:32 UTC, tUnknownLegend commented on source/letters.js
> +            return '';
здесь тоже лучше возвращать ошибку, как в 14 строке

2023-09-12 07:32 UTC, tUnknownLegend commented on tests/letters.js
> -		assert.strictEqual(letters('hello world', false), 'he world');
понимаю, но лучше сделать так, чтобы изменений не было в данном случае

2023-09-12 10:28 UTC, ellexo2456 commented on source/letters.js
> +            return '';
тогда же получится, что функция иногда возвращает строку, а иногда error
это норм?

2023-09-12 11:29 UTC, tUnknownLegend approved these changes

2023-09-12 11:30 UTC, tUnknownLegend commented on source/letters.js
> +            return '';
в целом да, зато будет точно ясно когда случилась ошибка

2023-09-12 11:53 UTC, DPeshkoff requested changes
Привет! Поздравляю с переходом на второй семестр)

Хорошее решение получилось, но у меня есть пара замечаний. Если возникнут вопросы - можешь писать в [Telegram](t.me/DmPesh)

2023-09-12 11:53 UTC, DPeshkoff commented on source/letters.js
> +        return Error("incorrect type of param words");
Ошибки лучше throw'ать - это позволит в дальнейшем их ловить в блоках try...catch

А еще в языке принято использовать одиночные кавычки, давай поменяем)

2023-09-13 10:10 UTC, DPeshkoff requested changes

2023-09-13 10:10 UTC, DPeshkoff commented on source/letters.js
> +        throw new Error('incorrect type of param words');
Лучше [так](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Error#%D1%82%D0%B8%D0%BF%D1%8B_%D0%BE%D1%88%D0%B8%D0%B1%D0%BE%D0%BA) + добавить информацию о throws в JSDoc

2023-09-13 17:13 UTC, ellexo2456 commented on source/letters.js
> +            throw new TypeError('incorrect type of param parameter');
вообще не знаю
boolean может принимать только два значения, поэтому всё , что bolean провалится в первые кейсы
Тогда получается, что в дефолт могут попасть только неправильные типы

2023-09-14 11:25 UTC, closed without merging