Коваленко Григорий web - 21 Variant 9
frontend-park-mail-ru/homework_2023_2 pull request #8
Opened 2023-09-06 16:53 UTC by CodeMaster482

2023-09-07 16:22 UTC, Ivan-Bir commented
Привет!
Добро пожаловать на курс по фронтенд-разработке 👋
Я буду проверять твое дз0. Ниже я оставлю комментарии по коду. Можно отвечать здесь или написать мне в телеграмм @Ivanchello_br.

2023-09-07 17:17 UTC, Ivan-Bir requested changes
В целом всё хорошо, остались мелкоправки

2023-09-07 17:17 UTC, Ivan-Bir commented on source/anagram.js
> +               anagram_groups[word_sorted] = [el];
А если скормим наряду с обычными словами пустые строки ''?
С повторяющимися словами баг или фича?

2023-09-07 17:17 UTC, Ivan-Bir commented on source/anagram.js
> +}
Пустую строчку давай не оставлять

2023-09-07 17:17 UTC, Ivan-Bir commented on tests/anagram.js
> +	QUnit.test('Функция работает правильно тест-1', function (assert) {
Давай позитивные кейсы поместим сверху

2023-09-07 17:17 UTC, Ivan-Bir commented on tests/anagram.js
> +	QUnit.test('Функция работает правильно тест-1', function (assert) {
'...' -> 'Функция работает правильно. Тест 1'

2023-09-07 17:17 UTC, Ivan-Bir commented on tests/anagram.js
>  		];
С тестами хорошо, не забудь только покрыть неучтённые кейсы.

2023-09-07 17:20 UTC, Ivan-Bir commented on source/anagram.js
> +const anagram = (input) => {
Хорошие разработчики документируют свой код.
Давай добавим JSDoc к функции https://jsdoc.app/about-getting-started.html

2023-09-08 19:57 UTC, Ivan-Bir requested changes

2023-09-08 19:57 UTC, Ivan-Bir commented on source/anagram.js
> + * @param {array} input
Массив может быть любой?
Давай уточним, благо JSDoc это позволяет

2023-09-08 19:57 UTC, Ivan-Bir commented on source/anagram.js
> +     input.forEach( (el) => {
Этот пробел не требуется. Вполне нормально смотрится ...((arg) => ...
Здесь и далее

2023-09-08 19:57 UTC, Ivan-Bir commented on source/anagram.js
> +}
Пардон, описался. Пустую строчку наоборот оставлять необходимо, чтобы при мерже не было конфликтов

2023-09-08 19:57 UTC, Ivan-Bir commented on source/anagram.js
> -     input.forEach( (el) => {
А если какой-то умник передаст в твою функцию undefined? Или допустим какой-нибудь пустой ввод от пользователя? Тогда в этом месте твоя функция взорвётся и приложение упадет :(

2023-09-08 20:39 UTC, Ivan-Bir commented
Если нужно повторное ревью, то можно сразу писать в тг

2023-09-11 09:11 UTC, Ivan-Bir requested changes

2023-09-11 09:11 UTC, Ivan-Bir commented on source/anagram.js
> +const anagram = (input) => {
Сюда могут передать далеко не массив массивов, давай сделаем разные проверки входных параметров, чтобы функция стала безопасной и не уронила приложение ошибкой

2023-09-11 09:11 UTC, Ivan-Bir commented on source/anagram.js
> +    input.forEach((el) => {
например здесь. Если input будет undefined, то здесь возникнет классическая для js ошибка
"TypeError: Cannot read properties of undefined"

2023-09-11 09:11 UTC, Ivan-Bir commented on tests/anagram.js
> +
Добавить тестов на проверку входных данных

2023-09-12 14:53 UTC, Ivan-Bir approved these changes

2023-09-12 14:53 UTC, Ivan-Bir commented on source/anagram.js
> +
пустые строки можно убрать, дока должна быть рядом с функцией

2023-09-13 10:36 UTC, DPeshkoff requested changes
Привет! Поздравляю с переходом на второй семестр)

Классное решение получилось, но у меня есть пара замечаний. Если возникнут вопросы - можешь писать в [Telegram](t.me/DmPesh)

2023-09-13 10:36 UTC, DPeshkoff commented on source/anagram.js
> +'use strict';
Распиши, пожалуйста, что делает эта строчка и зачем ты ее написал?

2023-09-13 10:36 UTC, DPeshkoff commented on source/anagram.js
> +    }
А если будет массив не строк, а чего-то другого? Массив Boolean?)

2023-09-13 10:36 UTC, DPeshkoff commented on source/anagram.js
> +        if (typeof el === 'string' && el.trim() !== '') {
Упс! 

![изображение](https://github.com/frontend-park-mail-ru/homework_2023_2/assets/31134795/5afd937a-9f4c-4dbd-a0a1-8d4662f11341)

При этом это валидные строки... непорядок! Давай подумаем, как это починить)

2023-09-13 10:36 UTC, DPeshkoff commented on tests/anagram.js
> +	});
Давай сюда тоже добавим тесты на проверку массивов не со строками

2023-09-13 11:31 UTC, CodeMaster482 commented on source/anagram.js
> +'use strict';
use strict - делает интерпритацию js кода более строгой. Это означает, что ошибки в коде, которые ранее могли быть проигнорированы или не вызывали ошибок, теперь выдают исключения. Например:
1. использвание переменных без обявления
2. запрещает использование зарезервированых js'ом слов
3. Значение this в функции зависит от контекста вызова предотвращает неожтдоное переопределение
4. запрет изменения аргументов функции

2023-09-13 11:35 UTC, CodeMaster482 commented on source/anagram.js
> +    }
Если на вход прийдет массив не строк функция пропустит знаения, которые нельзя перлставить ввиде анагарамы, или нужно сделть, что бы функция явно выбрасывала иключение?

2023-09-13 15:40 UTC, DPeshkoff requested changes

2023-09-13 15:40 UTC, DPeshkoff commented on tests/anagram.js
> +		const output = [];
Можно в 121 строку и без лишних переменных

2023-09-13 15:41 UTC, DPeshkoff commented on source/anagram.js
> +    }
Ты же разработчик, меня не спрашивай)

Вообще как будто бы да, выглядит, как то, что не очень валидно)

2023-09-14 11:26 UTC, DPeshkoff approved these changes

2023-09-14 11:27 UTC, closed without merging