Скандаков Егор WEB21 Вариант 17
frontend-park-mail-ru/homework_2023_2 pull request #9
Opened 2023-09-06 20:14 UTC by hjbaa

2023-09-06 20:25 UTC, Kostich31 commented
Привет, добро пожаловать на курс по фронтенд-разработке. Я буду проверять твое ДЗ 0. Ниже будут мои вопросы и комментарии по коду.

2023-09-07 15:48 UTC, Kostich31 requested changes

2023-09-07 15:48 UTC, Kostich31 commented on source/plainify.js
> +    if (!isObj(obj)) return obj;
Так как ожидаемое возвращаемое значение - это объект, то может быть стоит возвращать ошибку типа в том случае, если переданный аргумент не является объектом?

2023-09-07 15:48 UTC, Kostich31 commented on source/plainify.js
> +
Нужно добавить JSDoc к функции https://jsdoc.app/about-getting-started.html

2023-09-07 15:48 UTC, Kostich31 commented on source/plainify.js
> +    for (const [k, v] of Object.entries(obj)) {
Попробуй переписать с использованием reduce https://learn.javascript.ru/array-methods

2023-09-07 18:26 UTC, hjbaa commented on source/plainify.js
> +
Добавлено

2023-09-07 18:26 UTC, hjbaa commented on source/plainify.js
> +    if (!isObj(obj)) return obj;
Переделано

2023-09-07 18:37 UTC, Kostich31 requested changes

2023-09-07 18:37 UTC, Kostich31 commented on source/plainify.js
> +const isObj = (obj) => { return typeof obj === 'object' && obj !== null }
Может быть тогда добавить JSDoc и для этой функции?

2023-09-07 18:37 UTC, Kostich31 commented on source/plainify.js
> +'use strict';
Для чего нужен 'use strict'?

2023-09-07 18:57 UTC, hjbaa commented on source/plainify.js
> +'use strict';
строгий режим исполнения кода, делает код более предсказуемым + читаемым. К примеру: присваивание неопределенной переменной вызовет ошибку; дублирование имен параметров в функции будет считать ошибкой; использование неинициализированного this вызовет ошибку

2023-09-07 18:59 UTC, hjbaa commented on source/plainify.js
> +const isObj = (obj) => { return typeof obj === 'object' && obj !== null }
есть

2023-09-07 19:38 UTC, Kostich31 approved these changes

2023-09-10 21:02 UTC, DPeshkoff requested changes
Привет! Поздравляю с переходом на второй семестр)

Решение - огонь, но у меня есть пара замечаний. Если возникнут вопросы - можешь писать в [Telegram](t.me/DmPesh)

2023-09-10 21:02 UTC, DPeshkoff commented on source/plainify.js
> +    if (!isObj(obj)) return TypeError;
Лучше не return, а [так](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Statements/throw) - это поможет проще отловить такую ситуацию)

А еще давай не пренебрегать {} и читаемостью кода с:

2023-09-11 19:44 UTC, DPeshkoff approved these changes
`force push` - зло!
Остальное супер)

2023-09-11 19:45 UTC, closed without merging